### ISSUE TITLE
《研究生学位论文撰写规范》整理版

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#1]
本Issue列出《中国科学技术大学研究生学位论文撰写规范（2007年05月）》中写模板时需要注意的部分。

官方文档：
1.  [中国科学技术大学研究生学位论文撰写规范](http://gradschool.ustc.edu.cn/ylb/material/xw/wdxz/1.doc)
2. [文后参考文献著录规则](http://gradschool.ustc.edu.cn/ylb/material/xw/wdxz/19.pdf)

## 文档结构

- [ ] 中文封面
- [ ] 英文封面
- [ ] 其他语种封面（可选）
- [ ] 原创性声明与授权声明
- [ ] 中文摘要和关键词
- [ ] 英文摘要和关键词
- [ ] 其他语种摘要和关键词
- [ ] 目录
- [ ] 图目录（可选）
- [ ] 表目录（可选）
- [ ] 算法目录（可选）
- [ ] 符号说明（可选）
- [ ] 正文
- [ ] 参考文献
- [ ] 附录
- [ ] 致谢
- [ ] 在读期间发表的学术论文与取得的其他研究成果

### 封面
要求中文封面与学校提供的统一封面一致，但按照规范中要求得到的封面却与学校提供的封面不一致。另外，学校的封面要求中也有互相矛盾的地方。

- [ ] 密级（内部 | 秘密 | 机密）+保密年限（小于等于5年 | 小于等于10年 | 小于等于２０年）：仅限涉密论文
- [ ] 论文题目：最多30字，可加副标题，中文题目两行，英文题目三行
- [ ] 作者姓名：英文姓名，名在前，姓在后，需全拼
- [ ] 学科专业：全称，不可简写
- [ ] 导师姓名：一般最多两位指导老师，先主导师，后合作导师，格式为`XXX 教授`
- [ ] 完成时间：年月日，用汉字书写，注意零用`〇`表示

### 页码
- [ ] 封面、扉页、创新性声明不编页码
- [ ] 中文摘要起大写罗马数字编号
- [ ] 正文按阿拉伯数字编号
- [ ] 位于页脚居中（或右侧？）

### 页眉
- [ ] 从中文摘要开始
- [ ] 与一级标题相同
- [ ] 奇偶页相同
- [ ] 各章首页也有页眉

### 原创性和授权声明
略

### 摘要与关键词
- [ ] 关键词3～8词
- [ ] 摘要二字中间空一格
- [ ] 关键词另起一行并隔行列于摘要下方，左顶格
- [ ] 中文关键词用空格分隔，英文关键词用逗号分隔

### 目录
- [ ] `目  录`
- [ ] 中英文摘要＋正文＋参考文献+附录
- [ ] 格式：序号+标题+页码
- [ ] chapter + section + subsection 三级标题，例如`第１章`，`1.1`，`1.1.1`
- [ ] 一级标题顶格写，二级标题缩进一个汉字，三级标题缩进两个汉字
- [ ] 图目录：序号+图题+页码
- [ ] 表目录：序号+表题+页码

### 正文
- [ ] 分章节撰写，每章另起一页。实际上，每章应在奇数页起始
- [ ] 最多四级，即chapter+section+subsection+subsubsection
- [ ] 以阿拉伯数字连续编号，如`第１章`，`1.1`，`1.1.1`，`1.1.1.1`
- [ ] 除chapter外，其余序号左对齐
- [ ] 序号后空一个字距接标题

#### 图
- [ ] 编号为阿拉伯数字，按章连续编号，如`图1.1`
- [ ] 图号与图题之间空一个字符位置（汉字字符？）
- [ ] 图号与图题居中位于图下方
- [ ] 图注位于图题下方

#### 表
- [ ] 表号用阿拉伯数字分章编号，如`表1.1`
- [ ] 表号与表题之间空一个字符位置（汉字字符？）
- [ ] 表题与表号位于表上方
- [ ] 表注位于表题下方
- [ ] 跨页表格需在续表上方注明“续表”，并重复表头

#### 公式
- [ ] 量的符号一般为单个拉丁字母或希腊字母,并一律采用斜体(pH 例外)？
- [ ] 在表达量值时，在公式、图、表和文字叙述中，一律使用单位的国际符号，且无例外地用正体？
- [ ] 单位符号与数值之间留适当空隙
- [ ] 居中
- [ ] 阿拉伯数字分章编号
- [ ] 序号加圆括号，右对齐
- [ ] 较长的式如必须转行，只能在+,-,×,÷,<,>处转行，序号编于最后一行的最右边

### 参考文献
略
### 附录
- [ ] `附  录`
- [ ] 附录按阿拉伯数字编号？

### 致谢
- [ ] `致  谢`

### 在读期间发表的学术论文与取得的其他研究成果
- [ ] 按学术论文发表的时间顺序
- [ ] 发表或已录用的学术论文清单(发表刊物名称、卷册号、页码、年月及论文署名、作者排序)
- [ ] 其他：申请的专利、获得的奖项及完成的项目等
### 书脊
- [ ] 上方写论文题目
- [ ] 中间写系别
- [ ] 下方写作者姓名
- [ ] 底端写“中国科学技术大学”
- [ ] 距离上下边界3cm左右

### 字体
- [ ] 中文：宋体、黑体
- [ ] 英文：Times New Roman、Arial

若无特殊说明，中文的宋体与英文的Times New Roman对应，中文的黑体与英文的Arial等效

### 页面设置
- [ ] A4（210mmX297mm），白色
- [ ] 上下2.54cm，左右3.17cm，页眉1.5cm，页脚1.75cm，装订线0cm
- [ ] 页眉宋体10.5磅居中
- [ ] 页脚宋体10.5磅居中

### 封面
- [ ] 页面设置：上下3.8cm，左右3.2cm，页面页脚3.0cm（可以不用理会）
- [ ] 密级：仿宋14磅，Times New Roman 14磅
- [ ] 中国科学技术大学：36磅，居中，距离顶边5.2cm （实际为图片？）
- [ ] XX学位论文：黑体56号，居中，距顶边8.5 cm
- [ ] 论文题目：黑体26磅加粗居中，单倍行距，距顶边15.8 cm
- [ ] 作者姓名、学科专业等：黑体/宋体16磅，单倍行距，距左边距6cm，距下边界5 cm；
- [ ] 英文校名：Arial 20磅，居中，行距30，距顶边5 cm
- [ ] A dessertation for xxx: Arial 26磅居中，行距30磅，距顶边6cm
- [ ] 校徽：4.2x4.2cm，距顶边8.2cm
- [ ] 英文题目：Arial 26磅加粗居中，行距30磅，距顶边16cm
- [ ] Author等：Times New Roman 16 磅，行距30 磅，距左边界 6cm，距下边界5cm

### 摘要
- [ ] 摘要标题：与chapter标题相同
- [ ] 摘要内容：与正文相同
- [ ] 关键词：“关键词”、“Key Words”加粗，其他同正文

### 目录
- [ ] 目录标题：与chapter标题相同
- [ ] chapter标题：宋体14磅，单倍行距，段前6磅，段后0磅，两端对齐，页码右对齐
- [ ] section标题：宋体12磅，单倍行距，左缩进1个汉字，段前6磅，段后0磅，两端对齐，页码右对齐
- [ ] subsection标题：宋体 10.5 磅，单倍行距，左缩进 2 个汉字，段前 6 磅，段后 0 磅，两端对齐，页码右对齐

### 正文
- [ ] chapter标题：黑体16磅加粗居中，单倍行距，段前24磅，段后18磅
- [ ] section标题：黑体 14 磅顶左，单倍行距，段前 24 磅，段后 6 磅
- [ ] subsection标题：黑体 13 磅顶左，单倍行距，段前 12 磅，段后 6 磅
- [ ] subsubsection标题：黑体 12 磅顶左，单倍行距，段前 12 磅，段后 6 磅
- [ ] 正文：宋体12磅，两端对齐书写，段落首行左缩进 2 个汉字符，段前段后0磅，行距 20 磅

### 图标题
- [ ] 宋体10.5磅，居中，单倍行距，段前6磅，段后12磅
- [ ] 图序加粗
- [ ] 图注标题加粗，左缩进两个汉字符，续行悬挂缩进左对齐，两端对齐

### 表标题
- [ ] 宋体10.5磅，居中，单倍行距，段前6磅，段后**6**磅，其余与图同

### 其他
- [ ] 公式居中，序号加圆括号，宋体10.5磅，右顶格
- [ ] 符号说明：标题字体字号等同论文正文（不是chapter标题？），说明部分：宋体 10.5 磅，行距 16 磅，段前段后 0 磅
- [ ] 参考文献：标题黑体16磅加粗居中。注录部分：宋体10.5磅，行距20磅，段前段后0磅；中英文一率用正体；续行缩进两个字符，左对齐
- [ ] 附录：标题同参考文献，内容部分：同正文
- [ ] 致谢：标题同chapter标题，正文部分同正文
- [ ] 发表论文：标题同chapter标题；正文部分同正文

### 书脊
- [ ] 上下3.8cm，左右3.2cm，页眉页脚3.0cm
- [ ] 黑体12磅，行距14磅
- [ ] 上下各留3cm？

**Comment by zhengprince** [comment]
模板导出的公式字体并不是times new roman
