### ISSUE TITLE
新规范草稿

### ISSUE THREAD

**Issue by ywgATustcbbs** [ustctug/ustcthesis#100]
拿到了学校新规范的草稿，大家可以先看下，改动不是很大，但是条目要求等更细致了，可操作性也有提升。不知道后续会不会有改动

[1.zip](https://github.com/ustctug/ustcthesis/files/351262/1.zip)

**Comment by zepinglee** [comment]
姿磁！

**Comment by zepinglee** [comment]
PS 可以再联系一下制本厂，把装订的指南放在我们的模板中

**Comment by ywgATustcbbs** [comment]
出了新规范的二次草稿。与之前的规范相比改动还是有一些的。我仔细读了一下，主要改动是四个方面
1.把frontmatter移除索引（目录中不再索引摘要等，包括目录本身）
2.frontmatter、backmatter依旧奇数页起，但mainmatter连续排，不再奇数页起
3.目录编号规则由“第一章”-“1.1”-“1.1.1”-“1.1.1.1”这样的改为“第一章”-“1.1”-“1.1.1”-“1.“...
4.表格的形式，规范中只提到了普通的表格，没有关于三线表的描述。
这四个方面感觉上很怪，和惯例以及习惯有较大的差异。我已经反馈给学校了，但不知道有没有作用。

文件上传不了，不知道怎么回事，回头我发你们邮箱吧

**Comment by acgotaku** [comment]
致谢的正文 要求是仿宋。。。

**Comment by ywgATustcbbs** [comment]
这次可以传文件了，这个是学校的第二次草稿，后边就没有新的消息了。

这一版草稿对排版来说是个灾难，太迁就word了。

[20160923.pdf](https://github.com/ustctug/ustcthesis/files/811123/20160923.pdf)

**Comment by zepinglee** [comment]
@ywgATustcbbs 很好奇你这是从哪搞来的文件？

PS 这 pdf（方正生成的）简直了……连搜索都不行

**Comment by ywgATustcbbs** [comment]
这是学校出版社给的二稿，之前那个是一稿……很早之前就拿到了，开始一直发不上来，就没有持续重试。刚才又试了一下，等了好久终于传上了。
这草稿内容很丰富，但是和之前的习惯还是有很大出入的。特别是目录索引和正文的连续排版，也是醉了
表格的形式是我没有仔细阅读，其实还是推荐三线表。
还有就是草稿中要求章标题字数少的时候要加空格，两个字的标题和三个、四个字的标题加的空格不一样。致谢和附录加的也不一样……
还有就是专业硕士的封面不一样，不过专业硕士估计也不用latex。
不说了，都是泪

**Comment by ywgATustcbbs** [comment]
@zepinglee 我估摸着方正搞得这个pdf其实没有文字信息，就是直接把文字拆解成赤裸裸的线条，所以你搜索不了

**Comment by keyboard-man** [comment]
@ywgATustcbbs 专硕封面差距不算太大，自己使用时已照着模版修改了。问题不大。

**Comment by keyboard-man** [comment]
求问mac能在封面上使用隶书吗？看到有说mac不知隶书来着。

**Comment by zepinglee** [comment]
@keyboard-man 不是不支持，是系统自带的字体库没有，你可以从别的地方copy字体来用

**Comment by keyboard-man** [comment]
@zepinglee ,非常感谢，已解决！
