### ISSUE TITLE
设置每章的标题的上下间距在哪里可以调整？

### ISSUE THREAD

**Issue by acgotaku** [ustctug/ustcthesis#102]
我在 ustcthesis.cls 里面的  395和296行的
`
        beforeskip = 0bp,
        afterskip = 0bp,`

设置为0 但还是看到论文有上下间距 请问怎么调整？

**Comment by zepinglee** [comment]
这个距离比较复杂，应该还有parskip什么的，可能需要你自己去参考 the latex companion，和 latex 源码

**Comment by acgotaku** [comment]
确实很复杂 导致和 word的间距不一致

我有看 CLS文件的源码 但是还是不太清楚哪些代码 影响了这个间距 所以来问问

On Nov 15, 2016 09:08, "Zeping Lee" <notifications@github.com> wrote:

这个距离比较复杂，应该还有parskip什么的，可能需要你自己去参考 the latex companion，和 latex 源码

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ustctug/ustcthesis/issues/102#issuecomment-260515615>,
or mute the thread

**Comment by jiaopjie** [comment]
我觉得是因为章标题本身的行间距. 考虑到标题有可能有多行, 这个行间距是合理的. 所以标题前后后空白是合理的吧.

**Comment by zepinglee** [comment]
latex 排版出来的东西没必要跟word 一样

**Comment by jiaopjie** [comment]
老师一般不会抠这个细节吧. 我更新了 `ctex` 宏包. 2016.09.21 的说明文档里有一个 `fixskip` 选项来修正多余的空白. 更新一下 `ctex` 宏包, 然后把它设为 `true` 就行了. 实在不行你还可以设为负值嘛. 发布的模板应该不会把这个选项写进去. 这对 `ctex` 的版本要求太新了.

**Comment by zepinglee** [comment]
我仔细研究了一下，确实算是ctex的一个bug，虽然可以用 `fixskip = true`修正，但是这个功能是texlive2016 发布后才加进去的，大部分人即使用了texlive 2016 也不会更新宏包，这就很麻烦；我的想法是，先手动调整距离应付今年毕业生；从明年开始启用`fixskip = true`。

**Comment by zepinglee** [comment]
fixed in de21053

**Comment by waugpeiii** [comment]
设置为负值可以完美解决，简直神奇，居然可以设置为负值。。。感谢大佬@jiaopjie
