### ISSUE TITLE
参考文献前没有[1] [2] [3]...这样的标号

### ISSUE THREAD

**Issue by hhoufeng** [ustctug/ustcthesis#103]
我选择了提供的两种风格，都没有这样的标号，请问这样是正常的吗

**Comment by zepinglee** [comment]
估计是因为设置了natbib 的其他东西

**Comment by jiaopjie** [comment]
看你想要什么样的风格了. author-year 模式貌似就是没有数字排序的. 如果只想在正文中引用时使用  author-year 模式, 而在后面参考文献列表中用数字排序的模式的话, 在 `\bibliography` 命令之前要改回数字模式.
