### ISSUE TITLE
页眉badbox, 扉页不显示coadvisor, 单倍行距含义不统一

### ISSUE THREAD

**Issue by jiaopjie** [ustctug/ustcthesis#105]
1. 这个模板里的设置 `headsep=0.74cm, headheight=0cm` 把页眉高度设为 0 是为了严格控制文本上缘距离上边的距离为 `1.5cm` ? 可惜实测距离并不准确.

并且由于页眉高度设置太低, 每张有页眉的页面都会额外出现一个 badbox. 这虽然不算问题, 但是容易掩盖正文里出现的 badbox 数量.

我自己测试的 `headsep=0.7cm, headheight=0.34cm` 基本上是满意的.

2. 不管有没有填写 `coadvisor` 扉页中都不会出现 `coadvisor` 给出的信息.

3. 规范里 `单倍行距` 具体指多少行距含义不明. 不过模板里面对这个含义的解读也并不统一. 目录里的 `单倍行距` 似乎是被解读为 `1.2` 倍字号. 其他地方, 比如章节标题, 扉页里面被解读为 `2` 倍字号.

4. 扉页里 `ustc_logo_text` 的图片文字似乎偏大. 规范里要求 `36号` 字体. 那么把图片高度设为 `36bp` 就好了, 控制宽度并不准确.

另外模板里面制作扉页使用了 `tikz` 宏包. 但似乎文本的定位也不是那么的准确. 还不如像老模板里面使用 `\parbox` 命令.

**Comment by zepinglee** [comment]
1. 我测量的是准确的啊，提供一下你的代码来瞧瞧？
页眉恐怕只能这么设计了，我还没找到其他方案。

2. 我回去瞧瞧

3. 这应该是个bug

4. 图片的高度还包括了一些空白，所以直接设为36bp 不太合适。

5. 如果完全按照规范的要求，你会发现特别丑，所以调整了位置。老模板也没有按照规范。parbox 的方法太丑陋，一处调整后面的都要改

**Comment by jiaopjie** [comment]
1. 我是用 `Acrobat` 裁切工具测量的, 想来测量不会出错. 这里不能贴图片吧? 我还是语言叙述吧. 我指的是页眉文本上边缘与页面上边缘之间的距离. 按你们的设置, 测量出来的结果是 1.8cm, 这跟 2.54cm-0.74cm 的结果是吻合的. 所以即便是要为了准确的距离, 也应该是设置 `headsep=1.04cm` 而不是 `headsep=0.74cm`. 不过我又重新测量了一下, 在 `headsep=0.74cm` 的前提下设置 `headheight=0.3cm` 倒是蛮准确的.并且不会有 badbox. 所以你们原本想写的是 `headsep=0.74cm,headheight=0.3cm` 而不是 `headsep=0.74cm,headheight=0cm`?
```
\geometry{paper=a4paper,
  top=2.54cm, bottom=2.54cm, left=3.17cm, right=3.17cm,
  footskip=0.79cm, headsep=0.74cm, headheight=0.3cm,
}
```
效果还不错.

2. 虽然模板里定义了 `\setfontsize` 命令, 但模板里还是使用了 `ctex` 提供的 `\zihao` 命令. `\setfontsize` 在只有必选参数的时候行距是 2 倍字号, 而 `\zihao` 行距设定的是 1.2 倍字号. 就是这个原因造成了对 `单倍行距` 解读的不统一.

3. 关于图片四周的空白. 校徽图片周围的空白的确有点大, 不过校名四周基本没什么空白, 仅有的一点空白也是因为个别字比较高, 个别笔画伸的比较长的原因. 鉴于这个原因, 我觉得把高度设为 `36bp` 是合适的.

4. 我也不觉得完全按照规范来会比较好. 实际上就连规范里给的范例跟规范的要求有不小的差距. 当然用 `tikz`  定位还是比较准确的. 大概就是由于文本周围的留白问题, 导致稍微有那么一点的多余空白. 这当然是可以接受的. 用`parbox` 的确也比较繁琐, 一处修改之后, 后继的也要相应的修改. 不过好处是不用额外引入宏包, 并且配合 `\nointerlineskip` 命令可以把距离做到很精确. 当然这个不算什么问题了.

5. 另外, 不知道规范里干嘛要把扉页的页面边距单独拎出来设置. 本来扉页就不需要输出页眉页脚, 扉页内容也都规定了距离上边的距离. 因此重新设定上下边距并没有什么意义. 左右边距差了 `0.3cm` 并且都是居中的, 也没看出来有什么意义. 因此我自己的选择是无视规范里的这个要求, 统一页面边距设置. 省的麻烦.

**Comment by jiaopjie** [comment]
另外, 关于一个已经关闭的问题. issues #102 , 按照 `ctex` 的说明文档, 他们在 2016.06.03 更新引入了一个新的选项 `fixskip` 用于修正章标题前的多余空白. 当然, 由于这个参数太新了, 应该不适合写进模板的 `.cls` 文件中. 不过可以写在 `main` 文件的导言区, 并且默认注释掉, 加上解释说明. 或者有条件语句可以判断 `ctex` 宏包的版本? 如果有的话, 放在 `.cls` 文件中用一个条件判断来决定是否跳过也可以.

**Comment by ywgATustcbbs** [comment]
第一个，页眉变化问题，很可能并不是页眉本身的问题，而是latex里版心高度会根据页面输出变化导致的。页眉那里可能仅仅是限制了最小值。
我想第二个校徽留白并不是问题。如果我没猜错，校徽用的应该还是ustcvi里做的那个eps
学校的vi手册中的规定，校徽图片长宽各16，圆形外径14，所以有较大留白。校名在规定中是完全没有留白的。

**Comment by ywgATustcbbs** [comment]
如果用tikz定位的话，完全可以不管扉页页眉，使用页面绝对坐标，甚至可以考虑所有页眉页脚都用tikz定位

**Comment by ywgATustcbbs** [comment]
至于条件判断宏包版本，我记得之前在另外的问题上试过，但是似乎很不稳定，不知道为什么

**Comment by zepinglee** [comment]
@jiaopjie 你有兴趣接受这个工作嘛？

**Comment by jiaopjie** [comment]
@zepinglee 我不活跃哦. 写完毕业论文我就滚蛋了. 在用的过程中遇到的问题提交给你们就好了.

**Comment by zepinglee** [comment]
1. 没错原来是想写 `headsep=0.74cm,headheight=0.3cm`的，这是个bug【捂脸】

2. 对，新的模板不处理coadvisor了，如果需要的话跟advisor写在一起

3. 这也是个bug【捂脸】，一开始写的然后忘记改了……

4. 我用36磅华文行楷（上）和设置height=36bp的图片比较了一下：
![36](https://git.ustclug.org/ustctug/ustcthesis/uploads/7f972ef50b9525b44b88b408c825c765/36.png)
后者还是显得比前者要小一点的；
然后我试了一下height=37bp，虽然后者的字在尺度上略小一点，但是笔画上比较粗，所以整体字重差不多。

@jiaopjie 你读得真仔细啊……
