### ISSUE TITLE
咨询参考文献格式

### ISSUE THREAD

**Issue by xhhong** [ustctug/ustcthesis#106]
使用2.1.4版本，参考文献格式对于会议论文格式的问题，如：
Krizhevsky A, Sutskever I, Hinton G E. 2012. Imagenet classification with deep convolutional
neural networks[C]//proc. of NIPs. [S.l.], 1097–1105.

页码之前的[s.l.]指的是什么？

**Comment by zepinglee** [comment]
> (2) 无出版地时可著录为:[出版地不详]或[S.l.](S.l.是拉丁文 Sine loco 的缩写)。
(3) 无出版者时可著录为:[出版者不详]或[s.n.](s.n.是拉丁文 sine nomine 的缩写)。注意:不要出现〔S.l.〕:〔s.n.〕这样的著录形式。

**Comment by zepinglee** [comment]
老版本的规范里没说“不要出现〔S.l.〕:〔s.n.〕这样的著录形式”，所以这个规则我还没加进去
