### ISSUE TITLE
unused global options: [doctor]

### ISSUE THREAD

**Issue by yuewu001** [ustctug/ustcthesis#107]
编译过程中提示LaTeX Warning: Unused global option(s): [doctor]， 不影响编译结果

**Comment by zepinglee** [comment]
应该是 kvoption 的问题，我也不知道为啥会产生这个……

**Comment by jiaopjie** [comment]
的确应该跟 `kvoptions` 宏包有关系吧. 我自己试着修改过不用 `kvoptions` 宏包, 而使用原始的 `\DeclareOption` 命令. 这种情况下没有出现这种警告.

我觉得是 `\PassOptionsToClass{\CurrentOption}{ctexbook}` 把所有的文档选项都传递给了 `ctexbook` (包括 `doctor` 选项). 但 `doctor` 选项对于 `ctexbook` 来说的确是无用的. 所以有这个警告.

声明 `doctor` 文档选项的时候如果用的是 `\DeclareOption` 命令的话, 有可能该命令使得不传递 `doctor` 选项.

ps: 另外, 我觉得, 模板中设置的 `oneside` , `twoside`, `pdf`, `openright`, `openany`, `pageouter` 选项有冗余. 有些选项本来 `ctexbook` 中就有啊.

**Comment by zepinglee** [comment]
现在用最原始的 `\DeclareOption` 重写了，应该没有这个问题了
