### ISSUE TITLE
v2.1.4目录问题

### ISSUE THREAD

**Issue by hcAncientMoon** [ustctug/ustcthesis#109]
非常感谢模板的贡献者们！！我在使用最新的2.1.4版本时，发现生成的目录里依然索引了摘要，这似乎与最新版的论文规范不符。不知能否解答一下，谢谢！

**Comment by zepinglee** [comment]
呃……2.1.4 只更正了参考文献格式，还没update 到新的论文规范，你可以提供下新的论文规范链接嘛？

**Comment by hcAncientMoon** [comment]
不好意思，我也没有   我是看到了之前issue里ywgATustcbbs 给的那个草稿里说的，而且readme中给出的规范中给出的附录里的目录格式与代码生成的不一致

**Comment by zsynacl** [comment]
我看了一下目前研究生院挂的撰写规范，目录还是要求的包含论文所有内容。

**Comment by ywgATustcbbs** [comment]
新的规范到目前为止我知道的出了两次草稿，具体最终稿什么时候出，有多大变化都不清楚。放那个草稿只是为了让大家有个心理准备，还是要按照学校目前的规定来的。

**Comment by zepinglee** [comment]
我已经毕业了，不太清楚学校里的要求，也没看到正式版的新《规范》。有什么新的消息及时提在这里。

@hcAncientMoon 2007年版《规范》附录的目录格式并不符合《规范》本身（不自洽），具体你可以仔细阅读《规范》正文，以及github上以前讨论的issue

**Comment by hcAncientMoon** [comment]
好的，非常感谢！ @ywgATustcbbs @zepinglee
