### ISSUE TITLE
关于cite

### ISSUE THREAD

**Issue by tangbohu** [ustctug/ustcthesis#110]
请问最后要求的引用不是显示【1】【2】 这种类型吗？ 我看模板中是  Knuth et al (1998) 这种

**Comment by zsynacl** [comment]
这是两种被支持的引用类型，具体设置参见ustcthesis.pdf里面的指引。

**Comment by zepinglee** [comment]
《规范》2.7 

> 参考文献参照 GB/T 7714-2005《文后参考文献著录规则》执行。推荐使用 著者-出版年制，即在正文引用文献处标注著者姓名与出版年份，在文后的参考 文献表中标注参考文献的详细信息。
