### ISSUE TITLE
目录问题

### ISSUE THREAD

**Issue by kylinhao** [ustctug/ustcthesis#111]
对于含有3个级以上的\subsubsubsection
比如\subsubsubsection{1}
\subsubsubsection{2}
\subsubsubsection{3}
\subsubsubsection{4}
在目录中只能显示1.2前两个，甚至不显示

**Comment by zepinglee** [comment]
> 目录应包括论文的全部内容，包括中英文摘要和附录等，正文章节题名要求编到第3级标题，即×.×.×。

**Comment by kylinhao** [comment]
第四级就不行了。。。

**Comment by zsynacl** [comment]
意思是要求目录里最多显示到三级标题（chapter,section,subsection），四级标题（subsubsection及以下）不需要显示。
