### ISSUE TITLE
如何添加EB/OL的参考文献条目

### ISSUE THREAD

**Issue by zsynacl** [ustctug/ustcthesis#113]
使用了misc和online条目，最后显示都是M/OL

**Comment by zepinglee** [comment]
一个bst的bug，我稍后修复

**Comment by zepinglee** [comment]
同 https://github.com/zepinglee/gbt-7714-2015/issues/16

**Comment by zsynacl** [comment]
似乎应该把这里的bst文件改为引用你的gbt-7714库

**Comment by zepinglee** [comment]
不行，科大的《规范》在原来基础上有些修改，你diff 一下会发现很多不同

**Comment by zsynacl** [comment]
ok.我刚刚把你的gbt-7714 commit 82a3c6里面的FUNCTION {misc}和 FUNCTION {online} 直接放进本地的bst里了，这样对吧？

**Comment by zepinglee** [comment]
不对，author-year式中的各项顺序不太一样，我正在检查，很快push

**Comment by zsynacl** [comment]
好的，辛苦了。

**Comment by zepinglee** [comment]
fixed in 0c6ab7a
