### ISSUE TITLE
文件超出页边距，本地编译不过源，标题与段落距离过大等问题

### ISSUE THREAD

**Issue by gdh55555** [ustctug/ustcthesis#114]
目前发现四个问题
1. 在我的本地编译源， 提示maketitle 错误
2. 突然出现两页，其中页面中的字超出了页面，覆盖页眉，一直到底部
3. 图片的标题与下一个段落的间距是否过大，学校要求的是段前6磅，段后12磅
4 每章标题与页边框是否距离太远，还是作者刻意为之

**Comment by zepinglee** [comment]
1. 你是在什么环境下编译的？
2. 可以提供下你的代码嘛？
3. 图片的标题下面的空白可能有问题，我需要研究一下
4. 章标题好像是要求前面有个距离

**Comment by gdh55555** [comment]
1. 环境是texstudio+miktex
2 见附件， 我摘取了一部分， 出现问题的地方我使用newpage强制分页了，
你帮我看下是我写的有问题，还是有bug
`\section{系统成果以及功能测试}
实验在ARM平台开发板上，使用Linux Kernel3.4.35版本，Android对应4.2.2版本，基于LXC1.0.7的虚拟化解决方案，其硬件实验环境为：
\begin{longtable}{c c}
	% 首页表头
	\caption[硬件]{硬件参数配置} \label{tab:硬件} \\
	\toprule[1.5pt]
	部件 & 参数\\
	\midrule[1pt]
	\endfirsthead
	% 续页表头
	\caption[]{硬件参数配置（续）} \\
	\toprule[1.5pt]
	部件 & 参数\\
	\midrule[1pt]
	\endhead
	% 首页表尾
	\hline
	%\multicolumn{3}{r}{\small 续下页}
	\endfoot
	% 续页表尾
	\bottomrule[1.5pt]
	\endlastfoot
	
	CPU & 双核ARM Cortex A7 \\
	内存 & 1GB DRAM \\
	存储 & 8GB eMMC \\
\end{longtable}

PC端使用串口线连接Linux系统，通过adb协议连接Android系统。

1）功能测试

通过烧制系统集成Image，打开电源开关，宿主Linux系统和客户机Android系统同时启动，宿主系统显示其开机Logo，Android系统在另一个显示器显示“ANDROID”字样，代表 两个系统通过在宿主系统的inittab中加入lxc-start启动客户机系统命令启动成功，Android系统通过LXC工具正常启动，且通过两个屏
\newpage
幕分别显示不同系统界面，互相隔离相互不影响，表明双屏显示方案正常。

同时通过多次的开关机重启，双系统同时画面几乎同时启动且正常显示，表示其功能正常且稳定。且通过鼠标，键盘输出输出设备不会影响Android系统，只能点击和响应QT的界面，同时对于Android系统使用自带的触摸屏去触摸点击，以及文字输入均正常，且可以正常显示。表明输入输出隔离功能正常。

同时对于宿主系统和Android系统，通过串口工具以及adb工具观察不同系统的文件视图其所显示的内容不同，即不同系统无法感知对方的存在，实现了系统文件以及隐私信息的隔离以及安全性的提升。如图4.17 Android容器文件视图。
\begin{figure}[ht]
	\centering
	\includegraphics[width=14cm]{容器文件}
	\caption{Android容器文件视图}\label{fig:容器文件}
\end{figure}

通过一系列系统Sanity Test测试如表4.5，通过对音频视频等不同格式播放，同时对其他功能连接性的确定，共12大项，45个小项，表明各个系统功能均能正常使用。

\begin{longtable}{c c c c c c c}
	% 首页表头
	\caption[sanity]{Sanity Test列表} \label{tab:sanity} \\
	\toprule[1.5pt]
	ID & Category & Total & Pass & Fail & N/A & Description\\
	\midrule[1pt]
	\endfirsthead
	% 续页表头
	\caption[]{Sanity Test列表（续）} \\
	\toprule[1.5pt]
	ID & Category & Total & Pass & Fail & N/A & Description\\
	\midrule[1pt]
	\endhead
	% 首页表尾
	\hline
	\multicolumn{3}{r}{\small 续下页}
	\endfoot
	% 续页表尾
	\bottomrule[1.5pt]
	\endlastfoot
	
	1 &	BootLoader & 1 &	1 & 0 &	0 &	正常升级启动系统 \\
	2 &	Touch Panel	& 1 &	1 & 0 &	0 &	触摸使用正常 \\
	3 &	Display &	1 &	1 &	0 &	0 &	显示正常 \\
	4 &	Kernel &	1 &	1 &	0 &	0 &	测试kernel正常 \\
	5 &	Connectivity &	7 &	7 &	0 &	0 &	GPS蓝牙功能正常 \\
	6 &	SD &	1 & 1 &	0 &	0 &	SD使用正常 \\
	7 &	USB &	2 &	2 &	0 &	0 &	USB使用正常 \\
	8 &	Internal Storage &	1 &	1 &	0 &	0 &	内部存储使用正常 \\
	9 &	APP &	1 &	1 &	0 &	0 &	APP安装正常 \\
	10 &	Video &	15 &	15 &	0 &	0 &	视频播放正常\\
	11	& Image	 &1 &	1 &	0 &	0 &	图片显示正常\\
	12 & 	Audio &	13	& 13 &	0 &	0 &	音频播放正常\\
	Total &	45	& 45 &	0 &	0 & &	\\
	
\end{longtable}

2）性能测试
本课题采用LXC实现的轻量级虚拟化解决方案，通过共享同一kernel减少很多不同系统带来的开销，对于硬件设备性能不足的情况下，依然没有什么性能损耗，多个系统均能正常使用。`

**Comment by zepinglee** [comment]
看起来没啥问题，建议你把miktex的宏包update到最新再试试；
附件没传上来，你可以放到github的一个repo里嘛？或者发到我的邮箱

**Comment by gdh55555** [comment]
已经是最新版本的， 下面的代码就是我的附件的部分， 就是这部分出了问题， 超出了页面

**Comment by zepinglee** [comment]
没有上下文的话，我没法复现出你的问题

**Comment by kylinhao** [comment]
![image](https://cloud.githubusercontent.com/assets/5234656/24547945/05cb545a-1645-11e7-88c3-0ab3f7357912.png)
![image](https://cloud.githubusercontent.com/assets/5234656/24547973/2e71f396-1645-11e7-8b45-c98bd34dfeb1.png)


请看这间距大的要命，求改，这是再不改，都想手动调了

**Comment by zepinglee** [comment]
关于标题距离，参见这里 https://github.com/ustctug/ustcthesis/issues/102#issuecomment-294344979

**Comment by zepinglee** [comment]
1, 2 我没发重现
3 没有问题
4 已经修复

**Comment by zepinglee** [comment]
fixed in 55ca9721ece753a53aeb8120189d01e2760eb469
