### ISSUE TITLE
Windows和Linux下字体不一致

### ISSUE THREAD

**Issue by harrysummer** [ustctug/ustcthesis#116]
由于 CTeX 宏包默认会根据操作系统的类型来选择中文的字体集（见 texdoc ctex 中的 fontset 选项），这使得在Windows和Linux下编译的字体不一致。尤其在 Windows 10 下，默认的中文黑体是微软雅黑，该字体中宫过松，虽有利于屏幕显示的辨识度，但作为正式的纸质文本十分不严肃。

建议在模板中将 ctexbook 的 fontset 选项统一设置为 fandol，既保证了各平台下编译字体的统一性，又可保证美观。

**Comment by zepinglee** [comment]
关于微软雅黑，我也同意你的观点；但是 fandol 不能显示“〇”这个字符，这样扉页就有问题，所以不建议统一设置为 fandol

**Comment by harrysummer** [comment]
我觉得单单“〇”一个字符，也不是没有办法特殊处理。如果因为这一个字符，就要为整篇论文的字体委曲求全的事情，就有点因小失大了。我现在的处理是手工绘制这个“〇”：

```latex
\RequirePackage{newunicodechar}
\newunicodechar{〇}{\hspace*{0.15em}\tikz[baseline=(maru.south)]{\node[draw, circle, inner sep=0pt, minimum size=0.75em, line width=0.5pt](maru){};}\hspace*{0.15em}}
```

**Comment by zepinglee** [comment]
我的想法是，你可以自由选择你觉得好看的字体，但是没有必要全部统一

**Comment by harrysummer** [comment]
针对这个issue本身，我只是想从官方的立场出发，觉得发布的模板应该统一样式。

至于民间如何基于这个模板进行修改、美化，都与这个repo里发布的官方模板无关。

我认为理想的做法应该是：
1. 给模板提供一个规范、合理、统一的默认值（字体既不像微软雅黑那么丑，也不能缺少扉页上的字符）；
2. 给用户提供一个自定义字体的文档/说明，指导用户根据自己的喜好进行修改。

**Comment by zepinglee** [comment]
1. 如果要这样做，最好是把字体文件（比如 adobe 的）加到 repo 当中，但是这样模板就变得很大；我的原则是，模板应该设计成满足《规范》要求的最小集合，既然《规范》没规定用哪一套字体，我觉得没有必要去统一；

2. 可以加个“参见 ctex 文档”

**Comment by seisman** [comment]
说明文档中已经提示用户要根据自己的需求设置中文字体选项： https://github.com/ustctug/ustcthesis/blob/master/ustcthesis.dtx#L350-L389

**Comment by harrysummer** [comment]
@zepinglee 同意。那我关掉这个issue好了。

别的字体加到这里还会有版权的问题。
