### ISSUE TITLE
参考文献编译出错

### ISSUE THREAD

**Issue by kpskp77** [ustctug/ustcthesis#117]
在Win10下使用mingw-w64工具提供的make程序编译的时候会出现
```
I couldn't open database file bib/tex.bib
---line 154 of file main.aux
 : \bibdata{bib/tex
 :                            }
```
的错误。我把main.tex中的`bib/tex`改成绝对路径之后，编译能通过，但是编译出来的参考文献与bib/tex.bib文件中的内容不一致，只出来了前三个参考文献。

**Comment by zepinglee** [comment]
1. 不是 make 的问题，因为 make 只负责调用 latexmk，latexmk 调用了 bibtex 编译的；不知道这是什么错误。

2. 只出现前三个是因为你在正文中只 `\cite` 了前三个
