### ISSUE TITLE
[URGENT!] Getting problem in Latex to change Chinese Text into English (USTC Thesis)

### ISSUE THREAD

**Issue by MOmarFarooq** [ustctug/ustcthesis#118]
how to change these by default chinese texts into English in latex.
please need your help
![1](https://cloud.githubusercontent.com/assets/20922494/24695239/848b9bd0-1a17-11e7-80e6-7839fcddc950.jpg)
![2](https://cloud.githubusercontent.com/assets/20922494/24695252/909d9f36-1a17-11e7-9dd9-4283e03a6e91.jpg)
![3](https://cloud.githubusercontent.com/assets/20922494/24695257/9f366708-1a17-11e7-92a9-e9559b0c5650.jpg)
![4](https://cloud.githubusercontent.com/assets/20922494/24695267/ab1417b4-1a17-11e7-9306-68d562400134.jpg)

Regards,
Muhammad

**Comment by seisman** [comment]
A quick but dirty solution:

----
https://github.com/ustctug/ustcthesis/blob/master/ustcthesis.cls#L56

change 
```
\LoadClass[a4paper, UTF8, zihao=-4]{ctexbook}[2015/05/14]
```
to 
```        
\LoadClass[a4paper, UTF8, zihao=-4, scheme=plain]{ctexbook}[2015/05/14]
```

----

https://github.com/ustctug/ustcthesis/blob/master/ustcthesis.cls#L388-L396

change 
```
\ctexset{
    chapter = {
        format = \centering\sffamily\bfseries\setfontsize{16bp},
        nameformat = {},
        titleformat = {},
        number = \arabic{chapter},
        beforeskip = 24bp,
        afterskip = 18bp,
    }
```
to 
```
    chapter = {
        format = \centering\sffamily\bfseries\setfontsize{16bp},
        aftername = \quad,
        nameformat = {},
        titleformat = {},
        number = \arabic{chapter},
        beforeskip = 24bp,
        afterskip = 18bp,
    },
```

**Comment by MOmarFarooq** [comment]
It worked! Thank you so much.
But Still I am looking for more better solution for this issue

**Comment by MOmarFarooq** [comment]
@seisman It worked! Thank you so much.
But Still I am looking for more better solution for this issue.

**Comment by zepinglee** [comment]
The English version has not been developed yet. How many of you need it?

**Comment by MOmarFarooq** [comment]
@zepinglee It would be better for future work to have a USTC thesis template in English too!
Thanks!

**Comment by zepinglee** [comment]
I've just pushed 4aa3caa in which I added English version. You need to load the ustcthesis class with option `english` like `\documentclass[doctor,english]{ustcthesis}`.

**Comment by MOmarFarooq** [comment]
Thank you dear @zepinglee !
