### ISSUE TITLE
封面页“作者姓名”的行距有误

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#12]
“作者姓名”、“学科专业”等，规范中的要求是**16 磅,单倍行距**。

Word中的效果如下：
![qq 20150804143844](https://cloud.githubusercontent.com/assets/3974108/9054712/d1c56bb6-3ab6-11e5-85d3-246fc0063604.png)

模板中的效果如下：
![selection_001](https://cloud.githubusercontent.com/assets/3974108/9054722/ea2c27f8-3ab6-11e5-823d-e2b984e5c16c.png)

**Comment by seisman** [comment]
不知为何，Word中“单倍行距”和“双倍行距”的效果是一样的。

Windows 10 + Office 2013。

**Comment by seisman** [comment]
查了刘海洋的《LaTeX入门》以及网上的其他一些资料，似乎模板是对的。

假设字体大小为`10 pt`，则LaTeX中的基本行距为`12 pt`，`\linespread{1}`表示单倍行距即`12 pt`，`\linespread{2}`表示双倍行距即`24 pt`。而LaTeX中的行距因子与Word中的定义是相同的。

对于`setspace`宏包而言，因子的定义有些不同。setspace中的双倍行距为字号的两倍，也就是`20 pt`。

但是模板的效果与Word的效果不同，原因未知。

**Comment by zepinglee** [comment]
一个关键问题是，Word里面的“基本行距”是多少？有资料说Word版本的“基本行距”都不一样，我没有Word，所以目前还没查证。

**Comment by zepinglee** [comment]
只能通过实验测量了，我目测word里面baselineskip是fontsize的2倍

**Comment by seisman** [comment]
[这里](https://support.office.com/zh-cn/article/%E8%B0%83%E6%95%B4%E6%96%87%E6%9C%AC%E6%88%96%E6%AE%B5%E8%90%BD%E4%B9%8B%E9%97%B4%E7%9A%84%E8%A1%8C%E8%B7%9D-3eb8c1b8-d96a-4d9c-8bbb-48dc7e264d7f?ui=zh-CN&rs=zh-CN&ad=CN)提到：

    例如，单击“1.0”表示行距为早期版本的 Word 中使用的行距的一倍。单击“2.0”表示所选段落中的行距为
    双倍行距。单击“1.15”表示行距为 Word 2010 中使用的行距的一倍。

所以，不同Word版本中的基本行距可能真的不同。

我测试的结果是在字号为16 bp的情况下，“单倍行距”与“双倍行距”效果相同，这让我很不理解。也做了一些其他的测试，结果也很让我费解。

**Comment by zepinglee** [comment]
单倍与双倍相同？不会吧……不过我们的《规范》没有用到其他倍的行距，可以不用管这个问题了。
我读了那个页面，并没有讲“单倍行距”具体是多少，它只说“大小取决于所用的字体”。

**Comment by seisman** [comment]
仅对于`16 bp`字号来说，将行距因子设置为0到2之间的任意数字，实际行距都不变。
对于小四字号而言，单倍行距与双倍行距之间，则有明显不同。

不知道是Word的bug，还是说Word有特殊的考虑。

**Comment by zepinglee** [comment]
不知道微软怎么想的……

**Comment by seisman** [comment]
恩。单倍行距的准确定义还是需要考虑的。

在正文中可能差别不大，但是目前扉页中的行距与规范的示例中的行距差距还是挺大的。

**Comment by zepinglee** [comment]
你能不能去测量一下 Word 中单倍行距\baselineskip跟fontsize的比值？然后我写进\setfontsize{}命令，然后模板里所有单倍行距的地方用这个命令就可以了。
这里没有Word不太方便。

**Comment by seisman** [comment]
正如我上面解释的那样，字号为16 bp的情况下，“单倍行距”与“双倍行距”效果相同，而换做更小的字号时，单倍行距与双倍行距的效果是不同的。在没搞清楚这一点之前，应该没法测量`\baselineskip`与`fontsize`之间的比值吧？

**Comment by zepinglee** [comment]
那你测量一下 12bp 字体的？我先写个比1.2更合理的比值。

**Comment by seisman** [comment]
手动测量的办法精度太差

**Comment by bravepetrelc** [comment]
和英文一样加上行间距\s`etfontsize{16bp}[30bp]`后似乎正常了些。

OS X 10.10.5, BaiscTex2015

**Comment by zepinglee** [comment]
这个拖了好久了，必须 fix，统一设置行距为字号的 2 倍，

**Comment by zepinglee** [comment]
fixed in 31364e08

**Comment by zepinglee** [comment]
关于单倍行距的概念，刘海洋在 https://www.zhihu.com/question/62327906/answer/197899935 作了简单解释；另外在 https://www.zhihu.com/question/23349103 和 https://www.zhihu.com/question/23344087/answer/24288102 进行了更加深入的讨论。

总之，LaTeX 中可行的办法是使用量天尺。
