### ISSUE TITLE
请教如何修改目录中的章节标题，正文中章节标题，页眉中的标题以及图片与下文的距离

### ISSUE THREAD

**Issue by iamorz** [ustctug/ustcthesis#120]
1. 请问如何修改目录中的章节标题中的阿拉伯数字为中文数字，例如目录中的标题“第 1 章”如何修改为“第一章”；

2. 请问如何修改正文章节标题中的阿拉伯数字为中文数字，例如正文中的“第 1 章  绪论”修改为“第一章  绪论”；

3. 请问如何修改页眉中的阿拉伯数字为中文数字，例如页眉中的“第 1 章  绪论”修改为“第一章  绪论”；

4. 请问如何修改正文中图片与下文的距离，编译最新的模板之后感觉该距离过大。

因为上传图片失败，码字请求帮助。麻烦各位答主了:)

**Comment by zepinglee** [comment]
1. 《规范》正文要求的是“第 1 章”；
2. 同上
3. 同上
4. 我正在处理

**Comment by iamorz** [comment]
感谢 @zepinglee  大大的回复~~~

**Comment by zepinglee** [comment]
4. 没有问题，学校的要求是“段前 6 磅，段后 12 磅”，后面却是比较大

**Comment by zepinglee** [comment]
关于1，2，3，我在文档的使用说明第 4 节中新写了 《规范》中的若干问题。

https://git.ustclug.org/ustctug/ustcthesis/uploads/576ea4f4f367f0cf72764e5cf24c4424/ustcthesis.pdf

**Comment by zepinglee** [comment]
4. 我也觉得图片与下文的距离太大，caption宏包不靠谱啊。http://bbs.ctex.org/forum.php?mod=viewthread&tid=70899 这里有类似的问题，我再研究下

**Comment by sujerry** [comment]
@zepinglee 4.17日之前的版本中仍然存在图片上下间距距离上下文太大的问题问题。这个可以在文件ustcthesis.cls中在438行下面加一行“\setlength{\intextsep}{0pt}”，这样间距感觉会正好，你可以尝试一下。
ps: \intextsep表示文本页上，使用h位置选项排在页面中间的浮动体与上下文之间的垂直间距。

**Comment by zepinglee** [comment]
fixed in 55ca9721ece753a53aeb8120189d01e2760eb469
