### ISSUE TITLE
中文参考文献无法正常编译

### ISSUE THREAD

**Issue by zsynacl** [ustctug/ustcthesis#122]
![image](https://cloud.githubusercontent.com/assets/4392800/25046577/be21b2b8-2164-11e7-877b-37c4495329f4.png)

如图，参考文献中的第四个作者变成了问号

原条目：
```bibtex
@article{马2007基于插桩技术,
	title={基于插桩技术的并行程序性能分析方法设计和实现},
	author={{马桂杰} and {蒋昌俊} and {刘吟} and {王忱}},
	journal={计算机应用研究},
	volume={24},
	number={10},
	pages={225--228},
	year={2007}
}
```

还请能尽快提供个解决方案= =因为20号就要提交截止了/(ㄒoㄒ)/~~
感谢诸位大神

**Comment by zsynacl** [comment]
目前暂时使用en.cnki.com.cn提供的同一个文献的英文条目进行了替换，所以暂时可以不着急了

**Comment by zepinglee** [comment]
我编译的并没有问题：
![screen shot 2017-04-15 at 2 33 34 pm](https://cloud.githubusercontent.com/assets/12290822/25061418/8a1d80ee-21e8-11e7-8d39-0facce6c4160.png)
可能是因为你用了老一点的版本，用 git 更新一下应该就可以

**Comment by zepinglee** [comment]
PS 博士是20号截止嘛？

**Comment by zsynacl** [comment]
1.我试试
2.我们11系的硕士论文是20号。其他的不太清楚。

**Comment by zsynacl** [comment]
使用最新版的东西全部替换之后问题消失了。
