### ISSUE TITLE
学校新规范已出

### ISSUE THREAD

**Issue by hcAncientMoon** [ustctug/ustcthesis#123]
文件见链接 http://gradschool.ustc.edu.cn/ylb/material/xw/wdxz/32.pdf

**Comment by zepinglee** [comment]
什么时候实行啊？

**Comment by ywgATustcbbs** [comment]
很有可能在今年毕业季施行

**Comment by ywgATustcbbs** [comment]
新规定1.10那一页的注意事项里，写的真是醉了，基本上所有的内容都要求单面排即可，但是唯独符号说明要求双面排，而且后边第四点又说到中英文摘要也要双面排，这与第二点矛盾……

**Comment by zepinglee** [comment]
>  中科大火灾科学国家重点实验室闫维纲在编写过程中从学生的角度提出了很多宝贵建议。

哈哈哈哈

**Comment by zepinglee** [comment]
也不算是矛盾，估计是不同的人写的，结果表述不清。

大概意思是，全文用 onside，摘要、符号说明后面用 \cleardoublepage

**Comment by zepinglee** [comment]
我刚发邮件问了下研究生院的李兴权老师，他说是“基本上开始执行”……

那我们要不要更新到最新的规定？

**Comment by zepinglee** [comment]
我尽可能地写吧，更新的内容我新开了一个 issue #124
