### ISSUE TITLE
新版《撰写手册》内容提要

### ISSUE THREAD

**Issue by zepinglee** [ustctug/ustcthesis#124]
## 新版主要变化

- [x] 1.2 摘要关键词间隔符号
- [x] 1.4 目录之前的内容及目录本身不列入目录内
- [x] 1.10(1) openany 方式
- [x] 1.10(2) 符号说明不加页码
- [x] 1.10(3) 页码居中（矛盾）
- [x] 1.10(8) 空白页没有页眉
- [x] 2.2 二级以上节标题带缩进
- [x] 2.2 二级节标题（subsubsection）下采用“1.”“(1)”“①”
- [x] 2.9.1 规定了 \leqslant \geqslant 数学符号
- [x] 2.11.3 表字号略小
- [x] 2.13.1.2 脚注用带圈序号，脚注线，缩进两字
- [x] 2.14.1.1(4) 允许文献序号作为叙述文字的一部分
- [x] 2.14.2(1) 参考文献 俄文和日文的 et al
- [x] 2.14.2(4) 参考文献 列表中名字与年份之间为.
- [x] 2.14.3(3) 参考文献 不出现[S.l.]: [s.n.]
- [x] 3.5 目录序号与题名间空一字
- [x] 3.6 图号、图题加粗
- [x] 附录B 作者姓名居左
- [x] 附录B 完成时间包括年月日
- [x] 附录B 专业博士、硕士封面
- [x] 附录B 英文 "Author's name" 改为 "Author"
- [x] 附录B 摘要的页眉中间加入空格
- [x] 附录B 章题为两字时中间空两字，三字时空一字，四字时空半字，四字以上不空

**Comment by zepinglee** [comment]
新版的内容暂时 push 到 v3.0 分支。

**Comment by ywgATustcbbs** [comment]
2.14.3(3) 参考文献 不出现[S.l.]: [s.n.]
这个原文应该是两者最多出现一个，不能同时出现

**Comment by ywgATustcbbs** [comment]
封面有个很丑的框？
这个好像是直接从老版的word模板复制下来的，以前大家好像都无视了

**Comment by zepinglee** [comment]
没错，就是这个意思。

**Comment by zepinglee** [comment]
好消息！我就《撰写手册》中的问题联系了一下研究生院的李兴权老师，他给出的答复是：

1、页码可以标在右下角。

2、封面的灰框不需要。

3、校徽按照学校官网白底蓝字。

4、目录行距范例中是20磅，根据经验确定一个值，再来修改手册。

5、封面各个标题距离边的距离可以根实验确定一个比较美观的的值，然后修改手册。

@ywgATustcbbs @seisman @jiaopjie
