### ISSUE TITLE
版本2.2图片的上边距太小

### ISSUE THREAD

**Issue by kpskp77** [ustctug/ustcthesis#125]
修正图片下边距之后，上边距是不是太小了，几乎挨着了。

github图片上传不了，放在百度云了https://pan.baidu.com/s/1kV6x6yr

**Comment by zepinglee** [comment]
呃……上面又太小了……

**Comment by zepinglee** [comment]
Fixed in 798a3b165a464bdc96110a22da10b38b85e41b7f .

今天 GitHub 被墙了，我一时 push 不上来，你可以从校内镜像网站
 https://git.ustclug.org/ustctug/ustcthesis 上 merge 。

**Comment by kpskp77** [comment]
修复好了，非常感谢！
