### ISSUE TITLE
参考文献中的问题

### ISSUE THREAD

**Issue by simplecherry** [ustctug/ustcthesis#127]
中文学位论文标注[Master][Doctor]，这个是规范要求的吗？
中文参考文献用的好像是半角符号

**Comment by zepinglee** [comment]
1. 这是按照 2007 版的《规范》
2. 因为句点是必须用的，如果其他符号用全角，会显得太丑；而且 xecjk 处理的时候还会加上一个空白，所以我认为问题不大

**Comment by simplecherry** [comment]
能否给个引用online类型的的.bib文件范例，edition这里填什么?address这里填link?

**Comment by zepinglee** [comment]
关于online 前不久修复了一个 bug，你要 update 一下／

```
@online{noauthor_latex_2017,
	title = {{LaTeX}},
	url = {https://en.wikipedia.org/w/index.php?title=LaTeX&oldid=770118682},
	year = {2017},
}
```

**Comment by simplecherry** [comment]
问题已解决，感谢模板开发者们
