### ISSUE TITLE
中文参考文献与文献类型之间有一个空格，而英文的没有，现在还不知道怎么去掉

### ISSUE THREAD

**Issue by codespjw** [ustctug/ustcthesis#128]
例如，自动控制原理 [M].

等等。

**Comment by zepinglee** [comment]
xecjk 会在汉字和英文字符之间自动插入一个空格

**Comment by zepinglee** [comment]
我还是设置成统一加空格吧

**Comment by codespjw** [comment]
能设置成不加空格吗？一般规定是不加空格，谢谢。

**Comment by zepinglee** [comment]
这个我也不会，我去问问

**Comment by codespjw** [comment]
多谢多谢，我会及时关注这个帖子。

**Comment by zepinglee** [comment]
Fixed in 8d35210.

现在的 bst 还有些 bug ，欢迎及时指出！

**Comment by codespjw** [comment]
It works perfectly. 非常感谢! 

对于bst文件我也有一些修改，但是我没有权限上传，而且我用git的习惯还没有养成很好。第一，可以给我上传的权限么？第二，我上传之后你可以修改了再加入到模板中么？我是希望通过这个小工程来学习一下git更高级一点的用法，谢谢！

bst还存在的问题有：

1. 学位论文后面中英文还没有区分，现在都是[Phd]，而当是中文时，应该为[博士]或[硕士]，这个我已经修复了，但无法上传；

2. 期刊名，会议名，书名等应为斜体，这个我已经修复了，但无法上传；

另外，其他方面我也修复了很多问题，都没有上传到这个模板中，例如，

 图，表，算法的list前应为“图1.1”而不是“1.1”.等。

希望能够通过这个工程实现共同进步，谢谢！

**Comment by zepinglee** [comment]
你可以 fork 一个然后 push 到你自己的 repo 里，然后你可以对我发起 pull requset。

另外，研究生发布了新版的《撰写手册》，我正在根据新版的内容开发，所以有问题你提一下就好了。

1. 这个在新版的学校规范中已经取消了；

2. 本科生要求是斜体，但是研究生部要求使用正体；

3. 这个学校没有规定，我按照 LaTeX 默认来的；而且，图的 list 会看到一排的“图图图”，这样有点丑

**Comment by codespjw** [comment]
原来是这样，谢谢啦！
