### ISSUE TITLE
figure 导致页码和正文重叠

### ISSUE THREAD

**Issue by simplecherry** [ustctug/ustcthesis#129]
新版本目录行距变大了
为什么代码中`\captionsetup[figure]`被注释掉了？

**Comment by zepinglee** [comment]
see #126

**Comment by simplecherry** [comment]
发现有的页码和正文互相重叠了。。。
用之前的版本没有这个问题

**Comment by zepinglee** [comment]
你截图让我看看

**Comment by simplecherry** [comment]
![default](https://cloud.githubusercontent.com/assets/15326036/25370259/04fc39d8-29bc-11e7-877b-5a99a427894c.png)

**Comment by zepinglee** [comment]
这个是正文页的吧？
可以把你的代码 push 到一个 repo 上让我看一下嘛？

**Comment by zepinglee** [comment]
我猜测是图上方的距离问题导致到，你这一页应该有图吧？

**Comment by simplecherry** [comment]
对的，有图。
我把原来的`\captionsetup[figure]`加上就没有这问题了

**Comment by zepinglee** [comment]
但是不是图上方的距离太大了？

你试下把

 \setlength{\intextsep}{0bp}
\captionsetup[figure]{
    position = bottom,
    aboveskip = 6bp,
    belowskip = 12bp,
}

换成

\captionsetup[figure]{
    position = bottom,
    aboveskip = 6bp,
    belowskip = {12bp-\intextsep},
}

**Comment by simplecherry** [comment]
嗯？原来的代码就是12bp-\intextsep。最近的cls文件里没有这段代码的。

**Comment by zepinglee** [comment]
原来用 {12bp-\intextsep} 会出错，所以我暂时注释掉了；后来加上calc宏包，好像是忘记去掉注释错了。

你在dtx文件里面修改一下试试

**Comment by simplecherry** [comment]
嗯，看dtx文件的记录应该是忘记去掉注释了。
加上之后没有问题，thx。

**Comment by zepinglee** [comment]
fixed in 840b329, 但是我感觉去掉captionsetup[figure]的定义也不至于导致 vertical skip 出错呀

**Comment by simplecherry** [comment]
好像还是不对，仔细看还是有重叠。。。
这一页有两个图片，图片下方是subsection。
把subsection注释掉当成正文就没这个问题了，改成section或者subsubsection问题依然存在

**Comment by zepinglee** [comment]
可能是 subsection 标题前的距离的bug，见 #102 。我为了兼容性只能手动设置beforeskip，但是只考虑了前面是段落正文的情况，所以在前面是图片时就导致距离不对了。

如果你把 ctex 升级到最新，可以启用 ctex 的 fixskip，然后把beforeskip设置成正确的数值。

**Comment by jiaopjie** [comment]
`section` 与 `subsection` 的 `beforeskip` 似乎不用手动设置.
`chapter` 的 `beforeskip` 需要修正是因为它一定出现在当前页的顶端, 所以它之前的空白是强制产生的. 在这种情况下会产生额外的空白.
但 `section` 之类的出现在当前页顶端时, 它前面的空白会被吃掉. 所以也不会产生额外的空白, 也不需要修正.

**Comment by zepinglee** [comment]
我刚刚看了一下代码，事实上我也没有手动设置section/beforeskip（只设置了chapter的）；
那这个bug就比较令人费解了，我还是希望用源代码复现一下这个bug

**Comment by simplecherry** [comment]
我上传了我的论文源文件，你可以看一下
[](https://github.com/simplecherry/ustcthesis.git)

**Comment by zepinglee** [comment]
我改成了`\begin{figure}[htbp]`，然后两张图片就占满了全部的页面……算是暂时解决了这个问题吧……

我记得 thuthesis 里面有对 float 分页的修正，但是还没有全部理解。

**Comment by zepinglee** [comment]
PS，你可以直接在main.tex里面写，我在毕业季不会动这两个文件的
