### ISSUE TITLE
使用autoref的时候，章节引用显示的是chapter X

### ISSUE THREAD

**Issue by zsynacl** [ustctug/ustcthesis#130]
能否改为中文？没有尝试其他的autoref

**Comment by zepinglee** [comment]
图表什么的可以重定义 `\tableautorefname`，但是章、节就比较麻烦

**Comment by jiaopjie** [comment]
这个我设置过. 试试

    \def\chapterautorefname~#1\null{\CTEXthechapter\null}

**Comment by jiaopjie** [comment]
另外,学校规范里没要求等宽字体需要修改为 `Courier New` 吧? 我觉得 `CM` 的等宽字体挺好的...

**Comment by zepinglee** [comment]
1. ok 我可以加进模板里
2. 没有要求，随手一写。你可以在main.tex 里面修改。

**Comment by zepinglee** [comment]
@jiaopjie 这样不行，另外 \def 好像不是这么用的吧
