### ISSUE TITLE
首页和参考文献格式

### ISSUE THREAD

**Issue by kylinhao** [ustctug/ustcthesis#131]
![image](https://cloud.githubusercontent.com/assets/5234656/25375665/0381e59a-29d4-11e7-9787-419ce1e72b19.png)

![qq 20170425161430](https://cloud.githubusercontent.com/assets/5234656/25375552/a211c44c-29d3-11e7-8585-350aa3014fe3.png)

![image](https://cloud.githubusercontent.com/assets/5234656/25375630/e1733350-29d3-11e7-80e0-b066df175a70.png)

下面2个都是打印店的老师让改的，还有图2中的对应首字母要大写

还有图目录和表目录，如果各占一页，应该放到一页的正反面，而不是2张纸，对于算法空白的，应该删除空白页

**Comment by jiaopjie** [comment]
打印店的老师管的还真宽...学校规范就是这么规定的, 有什么办法.

打印店的老师大概就是好心提醒你一下. 毕竟他既不是你的老板, 又不是学位办的人, 你的封面合不合格还不是他说了算的.

图目录和表目录都从奇数页开始, 这也是合理的. 如果你有个性化的需求, 可以使用文档选项 `openany` (当然, 此时正文里每一章的第一页也不一定从奇数页开始).

算法空白的时候, 只需要在主文档 `main.tex` 中把算法索引那一行注释掉就行了...

**Comment by zepinglee** [comment]
1. 封面尺寸问题：你可以用尺子量一量那个尺寸，然而对比下《规范》：word 版的没按照《规范》。

2. bib 的 url 问题：我觉得有道理，在 76708ca 中修复。

3. 图目录奇数页开启问题：2007版《规范》没有说清楚，但是新版的《撰写手册》是要求“图表的清单须另页起”（奇数页开启）。算法页你要手动注释掉。

4. “还有图2中的对应首字母要大写”这句话我不太理解
