### ISSUE TITLE
关于目录的字体大小

### ISSUE THREAD

**Issue by Hedilict** [ustctug/ustcthesis#133]
![image](https://cloud.githubusercontent.com/assets/14339418/25377373/dca94980-29d9-11e7-9e6e-e8f2befbf46e.png)
要求的子目录字体貌似是不变的。
而模板显示的是递减的。

**Comment by zepinglee** [comment]
我按照研究生的要求实现的，没照顾到本科生这里……

**Comment by Hedilict** [comment]
有一份word，不知道怎么发给你。
