### ISSUE TITLE
参考文献标注形式ustcnumerical为什么基本都是上标呢？

### ISSUE THREAD

**Issue by codespjw** [ustctug/ustcthesis#135]
模板中给出的参考文献的标注形式ustcnumerical，如果我想说，见文献[2]，就变成了见文献^[2]，请问如何修复呢？

**Comment by zepinglee** [comment]
你是本科生还是研究生？

2007版规范中要求按照gb/t 7714-2005，那个规定用上标形式；

**Comment by codespjw** [comment]
我是研究生，我是说这个引用方式“在文献^[2]中”，在文章中是不合理的，甚至是错误的，一般会用“在文献[2]中”。另外，\cite，\citep和\citep*在效果上并没有什么区别。

**Comment by zepinglee** [comment]
1. nature 的citation style就是角标，所以谈不上“不合理或者错误”

2. GB/T 7714-2005 如下：
![screen shot 2017-05-02 at 6 13 54 pm](https://cloud.githubusercontent.com/assets/12290822/25614120/4061110e-2f63-11e7-9737-13c56f8ee48e.png)

3. numerical 模式下确实 \cite 等价于 \citep \citep*

4. 我可以加上在文中引用的模式，但是这不是  bug fix

**Comment by zepinglee** [comment]
在 fd5a397 中加入 ustcinline ，你可以替代 ustcnumerical

**Comment by codespjw** [comment]
谢谢！

没有说这是一个bug。

我的意思是，应该定义不同效果的 \cite， \citep， \citep*至于用哪一个，得由用户来决定。

再次感谢！
