### ISSUE TITLE
英文abstract只有一页时，pdf书签出错

### ISSUE THREAD

**Issue by ttlbyte** [ustctug/ustcthesis#136]
英文abstract只有一页时，pdf书签会被错误的链接到英文abstract的第二页

**Comment by zepinglee** [comment]
好像是目录的PDF书签链接到abstract第二页了吧？这是个bug

**Comment by jiaopjie** [comment]
这个无关紧要了, 只能说不完美了.

添加 PDF 书签之前可能需要先 `\clearpage` 或者 `\cleardoublepage`.

**Comment by zepinglee** [comment]
Fixed in ca33bae919d579eafff730997aaf07160d55b6d0.
