### ISSUE TITLE
Need to change the citation style inside the thesis text, ustc thesis template

### ISSUE THREAD

**Issue by MOmarFarooq** [ustctug/ustcthesis#138]
I am using the format of Marked References inside the thesis like [1], blah blah blah [2].
I want to use the style for marked references like as I shown in the Image. 
Please have a look on the image and guide me how to do this in latex using ustc thesis template.

Thank you
![citation style](https://cloud.githubusercontent.com/assets/20922494/25845896/50dfdaea-34e2-11e7-9ac5-25453830f703.jpg)

**Comment by zepinglee** [comment]
I guess you are trying to use "inline" style instead of superscript. Adding `\citestyle{ustcincline}` into the preamble should work.

**Comment by MOmarFarooq** [comment]
Well \citestyle{ustcnmerical} with the modification of \citep[][]{bibid} works for me at the moment, but the question is, I used this format "\citep[][]{bibid}" in first citation and all the citations changed automatically to the desired format which I have shown in the above picture.
Can you please focus on it.

Thanks in advance

**Comment by zepinglee** [comment]
Sorry I just misunderstood you. Do you want to have a blue line marked under the author's name?
