### ISSUE TITLE
bachelor thesis title page centering

### ISSUE THREAD

**Issue by lrunze** [ustctug/ustcthesis#139]
I want to make the bachelor thesis title page(Chinese 姓名，专业 and so on, English Name and so on) to be centered. And I trying to embedding tabular into table and using \centering, but it does't work.

Thank you~

**Comment by zepinglee** [comment]
The tabular containing author's name (and so on) is placed at a fixed position of the page using `\tikz` command. If you want to center it horizontally, you can follow the tikz settings of other entries like thesis title or logo.

**Comment by lrunze** [comment]
OK, thanks for your advice and it works~
