### ISSUE TITLE
Wrong format when cite @inproceedings in bibtex entries

### ISSUE THREAD

**Issue by zainryan** [ustctug/ustcthesis#140]
I use ustcnumerical.bst and below is the snippet of my bib file.

```
@inproceedings{atikoglu2012workload,
	title={Workload analysis of a large-scale key-value store},
	author={Atikoglu, Berk and Xu, Yuehai and Frachtenberg, Eitan and Jiang, Song and Paleczny, Mike},
	booktitle={ACM SIGMETRICS Performance Evaluation Review},
	volume={40},
	number={1},
	pages={53--64},
	year={2012},
	organization={ACM}
}
```

The final effect of generated pdf file looks like the third entry in
https://ibb.co/mr4RT5

**Comment by zepinglee** [comment]
你用的是哪个bst？以及提供一下你的 bib 文件

**Comment by zainryan** [comment]
I use ustcnumerical.bst and below is the snippet of my bib file.

`@inproceedings{atikoglu2012workload,
	title={Workload analysis of a large-scale key-value store},
	author={Atikoglu, Berk and Xu, Yuehai and Frachtenberg, Eitan and Jiang, Song and Paleczny, Mike},
	booktitle={ACM SIGMETRICS Performance Evaluation Review},
	volume={40},
	number={1},
	pages={53--64},
	year={2012},
	organization={ACM}
}`

The final effect of generated pdf file looks like the third entry in [http://img.027cgb.cn/20170510/2017511610871201743.png](url)

**Comment by zepinglee** [comment]
What is the problem?

**Comment by zepinglee** [comment]
Can you explain what is wrong?

**Comment by zainryan** [comment]
There are no emphasis on the name of proceedings and an extra // before it,

**Comment by zepinglee** [comment]
I guess you are an undergraduate. Actually the BibTeX style is using the exact graduates' thesis standard (aka. GB/T 7714-2005). I worked little on bachelor's bibtex style because it is not clearly defined. 
But if you don't like it, you can try `\bibliographystyle{unsrtnat}`.

**Comment by zainryan** [comment]
Maybe there is some misunderstanding, would u mind compare the visual difference of 1st entry(journal bib entry) in the aforementioned picture with the 3rd entry(inproceeding entry). Thx!

**Comment by zainryan** [comment]
It seems the web link of my picture is broken.. I'll fix it tomorrow. Sorry for the inconvience.

**Comment by zepinglee** [comment]
The standard [关于本科毕业论文（设计）格式和统一封面的通知](http://www.teach.ustc.edu.cn/document/doc-administration/4032.html) says 
> 外文期刊名用白斜体

which means the title of journals in foreign language should be emphasized. I think the booktitle of proceedings is different from a journal, so I did not emphasize it.

**Comment by zainryan** [comment]
I see. Thanks for ur response. However, why there is a "//" before the name of proceedings.(have updated the pic link)

**Comment by zepinglee** [comment]
It is following the standard for graduates.
