### ISSUE TITLE
参考文献的序号

### ISSUE THREAD

**Issue by Hedilict** [ustctug/ustcthesis#141]
为什么我的参考文献前面没有序号呢
![image](https://cloud.githubusercontent.com/assets/14339418/26030638/01d538bc-388b-11e7-93ef-ce77c1d542ac.png)
![fcg9g nucji chzmv68dk8](https://cloud.githubusercontent.com/assets/14339418/26030639/06b59aa2-388b-11e7-93f0-039c0d0af5ad.png)

**Comment by zepinglee** [comment]
默认是author-year，所以没有序号，你要把 bibliographystyle 改成 numerical

**Comment by Hedilict** [comment]
![image](https://cloud.githubusercontent.com/assets/14339418/26031088/762a75ac-3899-11e7-8bbf-f0e202ba03b3.png)
我这样写不对吗？还是没有效果。

**Comment by zepinglee** [comment]
\citestyle{ustcnumerical}
\bibliographystyle{ustcnumerical}

**Comment by zsynacl** [comment]
先看一下README，再看一下ustcthesis.pdf里面的说明。

**Comment by zepinglee** [comment]
这个地方的接口没设计好，而且也没处理本科生的情况……尤其是写到了main.tex，导致我现在也不太好改，所以在3.0版本里面修正了

**Comment by Hedilict** [comment]
谢谢两位，解决了这个问题。
