### ISSUE TITLE
更改章节样式问题

### ISSUE THREAD

**Issue by sunnaruto** [ustctug/ustcthesis#142]
想把汉字标题 第一章 改为阿拉伯数字 1  1.1  1.1.1
在 .tex中加入如下代码不生效
\renewcommand\thesection{\arabic{section}}
\renewcommand\thesubsection{\thesection.\arabic{subsection}}
\renewcommand\thesubsubsection{\thesubsection.\arabic{subsubsection}}
修改.cls中的这一段不太会
\def\chapterautorefname~#1\null{第~#1~章\null}%
  \def\sectionautorefname~#1\null{第~#1~节\null}%
  \def\subsectionautorefname~#1\null{第~#1~小节\null}%

小白一枚 望解答，谢了

**Comment by zepinglee** [comment]
本科生？

**Comment by sunnaruto** [comment]
因为学校要求的呀。。。
知道怎么改了   cls文件里把这地方改一下 把这里chapter 注释掉的 name   = {}, 放到\setcounter{secnumdepth}{3} 里的 chapter 里 

`\ifustc@opt@bachelor
\setcounter{secnumdepth}{4}
\ctexset{
	chapter={
		format = \centering\sffamily\setfontsize{16bp},
		%name   = {},
		number =  \arabic{chapter},
	},
	section = {
		format = \centering\sffamily\setfontsize{15bp},
		name   = {},
		number =  \thechapter.\arabic{section},
	},
	subsection = {
		format    = \sffamily\setfontsize{14bp},
		number    =  \thesection.\arabic{subsection},
		aftername = {.\},
	},`

这样目录，章节都会是阿拉伯样式了 1  1.1  1.1.1 ，不知道怎么就搞出来了，虽然不明白原理。。。

**Comment by zepinglee** [comment]
哪个地方要求的？！

**Comment by sunnaruto** [comment]
再求助一个问题 怎么加上参考文献编号 

\bibliographystyle{ustcnumerical}

用上边的语句没反应

**Comment by sunnaruto** [comment]
学校不一样。。。我只是套用模版，发现你的在mac上用着超级方便

**Comment by zepinglee** [comment]
这样……你解释清楚嘛，不然我以为模板有问题；

1. 如果你在写你们学校的模板，建议修改 dtx 文件，因为 `make` 会覆盖掉 cls 文件；

2. 你修改的章节编号应该是正确的，因为模板中用的是 ctex 的接口，不用 `\thechapter`，详情见 ctex 的使用说明；

3. numerical 风格参考文献带编号，你要修改 main.tex 的 `\bibliographystyle{}`

4. 这个模板就是针对跨平台设计的

**Comment by sunnaruto** [comment]
抱歉，表述确实不清造成困扰了
我就是在main.tex 更改的`\bibliographystyle{}` ，
`\bibliographystyle{ustcauthoryear}
%\bibliographystyle{ustcnumerical}`
模版里的两种样式显示效果都是不带编号的，不知道是不是操作有问题

**Comment by zepinglee** [comment]
`\bibliographystyle{ustcnumerical}` 也不带编号嘛？那你再试下
```
\bibliographystyle{ustcnumerical}
\citestyle{ustcnumerical}
```

**Comment by sunnaruto** [comment]
可以了，谢谢啦
