### ISSUE TITLE
参考文献英文作者名全变成大写

### ISSUE THREAD

**Issue by HongjianFang** [ustctug/ustcthesis#144]
按照新版本说明编译，参考文献选择的是authoryear,编译过后参考文献中英文作者名都变成大写了。请问如何解决呢？谢谢
<img width="437" alt="bug" src="https://cloud.githubusercontent.com/assets/8549718/26517732/919aa00e-42d1-11e7-8056-8640187d6986.png">

**Comment by zepinglee** [comment]
本科生还是研究生？

**Comment by HongjianFang** [comment]
研究生的。

**Comment by zepinglee** [comment]
仔细看《撰写手册》

**Comment by zepinglee** [comment]
《撰写手册》手册上没有规定参考文献姓名要大写，但是给的例子都是大写的，所以我暂时按照这个写。

另外，我向研究生院老提出建议改成首字母大写。

**Comment by HongjianFang** [comment]
是的，全大写感觉怪怪的。不过已经按照大写的去打印了。多谢！

**Comment by Lewis-Liu** [comment]
现在学校提供的word版中已经改成首字母大写了。
https://gradschool.ustc.edu.cn/static/upload/article/file/1647939735472/4d3ae966d71d41c8aea116456f9a0a66.doc
![Snipaste_2022-04-27_15-25-12](https://user-images.githubusercontent.com/5558564/165464360-1507eff0-1ab8-41f0-9b0c-c09af464c68d.jpg)

那该如何修改代码呢？
