### ISSUE TITLE
编译错误 \CTEXifname Undefined control sequence

### ISSUE THREAD

**Issue by XueDx** [ustctug/ustcthesis#145]
之前用的5月4日版本，最近想更新版本。

编译最新版(5月28日)模板时，make或‘xelatex main’ 出现如下错误，试了 ubuntu + Texlive， Mac + Texlive，在线环境 overleaf，都有同样问题。
但是 make doc 通过。

逐个试验，5月6日版本没问题，5月7日更新“add space into titles”开始出现如下问题。
> ! Undefined control sequence.
<argument> \CTEXifname
                       {\CTEXthechapter \quad }{} \protect \spacetitle {摘要}
l.3 \begin{abstract

**Comment by zepinglee** [comment]
现在 travis 上的 build 是通过的，我感觉是你的版本太低；

你用的 texlive 是哪一年版的？建议 2016

**Comment by XueDx** [comment]
本地用的是texlive 2016，科大的镜像: http://mirrors.ustc.edu.cn/CTAN/systems/texlive/Images/
在线版本 overleaf 的log显示为"This is XeTeX, Version 3.14159265-2.6-0.99996 (TeX Live 2016/Debian) (preloaded format=xelatex 2017.3.29) "

**Comment by zepinglee** [comment]
这就奇怪了，需要看一下你的源码。

可以传到 github 上的 repo 嘛？（把需要保密的信息去掉）

**Comment by XueDx** [comment]
我编译模板和更新自己的文档是同样错误。
如下是模板，从ustctug/ustcthesis checkout的两个版本
ustcthesis20170506-e1877b4
https://www.overleaf.com/9760464bnsxrdprgkfd#/35619424/
ustcthesis20170507-5b0a19b
https://www.overleaf.com/9760489cvxszgnyjcgr#/35619586/

**Comment by zepinglee** [comment]
这是由于 \CTEXifname 是 ctex 在 2016 年 9 月 18 号才引入的，你用的 texlive 2016 没有更新宏包。

我在 8ebf60b 中做了暂时的修改，应该可以兼容你的版本，但是不太完美，稍后研究。

**Comment by XueDx** [comment]
好的，编译通过了。
