### ISSUE TITLE
参考文献显示顺序

### ISSUE THREAD

**Issue by XueDx** [ustctug/ustcthesis#146]
开启 \listoffigures后引用文献的显示顺序发生改变。

如https://www.overleaf.com/9760853fnqwvtjckpgf#/35621333/ 第四章

```
第一次\cite{knuth86a}，
第二次\cite{tlc2}，
第三次\cite{slg}，
第四次\cite{ljs}，
第五次\cite{cjb}，

测试图片

\begin{figure}[htbp]
\centering
\includegraphics[width=.3\textwidth]{ustc_logo_fig}
\caption{测试图片\cite{ljs}}
\label{fig:logo_2}
\end{figure}

\begin{figure}[htbp]
\centering
\includegraphics[width=.3\textwidth]{ustc_logo_fig}
\caption{测试图片\cite{cjb}}
\label{fig:logo_3}
\end{figure}

\autoref{fig:logo_2}引用了文献\cite{ljs}，\autoref{fig:logo_3}引用了文献\cite{cjb}。
```

main.tex 未开启 \listoffigures
![fs_491](https://cloud.githubusercontent.com/assets/3871016/26530035/dccbc9de-43ff-11e7-8cac-6379801d6477.png)

main.tex 开启 \listoffigures
第四次\cite{ljs}，第五次\cite{cjb} 对应的文献出现在图片的caption里，会出现在图目录里，图目录在正文之前，判断这两篇文献顺序靠前，显示为第四次[1]，第五次[2]。
 
![fs_490](https://cloud.githubusercontent.com/assets/3871016/26530084/76d484da-4400-11e7-9179-b1c536a17dfd.png)

**Comment by zepinglee** [comment]
这不是bug，这是因为lof 调用了caption的的\cite，所以引用的序号就是1；解决方案：\caption[xxx]{xxx\cite{yyy}}
