### ISSUE TITLE
参考文献格式问题

### ISSUE THREAD

**Issue by guohao916** [ustctug/ustcthesis#147]
![referenceerror](https://cloud.githubusercontent.com/assets/4317838/26530317/6f380e68-4405-11e7-8ee1-f7e2c8941038.png)

如图所示，使用新版后参考文献中依旧出现[S.l]这种字样，同时当论文作者超过3个以后，之后的作者名字不再显示，自动缩写为.et al了。

**Comment by zepinglee** [comment]
能不能去看《撰写手册》？
