### ISSUE TITLE
章节从偶数页开始

### ISSUE THREAD

**Issue by yuewu001** [ustctug/ustcthesis#148]
博士论文编译以后章节内容从偶数页开始

**Comment by zepinglee** [comment]
你的 main.tex 中第一章前的章节内容是怎么安排的？

**Comment by zepinglee** [comment]
![screen shot 2017-06-03 at 4 40 09 pm](https://cloud.githubusercontent.com/assets/12290822/26752126/5710f73a-487b-11e7-8610-cb13ed25ceba.png)

学校新的标准要求章节之间不插入空白页，也就是在任意位置开启 openany，不分奇偶页。
