### ISSUE TITLE
扉页"学位论文"字间距以及图注字体行间距

### ISSUE THREAD

**Issue by jiaopjie** [ustctug/ustcthesis#149]
发现新版本加入了专业学位类型啊, 特意试了一下.

1. 增加 `professional` 选项的时候, `专业博士学位论文` 几个字变的比平常拥挤了, 看起来比较明显. 这个应该是由于规范要求设定的页面宽度不足引起的. 不过的确挤的蛮明显的, 是否可以考虑对这一行增加宽度, 即使超出规范要求的页面文本宽度, 也比这么拥挤好看啊.

2. 使用 `professional` 选项之后, 还需要手动设置 `\professionaltype` 与 `\enprofessionaltype`. 自动设置是不是更好.

3. 图与表的注用的似乎是 `small` 尺寸, 行间距比较小. 是否使用正文的行间距, 或者页眉的行间距比较好. 另外, 不记得在哪看到有人提到, 算法的行间距问题, 似乎可以考虑重定义 `\small` 命令. 或者至少应该在模板文档 `main.tex` 中把算法的示例修改下行距.

**Comment by zepinglee** [comment]
1. 我同意，我会反馈给研究生院的老师。

2. 我不知道这个“专业硕士类型”是要填什么内容，不知道能不能自动设置。

3. 有道理，我只定义了  \normalsize 以及对应的行距，\small \footnotesize 之类的就没处理，所以 \small 的行距是默认的 1.2 倍字号，导致有点太小

**Comment by zepinglee** [comment]
1 已经反馈；
3 已修复
