### ISSUE TITLE
安装的时候cp命令出错。

### ISSUE THREAD

**Issue by ruanyuanyu** [ustctug/ustcthesis#151]
**具体问题：**
[yu@yu:master]$make install
latexmk -xelatex ustcthesis.dtx
Latexmk: This is Latexmk, John Collins, 19 Jan. 2017, version: 4.52c.
Latexmk: All targets (ustcthesis.xdv ustcthesis.pdf) are up-to-date
mkdir -p /opt/texlive/texmf-local/{doc,source,tex}/latex/ustcthesis
mkdir -p /opt/texlive/texmf-local/bibtex/bst/ustcthesis
cp ustcthesis.dtx /opt/texlive/texmf-local/source/latex/ustcthesis
cp ustcthesis.cls /opt/texlive/texmf-local/tex/latex/ustcthesis
cp ustcthesis.pdf /opt/texlive/texmf-local/doc/latex/ustcthesis
cp ustc{numerical,authoryear}.bst /opt/texlive/texmf-local/bibtex/bst/ustcthesis
**cp: 无法获取"ustc{numerical,authoryear}.bst" 的文件状态(stat): 没有那个文件或目录
make: *** [install] 错误 1**

**正确结果：**
此处大括号应该被扩展开。大扩号扩展应该是属于shell的功能吧，cp本身应该无法处理吧。

**Comment by zepinglee** [comment]
可能展开时不一样，我用的是 zsh 5.2 (x86_64-apple-darwin16.0)、GNU Make 3.81

**Comment by zepinglee** [comment]
你修改一下然后发个PR

**Comment by zepinglee** [comment]
好像是因为你的 /bin/sh 不是bash，你试下在 Makefile 里加一句 `SHELL=/bin/bash` 行不行，参考 https://stackoverflow.com/questions/6681624/how-to-handle-shell-expansions-in-gnu-make-under-ubuntu

**Comment by ruanyuanyu** [comment]
嗯，试了下，是这个原因～

**Comment by zepinglee** [comment]
嗯我稍后修复吧，先关了你的 PR

**Comment by ruanyuanyu** [comment]
ok.

**Comment by zepinglee** [comment]
Fixed in 185f7c2f63b16643566f44a7d5e97abca78e61f1. 

你测试一下
