### ISSUE TITLE
新章节不从奇数页开始

### ISSUE THREAD

**Issue by litao3rd** [ustctug/ustcthesis#154]
Hi, 我使用了最新版本的 v3.0 的模板，但是 print 格式下，新章节不从奇数页开始了，这是为什么？哪里需要修改吗？

**Comment by litao3rd** [comment]
在手册中找到这么一句话“论文正文分章节撰写，每张应另起一面”。按照这里的意思，应该不要求奇数页开始。但是从历史论文来看，都是从奇数页开始的，这里不清楚审稿老师会是什么想法。如果我需要那样设置，该在哪里修改代码？谢谢

**Comment by zepinglee** [comment]
《手册》第 6 页脚注定义了“另面起”；第 1.10 (2) 节说“各部分之间不必留空白”。所以我建议按照要求去做。

从历史来看，关于是否从奇数页开启的问题，老版的《规范》有两处自相矛盾，所以 LaTeX 模板按照常见规则设计为奇数页开启。

如果你坚持要改，ustcthesis.dtx 有一处 \LoadClass[…, openany, …]{ctexbook}需要改为 openright，但是有可能其他地方也要改。

**Comment by zepinglee** [comment]
参考 issue #124

**Comment by litao3rd** [comment]
收到，已咨询老师可以不留空白页面。谢谢
