### ISSUE TITLE
subsubsection前的空白比section和subsection前的空白大，这正常吗？

### ISSUE THREAD

**Issue by iamabug** [ustctug/ustcthesis#156]
如题，不知道模板如此，还是我哪个地方出错了，请指教，谢谢。

**Comment by zepinglee** [comment]
我没观察到这个现象，可以附上你的代码和截图吗？

**Comment by iamabug** [comment]
这是代码，intro.tex：

![image 2](https://user-images.githubusercontent.com/11364605/33805183-58d6e0c0-ddef-11e7-94b5-72a13c814c3e.png)

这是效果：

![image 1](https://user-images.githubusercontent.com/11364605/33805173-28f76154-ddef-11e7-9719-fcd8a2708dee.png)

好像三级以后的小标题前的空白都比较大，我这是在clone的项目里测试的，只动了main.tex、abstract.tex和intro.tex。

**Comment by zepinglee** [comment]
嗯这是个问题，可能是因为 TeX 默认用的弹性距离，我研究一下

**Comment by iamabug** [comment]
好的，辛苦。

**Comment by zepinglee** [comment]
我只是用 ctex 的接口简单设置了一下 vertical spacing，但是这个问题似乎涉及到 LaTeX 的底层控制……

**Comment by iamabug** [comment]
如果大家一直用的模板都是这样，那影响也不大。

**Comment by zepinglee** [comment]
总之这个 bug 需要些时间去研究

**Comment by zepinglee** [comment]
Fixed in 6d175a0 .
主要是《规范》里面也没规定 subsubsection 及以下的标题前后的距离，我也没改 LaTeX 的默认距离，导致这个距离过大。

**Comment by iamabug** [comment]
恩，现在是统一的了，辛苦了，忙到凌晨两点。

**Comment by zlyliangyu** [comment]
> 恩，现在是统一的了，辛苦了，忙到凌晨两点。

请问怎么改的，我也是这个错误

**Comment by zepinglee** [comment]
> 请问怎么改的，我也是这个错误

@zlyliangyu 有什么问题新开 issue 讨论。这个 issue 是 2017 年的，之间都不知迭代过多少个版本了。
