### ISSUE TITLE
bib文件里如何注释掉一个参考文献？

### ISSUE THREAD

**Issue by iamabug** [ustctug/ustcthesis#157]
我试了用%注释：

![image](https://user-images.githubusercontent.com/11364605/34023029-b303cc02-e17d-11e7-81b8-5b447f7852b9.png)

但生成的PDF里面会有空的条目（我一共注释了两个）：

![image](https://user-images.githubusercontent.com/11364605/34023083-e7d712ea-e17d-11e7-82b5-5726ec491426.png)

请指教，谢谢！

**Comment by zepinglee** [comment]
Quote from btxdoc.pdf:

>  If you want to comment out an entry, simply remove the ‘@’ character preceding the entry type.

> LATEX’s comment character ‘%’ is not a comment character in the database files.
