### ISSUE TITLE
引用文献标注如何切换成数字标注？

### ISSUE THREAD

**Issue by iamabug** [ustctug/ustcthesis#158]
我在文档中看到，角标标注和数字标注的latex语法是一样的，但是默认好像是角标标注，请问如何换成普通的数字标注？

**Comment by zepinglee** [comment]
我写错了？角标是 super，数字是 numbers，跟 natbib 一样

**Comment by iamabug** [comment]
不好意思，没太懂具体的改法，我试了\usepackage[numbers]{natbib}和\cite[numbers]{}命令，都不对。

**Comment by zepinglee** [comment]
参考文献和引用标注支持的风格见表 9，默认为角标数字式。

如果要使用其他风格，可以在载入文档类时加入相应的参数:

\documentclass[doctor,numbers]{ustcthesis}

**Comment by zepinglee** [comment]
ustcthesis.pdf 的文档里面有说
