### ISSUE TITLE
关于奇偶页眉设置问题

### ISSUE THREAD

**Issue by fghosth** [ustctug/ustcthesis#160]
我想设置奇偶页面为不同的内容。使用
```
\if@ustc@bachelor

  \fancypagestyle{ustc@headings}{%
     \pagestyle{fancy}
     \fancyhf{}%

     \fancyhead[CE]{\setfontsize{9\bp@}上海理工大学毕业设计（论文）}%
     \fancyhead[CO]{\setfontsize{9\bp@}\ustc@title}%

     \fancyfoot[C]{\setfontsize{9\bp@}\thepage} %
    }%
\else
```

但是没有效果，会全部显示\ustc@title的内容。
进过测试 \fancyhead[CE]无效，不知道应该怎么实现奇偶页面不同设置的问题

**Comment by zepinglee** [comment]
1. 注意 `\if@ustc@bachelor` 的判断，我们学校的本科生和研究生要求不一样；
2. 因为你用 `\fancypagestyle` 定义了 `ustc@headings`， 所以应该调用 `\pagestyle{ustc@headings}`，而不是 `fancy`；
3. `\pagestyle` 要在 `\fancypagestyle` 外部调用。

**Comment by fghosth** [comment]
按照回复现在修改如下：
```
\if@ustc@bachelor
  \fancypagestyle{ustc@headings}{%
     \fancyhf{}%
     \fancyhead[CE]{\setfontsize{9\bp@}上海理工大学毕业设计（论文）}%
     \fancyhead[CO]{\setfontsize{9\bp@}\ustc@title}%
     \fancyfoot[C]{\setfontsize{9\bp@}\thepage} %
    }%
\else
  \fancypagestyle{ustc@headings}{%
    \fancyhf{}%
    \fancyhead[C]{\setfontsize{10.5\bp@}\leftmark}%
    \fancyfoot[C]{\setfontsize{10.5\bp@}\thepage}}%
\fi
\pagestyle{ustc@headings}
```
还是不行， 所有页面都显示一样的内容。奇偶页没有不同。是否还要设置其他地方？

**Comment by zepinglee** [comment]
1. 你编译的时候使用什么参数的？bachlor 还是 doctor？

2. 是不是把 `\ustc@title` 设置成 “上海理工大学毕业设计（论文）”了？

**Comment by fghosth** [comment]
使用的是bachlor。
\ustc@title设置的是『基于贝叶斯推断的邮件过滤系统』

**Comment by zepinglee** [comment]
这样设置应该没啥问题，但是这就奇怪了，我在 ustcthesis/master 上直接修改是有效的。我猜测可能是其他地方用 \pagestyle 修改了。

你可以把 `\if@ustc@bachelor \else \fi` 去掉试试行不行。

**Comment by fghosth** [comment]
问题解决了，我重新clone了一份master的版本，就好了。谢谢。

**Comment by zepinglee** [comment]
你修改的时候可以用 `git diff` 看一下变化

**Comment by fghosth** [comment]
我修改了main里面的
\documentclass[bachelor,pdf]{ustcthesis}
% bachelor|master|doctor [professional] [english] [pdf] [authoryear|numebers]
加上了pdf参数奇偶页的页眉就失效了，去掉pdf就好了

**Comment by zepinglee** [comment]
pdf 这个选项主要是为了输出一份电子版的文档，会更改超链接的颜色，不是用于打印的。
