### ISSUE TITLE
algorithm2e宏包报错

### ISSUE THREAD

**Issue by iamabug** [ustctug/ustcthesis#161]
这是我的main.tex的引言部分：

![image](https://user-images.githubusercontent.com/11364605/34673166-41ad68f4-f4bc-11e7-838c-d5e5df973346.png)

报错信息为：

![image](https://user-images.githubusercontent.com/11364605/34673406-1b8c1282-f4bd-11e7-8b46-a04601b70d0d.png)

另外，将\usepackage{algoritthm2e}这条命令调整位置：

![image](https://user-images.githubusercontent.com/11364605/34673248-9390495c-f4bc-11e7-800d-f892c1a43c3f.png)

 错误稍有不同：

![image 3](https://user-images.githubusercontent.com/11364605/34673414-238b3486-f4bd-11e7-9c43-bfa456c1a25c.png)

请问应该如何处理，谢谢。

**Comment by iamabug** [comment]
另外，一定要用algorithm2e吗？可以用algorithm和algorithmic吗？

**Comment by zepinglee** [comment]
ustcextra.sty 已经包含 algorithm2e 了，所以应该是重复载入的问题。

我了解到的用 algorithm2e 比较多，当时觉得为了标准化，就把这个加上了，你可以换成别的

**Comment by zepinglee** [comment]
整个 ustcextra 的内容你都可以不要

**Comment by iamabug** [comment]
明白了，谢谢你！

**Comment by zepinglee** [comment]
嗯……我也觉得这样有点不好，后续版本可能会把它移到 main.tex 中，只是作为一个 demo 来展示

**Comment by iamabug** [comment]
恩，我觉得可以按照推荐等级从高到低写在main.tex里，毕竟有些功能还是很好用的

**Comment by zepinglee** [comment]
嗯，好像 `\listofalgorithms` 是 algorithm2e 提供的

**Comment by HowardZorn** [comment]
> 嗯，好像 `\listofalgorithms` 是 algorithm2e 提供的

确实，不过我最近搞了个algorithmic系列宏包的可用\listofalgorithms。这里提供一下，给后来者使用：

[HowardZorn/USTC-Thesis-algorithmicx.tex](https://gist.github.com/HowardZorn/144a76da15837b31f073c76ce4e699c5)

只需要把alogrithm2e宏包的引入命令替换掉即可使用。
