### ISSUE TITLE
网址引用如何显示note

### ISSUE THREAD

**Issue by iamabug** [ustctug/ustcthesis#163]
bib文件里的写法如下：

`
@misc{test,
	note={accessed on May 30th, 2018},
	title={this is a note},
	year={2018},
	howpublished={\url{https://www.example.com/}}
}
`

**Comment by zepinglee** [comment]
我设计的时候参考了部分 BibLaTeX 的域：
```
@misc{test,
  urldate={2018-05-30},
  title={this is a note},
  year={2018},
  url={https://www.example.com/},
}
```

**Comment by iamabug** [comment]
恩，这个可以用，那么year和urldate的含义分别是什么呢，感觉year有点多余了。

**Comment by zepinglee** [comment]
你是本科生还是研究生啊？

**Comment by iamabug** [comment]
研究生。。

**Comment by zepinglee** [comment]
<img width="615" alt="screen shot 2018-01-30 at 2 44 30 pm" src="https://user-images.githubusercontent.com/12290822/35552104-6f6d7d8e-05cd-11e8-81a5-9e6c7f85c5c6.png">

year 是出版年，urldate 是引用日期。

howpublished 和 note 虽然是 BibTeX 的标准域，但是我没法将其用于 GB/T 7714-2015 的标准中，所以会忽略这两个。

**Comment by zepinglee** [comment]
year 是出版年，urldate 是引用日期。

howpublished 和 note 虽然是 BibTeX 的标准域，但是我没法将其用于 GB/T 7714-2015 的标准中，所以会忽略这两个。

**Comment by iamabug** [comment]
好的，非常感谢

**Comment by keyboard-man** [comment]
哈哈哈哈哈哈哈哈
