### ISSUE TITLE
图片上下的较大空白

### ISSUE THREAD

**Issue by iamabug** [ustctug/ustcthesis#164]
如下图所示：

![_20180309155942](https://user-images.githubusercontent.com/11364605/37196823-379ca1c4-23b3-11e8-8eb1-a00de11263a2.png)

图片上下空白都挺大的，但是感觉下一页的那个小标题是可以移到这一页的，这种情况出现的次数还挺多的，这个尤其大。。

**Comment by zepinglee** [comment]
LaTeX 要求页面底部新开的一节内容不少于两行问题，我猜测应该是因为这个。

我建议你先写完论文，然后用 `\vspace{-1cm}` 手动调，或者调整图片的位置或者尺寸。

**Comment by iamabug** [comment]
好
