### ISSUE TITLE
图片的caption无法添加footnote？

### ISSUE THREAD

**Issue by nickname029** [ustctug/ustcthesis#165]
我在想在图片上的caption加标例如：
\begin{figure}[htbp]
	\centering
	\includegraphics[width=0.85\linewidth]{figures/HL_LHC}
	\caption{LHC与HL-LHC的升级计划\footnote{test}}
	\label{fig:hllhc}
\end{figure}
直接报错如下：
Argument of \caption@ydblarg has an extra }. ...C与HL-LHC的升级计划\footnote{test}}

**Comment by zepinglee** [comment]
据我了解，这个是 LaTeX 功能的限制，与本模板无关。

建议 google 一下可能的解决方案。
