### ISSUE TITLE
参考文献格式问题汇总

### ISSUE THREAD

**Issue by nickname029** [ustctug/ustcthesis#166]
感谢ustcthesis模板的维护者的无私奉献，我在使用模板的时候，想对参考文献的格式提一下建议：
1. 人名大写：这个问题我看之前有人问过，但没看懂具体的解决方法。我想使用首字母大写但不知如何操作。我建议增加一个option，可以比较简便地允许作者选择参考文献的作者是全部大写还是首字母大写。

2. 对bib内容的解释：例如当一篇论文的作者很多时，有些网站导出的BibTeX为了避免篇幅太长，会省略后面的人名，使用others，例如文献 http://inspirehep.net/record/1124337 一共有2932名作者，我在这个网页导出的BibTeX格式为：
```
@article{Aad:2012tfa,
      author         = "Aad, Georges and others",
      title          = "{Observation of a new particle in the search for the
                        Standard Model Higgs boson with the ATLAS detector at the
                        LHC}",
      collaboration  = "ATLAS",
      journal        = "Phys. Lett.",
      volume         = "B716",
      year           = "2012",
      pages          = "1-29",
      doi            = "10.1016/j.physletb.2012.08.020",
      eprint         = "1207.7214",
      archivePrefix  = "arXiv",
      primaryClass   = "hep-ex",
      reportNumber   = "CERN-PH-EP-2012-218",
      SLACcitation   = "%%CITATION = ARXIV:1207.7214;%%"
}
```
我用一些模板时，他们会把others直接翻译成et al. 比如这个BibTeX在revtex4模板下翻译成了下面的格式
G. Aad et al. (ATLAS), Phys. Lett. B716, 1 (2012), 1207.7214.
而在ustcthesis模板下，则翻译成了
AAD G, OTHERS. Observation of a new particle in the search for the Standard Model
Higgs boson with the ATLAS detector at the LHC[J]. Phys. Lett., 2012, B716: 1–29. DOI:
10.1016/j.physletb.2012.08.020.
由于小写的单词others一般不会是人名，所以没有歧义。能否考虑按revtex4的习惯解析成el al.

3. 当论文的作者是不是人名而是一个课题组时，ustcthesis翻译的不太好，例如：
```
@article{CEPC-SPPCStudyGroup:2015csa,
      author         = "CEPC-SPPC Study Group",
      title          = "{CEPC-SPPC Preliminary Conceptual Design Report. 1.
                        Physics and Detector}",
      year           = "2015",
      reportNumber   = "IHEP-CEPC-DR-2015-01, IHEP-TH-2015-01, IHEP-EP-2015-01",
      SLACcitation   = "%%CITATION = IHEP-CEPC-DR-2015-01;%%"
}
```
的作者部分能否保留成CEPC-SPPC Study Group而不是GROUP C S S.
一般在BibTeX中，都是人名的首字母大写，合作组一般都是全大写CEPC-SPPC

感谢您能抽时间留意这些问题。

祝
    工作顺利！

**Comment by zepinglee** [comment]
1. 去掉 https://github.com/ustctug/ustcthesis/blob/master/ustcthesis.dtx#L2469 这一行，然后用 `make` 编译，就可以取消全大写。至于加一个 option 设置首字母大写，这违背了《撰写手册》，我建议自行修改 dtx 文件。

2. 这是个 bug， 我稍后修复。

3. 可以把这种组织的名称放进大括号里，这样 BibTeX 就不会当成姓名去处理：
```
author         = "{CEPC-SPPC Study Group}",
```

另外说一点，
```
title          = "{CEPC-SPPC Preliminary Conceptual Design Report. 1. Physics and Detector}",
```
这里不应该把 title 全部放进大括号，会导致不合标准（句首字母大写）。建议写成：
```
title          = "{CEPC-SPPC} Preliminary Conceptual Design Report. 1. Physics and Detector",
```
这样最后得到的应该是 “CEPC-SPPC preliminary conceptual design report. 1. physics and detector”

**Comment by nickname029** [comment]
感谢及时的回复，注销掉这一句确实能变成小写，同时others也能正确第翻译为et al.所以这个bug出在把作者名字转换为大写之后。

**Comment by zepinglee** [comment]
在 aac37bce11472ce5a8d07b46fddb2d3a4be4c9d7 中修复，不过你得再删一遍那行 `"u" change.chase$` ，因为直接 merge 的话那里有 conflicts。

**Comment by baymax-nexi** [comment]
misc{girshick2015fast,
    title={Fast R-CNN},
    author={Ross Girshick},
    year={2015},
    eprint={1504.08083},
    archivePrefix={arXiv},
    primaryClass={cs.CV}
}
但编译出的显示为：
GIRSHICK R. Fast r­cnn[Z]. 2015.
eprint关键字后面的信息显示不出来，请教下怎么解决？
