### ISSUE TITLE
论文标题超过一定长度，封面标题和作者就会错位

### ISSUE THREAD

**Issue by shui** [ustctug/ustcthesis#167]
举个例子：main.tex中：
```
\title{中国科学技术大学\\基于XXXXXX的应用层系统的研究与实现}
```
效果：  
![](https://user-images.githubusercontent.com/6127969/37698391-b045477a-2d1d-11e8-97d7-18e6d20ed82c.png)

别的地方没有改

* 系统：Ubuntu 16
* TexLive版本：2017
* 字体：Fandol字体库

不知道是不是我个例。手头没有别的机器测试能否复现。

谢谢！

**Comment by zepinglee** [comment]
第一行“中国科学技术大学 ”是多余的吧

**Comment by shui** [comment]
@zepinglee 
可能是我中午没睡醒……
我以为这个是学校规定的……
多谢
