### ISSUE TITLE
Texlive 编译最新模板提醒警告

### ISSUE THREAD

**Issue by innocnet** [ustctug/ustcthesis#169]
Package hyperref Warning: Token not allowed in a PDF string (Unicode):
(hyperref)                removing `\\' on input line 28.
能正常编译，但这个警告如何修正呢？

**Comment by zepinglee** [comment]
一般是你的章节标题，或者其他超链接有什么特殊符号，这个还是去查一下 hyperref 的文档吧

**Comment by innocnet** [comment]
查过，它报警告的的那行是\begin{document} 。。。
其余标题检查过没什么问题

**Comment by zepinglee** [comment]
应该是因为 `\title{}` 里面有个 `\\` ，然后模板会设置
```
\hypersetup{
  pdftitle={\ustc@title},
  pdfauthor={\ustc@author}
}
```
所以导致这个 warning。

**Comment by innocnet** [comment]
你编译的时候有这个问题吗

**Comment by zepinglee** [comment]
对，默认的 main.tex 有 `\title{中国科学技术大学\\学位论文模板示例文档}`，就是那个 `\\` 的问题

**Comment by innocnet** [comment]
谢谢，知道了。改成这样  \title{中国科学技术大学 \texorpdfstring{\\}\  学位论文模板示例文档}
就没有警告了。   你也可以把模板更新下

**Comment by zepinglee** [comment]
原来的是换行，应该写成 `\texorpdfstring{\\}{}` 吧？

因为 titile 要写在封面上，一些断词问题还是应该由用户手动设置，所以才有 `\\` 。但是一般用户没必要用 `\texorpdfstring`，这样代码不是很美观。

**Comment by zepinglee** [comment]
Fixed in 70ff0f4698b7dbbf1cb23a838b298aa84eb4e0ef. 现在允许 `\title{}` 里有 `\\`，但是不会产生 warning。
