### ISSUE TITLE
章节和摘要起始单双页问题

### ISSUE THREAD

**Issue by zvant** [ustctug/ustcthesis#170]
今天拿学硕论文去东区印刷厂打印，负责打印的老师说中英文摘要和每个新章都需要从单数页面开始，可能不同老师的看法还是不一样。建议打印时携带两个版本的论文免得麻烦。

**Comment by zvant** [comment]
在 ustcthesis.cls 里修改
`\LoadClass[UTF8, a4paper, openany, zihao=-4]{ctexbook}[2015/05/14]`
可以切换

**Comment by zepinglee** [comment]
Duplicate of issue #154 .

**Comment by zepinglee** [comment]
《手册》第 1.10 (2) 节规定“各部分之间不必留空白”。
