### ISSUE TITLE
关于论文规范的问题

### ISSUE THREAD

**Issue by iamabug** [ustctug/ustcthesis#171]
昨天收到了教学秘书发的关于毕业论文的邮件，有几个问题请教一下：
1. 工程硕士和工学硕士的论文规范区别在哪（封面能看出来吗，上一届的好像会在封面上区分），是否在main.tex中用 [professional]控制？
2. 教学秘书给的规范中，说各级标题都要左起顶格，但是现在好像三级标题往下都是缩进了的。
3. 若有不一致的地方，检查论文时是否只要使用该项目最新的版本就不会有问题？

**Comment by zepinglee** [comment]
1. 据我了解，研究生的学位论文规范都在 http://gradschool.ustc.edu.cn/ylb/material/xw/wdxz.html ，其中并没有“工程硕士”和“工学硕士”区分。professional 是控制“专业硕士”的。上一届是采用老版本的规范。

2. 无论是《撰写手册》的规定（第 2.2 节），还是《撰写手册》附录的样式，还是 Word 模板，都是带缩进的。

3. 这个不一定。

**Comment by iamabug** [comment]
1. 这是教学秘书的邮件：
![image](https://user-images.githubusercontent.com/11364605/38350303-4232be7c-38dd-11e8-8bd9-6d0ed55579e0.png)
我已经回邮件咨询了。
专业硕士指的是什么？哪些人需要使用prefessional ?
3. 我的意思是，只要使用这个项目来撰写毕业论文，除非自己专门改动了某些地方，否则不需要担心论文通不过学校的格式检查？

**Comment by zepinglee** [comment]
1. 我也不太清楚，好像是“工学硕士”是“学术型硕士”的一种，“工程硕士”是“专业型硕士”的一种。从《撰写手册》来看两者只有封面的区别，至于“工程硕士的论文撰写规范”，我没有看到过相关的文档。

2. 我不确定，我的依据只有http://gradschool.ustc.edu.cn/ylb/material/xw/wdxz.html 上的文档，至于其他的规定，我目前不抬清楚。

**Comment by zepinglee** [comment]
建议向教学秘书咨询清楚是否有除《撰写手册》之外的规定

**Comment by iamabug** [comment]
好的，谢谢你，我先把内容写完吧。

**Comment by iamabug** [comment]
用最新的编译，报错如下：
![image](https://user-images.githubusercontent.com/11364605/38649901-8fcab9e8-3e2b-11e8-916c-fb33b2f37d86.png)
我在windows上安装了kaiti_2312和fangsong_2312（第二次报这个错），就OK了。那么，对这两种字体的需求是一直都有，还是新加的用在封面上的呀~

**Comment by iamabug** [comment]
用最新的编译了，报了kaiti_2312和fangsong_2312的字体找不到错误，装了之后可以编译，但封面并没有变化：
![image](https://user-images.githubusercontent.com/11364605/38650476-a489b8e0-3e2e-11e8-9ed1-c0f51d1b5754.png)

**Comment by zepinglee** [comment]
你试一下现在的 master？

```
\documentclass[master,professional]{ustcthesis}
\professionaltype{专业学位类型}
\enprofessionaltype{Professional degree type}
```

<img width="741" alt="screen shot 2018-04-12 at 1 48 46 pm" src="https://user-images.githubusercontent.com/12290822/38658547-3de99a04-3e58-11e8-921a-0ace2d08773a.png">

**Comment by iamabug** [comment]
OK了
