### ISSUE TITLE
《研究生学位论文撰写手册》与 Word 模板中的问题

### ISSUE THREAD

**Issue by zepinglee** [ustctug/ustcthesis#174]
《研究生学位论文撰写手册》和 Word 模板中存在很多不一致的地方，我在这个 issue 中一一列出，并且注明了 LaTeX 模板的选择。

本列表持续更新中。

# 《撰写手册》中的问题：

1. 第 9 页“注意”第（2）条要求“英文摘要和目录均另面起”，而同页第（4）条又要求“英文摘要应以偶数页结束，内容不足则加一页”，意思是目录从奇数页开启。

1. 参考文献格式的文献类型标志
第 59 页 2.14.1(2) 节规定了“专著中的析出文献”格式，其中的“文献类型标志”被固定为“M”。而会议论文是会议论文集（proceedings）的析出文献，按《GB/T 7714-2015》应按“专著中的析出文献”格式处理，并且文献类型标志是会议的“C”。所以这里不应固定为“M”。
LaTeX 模板中的会议论文使用“专著中的析出文献”格式，并且文献类型为“C”。

1. 摘要的标题格式
第 66 页 3.4 节规定中文摘要的标题“两字之间空一字”，应改为两字中间空两字，因为第 88 页的格式范例的规定摘要“两字中间空两字”，实际空的距离也是两个汉字宽度。在 Word 模板中的摘要同样是空两字。LaTeX 模板选择空两字。

1. 图注和表注的格式
第 68 页 3.6 节规定，“图注位于图题下方，左缩进两字，续行悬挂缩进左对齐，两端对齐”。
这里的描述有点让人困惑，建议在附录的格式范例中给出图注和表注的示例。

1. 表题的字体
第 68 页 3.6 节规定，表号、表题“黑体 10.5 磅居中”，应该改为同图号、图题的字体（宋体）一样。

1. 符号说明的字号
第 68 页 3.7 节规定，符号说明“说明部分：宋体 10.5 磅，行距 16 磅“；而第 7 页 1.5 节规定，符号说明“内容同正文格式”，正文的字号是 12 磅、行距 20 磅。这里改为同正文保持一致更合理。

1. 封面的灰框
第 80 页格式范例的封面，各部分内容外边有灰色的框。Word 模板中也有这个问题。
LaTeX 模板中没有灰框。

1. 封面的校徽样式
第 80 页格式范例封面的校徽是蓝底白字的，而学校官网上的校徽是白底蓝字。Word 模板中也有这个问题。
LaTeX 模板使用学校最新版[视觉形象识别系统](https://vi.ustc.edu.cn)的校徽。

1. 封面的姓名、专业格式
第 80 页格式范例中文封面规定，作者姓名一列“居中上下对齐”，但实上际该列是居左的。
同样，第 81 页英文封面规定 “Author” 一列“居右”，但是实际是居左的；内容一列“居中上下对齐”，而实际没有对齐。

1. 摘要的关键词字体
第 88 页格式范例的中文摘要的关键词要求“宋体……“关键词”三字加粗”，而实际使用的是黑体。第 66 页 3.4 节同样规定“格式同‘段落文字’，‘关键词’三字加粗”。

1. 页眉内容
第 89 页格式范例的英文摘要，标题为“ABSTRACT”，页眉为“Abstract”，两者并不统一；而《撰写手册》第 10 页 1.10(8) 节规定“页眉内容与该部分的一级标题相同”。

1. 目录标题格式
第 90 页格式范例的目录要求标题“二字之间空一个汉字符位”应该改为“空两个汉字符位”。

1. 目录的二级节标题字体
第 90 页格式范例的目录中，二级节标题要求使用“仿宋体 12 磅”，而第 67 页 3.5 节规定二级节标题使用“宋体 10.5 磅”。

1. 图表的标题字体
第 91 页图 2.1 的标题要求“宋体 10.5 磅……图号、图题和图注标题加粗”，与第 68 页的规定一致，但实际使用的字体是黑体。同样第 92 页的表题有类似的问题。

1. 二级节标题缩进
第 92 页格式范例第 2.5.1 节，二级节标题“左顶格”，而《撰写手册》第 67 页 3.6 节规定“二级节标题左缩进两字”。

1. 致谢的标题格式
第 95 页 格式范例要求致谢标题“两字间空一字”，应该改为空两字。

# Word 模板中的问题：

1. 封面版式
封面的版式不符合《撰写手册》 第 80 页格式范例的要求，比如要求 “校名距顶边5.2cm”，而 Word 模板的校名距离顶端只有 4cm。同样，论文名称、题目、作者信息的距离上、左边界的尺寸都不合规定。
目前 LaTeX 模板以 Word 模板的尺寸为准。

1. 摘要和目录的标题字体
摘要标题是宋体加粗，而《撰写手册》第 66 页 3.4 节规定摘要标题“黑体 16 磅加粗居中”。
同样，第 6 页的“目录”标题是宋体加粗，而《撰写手册》第 67 页 3.5 节规定目录标题“黑体 16 磅加粗居中”。

1. 页码
摘要没有编页码，而《撰写手册》第 9 页 1.10(2) 要求“从‘中文摘要’开始页码用大写罗马数字”。

1. 目录的格式
目录的正文章标题段前 0 磅，而附录的章标题段前 6 磅；节标题段前 0 磅。而《撰写手册》第 67 页 3.5 节规定各章节标题段前 6 磅。LaTeX 模板使用折衷方案：章标题统一段前 6 磅，节标题段前 0 磅。
目录的二级节标题使用“仿宋 12 磅”，而《撰写手册》规定使用“宋体 10.5 磅”。

1. 章节标题的格式
第 1 章的标题格式是：黑体小二号（18 磅），段前半行，段后 0 行，对齐到网格；而《撰写手册》第 67 页 3.6 节要求各章标题“黑体 16 磅加粗，段前 24 磅，段后 18 磅”。
第 1.1 节标题的格式是：黑体小三号（15 磅），行距 20 磅，段前 1 行，段后 0 行，对齐到网格；而《撰写手册》第 67 页 3.6 节要求一级节标题“黑体 14 磅，单倍行距，段前 24 磅，段后 6 磅”。
第 2.4.1 节标题的格式是：黑体四号（14磅），左顶格，行距 20 磅，段前 1 行，段后 0 行，对齐到网格；而《撰写手册》第 67 页 3.6 节规定二级节标题“黑体 13 磅，左缩进两字，单倍行距，段前 12 磅，段后 6 磅”。

# 其他建议

1. 页码
第 10 页 1.10 节后的注意事项 (3) 中规定了“页码居中”，由于论文是双面打印的，建议改为“页码居外侧”。

1. 算法环境
建议增加算法/伪代码的格式和编号的规定。

1. 行距
《撰写手册》在封面、目录的格式、章节标题和图表的标题中的行距规定使用“单倍行距”。事实上，Microsoft Word 中的“单倍行距”的概念跟具体的字体有关。也就是说，在设置了“单倍行距”后，实际的行距相对于字号的倍数取决于使用的字体，比如 Times New Roman 的这一倍数为 1.15，中易宋体的倍数为 1.30，而思源宋体的倍数达到了 1.87。这会造成歧义，建议使用具体的数值规定行距。
另外在 Word 模板中很多地方开启了“对齐到网格”，这时行距的计算方式是基于网格系统的，与设置的固定行距或者“单倍行距”完全无关。建议在 Word 模板中不开启“对齐到网格”。

1. 参考文献的著者姓名大小写
第 57 页 2.14 节规定：参考文献参照《GB/T 7714-2015 信息与文献 参考文献著录规则》执行，而该标准中的著者姓名是全大写的。很多同学反映建议改为首字母大写，这样的可读性更好，而且更符合常见的参考文献样式。

**Comment by jmcui** [comment]
封面我之前做lyx模版的时候弄过些，有可能提供些代码。

最近注意到这个github项目做的很好了，我顺便把N年前做的lyx模版更新了一下。直接用本项目作为git子项目。


如何加入ustctug这个group？

**Comment by jmcui** [comment]
封面之前做lyx模板的时候，仔细调过。主要利用textblock环境，实现word中类似文本框的功能。
用这个可以定义内容所在位置，以及内容在texblock中 上下居中。
比较典型的情形是：题目比较长，需要三行才能显示的情况：
目前的模板，由于不能在特定位置上下居中，标题下方与作者姓名等，离得很近了。
见下图比较，左侧是我之前用的模板，右图是现在ustcthesis的模板。
![zhongwen](https://user-images.githubusercontent.com/6935902/47549488-d0d2d080-d92e-11e8-8f18-7408752c0d5f.png)

另外英文标题页，英文换行后，行间距感觉太小。导师一栏，很多情况下英文信息过长，需要换行。
![eng](https://user-images.githubusercontent.com/6935902/47549460-bd276a00-d92e-11e8-81be-cb117accabc3.png)

下面是我之前用的模板代码，你可以参考一下，看看能不能用到现在的模板里。我对现在模板里结构和变量不熟，就不直接commit代码了。

```` latex
\renewcommand\maketitle{%
    \pdfbookmark[0]{\ustc@title}{title}
    \cleardoublepage
    \thispagestyle{empty}
    \setlength{\TPHorizModule}{1mm}
    \setlength{\TPVertModule}{1mm}

    \begin{textblock}{150}[0.5,0](105,49)
        \begin{center}
            \includegraphics[scale=1]{ustc_logo_text.eps}
        \end{center}
    \end{textblock}

     \begin{textblock}{150}[0.5,0.5](105,85)
        \begin{center}
        \ifustc@doctor
            \heiti\fontsize{56}{67.2}\selectfont {博士学位论文}
        \else
            \heiti\fontsize{56}{67.2}\selectfont {硕士学位论文}
         \fi
        \end{center}
    \end{textblock}
   
    \begin{textblock}{150}[0.5,0.5](105,135)
        \begin{center}
        \includegraphics[width=4.52cm,height=4.52cm]{ustc_logo_fig.eps}
        \end{center}
    \end{textblock}
      
    \begin{textblock}{110}[0.5,0.387](105,183)
        \begin{center}
            \fontsize{26}{32}\selectfont\heiti\bfseries{\ustc@title}\par
        \end{center}
    \end{textblock}

    \begin{textblock}{120}[0.5,1](105,260)
    \begin{center}
        { \fontsize{16}{21.5}\selectfont
        \begin{tabular}[b]{l>{\centering}p{8.7cm}}
            \heiti{作者姓名：} & \ustc@author \tabularnewline
            \heiti{学科专业：} & \ustc@major \tabularnewline
            \heiti{导师姓名：} & \ustc@advisor \tabularnewline
            \heiti{完成时间：} & \ustc@submitdate
        \end{tabular}}
    \end{center}
    \end{textblock}
    \null
    \clearpage
    \if@twoside
        \thispagestyle{empty}
        \cleardoublepage
    \fi
}

\ustc@define@term{etitle}
\ustc@define@term{eauthor}
\ustc@define@term{eadvisor}
\ustc@define@term{ecoadvisor}
\ustc@define@term{esubmitdate}
\ustc@define@term{emajor}

\newcommand\makeetitle{%
    %\pdfbookmark{英文标题}{etitle}
    \cleardoublepage
    \thispagestyle{empty}
    \setlength{\TPHorizModule}{1mm}
    \setlength{\TPVertModule}{1mm}

    \begin{textblock}{150}[0.5,0](105,47.5)
        \begin{center}
         \fontsize{20}{30}\selectfont\textsf{University of Science and Technology of China}
        \end{center}
    \end{textblock}

    \begin{textblock}{150}[0.5,0](105,56.5)
        \begin{center}
        \ifustc@doctor
            \fontsize{26}{30}\selectfont\textsf{A dissertation for doctor degree}
        \else
            \fontsize{26}{30}\selectfont\textsf{A dissertation for master degree}
        \fi
        \end{center}
    \end{textblock}

    \begin{textblock}{150}[0.5,0](105,88)
        \begin{center}
        \includegraphics[width=4.52cm,height=4.52cm]{ustc_logo_fig.eps}
        \end{center}
    \end{textblock}

    \begin{textblock}{140}[0.5,0.613](105,173)
        \begin{center}
            \fontsize{26}{30}\selectfont\bfseries\textsf{\ustc@etitle}\par
        \end{center}
    \end{textblock}

    \begin{textblock}{120}[0.5,1](104,260)
        \begin{center}
        { \fontsize{16pt}{21.5pt}\selectfont
        \begin{tabular}[b]{l>{\centering}p{8.1cm}}
            Author's Name :&    \ustc@eauthor \tabularnewline
            Speciality :&       \ustc@emajor \tabularnewline
            Supervisor :&       \ustc@eadvisor \tabularnewline
            Finished Time :&    \ustc@esubmitdate
        \end{tabular}}
        \end{center}
    \end{textblock}
    \null
    \clearpage
    \if@twoside
        \thispagestyle{empty}
        \cleardoublepage
    \fi
}
````

**Comment by August15** [comment]
没有做任何改动，突然出现 ucasthesis.cls error \proofname undefined. \renewcommand{\proofname} ，还有 undefined control sequence \ctexset，请问如何解决？

**Comment by ProfKong** [comment]
《手册》2019版第81，83，85页那里的英文author, speciality, supervisors, finished time部分，pdf中显示的效果与图中的标注不符，在ustcthesis模版中是依据了pdf显示的效果

**Comment by zepinglee** [comment]
> 《手册》2019版第81，83，85页那里的英文author, speciality, supervisors, finished time部分，pdf中显示的效果与图中的标注不符，在ustcthesis模版中是依据了pdf显示的效果

`ustcthesis` 模板是依据 Word 模板的布局设置的。所以这是 Word 模板中的问题。
<img width="724" alt="Screen Shot 2022-04-19 at 13 28 16" src="https://user-images.githubusercontent.com/12290822/163926254-68790815-8bfe-495f-9943-1c82d9202456.png">

**Comment by ProfKong** [comment]
pdf 标注的author等一列是居右，内容一列是居中上下对齐，与显示的不一样，显示的没有分两列

**Comment by zepinglee** [comment]
> pdf 标注的author等一列是居右，内容一列是居中上下对齐，与显示的不一样，显示的没有分两列

嗯，那我也记录一下。

**Comment by CTCS-4** [comment]
在2022年版本的专业硕博Word模板中并未出现“专业学位类型”，并且在《撰写手册》中也未注明该项内容。
在当前版本的ustcthesis中如果选择专业学位并且不设定专业学位类型，会出现一对空的括号。

**Comment by zepinglee** [comment]
> 在2022年版本的专业硕博Word模板中并未出现“专业学位类型”，并且在《撰写手册》中也未注明该项内容。 在当前版本的ustcthesis中如果选择专业学位并且不设定专业学位类型，会出现一对空的括号。

1. 不要发在无关的 issue 中；2. 尝试使用最新版的模板；3. 参考 <https://github.com/ustctug/ustcthesis/issues/325#issuecomment-1054462220>。
