### ISSUE TITLE
参考文献authoryear排序的问题

### ISSUE THREAD

**Issue by pyfdrw** [ustctug/ustcthesis#179]
使用的这个:
\documentclass[doctor, authoryear, pdf]{ustcthesis}
文章中引用使用的是 \citep{}
安装的环境是TexLive 2015

英文排序没有问题，中文排序是乱的。
有办法解决吗？

感谢！

中文引文排版我截了一小段，如下:
> 王继先, 陈如松, 诸洪达. 1998. 中国参考人解剖生理和代谢数据[M]. 北京: 原子能出版社.
秦笃烈, 罗述谦, 周果宏, 等. 2003. 数字化虚拟中国人女性-1 (VCH F-1) 实验数据集血管标识
的突破进展[J]. 科学中国人(4): 4–8.
钟世镇. 2002. “虚拟中国人”(VCH) 切片建模研究进展[J]. 中国临床解剖学杂志, 20(5):
323–323.

**Comment by zepinglee** [comment]
https://github.com/ustctug/ustcthesis/blob/8d313043eeca532d31b7a1d5350c0abe2e2d27fc/ustcthesis.dtx#L596

参见这一段说明。

**Comment by pyfdrw** [comment]
研究生院的模版有些年头了，那个编译出来的说明文档我没看到这一段，实在是抱歉。
按照提示在说明文档里面找到 

> 在 bib 数据库中设置对应条目的 key 域为著者姓名拼音

使用这种方式解决了中文排序，十分感谢！

**Comment by zepinglee** [comment]
呃，其实是我提交给研究生院的那个版本时偷懒，没写这部分文档。😂
