### ISSUE TITLE
图表中的若干问题

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#18]
目前，模板中的图表与规范中不一致的地方有：
1. 规范中图表的label用的都是英文，即`figure`或`table`，而模板中是中文，即`图`和`表`；
2. 规范中图注的label是`Notes`，模板中是`注`；
3. 模板中labelsep定义为`\hspace{\ccwd}`。在中文环境下，与`labelsep=quad`效果一致，都是一个汉字的宽度，符合规范中的要求。若考虑到未来对多语言的支持，是否用`quad`更好？

PS：规范中用英文不合理，此处列出仅供记录。

**Comment by zepinglee** [comment]
1. 显然《规范》的格式范例不够规范啊，如果一篇中文文章里面出现个“Fig. 1”，会很突兀，更何况《规范》本身没有规定，所以应该保留中文的“图”、“表”、“注”。

3. ctex说明文档第15.4.8节提到：“将当前汉字的宽度保存到 \ccwd 中备用。不采用 1 em,因为这时的 1 em 实际上来自西文 字体的信息,未必等于汉字的宽度,这似乎在传统的 .tfm 字体上表现更明显。”

刘海洋在论坛里也说道（在 http://bbs.ctex.org/forum.php?mod=viewthread&tid=70408 ），
“em 是长度单位，字体确定的参数
quad 就是空一个 em
绝大多数中文字体一个汉字宽 1em，个别长或扁的字体不同。不过在 CJK 和 xeCJK 中有 \CJKglue 作用，还可能有出入。CCT 和 ctex 宏包用 \ccwd 表示汉字宽，并已经加上了 \CJKglue”

这里的说法也类似：http://bbs.ctex.org/forum.php?mod=viewthread&tid=45307&page=1#pid320398

所以严格来说，\quad是不对的，做英文模板支持时我再修改。
