### ISSUE TITLE
英文的书籍参考文献格式

### ISSUE THREAD

**Issue by jyhong836** [ustctug/ustcthesis#180]
按照格式要求，书名的首字母要大写。在bibtex里面定义为book的项会有个title属性。但是在编译的时候，自动被转换为句首字母大写了。如果要一个个手动改的话，像"{A}aa {B}bb"这样，会很麻烦。能不能再cls或sty文件里面修改一下？
类似的，booktitle应该要首字母大写，但是默认不会做任何处理。只能手动。。。

**Comment by zepinglee** [comment]
这里《撰写手册》的表述有误。这里应该是特指析出文献的 title 为“句首字母大写”，其 booktitle “首字母大写”。

一个例子是《撰写手册》第 61 页 2.14.2 节的示例：
![screen shot 2018-04-18 at 9 43 05 am](https://user-images.githubusercontent.com/12290822/38907142-f100fff4-42ec-11e8-9499-465a6e49d2eb.png)
这其实是一本书，但是 title 是“句首字母大写”。

另外参考 《[GB/T 7714-2015](https://github.com/Haixing-Hu/GBT7714-2005-BibTeX-Style/files/153951/GBT.7714-2015.pdf)》，其中所有的 title，无论是否 book，都是“句首字母大写”。

至于 booktitle 不做任何处理，这是 BibTeX 的传统，因为有一些介词如 at, in 是不应该首字母大写的。所以正确的著录方法是，在 bib 文件中著录为“Aaa of Bbb”的格式。然后模板会在需要“句首字母大写”的地方，把其他字母转为小写。
