### ISSUE TITLE
章节标题及几个参考文献格式问题

### ISSUE THREAD

**Issue by nickname029** [ustctug/ustcthesis#181]
1、章节标题强制把所有的英文字母转换为了大写。但是有时候大写和小写的英文可能分别代表不同的含义；有时大写不符合通常书写习惯，例如：
对于一个正负电子湮灭过程`$ e^+ e^- \to HZ $\，如果把它写在章节标题中就变成了\$ E^+ E^- \to HZ $\。
建议改进一下，可以让作者控制哪些可以进行大小写转换，或者取消大小写自动转换。

2、参考文献中人名缩写建议：
比如对杨振宁（Chen Ning Yang）比较常见的缩写是Yang, C. N.或Yang, C.-N.
但目前的模板给出的是Yang C N

3、有些文献会有勘误，一般放在BibTex的note部分，比如：
```
@article{Bodwin:1994jh,
	author         = "Bodwin, Geoffrey T. and Braaten, Eric and Lepage, G.
	Peter",
	title          = "{Rigorous QCD analysis of inclusive annihilation and
	production of heavy quarkonium}",
	journal        = "Phys. Rev.",
	volume         = "D51",
	year           = "1995",
	pages          = "1125-1171",
	doi            = "10.1103/PhysRevD.55.5853, 10.1103/PhysRevD.51.1125",
	note           = "[Erratum: Phys. Rev.D55,5853(1997)]",
	eprint         = "hep-ph/9407339",
	archivePrefix  = "arXiv",
	primaryClass   = "hep-ph",
	reportNumber   = "ANL-HEP-PR-94-24, FERMILAB-PUB-94-073-T, NUHEP-TH-94-5",
	SLACcitation   = "%%CITATION = HEP-PH/9407339;%%"
}
```
revtex4模板给出的参考文献格式为：
> G. T. Bodwin, E. Braaten and G. P. Lepage, Phys. Rev. D 51, 1125 (1995) Erratum: [Phys. Rev. D 55, 5853 (1997)] doi:10.1103/PhysRevD.55.5853, 10.1103/PhysRevD.51.1125 [hep-ph/9407339].

但是勘误目前在本模板无法体现。
另外，当参考文献出现勘误时，一般会有两个doi并列：
```
doi            = "10.1103/PhysRevD.55.5853, 10.1103/PhysRevD.51.1125",
```
此时应当按逗号分割开生成两个超链接。但本模板给出的是一个错误的超链接。

**Comment by zepinglee** [comment]
1. 应该是某次修改 headings 引入的 bug。

**Comment by zepinglee** [comment]
你试一下 master 版本，如果没问题我就 release 一个版本
