### ISSUE TITLE
中文引用文献中的英文被转换为小写，还有可以取消显示出版地不详吗

### ISSUE THREAD

**Issue by ustcjerry** [ustctug/ustcthesis#186]
如图

![qq 20180427174345](https://user-images.githubusercontent.com/11849381/39356491-b480de20-4a42-11e8-8832-5844b8ec6eab.jpg)

**Comment by zepinglee** [comment]
1. https://github.com/ustctug/ustcthesis/wiki/常见问题#6-参考文献列表中标题的专有名词如何强制大写

2. 这个参考《撰写手册》

**Comment by zepinglee** [comment]
我稍微改写了一下 FAQ，你可以再去瞧瞧。

不过我觉得中文文献标题中的英文单词可以不用转换小写。

**Comment by ustcjerry** [comment]
无出版地时可著录为这样，这个不是强制的吧
![qq 20180427223755](https://user-images.githubusercontent.com/11849381/39368252-ae596192-4a6b-11e8-99cf-bbda35a8c420.jpg)
一般来说会忽略不写，这样好看一些，可以加一个选项默认打开或关闭，这样会好点？

**Comment by zepinglee** [comment]
现在的 master 已经处理好了：

1. 不处理中文标题大小写

2. 不再著录“出版地不详”等信息

**Comment by zepinglee** [comment]
忘记改另外一个函数了，试下刚 push 的 1efc9801957e237c9d2b4583b8d40490fe2fb69d

**Comment by ustcjerry** [comment]
抱歉这几天没看，上述所有问题都解决了。THX~
