### ISSUE TITLE
subsubsection, paragraph, subparagraph 缩进问题

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#188]
《撰写手册》里的说法是：
![image](https://user-images.githubusercontent.com/3974108/39579106-87848f54-4f18-11e8-87dd-2c22b1bb364d.png)

按照这一规定，subsubsection, paragraph 和 subparagraph 都是缩进三个汉字。这样设置使得这些标题比接下来的正文部分多缩进一个汉字，这样挺丑的。

《撰写手册》虽然自己没有严格按照学位论文的要求去写，其自己的风格是
![image](https://user-images.githubusercontent.com/3974108/39579413-4ac8967c-4f19-11e8-9125-c1c622706162.png)
感觉这一风格才比较合理。

**Comment by seisman** [comment]
PS：建议在 `intro.tex` 中每级标题下面加上一些文字，以演示具体的效果。

**Comment by zepinglee** [comment]
有道理；我看了一下 word 模板，subsubsection 及以下都是缩进 2 个字宽的
