### ISSUE TITLE
列表间距过大

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#189]
![image](https://user-images.githubusercontent.com/3974108/39659844-5bf05d8a-5064-11e8-986a-b787c0a0478b.png)
如图所示，列表各项之间间距过大，明显超过行间距，不合理。

**Comment by zepinglee** [comment]
嗯这个确实有些问题，但我暂时没兴趣研究 list

**Comment by jiaopjie** [comment]
虽然这样的间距的确过大, 不过貌似这是 `book` 文档类原本的设置. `enumitem` 宏包可以处理, 一个命令 `\setlist{nolistsep}` 似乎就可以了.

**Comment by zepinglee** [comment]
在 3dcc4c4 中修复；没有用 enumitem 宏包，有需要的话用户可以自己调用
