### ISSUE TITLE
在“常见问题”中加入“使英文文献的标题保持原样”的解决办法

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#190]
FAQ中[参考文献列表的英文标题为何被转为小写](https://github.com/ustctug/ustcthesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#2-%E5%8F%82%E8%80%83%E6%96%87%E7%8C%AE%E5%88%97%E8%A1%A8%E7%9A%84%E8%8B%B1%E6%96%87%E6%A0%87%E9%A2%98%E4%B8%BA%E4%BD%95%E8%A2%AB%E8%BD%AC%E4%B8%BA%E5%B0%8F%E5%86%99)解释了为何会被转换为小写、bibtex的正确用法以及对于专有名词的解决办法。

这些都没有问题，但是这样做可能会很麻烦。以我个人的情况为例，我的bib文件里大概有200个条目，其中大部分条目的标题都是sentense case的，少部分是title case的。或许是由于研究方向的特殊性，200个条目里可能有100个条目标题都有“Earth”这个专有名词。按照FAQ里提到的解决办法，一个一个给专有名词加括号会很麻烦。所以如果能够使英文文献的标题保持原样，只需要手动修改少部分title case的条目即可，这种情况下也算是所见即所得了。

实际上Google Scholar、期刊官方以及Endnote自动获取的信息里也都是sentence case比较多，title case比较少，而且文章标题里有专有名词是很常见的。所以这个需求对于大多数用户也是成立的，从相关的issue里也可以看出来这一点。

建议在FAQ中加入“使英文文献标题保持原样”的解决办法，尽管这么做使得bibtex文件的适用性变弱，但对于大部分写学位论文的用户而言，这是最方便的做法。由用户自己决定用哪种解决办法。

**Comment by zepinglee** [comment]
GB/T 7714-2015 的 title 是 sentence case，booktitle 和 jounal 是 title case。

如果你的 bib 中的 title 大部分是 sentence case 才需要设置“保持原样”。

**Comment by seisman** [comment]
😢 我好像把 title case 和 sentence case 的定义完全弄反了。

我修改了第一个comment的描述

**Comment by seisman** [comment]
Closed as fixed.
