### ISSUE TITLE
二级标题左顶格

### ISSUE THREAD

**Issue by yuebai008** [ustctug/ustcthesis#193]
撰写手册中92页  二级标题左顶格问题  评审老师给我提了  能不能自己修改成左顶格

**Comment by zepinglee** [comment]
第 67 页 3.6 节规定二级节标题“左缩进两字”

**Comment by yuebai008** [comment]
我知道  但是 撰写手册92页也写二级标题左顶格  因为 评审意见有这一条  所以能不能修改成左顶格形式的模板

**Comment by zepinglee** [comment]
不能怼回去嘛？

https://github.com/ustctug/ustcthesis/blob/8b74d3341448f19d73f84309b2dfe1d848f3a8d5/ustcthesis.dtx#L1376 ，这里 `2\ccwd` 改成 `\z@`

**Comment by yuebai008** [comment]
这个更改之后怎么编译还是原来的模式

**Comment by zepinglee** [comment]
> 这个更改之后怎么编译还是原来的模式

改完之后用 `make` 编译，或者用 xetex （不是xelatex）编译一次 ustcthesis.dtx

**Comment by zepinglee** [comment]
或者在 cls 文件中再改一遍

**Comment by yuebai008** [comment]
搞定了，谢谢啦
