### ISSUE TITLE
封面页导师问题

### ISSUE THREAD

**Issue by vonfzm** [ustctug/ustcthesis#194]
封面页如果仅有一个导师的话，会在后面加一个“XXX教授”。以及字体改小了还是行距改小了？我用新版少了两页，而且致谢变成一页又空出一页，就用回旧版了。。。

**Comment by zepinglee** [comment]
1. 是我的锅
2. 可能是行距问题，我测试一下

我主要是整理了一下代码，没想到带了这么多 bug，感谢反馈！ @vonfzm

**Comment by zepinglee** [comment]
@vonfzm 
1. fixed in 06b5de7
2. 你是相对于哪个版本少了两页？

**Comment by zepinglee** [comment]
@vonfzm 试一下 70be41a 有没有修复行距问题
