### ISSUE TITLE
每一章应当从奇数页开始

### ISSUE THREAD

**Issue by FireUponSky** [ustctug/ustcthesis#196]
大家好，印刷厂要求论文的每一章都从奇数页开始（包括致谢，待发表论文等）。实现上，印刷厂让在每一章添加 `\cleardoublepage`。

能否在模板中直接实现？如果不知道这个，在印刷厂会耽误很多时间，非常感谢！

PS：虽然这个要求和撰写手册冲突，但拗不过印刷厂啊。。。

**Comment by zepinglee** [comment]
https://github.com/ustctug/ustcthesis/issues/154 

《撰写手册》有规定中间不留空白页，但是印刷厂那边似乎坚持要开启于奇数页，能不能给个他们的联系方式？

**Comment by FireUponSky** [comment]
@zepinglee 可否留个邮箱？我有印刷厂老师的微信。

另外，印刷厂给的修改方法非常奇葩。原话是说在 `\chapter` 后面添加 `\cleardoublepage`。这样造成，每一章标题后面会多出空白页这种奇葩排版。但他们不在乎，他们只在乎开启于奇数页。

**Comment by zepinglee** [comment]
zepinglee@gmail.com

应该是 `\chapter` 前面

**Comment by jiaopjie** [comment]
印刷厂现在这么霸道吗? 去年打印的时候是自助打印的. 有一些学生在帮忙, 可能是志愿者? 你坚持, 难道印刷厂还能坚持不给打?

**Comment by zepinglee** [comment]
有的老师没仔细看《撰写手册》，毕竟去年才出的
