### ISSUE TITLE
生僻字无法编译后显示

### ISSUE THREAD

**Issue by Damnatus7** [ustctug/ustcthesis#197]
字体库中缺少生僻字，如名字中含“芃”字会导致编译后作者栏不显示此字

**Comment by zepinglee** [comment]
你用的是什么系统，什么字体？

这个不是模板的问题，具体配置字体参考 ctex 宏包

**Comment by Damnatus7** [comment]
我是使用 sharelatex 的，😂打扰了。

**Comment by zepinglee** [comment]
sharelatex 上是 linux 系统，会自动调用 fandol 字库（一个缺了很多字的字库）。

建议你把 Mac 的字体（windows 的还凑合）拷贝上去，然后 `\documentclass[fontset=windows]{ustcthesis}`，应该就可以了，也可能还需要再配置一番

**Comment by Damnatus7** [comment]
好的，非常感谢！
