### ISSUE TITLE
编译出错 LaTeX Error: \begin{itemize}  ended by \end{document}.

### ISSUE THREAD

**Issue by Pengustc** [ustctug/ustcthesis#201]
编译出错。
问题：LaTeX Error: \begin{itemize} on input line 6 ended by \end{document}. [\end{document}]

已在 GitHub Issues 中搜索该问题的关键词，没有解决问题

使用的版本：
This is XeTeX, Version 3.14159265-2.6-0.99999 (MiKTeX 2.9.6840 64-bit) (preloaded format=xelatex 2018.10.11)  15 OCT 2018 11:16
entering extended mode
**./main.tex
(main.tex
LaTeX2e <2018-04-01> patch level 5
(ustcthesis.cls
Document Class: ustcthesis 2018/10/06 v3.1.01 USTC thesis template

正确的结果：应编译通过。

图片显示改动部分。
![_20181015113242](https://user-images.githubusercontent.com/26037002/46928675-553f6c80-d06e-11e8-8419-2fec74af01ad.png)

**Comment by zepinglee** [comment]
这个似乎不是模板的问题，估计是漏了 `\itemize` 吧？

你试下原始的模板示例能不能编译通过。

**Comment by Pengustc** [comment]
原始的模板示例能编译通过。我在使用中仅变动了图片中的内容，其余未作改动。
![_20181015120407](https://user-images.githubusercontent.com/26037002/46929485-73a76700-d072-11e8-8923-a1113a875377.png)

**Comment by Pengustc** [comment]
- 和内容无关。
- 后续尝试了多次，减少几个`\input`了的中文文件名，可以编译通过。
- 该问题可以关闭了，神奇的bug啊。
- 下图是尝试的部分截图。

![_20181016103924](https://user-images.githubusercontent.com/26037002/46989525-f93d1c80-d12f-11e8-8f54-01c056968fa1.png)
![_20181016104038](https://user-images.githubusercontent.com/26037002/46989526-f93d1c80-d12f-11e8-9ee0-864381d1e8e4.png)

**Comment by zepinglee** [comment]
windows 上 xelatex 不能使用中文文件名

**Comment by Pengustc** [comment]
Miktex里的xelatex能处理中文名的tex文件。
