### ISSUE TITLE
添加 Lyx 模板

### ISSUE THREAD

**Issue by zepinglee** [ustctug/ustcthesis#202]
由 @jmcui 来负责

另外 lyx 模板跟 latex 模板差别大嘛？所以是在 ustcthesis 这个项目上直接加文件还是另起一个项目？

**Comment by jmcui** [comment]
另起一个项目吧。

lyx调用了latex模板。
在latex模板的基础上，加了一个lyx layout层。把一些latex命令可视化了，用起来会方便一些而已。

这个模板一方面是提供给latex命令盲用的；另一方面LyX确实可以方便编辑，从而将编辑论文的注意力放到内容上，因此 我觉得尽量隐藏底层，在ustc-lyx中文件尽量简洁。

将ustcthesis直接作为子项目（子文件夹），放到ustc-lyx中，我觉得是个不错的设置。如果是git下载，用户就会同时下载两个项目里的最新版本。

**Comment by zepinglee** [comment]
Ok，那就新建一个项目吧

**Comment by zepinglee** [comment]
如果你愿意的话可以把原来的项目 transfer 到 ustctug 下，这样就不用维护两个项目了，如果别人访问原来的 https://github.com/jmcui/USTC-Lyx 会自动跳转到 ustctug 的
