### ISSUE TITLE
编译过程中提示Invalid fontname `[STIX2Math

### ISSUE THREAD

**Issue by qingpingjian** [ustctug/ustcthesis#207]
## 检查
- [OK ] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [OK ] 已经将模板升级到了最新版
- [ OK] 已经阅读使用说明文档 `ustcthesis.pdf`
- [OK ] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统： Windows 10 
- TeX 发行版： TeX Live 2017 
- 模板类型： master
![20181129221334](https://user-images.githubusercontent.com/26720442/49227465-1ef25c80-f424-11e8-93b0-a884917af70e.png)

## 描述问题
编译模板能够正常编译，不影响模板正常使用，但是在消息中给出提示：kpathsea:make_tex: Invalid fontname `[STIX2Math', contains '['

截图：

**Comment by zepinglee** [comment]
似乎跟 https://tex.stackexchange.com/q/419854/82731 相同，但是没有别的影响，可以不用管

**Comment by innocnet** [comment]
哈, 我也碰到这问题了
