### ISSUE TITLE
修改页眉与参考文献（与论文规范无关）

### ISSUE THREAD

**Issue by GongSiqiu** [ustctug/ustcthesis#208]
我想将这个模板用于其他论文写作，请问
1. 除了修改cls中ustc@header有没有什么简单的方法修改页眉
2. 怎样使参考文献不另起一页，从而使内容更加紧凑

**Comment by zepinglee** [comment]
1. 你可以修改把整个页眉部分替换为用 fancyhdr 实现，参考 ef45acf ；注意 fancyhdr 定义的风格不要随意切换。

2. 因为 `thesis` 是基于 `book` 类，所以 `\bibliography` 是一个 chapter，你可能需要使用 article 类，这样 `\bibliography` 就是一个 section，不会另起一页。

另外你写的是什么什么模板？如果使用比较广泛的话可以贡献到 ustctug

**Comment by GongSiqiu** [comment]
谢谢。
我只是喜欢用这个模板写课程论文。之前只需要稍微改一下封面和页眉就好。这次写近现代史纲要小论文，觉得不会有太多参考文献，所以想看看有没有可能使参考文献不分页。

**Comment by zepinglee** [comment]
史纲的话还是用 article 吧，不过要改的内容有点多，因为很多代码都是只考虑了 book 的。

建议在 article 的基础上，从 ustcthesis 加内容进去。

**Comment by GongSiqiu** [comment]
我最后直接让Chapter不换页了
\usepackage{xpatch}
\makeatletter
\xpatchcmd{\chapter}
  {\if@openright\cleardoublepage\else\clearpage\fi}{\par\relax}
  {}{}
\makeatother

https://liam.page/2015/04/22/cancle-clearpage-in-chapter/
