### ISSUE TITLE
段间距过大

### ISSUE THREAD

**Issue by Darerd** [ustctug/ustcthesis#209]
## 编译环境
- 编译的系统： / Windows 10 / 
- TeX 发行版： / TeX Live 2018 / 
- 模板类型： / master / 

## 描述问题

段间距过大。

![screenshot](https://user-images.githubusercontent.com/12290822/50943344-00718d80-14c7-11e9-83fb-ef7dc5c3e9df.jpg)

[使用模板时，遇到的问题.pdf](https://github.com/ustctug/ustcthesis/files/2743217/default.pdf)
问题描述在附件

**Comment by zepinglee** [comment]
这主要是因为，行距是一个固定的值（20bp），而段间距是一个弹性的值（0bp plus 1bp）。在你的情况里，为了让页面底部对齐，TeX 强行把行距拉大了。

**Comment by Stone-Zeng** [comment]
用 `\raggerbottom` 可以吗？

**Comment by zepinglee** [comment]
> 用 `\raggerbottom` 可以吗？

学习啦！我顺便还发现了 `\sloppy`

**Comment by Stone-Zeng** [comment]
可以参考 <https://github.com/CTeX-org/ctex-kit/issues/318>。

**Comment by Darerd** [comment]
\sloppy 怎么写呢？

是在段末\sloppy

这样吗？

________________________________
代宇辉
High Magnetic Field Laboratory, Chinese Academy of Sciences
Hefei, 230031, PR. China
Tel: 15665415003

发件人： Zeping Lee<mailto:notifications@github.com>
发送时间： 2019-01-10 15:49
收件人： ustctug/ustcthesis<mailto:ustcthesis@noreply.github.com>
抄送： Darerd<mailto:yuhuidai@outlook.com>; Author<mailto:author@noreply.github.com>
主题： Re: [ustctug/ustcthesis] 段间距过大 (#209)

用 \raggerbottom 可以吗？

学习啦！我顺便还发现了 \sloppy

―

**Comment by zepinglee** [comment]
@Darerd 我刚 push 到 master 分支，你更新模板就可以了，不需要在 main.tex 文件里添加内容
