### ISSUE TITLE
参考文献引用的问题

### ISSUE THREAD

**Issue by Darerd** [ustctug/ustcthesis#210]
## 编译环境
- 编译的系统： Windows 10 
- TeX 发行版： TeX Live 2018 
- 编译软件：TexStudio
- 模板类型： master 
[问题.pdf](https://github.com/ustctug/ustcthesis/files/2748671/default.pdf)

**Comment by zepinglee** [comment]
需要用 bibtex 编译

**Comment by Darerd** [comment]
收到，谢谢大佬回复小白的白痴问题 ??哈哈

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________
