### ISSUE TITLE
hyperref 的 `\autoref` 引用 amsthm 定义的 corollary 时名称不对

### ISSUE THREAD

**Issue by SirNing** [ustctug/ustcthesis#211]
## 描述问题
`\autoref` 一个 corollary 环境时 ，定义的 `\corollaryautorefname`并不起作用，对一个 corollary 环境`\autoref` 生成 的是 定理+编号，然而我希望能生成 推论+编号。
请问该怎么处理？

示例代码：
```TeX
\documentclass[doctor]{ustcthesis}

\usepackage{amsthm}
\usepackage{hyperref}
\newcommand{\corollaryautorefname}{推论} %然而这个似乎不起作用

\begin{document}

\chapter{Test}

\begin{theorem}
\label{thm}
\end{theorem}

\begin{corollary}
\label{cor}
\end{corollary}

\autoref{thm}  %生成的是  定理1
\autoref{cor}  %生成的是  定理2   然而我希望能生成  推论2

\end{document}
```

截图：
<img width="289" alt="screen shot 2019-01-16 at 3 24 33 pm" src="https://user-images.githubusercontent.com/12290822/51232758-d6c2d580-19a2-11e9-912a-ccd33135bb52.png">

**Comment by zepinglee** [comment]
你想表达什么？

**Comment by SirNing** [comment]
抱歉 不小心点错了。

我的问题是
\autoref 一个 corollary环境时 ，定义的\corollaryautorefname 并不起作用，对一个corollary环境\autoref生成 的是 定理+编号，然而我希望能生成 推论+编号。
请问该怎么处理？

**Comment by zepinglee** [comment]
示例代码和截图？

**Comment by SirNing** [comment]
\begin{theorem}
\label{thm}
\end{theorem}

\begin{corollary}
\label{cor}
\end{corollary}

\autoref{thm}  %生成的是  定理1
\autoref{cor}    %生成的是 定理2   然而我希望能生成  推论2

**Comment by SirNing** [comment]
已经定义过
\newcommand{\theoremautorefname}{定理}
\newcommand{\corollaryautorefname}{推论}    %然而这个似乎不起作用

**Comment by zepinglee** [comment]
嗯，我能复现你的问题，稍后研究一下

**Comment by SirNing** [comment]
多谢，麻烦了

**Comment by zepinglee** [comment]
参考 https://tex.stackexchange.com/q/187388/82731 ，我个人认为 cleveref 的方案最好。

不过这样还有个问题，现在是载入 `amsthm` 后立即定义 `corollary` 等环境的，但是 `cleveref` 的加载必须在载入`amsthm` 之后和 定义`corollary` 之前。

@Stone-Zeng 你怎么看？我这里的情况是，学校并没有规定“定理”等环境的格式，所以按照最小化的原则，模板不会自动加载 `amsthm` 或定义“定理”等环境。为了方便用户使用，我用 `ctexhook` 在用户载入 `amsthm` 后自动定义默认的“定理”等环境。我也考虑过用 `\AtBeginDocument` 等方案，但是这样用户在导言区定义的格式就会被覆盖，所以不够灵活。

**Comment by Stone-Zeng** [comment]
用 `\AtEndOfPackage` 之类的？

**Comment by zepinglee** [comment]
> 用 `\AtEndOfPackage` 之类的？

`\AtEndOfPackage` 只是在本宏包末尾执行一段代码，不能针对用户载入的其他宏包进行 patch

**Comment by Stone-Zeng** [comment]
`ctex` 提供了 `\ctex_at_end_package:nn`：

>与 `filehook` 宏包的 `\AtEndOfPackageFile*` 类似，如果原来没有在载入宏包则在宏包末尾执行语句，否则立即执行。

**Comment by zepinglee** [comment]
> `ctex` 提供了 `\ctex_at_end_package:nn`：
> 
> > 与 `filehook` 宏包的 `\AtEndOfPackageFile*` 类似，如果原来没有在载入宏包则在宏包末尾执行语句，否则立即执行。

我目前就是这样做的，比如在 cls 中有：
```
\ctex_at_end_package:nn{hyperref}{
  \newtheorem{corollary}[theorem]{\ustc@corollaryname}
}
```
但是用户在主文档中写
```
\usepackage{amsthm}
\usepackage{hyperref}
\usepackage{cleveref}
```
就会有问题，因为 `\newtheorem{corollary}[theorem]{\ustc@corollaryname}` 需要在 `\usepackage{cleveref}` 才会使 `\cref{cor}` 有效

**Comment by fylimas** [comment]
现在，我是在cls文件里添加了引用thmtools宏包这一行。考虑到thmtools宏包能够自动“修正”amsthm在与autoref、cleveref一起使用时，同一个counter产生的混淆，因此能够达到目的。

不过是不是符合自定义和最小化，就不是很确定了。
```
\ustc@atendpackage{amsthm}{
  \RequirePackage{thmtools}
```

**Comment by zepinglee** [comment]
我稍后测试一下

**Comment by zhedie** [comment]
我想问一下，texlive 编译后出现如下错误怎么解决

 fontspec error: "font-not-found"
! 
! The font "XITSMath-Regular" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.

**Comment by zepinglee** [comment]
@zhedie 参考 #214

**Comment by zhedie** [comment]
对了，编译文件所在目录与texlive 安装目录不在一个磁盘，这应该没有影响吧？

**Comment by zepinglee** [comment]
@zhedie 没影响，新开 issue 讨论不相关的问题

**Comment by zepinglee** [comment]
好像是可以，不过我更建议手动写成 `引理~\ref{lem:foo}`
