### ISSUE TITLE
word版本 字数统计

### ISSUE THREAD

**Issue by z740695564** [ustctug/ustcthesis#213]
软件环境：
    操作系统：win10 64位专业版；
    使用软件：TeX Live；
    编辑器软件：TEXStudio和SumatraPDF
问题：
1、科大硕士论文是否要求提交word版本？
2、是否需要用word版本查重？
3、tex如何统计字数？

**Comment by zepinglee** [comment]
1. 我不太了解现在的情况，根据往年清咖滚 1，2是不一样的
2. 据我了解，tex 统计字数没有一个特别靠谱的方法，尤其是对中文；有其他学校的 thesis 有一些实验性的脚本，你不妨研究一下发个 PR。

另外一种可能方法是把 pdf 的内容复制到 word 里。
