### ISSUE TITLE
字体问题

### ISSUE THREAD

**Issue by gky1993** [ustctug/ustcthesis#214]
在Xelatex编译main时出现了一个字体问题

The font "XITSMath-Regular" cannot be found

我在压缩包里没见到otf文件，我想知道字体有没有提供的资源

谢谢

**Comment by zepinglee** [comment]
texlive 是怎么安装的？按照模板去填一下

**Comment by gky1993** [comment]
我用的清华的镜像安装的

**Comment by zepinglee** [comment]
## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：MacTeX 2018 / TeX Live 2018 / MikTeX 2.9.6753
- 相关宏包版本：ctex v2.4.14 / unicode-math v0.8m
- 模板类型： doctor / master / bachelor

**Comment by gky1993** [comment]
我用的是win10， Tex Live2018， unicode-math
模板是master其他默认

我用老版的也是字体问题
The font "Courier" cannot be found.

**Comment by zepinglee** [comment]
研究生院的版本有 Courier 字体的问题，在最新版已经修复。

XITSMath-Regular 的问题是 fontspec 的 \IfFontExists 命令检测有误，也有人报告相同的问题，目前还不知道原因。

你可以用 tlmgr 将 xits 宏包升级到最新应该就可以正常编译

**Comment by gky1993** [comment]
嗯，可以编译了，谢谢

**Comment by yhli097** [comment]
> 研究生院的版本有 Courier 字体的问题，在最新版已经修复。
> 
> XITSMath-Regular 的问题是 fontspec 的 \IfFontExists 命令检测有误，也有人报告相同的问题，目前还不知道原因。
> 
> 你可以用 tlmgr 将 xits 宏包升级到最新应该就可以正常编译

我在Windows 10下TeX live 2018  无法在cmd下进行如Q&A中的更新，
cmd中结果如下：
![image](https://user-images.githubusercontent.com/48901061/56225575-3e70e580-60a4-11e9-9020-affbd3f63c08.png)

**Comment by zepinglee** [comment]
@yhli097 这个frozen 并不影响升级

**Comment by jungleblack007** [comment]
我也遇到这个问题了，而且没办法用tlmgr升级。
```cmd
C:\Users\Jungle Black>tlmgr update --self fonspec xits
tlmgr.pl: Remote repository is newer than local (2018 < 2019)
Cross release updates are only supported with
  update-tlmgr-latest(.sh/.exe) --update
Please see https://tug.org/texlive/upgrade.html for details.
```

**Comment by jungleblack007** [comment]
> 嗯，可以编译了，谢谢

想问您是怎么解决的，我遇到了完全一样的问题

**Comment by zepinglee** [comment]
@jungleblack007 这个应该已经修复了，你试试最新的模板

**Comment by jungleblack007** [comment]
> @jungleblack007 这个应该已经修复了，你试试最新的模板

我下的是今年4月份上传的模板，应该是最新的了

**Comment by zepinglee** [comment]
> 我下的是今年4月份上传的模板，应该是最新的了

https://github.com/ustctug/ustcthesis/releases

**Comment by jungleblack007** [comment]
中国科学技术大学。呃我是国科大的QAQ

**Comment by gky1993** [comment]
> > 嗯，可以编译了，谢谢
> 
> 想问您是怎么解决的，我遇到了完全一样的问题

你特定更新一下xits的软件包试试

**Comment by jungleblack007** [comment]
更新这个包也没什么用，我知道了，是要用pdflatex编译。但是这个编译完之后参考文献会显示问号，然后按一次bibtex编译，再连续两次pdflatex编译，参考文献也就能显示了。目前我是这样用的
