### ISSUE TITLE
关于minipage的问题

### ISSUE THREAD

**Issue by ustcerlik** [ustctug/ustcthesis#215]
当使用minipage时出现以下情况，当图像为长矩形时，文中会出现较多空行；
如果图像接近正方形，则无异常。见下面两图。
![uo _ jr41t29 bzyvyikot3](https://user-images.githubusercontent.com/31697817/53958596-6b80be80-411c-11e9-96fe-22cd8f415f21.png)
![lmzl1pti rasu3jq_tq y](https://user-images.githubusercontent.com/31697817/53958607-71769f80-411c-11e9-84b2-d5fc88e1e2e9.png)

**Comment by ustcerlik** [comment]
已解决，是因为下面没写字，写完字以没有这个问题了。

**Comment by zepinglee** [comment]
我无法复现这个问题，可能跟 #209 有关，建议使用 master 分支上最新的版本。

```
\documentclass[doctor]{ustcthesis}

\usepackage{zhlipsum}

\begin{document}

\begin{figure}
  \begin{minipage}{0.48\linewidth}
    \centering
    \includegraphics[width=0.96\textwidth]{figures/circleLBP.png}
    \caption{几种圆形模式的LBP算子}
    \label{circleLBP}
  \end{minipage}%
  \begin{minipage}{0.48\linewidth}
    \centering
    \includegraphics[width=0.96\textwidth]{figures/rotationLBP.png}
    \caption{旋转不变模式的LBP算子}
    \label{rotationLBP}
  \end{minipage}
\end{figure}

\zhlipsum[1-2]

\subsection{Test}
\zhlipsum[1-2]

\end{document}
```
![Screen Shot 2019-03-11 at 9 55 50 PM](https://user-images.githubusercontent.com/12290822/54129066-71421100-4448-11e9-8663-d2bdf2c14692.png)
![circleLBP](https://user-images.githubusercontent.com/12290822/54129096-7ef79680-4448-11e9-8716-02ca92ed71e4.png)
![rotationLBP](https://user-images.githubusercontent.com/12290822/54129097-7f902d00-4448-11e9-81ac-3baa582c1edd.png)
