### ISSUE TITLE
黑体缺失

### ISSUE THREAD

**Issue by devzhui** [ustctug/ustcthesis#216]
## 检查
- [ ] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 
- TeX 发行版：TeX Live 2018 
- 相关宏包版本：ctex v2.4.14 / unicode-math v0.8m
- 模板类型： doctor / master / bachelor

## 描述问题
《撰写手册》第 xx 页要求……而模板编译的结果是……

黑体缺失，不是很清楚里面你们的字体是怎么弄的。源码，在我的环境下，所有需要黑体字的地方，全部变成了宋体。编译log中并没有发现字体缺失的问题，而且我自己mac上的黑体也是没有缺失的。(ps 我在Linux环境下也是同样，黑体缺失)
![image](https://user-images.githubusercontent.com/6292260/54534570-9cd47680-49c7-11e9-911b-7f113d7965bf.png)

> 我无法复现你的问题。
> 
> Mac 系统的中文字体配置主要在这一段：
> [ustcthesis/ustcthesis.dtx](https://github.com/ustctug/ustcthesis/blob/af4cad0a091a671168eb2d3c3a592a5d4447773e/ustcthesis.dtx#L842)
> 
> Line 842 in [af4cad0](/ustctug/ustcthesis/commit/af4cad0a091a671168eb2d3c3a592a5d4447773e)
> 
>  \setCJKmainfont[ 
> 你可以在 Font Book 里检查一下 Heiti SC 是不是缺失了

多谢，我记起来这个我mac上下的这个模板是不是最新的，刚下了个最新的试了一下，正常了。Linux下可能是我字体缺失

**Comment by zepinglee** [comment]
我无法复现你的问题。

Mac 系统的中文字体配置主要在这一段：
https://github.com/ustctug/ustcthesis/blob/af4cad0a091a671168eb2d3c3a592a5d4447773e/ustcthesis.dtx#L842

你可以在 Font Book 里检查一下 Heiti SC 是不是缺失了
