### ISSUE TITLE
参考文献

### ISSUE THREAD

**Issue by qiuqiula** [ustctug/ustcthesis#218]
有几个关于参考文献的问题。
1. 想要去掉 inbook,incollection,inproceedings 中析出来源文献前的//符号
    找到了关于bibtex编辑的pdf, 里面是说把gbpunctin=false就可以了。但是我在源代码ustcnumerical文档中没有找到参数gbpunctin. 请问应该改哪个参数？
2. 如何把引用的文献标题改成斜体的？（这里的文献是英文的）
3. 参考文献按作者的姓排序，但是年份是放在杂志后面的，文中引用文献的文献若连续，仍显示[1-3]. 请问这样可以实现吗？如果可以，该怎么改？

问题有点多，谢谢！

**Comment by zepinglee** [comment]
1. 这是学校研究生院规定的；`gbpunctin=false` 是 biblatex 的，`ustcthesis` 用的是 `bibtex` + `natbib`;
2. 也是学校规定的；
3. 《研究生学位论文撰写手册》里面规定了具体的格式，建议先阅读一遍。

**Comment by qiuqiula** [comment]
谢谢你的回复！
对于第一条，在bibtex+natbib下，能不能把‘//’这个符号去掉改成‘in’呢？

**Comment by zepinglee** [comment]
需要自行修改 `bst` 文件，我不建议自定义参考文献格式。

**Comment by qiuqiula** [comment]
请问该怎么修改呢？需要改动很多吗？
