### ISSUE TITLE
\ref标签并不能显示某个具体子章节，例如  3.2.2

### ISSUE THREAD

**Issue by popoaichuiniu** [ustctug/ustcthesis#219]
## 检查
- [ ] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：MacTeX 2018 / TeX Live 2018 / MikTeX 2.9.6753
- 相关宏包版本：ctex v2.4.14 / unicode-math v0.8m
- 模板类型： doctor / master / bachelor

## 描述问题
《撰写手册》第 xx 页要求……而模板编译的结果是……

示例代码：
```TeX
\documentclass[doctor]{ustcthesis}
\begin{document}
abc
\end{document}
```

截图：

**Comment by popoaichuiniu** [comment]
> ## 检查
> * [ ]  已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
> * [ ]  已经将模板升级到了最新版
> * [ ]  已经阅读使用说明文档 `ustcthesis.pdf`
> * [ ]  已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98)
> 
> ## 编译环境
> * 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
> * TeX 发行版：MacTeX 2018 / TeX Live 2018 / MikTeX 2.9.6753
> * 相关宏包版本：ctex v2.4.14 / unicode-math v0.8m
> * 模板类型： doctor / master / bachelor
> 
> ## 描述问题
> 《撰写手册》第 xx 页要求……而模板编译的结果是……
> 
> 示例代码：
> 
> ```
> \documentclass[doctor]{ustcthesis}
> \begin{document}
> abc
> \end{document}
>

**Comment by popoaichuiniu** [comment]
是不是不支持四级标题啊！

**Comment by popoaichuiniu** [comment]
四级标题又变成了一级3.2.2.2 变成了2

**Comment by zepinglee** [comment]
《撰写手册》第 11 页有一个推荐的标题形式
