### ISSUE TITLE
交叉引用之后缺少空格

### ISSUE THREAD

**Issue by kfckfckf** [ustctug/ustcthesis#220]
## 编译环境
- 编译的系统：Windows 10
- TeX 发行版：MikTeX 2.9.6753
- 相关宏包版本：ctex v2.4.14 / unicode-math v0.8n
- 模板类型： doctor

## 描述问题
在交叉引用的时候数字与后面的中文之间没有自动添加空格，不知道算不算一个bug？

示例代码：
```TeX
本算法的工作流程如\autoref{fig:pipeline}所示。本算法的工作流程如图3.2所示。
```

截图：
![Annotation 2019-04-02 140954](https://user-images.githubusercontent.com/7316919/55379898-0e2c3180-5551-11e9-947c-dbbb00f25f98.png)

**Comment by zepinglee** [comment]
参考 https://github.com/CTeX-org/ctex-kit/issues/392

建议写成 `如图~\ref{fig:pipeline} 所示`
