### ISSUE TITLE
字体更新后仍然找不到

### ISSUE THREAD

**Issue by qweer2416** [ustctug/ustcthesis#221]
## 检查
- [ √] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [√ ] 已经将模板升级到了最新版
- [√ ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [ √] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：MacTeX 2018 / TeX Live 2018 / MikTeX 2.9.6753
- 相关宏包版本：ctex v2.4.14 / unicode-math v0.8m
- 模板类型： doctor / master / bachelor

## 描述问题
提示 XITSMath-Regular  找不到。
在使用tlg命令行更新后仍然找不到字体，更新时提示texlive2018被冻结

截图：
![图片](https://user-images.githubusercontent.com/49311237/55628800-3c756f80-57e4-11e9-88d5-e8faa8ea9e4a.png)
![图片](https://user-images.githubusercontent.com/49311237/55628833-5020d600-57e4-11e9-987d-97e37c4aac36.png)

**Comment by stone-zeng** [comment]
图片没有插好：

![图片](https://user-images.githubusercontent.com/49311237/55628800-3c756f80-57e4-11e9-88d5-e8faa8ea9e4a.png)
![图片](https://user-images.githubusercontent.com/49311237/55628833-5020d600-57e4-11e9-987d-97e37c4aac36.png)

TeX Live 快要发布新版本前旧版本就会冻结。可以打开路径（`<texlive>/<年份>/texmf-dist/fonts/opentype/public/xits/`）检查一下到底有没有更新成功。

**Comment by zepinglee** [comment]
@qweer2416 你试下 `tlmgr update xits`，其实只需要更新 `xits` 就可以了

**Comment by hsiangyunK** [comment]
`tlmgr update xits`是不能解决问题的 至少我这个错误提示还有
建议换MikTex后
```
mpm.exe --set-repository=http://mirrors.ustc.edu.cn/CTAN/systems/win32/miktex/tm/packages/
```

**Comment by zepinglee** [comment]
这个 bug 很奇怪，事实上我是有判断 xits 的字体名的：
https://github.com/ustctug/ustcthesis/blob/cc19903fd6858e6cc493eca6e13e3807faab9726/ustcthesis.cls#L181

但是很多人新装的 TeX Live 2018 会判断认为 `XITS-Regular.otf` 存在所以调用新的字体名，但实际上xits 字体还是旧的，所以会找不到 `XITS-Regular.otf`。这可能是 `fontspec` 的 bug。

@qweer2416 你检查一下 `<texlive>/<年份>/texmf-dist/fonts/opentype/public/xits/` 目录下的文件名，再试试更新一下 `fontspec` ？

@hsiangyunK 我这里的 texlive 2018 （全部宏包已经升级到最新）是可以编译通过的。

**Comment by qweer2416** [comment]
也许最简单的方法是换用Miktex,,,

**Comment by qweer2416** [comment]
> 
> 
> 这个 bug 很奇怪，事实上我是有判断 xits 的字体名的：
> 
> [ustcthesis/ustcthesis.cls](https://github.com/ustctug/ustcthesis/blob/cc19903fd6858e6cc493eca6e13e3807faab9726/ustcthesis.cls#L181)
> 
> Line 181 in [cc19903](/ustctug/ustcthesis/commit/cc19903fd6858e6cc493eca6e13e3807faab9726)
>  \IfFontExistsTF{XITS-Regular.otf}{ 
> 
> 但是很多人新装的 TeX Live 2018 会判断认为 `XITS-Regular.otf` 存在所以调用新的字体名，但实际上xits 字体还是旧的，所以会找不到 `XITS-Regular.otf`。这可能是 `fontspec` 的 bug。
> 
> @qweer2416 你检查一下 `<texlive>/<年份>/texmf-dist/fonts/opentype/public/xits/` 目录下的文件名，再试试更新一下 `fontspec` ？
> 
> @hsiangyunK 我这里的 texlive 2018 （全部宏包已经升级到最新）是可以编译通过的。

![图片](https://user-images.githubusercontent.com/49311237/55670912-5d10f880-58bc-11e9-8b5b-f5b036ccdf7c.png)
我试试换下大小写

**Comment by stone-zeng** [comment]
这样确实是没有更新的状态……

可以试一试 `tlmgr info xits` 检查安装状态。其实你最开始的那一个截屏是正常的，但并没有截完整。我怀疑可能是下载过程中出现问题，然后就没有继续更新了。

**Comment by qweer2416** [comment]
多谢，已解决。

**Comment by lailoo** [comment]
你好可以问一下是怎么解决的吗？

**Comment by lailoo** [comment]
我和你出现的问题是一模一样的，但网站找了很久都没有发现要怎么做才好

**Comment by zepinglee** [comment]
@lailoo 用 master 分支的版本应该不存在这个问题
