### ISSUE TITLE
摘要和目录不是奇数页开始

### ISSUE THREAD

**Issue by liuerhei** [ustctug/ustcthesis#222]
## 描述问题
印刷厂老师要求中英文摘要、文章目录、图/表/算法目录均需奇数页开始，但是由于模板使用openany，因此会导致偶数页开始，不符合文章打印要求。最近大家打印文章时，因为这个问题需要修改文章排版。

##建议
建议将将openany选项更改为openright。

**Comment by zepinglee** [comment]
请阅读《研究生􏰃􏰊􏰋􏰌􏰍􏰎􏰏􏰐学位论文撰写手册》第 9 页 第 (2) 条

**Comment by zepinglee** [comment]
模板以研究生院的《撰写手册》为准，如果你对撰写手册有异议，可以向研究生院反馈，经研究生院确认后我可以修改。

**Comment by liuerhei** [comment]
好的，看来摘要这些部分需要自己手动加空白页。谢谢
