### ISSUE TITLE
章标题中不能插入转义符号

### ISSUE THREAD

**Issue by liye0713** [ustctug/ustcthesis#223]
## 检查
- [ ] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统： Windows 10 
- TeX 发行版： TeX Live 2018
- 模板类型：  master

## 描述问题
在章标题中插入转义字符，编译报错

示例代码：
\section{三线表 $\alpha$}

截图：
![image](https://user-images.githubusercontent.com/25117645/56586532-77fca000-6612-11e9-9c7c-abdae5be39fd.png)

**Comment by zepinglee** [comment]
我能复现你的问题，经测试是因为 hyperref 宏包导致的，下面的代码注释掉第二行就可以编译通过
```TeX
\documentclass[doctor]{ustcthesis}
\usepackage{hyperref}
\begin{document}
\chapter{Foo}
\section{Table $\alpha$}
\end{document}
```

可能是 hyperref 的配置有些问题

**Comment by stone-zeng** [comment]
是与 `unicode-math` 的兼容性问题，见 <https://tex.stackexchange.com/q/69331>。

**Comment by zepinglee** [comment]
@liye0713 可以用 `\texorpdfstring` 暂时解决，但是根本上还是需要 `unicode-math` 和 `hyperref` 宏包来解决

**Comment by zepinglee** [comment]
另外参考 https://www.zhihu.com/question/30287181

**Comment by zepinglee** [comment]
`\mu` 的问题已经修复： https://github.com/ho-tex/hyperref/pull/90

**Comment by zepinglee** [comment]
Fixed in ce808b2 .
