### ISSUE TITLE
模板导出的公式字体并不是times new roman

### ISSUE THREAD

**Issue by zepinglee** [ustctug/ustcthesis#224]
模板导出的公式字体并不是times new roman

_Originally posted by @zhengprince in https://github.com/ustctug/ustcthesis/issues/1#issuecomment-486545289_

**Comment by zepinglee** [comment]
@zhengprince Times New Roman 没有数学符号，所以不能作为数学字体；模板用的是 XITS，算是 Times clone，所以跟西文字体 Times New Roman 搭配使用没有问题

**Comment by zhengprince** [comment]
> @zhengprince Times New Roman 没有数学符号，所以不能作为数学字体；模板用的是 XITS，算是 Times clone，所以跟西文字体 Times New Roman 搭配使用没有问题

看上去还是不大习惯，很烦恼

**Comment by zepinglee** [comment]
另外参考 https://github.com/xueruini/thuthesis/issues/361

**Comment by zepinglee** [comment]
> > @zhengprince Times New Roman 没有数学符号，所以不能作为数学字体；模板用的是 XITS，算是 Times clone，所以跟西文字体 Times New Roman 搭配使用没有问题
> 
> 看上去还是不大习惯，很烦恼

所以你不妨来做一套数学字体搭配 Times New Roman 【滑稽】

**Comment by zhengprince** [comment]
> > > @zhengprince Times New Roman 没有数学符号，所以不能作为数学字体；模板用的是 XITS，算是 Times clone，所以跟西文字体 Times New Roman 搭配使用没有问题
> > 
> > 
> > 看上去还是不大习惯，很烦恼
> 
> 所以你不妨来做一套数学字体搭配 Times New Roman 【滑稽】

请不要太【滑稽】

**Comment by zepinglee** [comment]
> > > > @zhengprince Times New Roman 没有数学符号，所以不能作为数学字体；模板用的是 XITS，算是 Times clone，所以跟西文字体 Times New Roman 搭配使用没有问题
> > > 
> > > 
> > > 看上去还是不大习惯，很烦恼
> > 
> > 
> > 所以你不妨来做一套数学字体搭配 Times New Roman 【滑稽】
> 
> 请不要太【滑稽】

https://github.com/stipub/stixfonts
https://github.com/alif-type/xits
https://github.com/firamath/firamath
https://github.com/YuanshengZhao/armt

这几个都是开源的，你可以参考一下【斜眼笑】

**Comment by zhengprince** [comment]
@zepinglee 

> 我最近测试了一下 `unicode-math` + Times New Roman + STIX2Math，感觉数学字体部分有点太粗了，如图所示：
> ![screen shot 2018-07-18 at 11 57 38 pm](https://user-images.githubusercontent.com/12290822/42893326-9c3da99e-8ae6-11e8-8bf1-6fdbfc24d964.png)
> 一眼看过去，文字中的数学符“f”和“g”几乎能被认为是粗体。
> 
> 另外，`newtx` 的作者 Michael Sharpe 在 stickstoo 宏包中说：
> 
> > As of the initial release of STIX2, the math fonts have some problem which make them unsuited to high quality mathematical typesetting...
> 
> @xueruini 怎么看？


> 我失误了，刚刚给的例子的西文字体没设成 Times New Roman，还是 Computer Modern。其实 STIX2Math 在 Times New Roman 中的效果还不错：
> 
> ![screen shot 2018-07-19 at 10 34 58 pm](https://user-images.githubusercontent.com/12290822/42949329-1bba2752-8ba4-11e8-810f-9faaefd031ec.png)

请问这段代码在哪？谢谢~

**Comment by zepinglee** [comment]
模板的实例文档 `math.tex` 里有

**Comment by zhengprince** [comment]
> 模板的实例文档 `math.tex` 里有

我指的是对字体的设置

**Comment by zepinglee** [comment]
> > 模板的实例文档 `math.tex` 里有
> 
> 我指的是对字体的设置

这里是若干个版本前的，当时用了 STIX Two Math 字体，但是这个字体依然有很多问题，所以后来又改成了 XITS Math，见 dd71231

**Comment by zhengprince** [comment]
![image](https://user-images.githubusercontent.com/11679672/56717783-ffabf100-676f-11e9-8bd6-dd81d4d20f0f.png)
这就有点意思了，我看ustcthesis.cls里依然把STIX Two Math的优先级设的比XITS Math高，这个是Lyx模板里的

**Comment by zepinglee** [comment]
`ustclyx` 是把 `ustcthesis` 作为 git submodule，你可以用 `git submodule update --init --remote --merge --recursive` 更新一下

**Comment by zhengprince** [comment]
> `ustclyx` 是把 `ustcthesis` 作为 git submodule，你可以用 `git submodule update --init --remote --merge --recursive` 更新一下

我装一下git先。。。【熊猫挠头。jpg

**Comment by zhengprince** [comment]
> `ustclyx` 是把 `ustcthesis` 作为 git submodule，你可以用 `git submodule update --init --remote --merge --recursive` 更新一下

现在问题貌似更多了。。。编译都无法通过。

**Comment by zhengprince** [comment]
似乎要好了点

**Comment by zhengprince** [comment]
似乎要好了点。昨晚找到了`MathTime`，[链接](http://www.latexstudio.net/archives/241.html)，正在研究

**Comment by zepinglee** [comment]
模板里面用了 `fontspec` 和 `unicode-math`，跟 mathtype 不一定兼容

**Comment by zhengprince** [comment]
是不太兼容

**Comment by zhengprince** [comment]
我尝试把`unicode-math`和`fontspec`从`ustcthesis.cls`中移除换成`MathTimePro2`，做了如下努力:（用的是最新的latex模板v3.1.05）
- 注释掉`\RequirePackage{unicode-math}`
以及
```
\unimathsetup{
  math-style = ISO,
  bold-style = ISO,
  nabla      = upright,
  partial    = upright,
}
```
- 注释’fontspec‘从177到184行
- 注释`stixtwo`和’xitsnew‘相关语句从185行到222行
编译时报错，
```
! Undefined control sequence.
l.1012 \removenolimits
                      {%
? 
```
不是很懂是什么错，于是先把1012行到1018行注释掉看看，然后报的错就让我不敢继续乱改了! ```
Undefined control sequence.
\square ->\mdlgwhtsquare 
                         
l.61 \makestatement
                   
? 
```
求教，后面这两个错误是什么原因导致的？这是什么样的关联？以及到底应该怎么移除`unicode-math`而不出错？thx

**Comment by zepinglee** [comment]
1. 不建议这样折腾，因为中文字体需要 fontspec，所以搭配传统的 nfss 使用会有很多坑；
2. 选择 `unicode-math` 是为了让模板尽可能遵循 GB 3102.11-1993，一些符号与 LaTeX 的习惯不太一致。（参考 https://github.com/latexstudio/ChinaThesis/wiki/GB-math ）
3. 与其折腾 nfss，不如做一套 opentype math 字体，在 word 里也可以使用（滑稽）。或者修修 `unicode-math` 的 bug 也有价值。
4. 如果你选择折腾：（围笑）
  - 建议你修改 dtx 文件，make 时会覆盖掉 cls；
  - `\removenolimits` 和 `\mdlgwhtsquare` 都是 `unicode-math` 的命令；你需要把 unicode 相关的命令全部删掉或者替换为等价的命令（围笑）

**Comment by zhengprince** [comment]
3.word里mathtype可以解决所有公式问题，并不需要新的字体，至少我用word写文章没碰到过latex的这些问题
1. 2. 4. 尴尬……

**Comment by zepinglee** [comment]
> 3.word里mathtype可以解决所有公式问题，并不需要新的字体，至少我用word写文章没碰到过latex的这些问题
> `1.` `2.` `4.` 尴尬……

那是因为 mathtype 提供了数学字体

**Comment by zhengprince** [comment]
所以没必要做一套math字体啊（抠鼻

**Comment by zepinglee** [comment]
主要是你自己对 STIX2 和 XITS 不满意

**Comment by zhengprince** [comment]
嗯 是

**Comment by zhengprince** [comment]
本科毕业论也是用latex写的，那时候就碰到过公式字体的问题，最后好像无奈选了latex默认的字体，好在老师没在这个上面卡我。
我以为这么多年过去了，这事会有新方法解决……

**Comment by stone-zeng** [comment]
有具体不满意/看着不爽的地方，可以提出来吗？那个 armt 项目原则上我也可以参与（逃

另外，MathType 用的也不是 Times New Roman；而 stix2 我也不知道到底发生了什么以至于背离了 Times 的感觉……

**Comment by zhengprince** [comment]
> 有具体不满意/看着不爽的地方，可以提出来吗？那个 armt 项目原则上我也可以参与（逃
> 
> 另外，MathType 用的也不是 Times New Roman；而 stix2 我也不知道到底发生了什么以至于背离了 Times 的感觉……

你好，上面已经说了，就是对公式用到的字体与times new roman有点区别而烦恼。
![image](https://user-images.githubusercontent.com/11679672/56821897-21959880-6882-11e9-8a23-5da11b0713bf.png)
Mathtype在字母这部分能用times n r就够了

**Comment by stone-zeng** [comment]
你若是要换，也不是不能换：

```latex
\documentclass{ctexart}
\usepackage{amsmath,unicode-math,xcolor}
\setmainfont{Times New Roman}
\setmathfont{XITSMath-Regular.otf}[Color=gray]
\setmathfont{Times New Roman}[range=up,Color=blue]
\setmathfont{Times New Roman Italic}[range=it,Color=red]
\setmathfont{Times New Roman Bold}[range=bfup,Color=brown]
\setmathfont{Times New Roman Bold Italic}[range=bfit,Color=teal]

\begin{document}
通用
\[ \int_0^\infty {\mathrm{e}}^{-x^2} = \sin\theta \]
\[ A \oplus \sum_n \cos\beta_n + \mathbf{V} \cdot \mathbf{M} \times \mathrm{x}^{\mu} \in \mathbb{R}^m \]
文本，函数
\[ \sin\theta, \cos\beta, \log z \text{\ are speical functions} \]
\[ \symrm{Re} \text{\ 是雷诺数} \]
\[ v_{\text{rms}} \text{\ is root-mean-squared velocity} \]
变量
\[
  A+B+a+z+\alpha+\beta+\Gamma+\Omega \quad
  \symrm{A}+\symrm{B}+\symrm{a}+\symrm{z}+\symrm{\alpha}+\symrm{\beta}+\symrm{\Gamma}+\symrm{\Omega}
  \tag{\texttt{normal/symrm}}
\]
\[
  \symbfit{A}+\symbfit{B}+\symbfit{a}+\symbfit{z}+\symbfit{\alpha}+\symbfit{\beta}+\symbfit{\Gamma}+\symbfit{\Omega} \quad
  \symbfup{A}+\symbfup{B}+\symbfup{a}+\symbfup{z}+\symbfup{\alpha}+\symbfup{\beta}+\symbfup{\Gamma}+\symbfup{\Omega}
  \tag{\texttt{symbfit/bfup}}
\]
\[
  \mathrm{A}+\mathrm{B}+\mathrm{a}+\mathrm{z}+\mathrm{\alpha}+\mathrm{\beta}+\mathrm{\Gamma}+\mathrm{\Omega} \quad
  \mathbf{A}+\mathbf{B}+\mathbf{a}+\mathbf{z}+\mathbf{\alpha}+\mathbf{\beta}+\mathbf{\Gamma}+\mathbf{\Omega}
  \tag{\texttt{mathrm/bf}}
\]
\end{document}
```

![image](https://user-images.githubusercontent.com/18233088/56823673-1abd5480-6887-11e9-9528-261d1105da66.png)

作为对照，还做了一个纯用 xits 的例子（右图），唯一明显的不同就是那个 italic 的 z 了：

![image](https://user-images.githubusercontent.com/18233088/56823798-77207400-6887-11e9-881a-164eaacb8530.png)

至于符号，如果也想换也可以换（不过不保证能做成）。此外，既然用了 `unicode-math`，那么 `\mathbf` 这样被标记为 legacy 的命令就不要用了，要不然会出 tofu。

**Comment by stone-zeng** [comment]
> 我以为这么多年过去了，这事会有新方法解决……

新方法就是 Unicode/OpenType Math，实现的成品包括 XITS、STIX(2) 还有 office 自带的 Cambria Math 等，但并没有 Times New Roman。

Times New Roman 只是为了正文设计（实际上是 *Times* 报纸），虽然现在加了很多文种的支持，但它没有（也应该不会考虑）做数学支持。

归根结底，请不要认为一套字体只包含了 glyph 的信息（某个符号长什么样子），它还需要包含相当数量的间距、位置、组合等信息，而这些对于数学排版都是非常关键的。这些信息，要么是排版引擎自带（mathtype 似乎就是的？），要么就得写进文件，无论是传统 TeX 的 tfm 还是现在 OpenType 的 `MATH` 表。不带 `MATH` 表的字体，比如 Times New Roman 是没有办法直接拿来排公式的，除非你把 [该给的信息](https://docs.microsoft.com/zh-cn/typography/opentype/spec/math) 给全了。当然，一是因为版权原因这不可能（姑且认为你不是 monotype 的人）；二来，为什么不另起炉灶自己做一个呢【滑稽】？

**Comment by zhengprince** [comment]
![image](https://user-images.githubusercontent.com/11679672/56825648-59094280-688c-11e9-8f88-62e2d45e80a1.png)
很奇怪，我用lyx模板，生成的公式为什么不如你的那么好呢，注意红框里两个J的样式，左边是用公式生成的，右边的是普通文字

**Comment by zhengprince** [comment]
> 二来，为什么不另起炉灶自己做一个呢【滑稽】？
为什么你们都提到让我自己做一个呢？是在挖苦我吗？（希望是我自己的恶意揣测）
我就是想吃口饭，不想连打铁做锅的技术都学会。。。（挠头

**Comment by zhengprince** [comment]
> 你若是要换，也不是不能换：
> 
> ```
> \documentclass{ctexart}
> \usepackage{amsmath,unicode-math,xcolor}
> \setmainfont{Times New Roman}
> \setmathfont{XITSMath-Regular.otf}[Color=gray]
> \setmathfont{Times New Roman}[range=up,Color=blue]
> \setmathfont{Times New Roman Italic}[range=it,Color=red]
> \setmathfont{Times New Roman Bold}[range=bfup,Color=brown]
> \setmathfont{Times New Roman Bold Italic}[range=bfit,Color=teal]
> 
> \begin{document}
> 通用
> \[ \int_0^\infty {\mathrm{e}}^{-x^2} = \sin\theta \]
> \[ A \oplus \sum_n \cos\beta_n + \mathbf{V} \cdot \mathbf{M} \times \mathrm{x}^{\mu} \in \mathbb{R}^m \]
> 文本，函数
> \[ \sin\theta, \cos\beta, \log z \text{\ are speical functions} \]
> \[ \symrm{Re} \text{\ 是雷诺数} \]
> \[ v_{\text{rms}} \text{\ is root-mean-squared velocity} \]
> 变量
> \[
>   A+B+a+z+\alpha+\beta+\Gamma+\Omega \quad
>   \symrm{A}+\symrm{B}+\symrm{a}+\symrm{z}+\symrm{\alpha}+\symrm{\beta}+\symrm{\Gamma}+\symrm{\Omega}
>   \tag{\texttt{normal/symrm}}
> \]
> \[
>   \symbfit{A}+\symbfit{B}+\symbfit{a}+\symbfit{z}+\symbfit{\alpha}+\symbfit{\beta}+\symbfit{\Gamma}+\symbfit{\Omega} \quad
>   \symbfup{A}+\symbfup{B}+\symbfup{a}+\symbfup{z}+\symbfup{\alpha}+\symbfup{\beta}+\symbfup{\Gamma}+\symbfup{\Omega}
>   \tag{\texttt{symbfit/bfup}}
> \]
> \[
>   \mathrm{A}+\mathrm{B}+\mathrm{a}+\mathrm{z}+\mathrm{\alpha}+\mathrm{\beta}+\mathrm{\Gamma}+\mathrm{\Omega} \quad
>   \mathbf{A}+\mathbf{B}+\mathbf{a}+\mathbf{z}+\mathbf{\alpha}+\mathbf{\beta}+\mathbf{\Gamma}+\mathbf{\Omega}
>   \tag{\texttt{mathrm/bf}}
> \]
> \end{document}
> ```
> 
> ![image](https://user-images.githubusercontent.com/18233088/56823673-1abd5480-6887-11e9-9528-261d1105da66.png)
> 
> 作为对照，还做了一个纯用 xits 的例子（右图），希望你能找出差别：
> 
> ![image](https://user-images.githubusercontent.com/18233088/56823798-77207400-6887-11e9-881a-164eaacb8530.png)
> 
> 至于符号，如果也想换也可以换（不过不保证能做成）。此外，既然用了 `unicode-math`，那么 `\mathbf` 这样被标记为 legacy 的命令就不要用了，要不然会出 tofu。

谢谢，我会参考的。

**Comment by zepinglee** [comment]
> 很奇怪，我用lyx模板，生成的公式为什么不如你的那么好呢，注意红框里两个J的样式，左边为行内公式，右边的是普通文字
> 刚用latex模板测试了，并不存在此问题

看来你还没把 lyx 模板的 stix2 字体换成 xits。

> 为什么你们都提到让我自己做一个呢？还都带”滑稽“。

我之前打算做的，后来鸽了；所以能骗你去做一套就最好不过了【滑稽】

**Comment by zhengprince** [comment]
> 看来你还没把 lyx 模板的 stix2 字体换成 xits。

不可能，我编译前特地从ustcthesis里拷过来一份覆盖了lyx下的文件，ustcthesis是用你之前教我的方法更新过的，我刚还对比了下文件，确保是一样的，关掉lyx重新打开再编译还是这样。我觉得你是不是应该检查一下看是不是bug？如果是的话，那我上面的很多发言就很尴尬了。

> 我之前打算做的，后来鸽了；所以能骗你去做一套就最好不过了【滑稽】

狼子野心……

**Comment by zepinglee** [comment]
1. 我只负责 `ustcthesis` 的项目，`ustclyx` 的项目你最好去那个 repo 的 issue 里再问下
2. `git submodule update --init --remote --merge --recursive` 命令是在 `ustclyx` 目录下用的，你要是更新 ustcthesis 只需要 git fetch origin; git merge origin/dev;

**Comment by zhengprince** [comment]
@jmcui 这样行不行

**Comment by zhengprince** [comment]
补充一些东西
![image](https://user-images.githubusercontent.com/11679672/56858520-d2e51d00-69ad-11e9-98ac-a0b69b69f48b.png)
这是lyx对公式和普通加粗斜体文字的处理，右边是对应的代码
![image](https://user-images.githubusercontent.com/11679672/56858776-ba2b3600-69b2-11e9-88ce-ba1d446a3b5c.png)
这是导出的pdf的结果
![image](https://user-images.githubusercontent.com/11679672/56858866-f4e19e00-69b3-11e9-82ac-9f89ba94c4d2.png)
![image](https://user-images.githubusercontent.com/11679672/56858859-d4194880-69b3-11e9-8dd2-2adb023a6049.png)
这是上面同样的代码在latex中处理得到的结果
@jmcui

**Comment by zhengprince** [comment]
折腾了一下，把unicode-math去掉了，换成了MathTimePro2，公式显示没什么问题
![image](https://user-images.githubusercontent.com/11679672/57399544-0de41d80-7204-11e9-9c70-7627ad88d84f.png)
![image](https://user-images.githubusercontent.com/11679672/57399576-205e5700-7204-11e9-992f-a934343e1060.png)
![image](https://user-images.githubusercontent.com/11679672/57399685-54397c80-7204-11e9-8775-4463c19c65e6.png)
![image](https://user-images.githubusercontent.com/11679672/57399731-703d1e00-7204-11e9-8615-12bcbbcdad83.png)
目前的问题有：
1. 张量不是sans serif
2. i和e不是正体
3. 有些地方可能不符合国标，比如积分号
4. 部分汉字加粗失败，比如小标题和定理证明部分（搞不懂……

改动的部分不多，有兴趣可以看一下→[test.zip](https://github.com/ustctug/ustcthesis/files/3158889/test.zip)

**Comment by zepinglee** [comment]
> 1. 张量不是sans serif

张量在国标中没要求 sans serif，只要求粗斜体，sf 是在 ISO 标准中要求的，所以这个问题不大

> 2. i和e不是正体

用 `\mathrm{i}` `\mathrm{e}` 就可以

> 4. 部分汉字加粗失败，比如小标题和定理证明部分（搞不懂……

同搞不懂

这个你自己使用就可以，不太可能 merge 到 master，主要是因为字体版权问题。

**Comment by zhengprince** [comment]
加粗这个问题很严重，我也不太可能自己用，就是用来测试的
