### ISSUE TITLE
Windows TeXLive 2019编译失败

### ISSUE THREAD

**Issue by Tiaonmmn** [ustctug/ustcthesis#227]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 10 
- TeX 发行版：TeX Live 2019
- 相关宏包版本：已更新至最新版
- 模板类型： master

## 描述问题
使用latexmk -xelatex main.tex编译示例文档失败，发生错误信息：
```
Latexmk: Found input bbl file 'main.bbl'
Latexmk: Log file says output to 'main.xdv'
Latexmk: Found bibliography file(s) [bib/ustc.bib]
Latexmk: applying rule 'xdvipdfmx'...
Rule 'xdvipdfmx': File changes, etc:
   Changed files, or newly in use since previous run(s):
      'main.xdv'
------------
Run number 1 of rule 'xdvipdfmx'
------------
For rule 'xdvipdfmx', running '&do_viewfile(  )' ...
------------
Running 'xdvipdfmx -q -E -o "main.pdf"  "main.xdv"'
------------

xdvipdfmx:fatal: Charsets data not available

No output PDF file written.
Latexmk: Errors, so I did not complete making targets
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
```
但可以通过latexmk -xelatex ustcthesis.dtx成功编译说明文档。

**Comment by zepinglee** [comment]
Mac 下的 TeX Live 无法复现你的问题，似乎跟 https://github.com/CTeX-org/forum/issues/30 一样，应该是 `xdvipdfmx` 的 bug。

**Comment by Tiaonmmn** [comment]
换了MiKTeX就OK了，TeX Live 2019不咋好用啊（逃

**Comment by zepinglee** [comment]
这是一个 minor bug，影响不大

**Comment by stone-zeng** [comment]
确定已经 `tlmgr update --all` 了吗？
