### ISSUE TITLE
参考文献title,series和volume的顺序

### ISSUE THREAD

**Issue by Jikomwoi** [ustctug/ustcthesis#228]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Overleaf
- 相关宏包版本：unicode-math v0.8m
- 模板类型： bachelor

## 描述问题
《关于本科毕业论文（设计）格式和统一封面的通知》第 10页给出的示例中没有明确对一本书的卷名和标题的顺序。查看国家标准GB7714-2015第4页4.2.2节规范，顺序应是标题，系列名，卷数。但实际显示的为系列名，卷数，标题。应该如何解决

**Comment by zepinglee** [comment]
你观察得很仔细。

1. [《关于本科毕业论文（设计）格式和统一封面的通知》](https://www.teach.ustc.edu.cn/document/doc-administration/4032.html) 好像没有第 10 页啊，你指的是哪里？不妨把链接或者截图发一下。

2. GB/T 7714-2015 第 4.2.2 节所描述的是“专著中的吸出文献”，比如 proceedings 中的某一篇文章。而你说的“一本书的卷名和标题”，应该按照“专著”的格式执行（见第 4.2 节）。所以 BibTeX 中的 `series`, `volume`, `title` 对应于“题名：其他题名信息”，按照第 8.2.3 节的要求（示例 7），按照“系列名，卷数，标题”的顺序是合理的。

![Screen Shot 2019-05-14 at 11 26 09 AM](https://user-images.githubusercontent.com/12290822/57668763-150f8f00-763b-11e9-87f5-0d34fe69a0a4.png)
