### ISSUE TITLE
考虑集成STIX2math数学字体

### ISSUE THREAD

**Issue by fylimas** [ustctug/ustcthesis#229]
当前宏包通过使用IfFontExistsTF判断STIX字体（当前文件夹、系统字体、tex字体）的存在与否来确定使用新的STIX字体还是旧的XITS字体，是一个自动化的方案，也是挺好的。

但是由于STIX字体（https://github.com/stipub/stixfonts ）在不停的迭代更新，这样的话，字体这个变量在用户端可能会发生改变，例如个别字符的重新绘制。

是否可以考虑在宏包中增加font/文件夹，内部预置某个版本的数学字体，从而保持与用户本机环境、字体更新的相对独立性？

**Comment by zepinglee** [comment]
STIX2 的字体还有些问题，目前模板已经换成了 XITS 字体。感觉 XITS 的字体变化不大（尤其相比于 `unicode-math`），所以没必要带这个字体。

**Comment by fylimas** [comment]
你回复太快了！

举个例子如下：
XITS的一个公式
![xits](https://user-images.githubusercontent.com/17979090/57968055-28eb2600-7998-11e9-8285-94995ffb7bb1.png)
STIX2的一个公式
![stix2](https://user-images.githubusercontent.com/17979090/57968057-2ee10700-7998-11e9-9c1c-a6394cb97009.png)

stix2比xits要好看那么一些，特别是求和符号

**Comment by fylimas** [comment]
哦哦，好的吧👌，我刚刚查看了一下当前版本，果然是用的XITS。

我用的还是以前的版本😂。我自己本地先用着吧

**Comment by zepinglee** [comment]
但是 STIX2 的希腊字母跟拉丁字母很不搭配。其实我一开始是用的 STIX2Math，但是发现它的希腊字母很丑，所以暂且保守一点换成 XITS 了。

另外也有其他搞 Times-compatible 字体的项目，比如 https://github.com/YuanshengZhao/armt ；我自己也打算搞一套，不过应该会鸽一段时间。
