### ISSUE TITLE
考虑增加查重选项

### ISSUE THREAD

**Issue by zepinglee** [ustctug/ustcthesis#230]
据 Liu You 同学反映，使用本科模板撰写的论文在查重时被检测重复了两千字以上（其实内容完全不相关），主要集中在目录和参考文献。

目前考虑在模板添加一个选项用于提交查重时的版本，启用该选项后会去掉以下内容：

- 封面/title page
- 目录
- 页眉和页脚
- 参考文献
- 致谢
- 已发表研究成果

大家有没有别的建议？

**Comment by stone-zeng** [comment]
参考文献好像不能去掉的

**Comment by yy8yy** [comment]
用acrobat编辑pdf，把除正文之外的页面都删掉后提交就行了。为了查重 重构代码好像不太划算
