### ISSUE TITLE
参考文献的顺序问题

### ISSUE THREAD

**Issue by QianyiWu** [ustctug/ustcthesis#231]
Hi,
关于参考文献的顺序，默认是按照文章中引用文献出现的顺序，不知道可不可以调整为按照音序排列（即Ａ－Ｚ），或者按照出版时间排序？

**Comment by zepinglee** [comment]
研究生/本科生？

**Comment by QianyiWu** [comment]
研究生。试过改bibgraphystyle发现似乎没变化

**Comment by zepinglee** [comment]
author-year 是按照作者姓名排序的

**Comment by QianyiWu** [comment]
但发现序号丢失了，不知道怎么把序号加回来呢？

**Comment by zepinglee** [comment]
阅读《撰写手册》和《GB/T 7714-2015》

**Comment by xuejichenhuan** [comment]
如何按照作者的姓氏字母排名啊，老师是这么规定的，撰写手册找不到了

**Comment by zepinglee** [comment]
http://gradschool.ustc.edu.cn/ylb/material/xw/wdxz/32.pdf

**Comment by xuejichenhuan** [comment]
Lee老师，我一打开就显示404，科学上网也打不开



---原始邮件---
发件人: "Zeping Lee"<notifications@github.com&gt;
发送时间: 2020年5月26日(周二) 中午11:06
收件人: "ustctug/ustcthesis"<ustcthesis@noreply.github.com&gt;;
抄送: "xuejichenhuan"<2534577340@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [ustctug/ustcthesis] 参考文献的顺序问题 (#231)




 
http://gradschool.ustc.edu.cn/ylb/material/xw/wdxz/32.pdf

**Comment by zepinglee** [comment]
> Lee老师，我一打开就显示404，科学上网也打不开
> […](#)

最近网站换了，http://gradschool.ustc.edu.cn/column/65

**Comment by xuejichenhuan** [comment]
谢谢！收到



---原始邮件---
发件人: "Zeping Lee"<notifications@github.com&gt;
发送时间: 2020年5月26日(周二) 中午11:31
收件人: "ustctug/ustcthesis"<ustcthesis@noreply.github.com&gt;;
抄送: "xuejichenhuan"<2534577340@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [ustctug/ustcthesis] 参考文献的顺序问题 (#231)




  
Lee老师，我一打开就显示404，科学上网也打不开
 …
  
最近网站换了，http://gradschool.ustc.edu.cn/column/65

**Comment by cugliming** [comment]
> author-year 是按照作者姓名排序的

你好。我用的author-year格式，发现英文是严格按照作者姓名排序的。但中文既未按拼音排序，也未按文中顺序排。是怎么回事呢？谢谢您。
![Snipaste_2021-01-12_16-34-46](https://user-images.githubusercontent.com/32346042/104289456-1ff78280-54f4-11eb-8817-778ba166368a.png)
