### ISSUE TITLE
bicaption

### ISSUE THREAD

**Issue by yy8yy** [ustctug/ustcthesis#232]
## 检查
- [ ] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MikTeX 2.9.6753
- 模板类型：doctor / master / bachelor

## 描述问题
学位论文的图片、表格需要中英双标题。但模板似乎没有这个功能，试着自己加个个包：

复现上述问题的代码：
```TeX
\usepackage{ccaption}
\begin{figure}
\centering
\includegraphics{image}
\bicaption{图}{中文标题}{Figure}{English title}
\end{figure}
```

编译不能通过。

**Comment by yy8yy** [comment]
学位论文的图片、表格需要中英双标题。但模板似乎没有这个功能，试着自己加个个包：
\usepackage{ccaption}
\begin{figure}
    \centering
    \includegraphics{image}
    \bicaption{图}{中文标题}{Figure}{English title}
\end{figure}
编译不能通过。

**Comment by zepinglee** [comment]
哪里要求中英文双标题的？

**Comment by yy8yy** [comment]
> 
> 
> 哪里要求中英文双标题的？

嗯 我查了学位论文撰写手册 确实没有这个要求。看实验室往届师兄的论文都有双标题。以手册为准，哈哈。还省得写了。

**Comment by zepinglee** [comment]
所以要按照 issue 模板来填写啊
