### ISSUE TITLE
关于\mathcal{U}实现字母U的花体问题

### ISSUE THREAD

**Issue by andylpro** [ustctug/ustcthesis#233]
\mathcal{U}这个代码在科大的模板中结果是
![TIM图片20190818205832](https://user-images.githubusercontent.com/32116334/63224871-efc38b80-c1fc-11e9-94a1-637f00eb73d0.png);
但是利用IEEE trans的模板结果是
![4(I(QQLDFM8 C }~84O2ZRN](https://user-images.githubusercontent.com/32116334/63224880-0a960000-c1fd-11e9-9c5c-b75d8f4fa888.png)，后者的样子更加通用一些，希望改进一下。

**Comment by zepinglee** [comment]
暂时没有处理数学字体的计划，临时方案是调用 Latin Modern Math 作为 `\mathcal` 的字体，需要在导言区：
```LaTeX
\setmathfont{latinmodern-math.otf}[
  range        = {cal,bfcal},
]%
```
<img width="96" alt="Screen Shot 2020-10-12 at 18 57 15" src="https://user-images.githubusercontent.com/12290822/95739033-c39a8200-0cbc-11eb-9037-17f10d7906d6.png">
