### ISSUE TITLE
wiki编辑权限

### ISSUE THREAD

**Issue by GongSiqiu** [ustctug/ustcthesis#234]
该仓库的wiki编辑权限是开放的，任何人可以编辑，具有一定风险

**Comment by zepinglee** [comment]
wiki 本来的含义就是让大家都可以编辑啊，另外所有的编辑都有记录的，总之不会丢

**Comment by GongSiqiu** [comment]
我以为你是把wiki当说明文档了，担心发生恶意篡改。既然你不介意，那就算了

**Comment by zepinglee** [comment]
这里有全部的历史记录 https://github.com/ustctug/ustcthesis/wiki/Home/_history
