### ISSUE TITLE
改进对 hyperref 缺 \mu 的兼容

### ISSUE THREAD

**Issue by muzimuzhi** [ustctug/ustcthesis#235]
目前的实现
https://github.com/ustctug/ustcthesis/blob/48d6d011dfd401e54481a54985c86d69666bb59a/ustcthesis.dtx#L2464-L2472

改进建议
 - 与 hyperref 做的修改保持一致
hyperref 的改法是，向文件 `psdextra.def` 添加了 `\let\mu\textmu`，见提交 https://github.com/ho-tex/hyperref/commit/7be40c9ba8447f17e68b606964cf9bb0c42beb55。
 - 调整对 hyperref 版本日期的判断
   - 目前用的是 hyperref v3.88g 的日期，但这个版本没有提交到 CTAN，包含该修改的最老 CTAN 版本是 v3.88h（见 [CTAN update: hyperref](https://www.ctan.org/ctan-ann/id/mailman.830.1564249964.9289.ctan-ann@ctan.org)）。
   - 可以考虑用 v3.88h 的发布时间 `2019/06/22` 判断模板用户的 hyperref 版本。同时，以注释形式说明「hyperref 在版本 x 修复了某问题，对在此之前的版本，模板手动做相应修改」

相关 issue: https://github.com/ustctug/ustcthesis/issues/223

**Comment by zepinglee** [comment]
1. `hyperref` 就是在 `\psdmapshortnames` 命令里加了 `\mu` 的处理（https://github.com/ho-tex/hyperref/blob/8a9f6b527c7d2cfeaac864d250237032154de9c9/hyperref.dtx#L26473 ）。

2. 我在代码里应该是以 `\ProvidesPackage{hyperref}[]` 后面的日期为准，跟啥时候上传到 CTAN 上无关。比如要是有人测试 `hyperref` 在 github 上的版本，checkout 到了 3.88g，这样写逻辑才正确。

**Comment by muzimuzhi** [comment]
1. hyperref 的改法是增加了 `\let\mu\textmu`，模板里的兼容代码是增加了 `\let\mu\textmugreek`。我的建议是模板里也用 `\let\mu\textmu`，和 hyperref 保持一致。

2. 你说得有道理，我考虑不周。

**Comment by zepinglee** [comment]
诶我没注意到是 `\textmu`
