### ISSUE TITLE
professional模板编译失败

### ISSUE THREAD

**Issue by PanJingshen** [ustctug/ustcthesis#236]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.15
- TeX 发行版：MacTeX 2019
- 模板类型：professional

## 描述问题
模板编译失败，描述为字体缺失（而字体已安装）。

截图：
<img width="836" alt="image" src="https://user-images.githubusercontent.com/22728233/67651009-1da21a80-f97a-11e9-96bd-04e9022be937.png">
<img width="887" alt="image" src="https://user-images.githubusercontent.com/22728233/67651029-37436200-f97a-11e9-910d-2018079df031.png">

复现上述问题的代码：
```TeX
\documentclass[professional]{ustcthesis}
\begin{document}
abc
\end{document}
```

**Comment by stone-zeng** [comment]
只装在系统里面的话，没办法通过字体的**文件名**来调用。所以，请使用 TeX Live 自带的包管理器来装：

```sh
sudo tlmgr install xits
```

**Comment by PanJingshen** [comment]
> 只装在系统里面的话，没办法通过字体的**文件名**来调用。所以，请使用 TeX Live 自带的包管理器来装：
> 
> ```shell
> sudo tlmgr install xits
> ```

感谢解答！

按照上述命令安装显示xtis字体已有，仍然编译失败。
<img width="723" alt="image" src="https://user-images.githubusercontent.com/22728233/67656941-3289a880-f990-11e9-87d8-f568a88edf38.png">
<img width="722" alt="image" src="https://user-images.githubusercontent.com/22728233/67656982-5e0c9300-f990-11e9-9987-904ce61caf5e.png">

**Comment by stone-zeng** [comment]
试一下下面两条命令，看下分别是什么结果：

```sh
kpsewhich XITS-Regular.otf
kpsewhich xits-regular.otf
```

**Comment by PanJingshen** [comment]
> 试一下下面两条命令，看下分别是什么结果：
> 
> ```shell
> kpsewhich XITS-Regular.otf
> kpsewhich xits-regular.otf
> ```
结果如下：
<img width="716" alt="image" src="https://user-images.githubusercontent.com/22728233/67665576-eeed6980-f9a4-11e9-8d51-b9e30353e920.png">

**Comment by zepinglee** [comment]
这里为了兼容性检查了 xits 字体的文件名：
https://github.com/ustctug/ustcthesis/blob/48d6d011dfd401e54481a54985c86d69666bb59a/ustcthesis.dtx#L872-L877
你的 TeX Live 显然存在新的文件名“XITS-Regular.otf”，但是编译的报错中却在找旧的字体名“ xits-regular.otf”，应该是 874 行的判断给出了错误的结果，可能跟 latex3 kernel 的 bug 有关，你可以执行
```
tlmgr info fontspec;
tlmgr info l3kernel;
```
检查一下这两个包的版本，然后 `sudo tlmgr update --self --all --reinstall-forcibly-removed` 升级全部宏包，再检查一下还会不会报错。

**Comment by PanJingshen** [comment]
@zepinglee 谢谢解答！

已按命令升级全部宏包，检查结果如下：
fontspec包检查
<img width="718" alt="image" src="https://user-images.githubusercontent.com/22728233/67668788-94a3d700-f9ab-11e9-937f-4fadb51d9178.png">
l3kernel包检查：
<img width="721" alt="image" src="https://user-images.githubusercontent.com/22728233/67669019-04b25d00-f9ac-11e9-928a-c6cf4360d42d.png">
编译结果仍然出错：@_@
<img width="850" alt="image" src="https://user-images.githubusercontent.com/22728233/67669069-20b5fe80-f9ac-11e9-9a1f-a2897dbeaea4.png">

**Comment by PanJingshen** [comment]
@zepinglee 重装大法已解决问题，非常感谢！

**Comment by zepinglee** [comment]
看来不是模板本身的问题，不过我可以把 `xitsnew` 设置成默认的，这样应该可以减少出错的可能。

另外感谢 @stone-zeng 的解答！
