### ISSUE TITLE
macOS 10.15 Catalina 默认字体缺失部分字形

### ISSUE THREAD

**Issue by PanJingshen** [ustctug/ustcthesis#237]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.15
- TeX 发行版：MacTeX 2019
- 模板类型：master

## 描述问题
姓名有点复杂，”倞燊“在字体里无法显现，求教如何处理？

截图：
<img width="326" alt="image" src="https://user-images.githubusercontent.com/22728233/69062312-b564c700-0a55-11ea-90d3-7861679af6a6.png">

复现上述问题的代码：
```TeX
\author{潘倞燊}
\major{软件工程}
```

**Comment by zepinglee** [comment]
看起来是调用了 fandol 字体，你可以手动调用 mac 的字体：`\documentclass[doctor,fontset=mac]{ustcthesis}`，这套字体是有这两个字形的。

另外你确定是 macOS 10.14，没升级 10.15 Catalina？

**Comment by PanJingshen** [comment]
@zepinglee 感谢回答！
但是这个调整貌似没有作用啊，结果如下：
<img width="602" alt="image" src="https://user-images.githubusercontent.com/22728233/69064221-c8c56180-0a58-11ea-9a6e-b2bf9a4bedad.png">

<img width="348" alt="image" src="https://user-images.githubusercontent.com/22728233/69064360-032efe80-0a59-11ea-8b3e-3aa088237ec4.png">
另，系统是10.15，当时没注意这个，已更改。

**Comment by zepinglee** [comment]
同 https://github.com/CTeX-org/ctex-kit/issues/455

**Comment by PanJingshen** [comment]
@zepinglee 解决了，非常感谢！

按照如下方案：
\documentclass[master,professional,fontset=macnew]{ustcthesis}

**Comment by zepinglee** [comment]
> 但是这个调整貌似没有作用啊，结果如下：

我这里正常：
<img width="398" alt="Screen Shot 2019-11-18 at 11 20 20 PM" src="https://user-images.githubusercontent.com/12290822/69065021-ff4fac00-0a59-11ea-9d5f-e9f1a7c2d3bc.png">

你先 `make clean` 再 `make` 下？

**Comment by zepinglee** [comment]
> @zepinglee 解决了，非常感谢！
> 
> 按照如下方案：
> \documentclass[master,professional,fontset=macnew]{ustcthesis}

这样会有些问题，因为我的代码中 https://github.com/ustctug/ustcthesis/blob/cf4077db208511e33098ebd597a0236d6ce20d02/ustcthesis.dtx#L825-L847 是按照 `fontset` 是否等于 `mac` 去判断的，所以你设成 macnew 的话，ctex 宏包没有问题，但是模板的字体配置就不对了

**Comment by PanJingshen** [comment]
嗯嗯，已更改为`\documentclass[master,professional,fontset=mac]{ustcthesis}`，模板字体显示都完整，非常感谢！
