### ISSUE TITLE
英文封面名字错误

### ISSUE THREAD

**Issue by foolishflyfox** [ustctug/ustcthesis#238]
[中国科学技术大学研究生学位论文撰写手册](https://gradschool.ustc.edu.cn/ylb/material/xw/wdxz/32.pdf) 1.1 封面节说明中第三点作者姓名中要求：
> 英文方面作者姓名按姓在前、名在后的格式缩写，姓名需要写全拼，如Zhang Jangguo

仓库中为名在前，姓在后，如 Zeping Li，望改正！

**Comment by zepinglee** [comment]
嗯，有道理！
