### ISSUE TITLE
建议把模板的`开发`和`使用`明确地分离开

### ISSUE THREAD

**Issue by zhjp0** [ustctug/ustcthesis#239]
注意到现在的仓库把`模板的开发维护等专业性工作`和`普通用户的使用`混在一起，这样可能会导致误用或者一些误会（特别是对不熟悉 latex 语言的普通使用用户），故建议将两者分离开，一个简单的做法是：把开发细节单独放到一个目录里，减少对用户的干扰，毕竟使用用户要远远多于贡献者。例如下面的目录结构：
- ustc-thesis
	- src
		- 各种源码文件
		- READMD.md (包括代码，开发指南和准则，如何为此项目作出贡献等等)
	- *.cls
	- README.md （包括 latex 入门链接，如何使用此模板（例如各个文件的阅读顺序），如何提交 bug、issue、proposal 等）
	- instructions.tex/pdf （详细的使用说明，如何编写 tex、编译等）
	- example.tex/pdf

建议参考常见项目如 [jquery](https://github.com/jquery/jquery) 的目录结构，大致意思是把 src、build、test 明确分开，比如 jquery 的 release 是一个完整的 js 文件，并无其他。

当然，这些只是建议了。

**Comment by zepinglee** [comment]
1. `jquery` 目录的设计是用于开发的，而用户是通过 `npm install` 来安装使用的；但是 `ustcthesis` 是让用户直接 clone 下来撰写的，依靠 `tlmgr` 来安装很不靠谱。所以我更倾向于扁平式的目录结构。

2. 目录的文件/目录并不像 `jquery` 那么复杂，尤其是 `ustcthesis.dtx` 相当于你说的“各种源码文件”和“`instructions.tex`”合在一起，纯粹用于开发的文件/目录如下，我感觉不会引起误用啊。
    - .github/
    - test/
    - build.lua

所以目前我更倾向于扁平式的目录结构，之后可能会考虑把 dtx 拆开，那样可能统一放到 `src/` 更合适。

**Comment by zhjp0** [comment]
我上面说的确实有些麻烦了，意思就是用户和开发人员所关心的并不一样：

用户所关心的是，使用说明书在哪里？我要打开哪个文件开始编辑？剩余其他所有的问题是开发人员需要关心的。

之前找的 jQuery 的目录确实很不合适，建议参考 [IEEE trans latex 模板](https://www.ieee.org/conferences/publishing/templates.html)目录结构：
```
.
├── IEEEtran.cls
├── IEEEtran_HOWTO.pdf
├── conference_101719.pdf
└── conference_101719.tex
```

以下是具体建议的做法：

目前这个仓库只供开发人员使用，只是 release 的不是这个仓库，而是像上述 IEEE trans 的目录结构，去除一切用户不需要关心的东西，例如：
```
.
├── figures
│   └── figure1.pdf
│       ...
├── template.pdf
├── template.tex
├── ustc-thesis-HOWTO.pdf
└── ustc-thesis.cls
```

**Comment by zepinglee** [comment]
1. 用户应该先去阅读 README 吧？里面还是描述得比较清楚的，我搞不懂哪个文件造成了干扰。
2. 拆成两个仓库事实上只节省了以上 4 个文件，用户还不如直接去下 https://github.com/ustctug/ustcthesis/releases 。

**Comment by zhjp0** [comment]
1. 我在 [https://github.com/ustctug/ustcthesis/releases](https://github.com/ustctug/ustcthesis/releases) 下载了最新的 release，以我自己为例：

    - 不明白干什么的文件，不知道是不是只有开发人员才会用，也不知道能不能删：
        - latexmkrc
        - math-commands.tex
        - ustcsetup.tex
        - ustcthesis-authoryear.bst
        - ustcthesis-bachelor.bst
        - ustcthesis-numerical.bst

    - 我觉得用户用不到的文件：
        - ustcthesis.dtx 用户应该不需要自己去修改或者编译`说明文档`

2. 并不是要拆分成两个仓库，之前考虑的不周全，其实不用拆分仓库，只需要控制 release 里的文件即可，至少不能包含只有开发才会用到的文件（比如上面列出的那些），这样的话，release 里应该只包含以下文件/目录：
    - bib
    - chapters
    - figures
    - LICENSE
    - main.tex/pdf // 建议改成 my-paper/template 之类的名字，main 并不直观
    - README.md // 这个其实也不需要，建议加到下面的使用说明 pdf 文档里，两个理由：1. 一份使用说明即可；2. latex 模板，放个 markdown 文件不合适（markdown 一般对程序员友好，但并不是所有专业的同学，况且一般 latex 输出的就是 pdf 文件）
    - ustcthesis.cls
    - ustcthesis.pdf // 看到这个名字，应该没人会想到这是个使用说明文档吧，建议改成 ustc-thesis-HOWTO/INSTRUCTIONS 之类的

**Comment by zepinglee** [comment]
1. 这部分在 pdf 文档里描述得很清楚：
<img width="907" alt="Screen Shot 2020-01-08 at 6 27 42 PM" src="https://user-images.githubusercontent.com/12290822/71971430-96a8d280-3245-11ea-83a6-bfedfffd29d2.png">
<img width="594" alt="Screen Shot 2020-01-08 at 6 30 35 PM" src="https://user-images.githubusercontent.com/12290822/71971442-9b6d8680-3245-11ea-8ab4-3f2d498aaf8c.png">

2. 这些文件的命名其实是初写模板时参考了其他学位论文模板（准确滴说是 `thuthesis`），以及 latex 宏包的传统，并不是瞎命名的；但是从现在的角度来看，有些确实比较过时。
    - `main.tex`：`main`是很多程序的入口，所以我觉得不太会造成困惑。
    - `ustcthesis.dtx`：之所以带着这个，主要是因为 `Makefile` 的逻辑中，`ustcthesis.cls` 依赖于 `.dtx`。
    - `ustcthesis.pdf`：这是从 `ustcthesis.dtx` 编译生成的，默认名字一样；另外 latex 的宏包 `foo` 的文档一般就叫 `foo.pdf`，比如 [ucbthesis](https://ctan.org/tex-archive/macros/latex/contrib/ucbthesis)，当然也有叫 `foo-doc.pdf` 的。
    - `README.md`：虽然 macOS/Linux 用户很方便地看到里面的内容，但是 windows 用户可能有些问题（考虑到编码什么的），所以你说的比较有道理。

3. 我觉得可以把用户分为两类：
    1. 会使用 git 的：应该先阅读 GitHub 仓库主页（`README.md`），按照简单的指南编译出详细的 pdf 文档然后使用模板。这一部分人应该有足够的工程能力，所以里面含有一些开发用的文件/目录也没问题。 
    2. 不会用 git 的：从研究生院官网或 GitHub Releases 下载、解压 zip 包，直接阅读 pdf 文档。这一部分人应该也不会使用 `make` 等工具，所以 `Makefile` 似乎也可以去掉了。

4. 传统的 latex 宏包写法是 `.dtx` 既能去掉注释生成 `.cls` 代码，又可以编译为 `.pdf` 文档（aka “文学式编程”）。但是我现在越来越不太赞成这一结构，所以也在考虑：
    - 将文档和代码+注释写在一起是否合理？这样做的初衷是为了在一个 pdf 里同时阅读文档和代码注释，但是我感觉代码注释更适合在编辑器里阅读；如果这样就可以把文档单独放到一个 `.tex` 里。
    - 从 `.dtx` 去掉注释注释是否有必要？这需要实验比较一下性能；如果没必要的话，可以直接将注释带到 `.cls` 里。
    - 目前的 `.dtx` 有 3 千多行代码，应该分拆成几个小一些的文件（然后放到 `src/` 目录下）更方便查找。

**Comment by zhjp0** [comment]
请原谅我的无知和对你们辛苦工作的指指点点，目前的状态已经很好了，是我过于较真了，实在抱歉！
