### ISSUE TITLE
关于参考文献格式

### ISSUE THREAD

**Issue by liuliu66** [ustctug/ustcthesis#240]
我在使用该模板时发现生成的参考文献格式与研究院官网的word版本和历届科大博士论文出版后的版本不同：

该latex模板生成参考文献作者名为全大写，如GIRSHICK R
而word版本和已出版的科大博士版本为姓首字母大写，其他小写，如Girshick R

我使用的模板为3.2版本，请问是否有更新的release模板使用？参考文献格式以哪个为准？谢谢！

**Comment by zepinglee** [comment]
阅读 [FAQ](https://github.com/ustctug/ustcthesis/wiki/常见问题#1-为何参考文献的著者姓名全部大写)
