### ISSUE TITLE
LaTeX3 error: '\str_if_eq_x:nnTF' deprecated

### ISSUE THREAD

**Issue by zepinglee** [ustctug/ustcthesis#241]
[LaTeX3 2020-01-12](https://ctan.org/ctan-ann/id/mailman.3173.1579011463.2586.ctan-ann@ctan.org) 更新后，`ustcthesis` 编译报错：
```
./ustcthesis.cls:210: Undefined control sequence.
<argument> \LaTeX3 error:
                           '\str_if_eq_x:nnTF' deprecated on 2020-01-01. Use...
l.210 \ustc@strifeq
                   {\ustc@fontset}{fandol}{
```

**Comment by zepinglee** [comment]
暂时在 aa26736 临时解决一下。

之后会重写调用字体，同时也可以避免 `ctex` 更新不及时造成的问题。

**Comment by HaisongDing** [comment]
根据：https://github.com/latex3/latex3/blob/3cbe5493916c785fb54ad91081bead3f4f74f9d5/l3kernel/l3deprecation.dtx#L916
把\str_if_eq_x:nnTF替换成\str_if_eq:eeTF就可以了。

**Comment by zepinglee** [comment]
这样没法兼容到 texlive 2017；目前 master 已经修复；之后打算像 fduthesis 一样拓展 fontset

发自我的iPhone

**Comment by Sunshimy** [comment]
> 暂时在 [aa26736](https://github.com/ustctug/ustcthesis/commit/aa26736593d633b48ef69ab4ba553405ebe4525c) 临时解决一下。
> 
> 之后会重写调用字体，同时也可以避免 `ctex` 更新不及时造成的问题。



> [LaTeX3 2020-01-12](https://ctan.org/ctan-ann/id/mailman.3173.1579011463.2586.ctan-ann@ctan.org) 更新后，`ustcthesis` 编译报错：
> 
> ```
> ./ustcthesis.cls:210: Undefined control sequence.
> <argument> \LaTeX3 error:
>                            '\str_if_eq_x:nnTF' deprecated on 2020-01-01. Use...
> l.210 \ustc@strifeq
>                    {\ustc@fontset}{fandol}{
> ```

请问问题如何解决？答案看不懂

**Comment by zepinglee** [comment]
新版已经改好了，使用 github 上最新版
