### ISSUE TITLE
关于博士论文模板--章节的参考文献问题

### ISSUE THREAD

**Issue by ustc-bell** [ustctug/ustcthesis#242]
## 描述问题
  关于参考文献的分章问题，希望是可以分章节的print参考文献。采用natbib包的multibib进行设置，总是不能生成参考文献的分章节。
\ustcsetup中加入定义后，
\usepackage[resetlabels]{multibib}
\newcites{sec}{Reference}
在第一章采用了正常的引用cite{}第二章采用了citesec{}的引用，然而生成的文献被强制的放在了一个章节里面了。应该怎么修改？

**Comment by zepinglee** [comment]
相比于 `multibib`，我更推荐使用 `chapterbib`，因为不需要定义额外的命令（比如 `\citesec` ）。

目前的模板修改了一些 LaTeX 底层，会导致跟 `chapterbib` 的冲突。

**Comment by zepinglee** [comment]
目前 `chapterbib` 是可以使用的：
`main.tex`：
```
\documentclass{ustcthesis}
\usepackage{chapterbib}
\begin{document}
\include{chapters/foo}
\include{chapters/bar}
\end{document}
```

`chapters/foo.tex`：
```
\chapter{Foo}
\section{Foo}
Foo\cite{knuth84,knuth86a}
\bibliographystyle{ustcthesis-numerical}
\bibliography{bib/ustc}
```

`chapters/bar.tex`：
```
\chapter{Bar}
\section{Bar}
Bar\cite{lamport94,tlc2}
\bibliographystyle{ustcthesis-numerical}
\bibliography{bib/ustc}
```

注意，`main.tex` 调用子文件的时候必须使用 `\include`。

目前这样编译出来的还有些格式上的问题，我再 patch 一下。

**Comment by ustc-bell** [comment]
感谢，用超儿

> 目前 `chapterbib` 是可以使用的：
> `main.tex`：
> 
> ```
> \documentclass{ustcthesis}
> \usepackage{chapterbib}
> \begin{document}
> \include{chapters/foo}
> \include{chapters/bar}
> \end{document}
> ```
> 
> `chapters/foo.tex`：
> 
> ```
> \chapter{Foo}
> \section{Foo}
> Foo\cite{knuth84,knuth86a}
> \bibliographystyle{ustcthesis-numerical}
> \bibliography{bib/ustc}
> ```
> 
> `chapters/bar.tex`：
> 
> ```
> \chapter{Bar}
> \section{Bar}
> Bar\cite{lamport94,tlc2}
> \bibliographystyle{ustcthesis-numerical}
> \bibliography{bib/ustc}
> ```
> 
> 注意，`main.tex` 调用子文件的时候必须使用 `\include`。
> 
> 目前这样编译出来的还有些格式上的问题，我再 patch 一下。

感谢zeping的代码，采用了这个chapter确实好用。尽管bibtex编译的时候出现Illegal， another \bibdata command -line ** file chapters/..，但是确实对生成的pdf没有影响。 需要注意的是编译时，先对主文件进行latex编译，再分别对各个章节文件进行bbitex编译，再对主文件两次latex。才能显示正确。

**Comment by zepinglee** [comment]
你可以用 `latexmk` 直接编译 `main.tex`。

另外现在的参考文献依然是 chapter，需要改成 section，但是这部分是都要编号？

**Comment by ustc-bell** [comment]
我查了以前的博士论文，参考文献不需要编号，chapter后面直接附上就行。

**Comment by zepinglee** [comment]
你试下 1c0f92a 的效果

**Comment by ustc-bell** [comment]
十分感谢。我来试一下。

**Comment by Chenjaekr** [comment]
想请问一下，在main.tex使用了\usepackage[sectionbib]{chapterbib}后，ustcthesis-numerical的引文格式似乎就无法生效了…也没并没有任何报错，不知道是什么原因？

**Comment by zepinglee** [comment]
> 想请问一下，在main.tex使用了\usepackage[sectionbib]{chapterbib}后，ustcthesis-numerical的引文格式似乎就无法生效了…也没并没有任何报错，不知道是什么原因？

建议新开个 issue 详细描述你的问题。

**Comment by Chenjaekr** [comment]
> > 想请问一下，在main.tex使用了\usepackage[sectionbib]{chapterbib}后，ustcthesis-numerical的引文格式似乎就无法生效了…也没并没有任何报错，不知道是什么原因？
> 
> 建议新开个 issue 详细描述你的问题。

谢谢您的回复，我发现反而是在不使用chapterbib时，bst内的show.url/show.doi并不会被编译出来。所以直接修改了bst文件解决了。
