### ISSUE TITLE
关于Misplaced alignment tab character &. \copyrightpage的报错

### ISSUE THREAD

**Issue by X-zcer** [ustctug/ustcthesis#243]
## 检查
- [ √ ] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [ √ ] 已经将模板升级到了最新版
- [ √ ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [ √ ] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 10
- TeX 发行版：TeX Live 2019
- 模板类型：master

## 描述问题
编译时报错：
行 29: Misplaced alignment tab character &. \copyrightpage
不过不影响预览，版权声明页依然可以显示。

截图：
![tex中copyright的错误](https://user-images.githubusercontent.com/4530696/75250399-409ee700-5813-11ea-843a-3a6e34717642.PNG)

复现上述问题的代码：
即为原代码（编译时的error）

**Comment by X-zcer** [comment]
已解决。。

**Comment by zepinglee** [comment]
到底是啥情况啊？
