### ISSUE TITLE
main.tex中的注释代码\bibliography{ustcthesis-authoryear}

### ISSUE THREAD

**Issue by Yao1993** [ustctug/ustcthesis#244]
https://github.com/ustctug/ustcthesis/blob/90ddc776679fef67e31c3af11ee5b08771760fe3/main.tex#L46
\bibliography{ustcthesis-authoryear}应该是\bibliographystyle{ustcthesis-authoryear}吧？

**Comment by zepinglee** [comment]
啊写错了
