### ISSUE TITLE
加粗的希腊字符显示不出来

### ISSUE THREAD

**Issue by ustcjerry** [ustctug/ustcthesis#245]
## 编译环境
- 编译的系统：Windows 10 
- TeX 发行版：TeX Live 2019
- 模板类型：doctor 
- 使用的是v3.2版本的模板

## 描述问题
\mathbf, \bf, \textbf加粗的希腊字符显示不出来，显示为方块

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{ustcthesis}
\begin{document}

$\mu$
$\bf{\mu}$
$\mathbf{\mu}$
$\textbf{\mu}$


\end{document}
```

**Comment by stone-zeng** [comment]
`$\symbf{\mu}$`

**Comment by ustcjerry** [comment]
update：
添加 bm 宏包后可以正常显示

**Comment by stone-zeng** [comment]
呃……别混用啊

**Comment by zepinglee** [comment]
阅读 unicode-math 宏包；

下个版本把 bm 给禁了。

**Comment by zepinglee** [comment]
38941cf 加了不兼容宏包的报错，这样可以有效防止用户误使用不兼容的宏包。
