### ISSUE TITLE
v3.2中ustcthesis.cls中有处错误

### ISSUE THREAD

**Issue by fengboo** [ustctug/ustcthesis#250]
ustcthesis.cls第170行应为：
`\DeclareVoidOption{pdf}{\ustcsetup{output=electronic}}`
pdf改为output，否则无法使用不带空白页的电子版pdf模式。
个人见解，只会用不会写模板，如我理解有误请忽略。
最后感谢大佬的模板，毕业全靠它了。

**Comment by zepinglee** [comment]
啊，对这里写错了。不过建议使用新版的 key-value 式接口，这里也是为了向前兼容。
