### ISSUE TITLE
定积分上下界位置不对

### ISSUE THREAD

**Issue by ustcjerry** [ustctug/ustcthesis#252]
## 编译环境
- 编译的系统： Windows 7
- TeX 发行版：TeX Live 2020
- 模板类型：doctor

## 描述问题
定积分上下界位置不对

截图：
![捕获3](https://user-images.githubusercontent.com/11849381/79069735-222d7600-7d03-11ea-8f58-1b4385cabdb3.PNG)

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{ustcthesis}
\begin{document}

\[\int_0^T {x(t)} dt\]
\[\int\limits_0^T {x(t)dt} \]

\begin{equation}
\int_0^T {x(t)} dt
\end{equation}

\begin{equation}
\int\limits_0^T {x(t)dt}
\end{equation}

\end{document}
```

**Comment by ustcjerry** [comment]
撰写手册第34页里说数学公式中 “各单元不能交叉。数学式中各单元交叉混排的情况，主要出现在求和号，积分号和缩写字所在部位”    没太看懂这里定义的“不能交叉”是不是模板中公式打出来的这种上下界形式

**Comment by zepinglee** [comment]
GB 3102.11-1993 物理科学和技术中使用的数学符号：
<img width="715" alt="Screen Shot 2020-04-12 at 10 14 06 PM" src="https://user-images.githubusercontent.com/12290822/79070862-ee564e80-7d0a-11ea-8a3c-9d5a929de38c.png">
哪里有问题？

**Comment by zepinglee** [comment]
> 撰写手册第34页里说数学公式中 “各单元不能交叉。数学式中各单元交叉混排的情况，主要出现在求和号，积分号和缩写字所在部位” 没太看懂这里定义的“不能交叉”是不是模板中公式打出来的这种上下界形式

我也没看懂这段

**Comment by ustcjerry** [comment]
请问可以实现积分上下界在积分号右边这种样式吗？下面两条命令应该能分别实现11-6.24图中两种样式的积分符号，但是在模板里都显示一样。
```
\[\int_0^T {x(t)} dt\] 
\[\int\limits_0^T {x(t)dt} \]
```

**Comment by zepinglee** [comment]
模板实现的默认样式是遵循国内排版数学公式的习惯，（参考大一的微积分教材），不建议自已去改。
