### ISSUE TITLE
关于参考文献的几点建议

### ISSUE THREAD

**Issue by mri1998** [ustctug/ustcthesis#254]
文献的全部引用：`\cite{slg,lyc,ljs,cgw,cjb,kqy,yhs,yx,dwx,jxz,wjk,syw,wf,xd,twh,huston}`
可以换成 `\nocite{*}`，不然的话，要不无法向参考文献中添加一篇没被引用的文献，要不出现一长串不知所谓数字标号，还不能调成白色，因为会被认定是凑字数
同时 `\nocite{*}` 可以放到最前面，那么会按.bib文件中的顺序排序

建议在指南中添加“修改文献时需使用记事本打开ustc.bib文件，并向内添加BibTex格式的文献信息”（可以对新手+时间紧迫的毕业生友好一些）

**Comment by zepinglee** [comment]
1. 参考文献表的文献必须在正文中引用，示例文档最好也遵守这一习惯，所以不要“添加一篇没被引用的文献”。另外引用的标注是学校规定的格式，不存在“会被认定是凑字数”。

2. 编辑 `.bib` 是使用 BibTeX 的基本操作，新手应该去看 lshort-zh-cn。另外 Windows 的“记事本”在编辑 UTF-8 的内容时容易出现 BOM 的问题，不推荐使用。
