### ISSUE TITLE
在Overleaf上使用模板

### ISSUE THREAD

**Issue by seconrg** [ustctug/ustcthesis#256]
Overleaf是一款非常好用的在线编辑latex的网站，可否在仓库中加上对overleaf上导入模板的说明，以帮助一部分想在overleaf上完成论文的同学减少潜在的问题。

**Comment by zepinglee** [comment]
嗯，可以加一些。

OverLeaf 上的 https://www.overleaf.com/latex/templates/latex-template-for-ustc-thesis/jvtdfkqsrycm 其实也是我上传的，只是忘记在写到文档里了。

**Comment by Litosty** [comment]
> 嗯，可以加一些。
> 
> OverLeaf 上的 https://www.overleaf.com/latex/templates/latex-template-for-ustc-thesis/jvtdfkqsrycm 其实也是我上传的，只是忘记在写到文档里了。

请问Overleaf上的文档是和github上同步更新的吗？目前看到Overleaf上模板的Last Updated是在3月左右。

**Comment by sikouhjw** [comment]
> 

一般是跟随 https://github.com/ustctug/ustcthesis/releases/latest 更新

**Comment by zepinglee** [comment]
> 请问Overleaf上的文档是和github上同步更新的吗？目前看到Overleaf上模板的Last Updated是在3月左右。

不是。Overleaf 上每次发布都得提交审核，所以只有发布新版本的时候更新 overleaf 上的。
