### ISSUE TITLE
vscode不能正确编译有引用的文档

### ISSUE THREAD

**Issue by kanglcn** [ustctug/ustcthesis#257]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Manjaro 20.0
- TeX 发行版：TeX Live 2019
- 模板类型：bachelor

## 描述问题
如题，使用vscode编写文档且用vscode的latex workshop插件时，不能正确编译有引用的文档。
而直接使用`latexmk -xelatex main.tex`则不会有任何问题。

直接下载最新版的模板用vscode插件编译就会发现此问题。

**Comment by zepinglee** [comment]
我无法复现你的问题，你用的是 latex-workshop 的哪个 recipe？

模板中的 `.vscode/settings.json` 配置了 `latexmk with xelatex`，你可以参考这个自己配置下。

**Comment by kanglcn** [comment]
抱歉，我刚开始用vscode，我的`.vscode/settings.json`如下，应该是模板中的配置，我没动过。我用的是latex-workshop 8.9.0。谢谢学长。
```
{
    "latex-workshop.latex.recipes": [
        {
            "name": "latexmk with xelatex",
            "tools": ["latexmk-xelatex"]
        }
    ],
    "latex-workshop.latex.tools": [
        {
            "name": "latexmk-xelatex",
            "command": "latexmk",
            "args": [
                "-xelatex",
                "-file-line-error",
                "-halt-on-error",
                "-interaction=nonstopmode",
                "-synctex=1",
                "-outdir=%OUTDIR%",
                "%DOC%"
            ],
            "env": {}
        }
    ]
}
```

**Comment by zepinglee** [comment]
你说的“不能正确编译有引用的文档”是具体什么样的问题？

**Comment by kanglcn** [comment]
指编译后的引用文献时右上角的角标会变成[?]

**Comment by zepinglee** [comment]
依然无法复现你的问题。

macOS 10.15.4
Visual Studio Code Version: 1.45.1
LaTeX Workshop 8.9.0
TeX Live 2020

**Comment by Lkunyu** [comment]
可以试试用"xe->bib->xe->xe"的顺序编译，`.vscode/settings.json`的对应项中添加以下配置
```
"latex-workshop.latex.recipes": [
        {
            "name": "latexmk with xelatex",
            "tools": [
                "latexmk-xelatex"
            ]
        },
        {
            "name": "xe->bib->xe->xe",
            "tools": [
                "xelatex",
                "bibtex",
                "xelatex",
                "xelatex"
            ]
        }
    ],
    "latex-workshop.latex.tools": [
        {
            "name": "latexmk-xelatex",
            "command": "latexmk",
            "args": [
                "-xelatex",
                "-file-line-error",
                "-halt-on-error",
                "-interaction=nonstopmode",
                "-synctex=1",
                "-outdir=%OUTDIR%",
                "%DOC%"
            ],
            "env": {}
        },
        {
            // 编译工具和命令
            "name": "xelatex",
            "command": "xelatex",
            "args": [
                "-synctex=1",
                "-interaction=nonstopmode",
                "-file-line-error",
                "-pdf",
                "%DOCFILE%"
            ]
        },
        {
            "name": "bibtex",
            "command": "bibtex",
            "args": [
                "%DOCFILE%"
            ]
        }
    ],
```
然后就可以用"xe->bib->xe->xe"这个recipe编译

**Comment by hellojialee** [comment]
xelatex->bib->xelatex*2 这种顺序编译虽然没有问题，但是相对于texstudio，编译时间明显变长了

**Comment by syvshc** [comment]
> xelatex->bib->xelatex*2 这种顺序编译虽然没有问题，但是相对于texstudio，编译时间明显变长了

如果 TeXStudio 中也使用相同的编译链的话, 时间不会有明显的差距

**Comment by hellojialee** [comment]
TeXStudio使用了xelatex并没有用xelatex->bib->xelatex*2 。但是能正常编译

**Comment by xyzhou-1** [comment]
我也遇到了这个问题。
复现：手动选择recipe,编译正常；使用ctrl alt b快捷键编译错误。

解决：
![image](https://user-images.githubusercontent.com/47747466/110438046-fd977500-80f0-11eb-9946-3a14fb2b8b16.png)

猜测原因：some magic comments？（对latex开发不了解。。。）

**Comment by zepinglee** [comment]
有道理，我改一下。

**Comment by QJieWang** [comment]
我也遇到了编译问题，使用"xe->bib->xe->xe"可以编译，但也存在编译时间过长的问题。

**Comment by zepinglee** [comment]
> 我也遇到了编译问题，使用"xe->bib->xe->xe"可以编译，但也存在编译时间过长的问题。

使用这个

https://github.com/ustctug/ustcthesis/blob/052eeee6b4bcfe5f76c681fb060f757f5e3268b7/.vscode/settings.json#L5

**Comment by QJieWang** [comment]
> > 我也遇到了编译问题，使用"xe->bib->xe->xe"可以编译，但也存在编译时间过长的问题。
> 
> 使用这个
> 
> https://github.com/ustctug/ustcthesis/blob/052eeee6b4bcfe5f76c681fb060f757f5e3268b7/.vscode/settings.json#L5

报错信息是`Undefined control sequence.`好像是我文档路径里存在中文，"xe->bib->xe->xe"能用，慢一点也能接受，多谢开发者闪电答复。

**Comment by zepinglee** [comment]
> 报错信息是`Undefined control sequence.`好像是我文档路径里存在中文，"xe->bib->xe->xe"能用，慢一点也能接受，多谢开发者闪电答复。

建议另开 issue 将完整报错和截图发上来。
