### ISSUE TITLE
没有电脑该怎么办？

### ISSUE THREAD

**Issue by liuhunjijiu** [ustctug/ustcthesis#259]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型：doctor / master / bachelor

## 描述问题
对于一位着急毕业、买不起电脑（只有手机和iPad）、因为疫情影响网吧无法营业的学生将如何完成论文，您有什么建议吗？

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{ustcthesis}
\begin{document}
abc
\end{document}
```

**Comment by stone-zeng** [comment]
Overleaf 了解一下～

**Comment by liuhunjijiu** [comment]
> Overleaf 了解一下～
> 
> （事实上能编译 latex 的 PC 估计 1k 左右就能买到了，比 ipad 便宜多了←_←

Overleaf 不好使

**Comment by sunmy2019** [comment]
手机和 iPad 都不适合输入大段文字，而且 iPad 文件管理非常糟糕。这两个上面能用自定义模板的希望=0.
