### ISSUE TITLE
参考文献中两个作者和三个作者问题

### ISSUE THREAD

**Issue by ColinLii** [ustctug/ustcthesis#260]
英文参考文献中超过三个作者需要使用et. al. 而仅有两个作者时需要使用A&B， 为了解决这个问题我使用了citet*，但是英文引用时显示为A and B，这显然对于中文环境来说不合适，怎么修改为A &B呢？另外可否实现自动分辨是两个作者还是两个以上作者情况？

**Comment by zepinglee** [comment]
> 而仅有两个作者时需要使用A&B。

GB/T 7714-2015 和研究生《撰写手册》没有这样要求，都是用“et al”。

<img width="697" alt="Screen Shot 2020-05-25 at 5 04 47 PM" src="https://user-images.githubusercontent.com/12290822/82797638-f4168680-9ea9-11ea-9753-221906dfaed2.png">

**Comment by Lewis-Liu** [comment]
![Snipaste_2021-11-03_16-39-10](https://user-images.githubusercontent.com/5558564/140030224-a64d0b32-e13e-493e-8370-275be2ac406c.jpg)
三人及以下全部录入。
