### ISSUE TITLE
缺乏字体的警告

### ISSUE THREAD

**Issue by ChauncyFr** [ustctug/ustcthesis#261]
使用Mac系统用vscode编译生成PDF时，会报缺乏字体中的一些东西的警告，具体警告内容如下：

```
You are using Fandol font family.
(ustcthesis)	Some glyphs may be missing.
(ustcthesis)	Please switch to a high-quality font set .

```
如何解决啊？

**Comment by zepinglee** [comment]
字面意思，就是警告你 Fandol 可能缺字，留意一下有没有没显示出来的字形

**Comment by ChauncyFr** [comment]
> 字面意思，就是警告你 Fandol 可能缺字，留意一下有没有没显示出来的字形

没出现这种情况，但是我发现跟我同学生成的pdf的标题的字体好像不一样

**Comment by zepinglee** [comment]
不同平台的中文字体不一样，比如 macOS 的华文黑体，Windows 的中易黑体，如果你用 Linux 就是 Fandol 黑体了，字形会有所区别。

**Comment by zepinglee** [comment]
对，但是你用 mac 却调用了 Fandol 字体，这不太对啊。检查一下你用的版本？
