### ISSUE TITLE
参考文献的如何去掉editor、DOI和url

### ISSUE THREAD

**Issue by lyhangustc** [ustctug/ustcthesis#262]
研究生，绝大部分参考文献都是英文会议论文@inproceedings。

由于参考文献的bib中，并不是每一个文献都能找到对应的editor、DOI和url，导致显示出来的参考文献一部分有这几项内容，另一部分没有，不能统一会很难看。

我在撰写手册中看到"专著[M]”中有“其他责任人”和“获取和访问路径”，但是“期刊[J]”中没有这两项。我没有找到“会议论文[C]”的参考引用格式，感觉应该参照“期刊[J]”，不需要加入editor、DOI和url。

不管这些项目是否必须加入，还是想请问一下，要如何修改模板（而不需要逐项修改bib项目）才能去掉参考文献中的editor、DOI和url项目？

以下是一个例子：
目前的参考文献格式：
```
PASZKE A, GROSS S, MASSA F, et al. Pytorch: An imperative style, high-performance deep
learning library[C/OL]//WALLACH H M, LAROCHELLE H, BEYGELZIMER A, et al. Advances in Neural Information Processing Systems 32: Annual Conference on Neural Information Processing Systems 2019, NeurIPS 2019, 8-14 December 2019, Vancouver, BC, Canada. 2019: 8024-8035. http://papers.nips.cc/paper/9015-pytorch-an-imperative-style-high-perfo
rmance-deep-learning-library.
```

其中```WALLACH H M, LAROCHELLE H, BEYGELZIMER A, et al.  ```为bib项目中的editor, ```http://papers.nips.cc/paper/9015-pytorch-an-imperative-style-high-perfo
rmance-deep-learning-library.```为bib项目中的url。

希望出来的参考文献格式：
```
PASZKE A, GROSS S, MASSA F, et al. Pytorch: An imperative style, high-performance deep
learning library[C]//Advances in Neural Information Processing Systems 32: Annual Conference on Neural Information Processing Systems 2019, NeurIPS 2019, 8-14 December 2019, Vancouver, BC, Canada. 2019: 8024-8035. 
```
谢谢。

**Comment by zepinglee** [comment]
会议论文应该按照“专著中的析出文献”处理。

另外学校的《撰写手册》是依据 GB/T 7714-2015 的，这份标准中的“专著中的析出文献”格式是有 url 和 DOI 的：
<img width="732" alt="Screen Shot 2020-06-02 at 15 10 38" src="https://user-images.githubusercontent.com/12290822/83490803-4592c700-a4e3-11ea-9fb6-5e30d7a01e07.png">
通常这些项目如果有就填写，如果没有就省略，不必统一。
