### ISSUE TITLE
建议在模板中加入对etex包的调用

### ISSUE THREAD

**Issue by USTCmyw** [ustctug/ustcthesis#263]
```TeX
\documentclass{article}

\RequirePackage{amsmath}
\RequirePackage{unicode-math}
\RequirePackage[driver=xetex]{geometry}
\RequirePackage[perpage]{footmisc}

\usepackage{tkz-euclide}

\begin{document}
123
\end{document} 
```
模板中的这四个包与tkz-euclide合用会出现warning: Package etex Warning: Extended allocation already in use。

tex.stackexchange上给出了一个[解决方案](https://tex.stackexchange.com/questions/253807)，在前面添加 \RequirePackage{etex}。

该问题较为隐蔽，涉及模板中的四个包和自己调用的一个包，去掉其中任何一个都不会显示warning，使人很难发现问题所在。

建议模板中加入 \RequirePackage{etex} 以避免此问题再次出现

**Comment by zepinglee** [comment]
这是由更适合自己写在 `\documentclass`，不宜加到模板中。
