### ISSUE TITLE
模板附录部分不符合规范

### ISSUE THREAD

**Issue by wffx** [ustctug/ustcthesis#265]
《中国科学技术大学研究生学位论文撰写手册，二零一六年六月》，上面介绍的附录部分规范应该是：
附录A 
A.1
A.2
......
而本模板编译出来的效果是：
附录
.1
.2
.......
---------------------------
目前还在查如何修改，啊啊啊。。。

**Comment by zepinglee** [comment]
这个在 51c1ba8 中已经修复了
