### ISSUE TITLE
英文参考文献题目与文献标识之间空格问题

### ISSUE THREAD

**Issue by ustcjerry** [ustctug/ustcthesis#267]
## 编译环境
- 编译的系统：Windows 10 
- TeX 发行版：TeX Live 2020
- 模板类型：doctor

## 描述问题
《研究生学位论文撰写手册》第 61页示例：英文文献标题后与类型之间有空格

![image](https://user-images.githubusercontent.com/11849381/85354384-06352480-b53d-11ea-9ddd-366b920da5dc.png)

但是模板编译出来的没有空格

**Comment by ustcjerry** [comment]
额，但是GB/T 7714中没有要求加空格

**Comment by zepinglee** [comment]
GB/T 7714-2015 的英文示例中大部分都没有空格，但是在英文的使用习惯上还是要加空格的，我觉得还是改一下吧。

**Comment by zepinglee** [comment]
这份标准在空格的使用上不统一，不够严谨。GB/T 7714-2005 也有不带空格的：
<img width="838" alt="Screen Shot 2020-06-23 at 10 53 37" src="https://user-images.githubusercontent.com/12290822/85355710-cde31580-b53f-11ea-8c0e-a4e8572ca51c.png">

**Comment by ustcjerry** [comment]
不如默认按照《撰写手册》标准吧，然后此争议放到“常见问题”里？

**Comment by zepinglee** [comment]
对。学校的《撰写手册》可以理解为在 GB/T 7714-2015 基础上的额外规定，所以应该没有争议。

**Comment by ustcjerry** [comment]
恩

**Comment by zepinglee** [comment]
已经修好了

**Comment by ustcjerry** [comment]
中文的参考文献后应该不加空格的

**Comment by zepinglee** [comment]
正常情况下中文和西文字符之间要加一些空白，我在之前为了允许在这里断行加了 `\allowbreak`，抑制了这个空白。

所以其实加空白更自然一些。

**Comment by ustcjerry** [comment]
可是这样感觉空白间距太大了？

**Comment by zepinglee** [comment]
在 LaTeX 里直接写也会有些空白：

```latex
测试[]

测试\allowbreak[]

测试 []
```

<img width="85" alt="Screen Shot 2020-06-23 at 15 29 22" src="https://user-images.githubusercontent.com/12290822/85373765-5379bc00-b566-11ea-9ae3-2d3d10957be9.png">

**Comment by ustcjerry** [comment]
放到中文参考文献里感觉很扎眼，可以对中文的参考文献抑制空白吗？

**Comment by muzimuzhi** [comment]
> 这份标准在空格的使用上不统一，不够严谨。GB/T 7714-2005 也有不带空格的：
> <img alt="Screen Shot 2020-06-23 at 10 53 37" width="838" src="https://user-images.githubusercontent.com/12290822/85355710-cde31580-b53f-11ea-8c0e-a4e8572ca51c.png">

gbt 7714-2015 的示例里，西文文献的文献标识之前要不要空格，还可以理解成：
为保持段落两端对齐，而让词间空格拉伸（到某个程度）时，文献标识之前插入相当于一个空格的拉伸部分的横向间距。否则，文献标识之前不插入空格。

当然，这部分 gbt 7714-2015 没有用文字明确说明，要不要空格只是读者根据里面的示例推断出来的。

**Comment by zepinglee** [comment]
> gbt 7714-2015 的示例里，西文文献的文献标识之前要不要空格，还可以理解成：
> 为保持段落两端对齐，而让词间空格拉伸（到某个程度）时，文献标识之前插入相当于一个空格的拉伸部分的横向间距。例如，当词间空格的跨度从 1000 拉伸到 1500 时，在文献标识之前插入宽度相当于 500 的横向间距。否则，文献标识之前不插入空格。

虽然示例的策略差不多是这样，但我觉得还是应该按照西文的习惯处理。考虑到这里的语义，“[M]” 是对整个标题的补充说明，类似的用法是“Title of the article (conference paper)”。所以应该按照西文的习惯加空格。

另外见过好多人按照中文的习惯用西文的标点符号，后面不加空格，简直辣眼睛。
