### ISSUE TITLE
每章另页起的问题

### ISSUE THREAD

**Issue by fengboo** [ustctug/ustcthesis#269]
在《撰写手册》中没要求每章要另页起，但现在在学校印刷厂打印时要求每章另页起，推荐增加另页起的可选项。

**Comment by zepinglee** [comment]
见 https://github.com/ustctug/ustcthesis/issues/154#issuecomment-331323153 。

另外 ec241282772e89173798d3ac64cfebaec927e5e8 的修改允许在 `\documentclass` 的参数中使用 `openright`
