### ISSUE TITLE
工程硕士论文的封面有一个空括号

### ISSUE THREAD

**Issue by miraclewk** [ustctug/ustcthesis#270]
\documentclass[degree=master,degree-type=professional]{ustcthesis}

使用上述代码会生成工程硕士论文的封面，但是下面会有一个空括号生成，请问怎么样在括号里填字

**Comment by zepinglee** [comment]
专业学位的学位类型

发自我的iPhone

**Comment by miraclewk** [comment]
我是想咨询括号里的字要在源文件哪里才可以加上，我没找到地方😂



---原始邮件---
发件人: "Zeping Lee"<notifications@github.com&gt;
发送时间: 2020年7月11日(周六) 晚上10:56
收件人: "ustctug/ustcthesis"<ustcthesis@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"万凯"<254034435@qq.com&gt;;
主题: Re: [ustctug/ustcthesis] 咨询一个问题 (#270)




 专业学位的学位类型
 
 发自我的iPhone
 
 &gt; 在 2020年7月11日，22:40，万凯 <notifications@github.com&gt; 写道：
 &gt; 
 &gt; ﻿
 &gt; \documentclass[degree=master,degree-type=professional]{ustcthesis}
 &gt; 
 &gt; 使用上述代码会生成工程硕士论文的封面，但是下面会有一个空括号生成，请问怎么样在括号里填字
 &gt; 
 &gt; —
 &gt; You are receiving this because you are subscribed to this thread.
 &gt; Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by miraclewk** [comment]
> 专业学位的学位类型 发自我的iPhone
> […](#)
> 在 2020年7月11日，22:40，万凯 ***@***.***> 写道： ﻿ \documentclass[degree=master,degree-type=professional]{ustcthesis} 使用上述代码会生成工程硕士论文的封面，但是下面会有一个空括号生成，请问怎么样在括号里填字 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我是想咨询一下怎么在LaTeX代码里给括号加上字，没有找到相对应的地方

**Comment by zepinglee** [comment]
https://github.com/ustctug/ustcthesis/blob/d28aa789a04898981e23ffa8a70089f56b05759a/ustcsetup.tex#L14-L15

**Comment by miraclewk** [comment]
> https://github.com/ustctug/ustcthesis/blob/d28aa789a04898981e23ffa8a70089f56b05759a/ustcsetup.tex#L14-L15

谢谢，看到了

**Comment by zhangddjs** [comment]
求助，\documentclass[degree=master,degree-type=professional]{ustcthesis} 我添加上degree-type参数为professional后用xelatex编译会失败。。

**Comment by zepinglee** [comment]
> 求助，\documentclass[degree=master,degree-type=professional]{ustcthesis} 我添加上degree-type参数为professional后用xelatex编译会失败。。

报什么错？我猜不来

**Comment by zhangddjs** [comment]
! Package fontspec Error: The font "LiSu" cannot be found.

**Comment by zhangddjs** [comment]
> > 求助，\documentclass[degree=master,degree-type=professional]{ustcthesis} 我添加上degree-type参数为professional后用xelatex编译会失败。。
> 
> 报什么错？我猜不来

用的是最新的release版本。
