### ISSUE TITLE
求助，degree-type参数为professional后用xelatex编译会失败。。

### ISSUE THREAD

**Issue by zepinglee** [ustctug/ustcthesis#271]
求助，\documentclass[degree=master,degree-type=professional]{ustcthesis} 我添加上degree-type参数为professional后用xelatex编译会失败。。

_Originally posted by @zhangddjs in https://github.com/ustctug/ustcthesis/issues/270#issuecomment-666532406_

**Comment by zepinglee** [comment]
系统缺隶书字体。

**Comment by zhangddjs** [comment]
安装了隶书字体，现在编译成功了，谢谢~
