### ISSUE TITLE
参考文献的 eprint 显示不出来

### ISSUE THREAD

**Issue by zepinglee** [ustctug/ustcthesis#272]
```
misc{girshick2015fast,
    title={Fast R-CNN},
    author={Ross Girshick},
    year={2015},
    eprint={1504.08083},
    archivePrefix={arXiv},
    primaryClass={cs.CV}
}
```
但编译出的显示为：
GIRSHICK R. Fast r­cnn[Z]. 2015.
eprint关键字后面的信息显示不出来，请教下怎么解决？

_Originally posted by @baymax-nexi in https://github.com/ustctug/ustcthesis/issues/166#issuecomment-674730990_

**Comment by zepinglee** [comment]
新开 issue 讨论吧

**Comment by zepinglee** [comment]
研究生的撰写手册和 GB/T 7714-2015 均未对预印本文献类型作出规定，默认的 bst 是严格按照这些规定的格式，所以没有显示 `eprint` 和 `archivePrefix`。

你可以将 `bst` 文件的 `#0 'show.preprint :=` 一行改为 `#1` 以支持扩充的预印本的格式。

**Comment by baymax-nexi** [comment]
> 研究生的撰写手册和 GB/T 7714-2015 均未对预印本文献类型作出规定，默认的 bst 是严格按照这些规定的格式，所以没有显示 `eprint` 和 `archivePrefix`。
> 
> 你可以将 `bst` 文件的 `#0 'show.preprint :=` 一行改为 `#1` 以支持扩充的预印本的格式。

我用的release 3.2.1 没找到这行。master有，怎么解决方便，在release上直接加上这行参数是否可以？

**Comment by zepinglee** [comment]
> 我用的release 3.2.1 没找到这行。master有，怎么解决方便，在release上直接加上这行参数是否可以？

你需要把整个 bst 文件用 master 的替换。

这个功能是今年加的： https://github.com/CTeX-org/gbt7714-bibtex-style/commit/058d365131121bc003b6f06c74634fa18af57a8f ，我在考虑要不要将其设为默认。

**Comment by baymax-nexi** [comment]
> > 我用的release 3.2.1 没找到这行。master有，怎么解决方便，在release上直接加上这行参数是否可以？
> 
> 你需要把整个 bst 文件用 master 的替换。
> 
> 这个功能是今年加的： [CTeX-org/gbt7714-bibtex-style@058d365](https://github.com/CTeX-org/gbt7714-bibtex-style/commit/058d365131121bc003b6f06c74634fa18af57a8f) ，我在考虑要不要将其设为默认。

可以了，谢谢。 最好吧，cs方面引用的这种文章挺多的

**Comment by zepinglee** [comment]
但是像这篇已经发表了的，应该更新成 inproceedings 比较符合学术规范。
```
@inproceedings{girshick2015fast,
  title={Fast r-cnn},
  author={Girshick, Ross},
  booktitle={Proceedings of the IEEE international conference on computer vision},
  pages={1440--1448},
  year={2015}
}
```
