### ISSUE TITLE
怎样删除插图和表格清单中的标题的参考文献引用，而在正文中保留引用？

### ISSUE THREAD

**Issue by ustcjerry** [ustctug/ustcthesis#275]
## 编译环境
- 编译的系统： Windows 10 
- TeX 发行版：TeX Live 2020
- 模板类型：doctor

## 描述问题

怎样删除插图和表格清单中的标题的参考文献引用，而在正文中保留引用？

**Comment by ustcjerry** [comment]
以及请问如何在 插图清单 和 表格清单 中每项改为： 图1.1 xxx  表1.1 yyy  而不是单纯 1.1 xxxx  1.1 yyyy

**Comment by zepinglee** [comment]
> 怎样删除插图和表格清单中的标题的参考文献引用，而在正文中保留引用？

目前最新版使用了 `notoccite` 宏包，lof 中应该不会出现引用。你给个 mwe？

**Comment by zepinglee** [comment]
> 以及请问如何在 插图清单 和 表格清单 中每项改为： 图1.1 xxx 表1.1 yyy 而不是单纯 1.1 xxxx 1.1 yyyy

这个主要是因为英文版 "Figure 1.1" 的宽度和中文的不一样，已经在 e6ae89f 中修改。

**Comment by ustcjerry** [comment]
> > 怎样删除插图和表格清单中的标题的参考文献引用，而在正文中保留引用？
> 
> 目前最新版使用了 `notoccite` 宏包，lof 中应该不会出现引用。你给个 mwe？

例如模板中给校徽图片标题加入引用：

\begin{figure}[htb]
  \centering
  \includegraphics[width=0.3\textwidth]{ustc-badge.pdf}
  \caption{图号、图题置于图的下方\cite{slg}}
  \label{fig:badge}
  \note{注：图注的内容不宜放到图题中。}
\end{figure}

那么插图清单里就会显示：

![QQ截图20201010231837](https://user-images.githubusercontent.com/11849381/95658705-fe7ea780-0b4e-11eb-8c3a-fa6715e1ec5c.jpg)

**Comment by zepinglee** [comment]
噢我记错了，`notoccite` 不能去掉 `\cite` 的编号。恐怕只能用 `\caption[图号、图题置于图的下方]{图号、图题置于图的下方\cite{slg}}` 的方法。

**Comment by ustcjerry** [comment]
> 噢我记错了，`notoccite` 不能去掉 `\cite` 的编号。恐怕只能用 `\caption[图号、图题置于图的下方]{图号、图题置于图的下方\cite{slg}}` 的方法。

这个方法可以。多谢！

另外，感觉 `图2.1 图号、图题置于图的下方` 这里空格间距略大？

**Comment by zepinglee** [comment]
这里设置了 1.5em 的空白，主要是为了两位编号时依然有足够的空间，比如“图 2.12”。我还是改小一点吧。

**Comment by ustcjerry** [comment]
> 这里设置了 1.5em 的空白，主要是为了两位编号时依然有足够的空间，比如“图 2.12”。我还是改小一点吧。

感觉0.5em比较符合我自己的审美，，，
