### ISSUE TITLE
软件学院论文模板封面有额外要求

### ISSUE THREAD

**Issue by coolxxy** [ustctug/ustcthesis#276]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 10
- TeX 发行版：TeX Live 2019
- 模板类型：master

## 描述问题
由于大部分软件学院学生的论文有校内导师和企业导师共同指导完成，因此封面的导师信息与本模板不一致，软件学院模板的截图如下：
![image](https://user-images.githubusercontent.com/11879017/96331156-9b7c9b80-108d-11eb-80cd-112560ce32f6.png)
另外，从该截图可以看出除了导师信息，还有一个科大 logo 和 文本框框线不一致。

期待您的协助！

**Comment by zepinglee** [comment]
可以发一份官方文件或者官网链接吗？

**Comment by coolxxy** [comment]
文件在软院信息系统提供，由于该网站需要登录，我将截图和相关文件上传，截图如下：

![image](https://user-images.githubusercontent.com/11879017/96333202-126c6100-109b-11eb-892a-eed72e60316d.png)

文件解压后如下：

![image](https://user-images.githubusercontent.com/11879017/96333222-362fa700-109b-11eb-9b7a-d8f33d0a4091.png)

软院下载压缩包如下：

[学位论文写作相关文件.zip](https://github.com/ustctug/ustcthesis/files/5395253/default.zip)

**Comment by zepinglee** [comment]
ok，我想想怎么设计接口

**Comment by coolxxy** [comment]
非常非常感谢！: )

**Comment by zepinglee** [comment]
现在使用 `advisor` 和 `advisor*` 设置企业导师的姓名，如果为空则按照普通的模板格式。
