### ISSUE TITLE
编译出错

### ISSUE THREAD

**Issue by Jacio-Y** [ustctug/ustcthesis#277]
## 检查
- [v] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [v] 已经将模板升级到了最新版
- [v] 已经阅读使用说明文档 `ustcthesis.pdf`
- [v] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 10 
- TeX 发行版：TeX Live 2020
- 模板类型：doctor

## 描述问题
下载了最新的模板后，没有修改任何内容，打开main文件进行编译，出现以下错误：

截图：
![Latex编译问题](https://user-images.githubusercontent.com/73462523/97146551-01120b80-17a3-11eb-810a-122c35b2dae8.JPG)

复现上述问题的代码：
fontspec.sty文件中第2-7行
```TeX

\documentclass{ctexart}
\usepackage{xcolor}  	%高亮使用的颜色
\definecolor{commentcolor}{RGB}{85,139,78}
\definecolor{stringcolor}{RGB}{206,145,108}
\definecolor{keywordcolor}{RGB}{34,34,250}
\definecolor{backcolor}{RGB}{220,220,220}
```
fontspec.sty文件中第34-44行
```Tex
\begin{document}
 	这是Python语法高亮
	
	\begin{lstlisting}
	def prtmotto(n):
	for i in range(0,n):
	print("lift is short, i use Python!")
	\end{lstlisting}
	
\end{document}
}
```

**Comment by zepinglee** [comment]
报错第 1 条很明显，只能有一个 `\documentclass`。

另外，模板依赖 https://ctan.org/pkg/fontspec ，但是却找到了你自己新建的 `fontspec.sty`。
