### ISSUE TITLE
汉字显示为方框

### ISSUE THREAD

**Issue by Liu-JiaCheng** [ustctug/ustcthesis#278]
### 检查
已经阅读《研究生学位论文撰写手册》
已经将模板升级到了最新版
已经阅读使用说明文档 ustcthesis.pdf
已经阅读 常见问题

### 编译环境
编译的系统：Windows 7 Service Pack 1
TeX 发行版：TeX Live 2020
模板类型：doctor

### 额外说明
电脑之前装了CTeX和texlive2015，现已删除，只剩texlive2020

### 描述问题
下载了最新的模板后，没有修改任何内容，用texworks.exe打开main.tex文件进行点XeLaTex编译后，出现以下情况：
![2020-10-31_230418](https://user-images.githubusercontent.com/46340154/97782621-86dfed80-1bcd-11eb-9e00-7ef9bfb5a7a9.png)

检查main.log文件后相关结果如下：
```
File: figures/ustc-name.pdf Graphic file (type pdf)
<use figures/ustc-name.pdf>
Missing character: There is no 博 in font SubahibiFont/OT:language=dflt;!
Missing character: There is no 士 in font SubahibiFont/OT:language=dflt;!
Missing character: There is no 学 in font SubahibiFont/OT:language=dflt;!
Missing character: There is no 位 in font SubahibiFont/OT:language=dflt;!
Missing character: There is no 论 in font SubahibiFont/OT:language=dflt;!
Missing character: There is no 文 in font SubahibiFont/OT:language=dflt;!
File: figures/ustc-badge.pdf Graphic file (type pdf)
<use figures/ustc-badge.pdf>
```
这是main.log文件：
[main.log](https://github.com/ustctug/ustcthesis/files/5469291/main.log)

摘要和正文的汉字可以正常显示，基本上跟标题有关的汉字就是方框。用谷歌镜像后没找到这个SubahibiFont是什么字体。

命令提示符运行fc-list后全文只有下面这个地方出现了SubahibiFont如下所示：
```
C:/Windows/fonts/font_1.ttf: SimHei,素晴字体,**_SubahibiFont_**:style=Regular,Normal,obyčejné,Standard,Κανονικά,Normaali,Normál,Normale,Standaard,Normalny,Обычный,Normálne,Navadno,Arrunta
```
这是fc-list文件：
[fc-list.txt](https://github.com/ustctug/ustcthesis/files/5469311/fc-list.txt)

另外我在C:/Windows/fonts目录下面并没有找到font_1.ttf文件

**Comment by stone-zeng** [comment]
看起来你电脑里面的中易黑体（SimHei）文件损坏了，可以去找一个正常版本的替换掉。`C:/Windows/fonts` 路径比较特别，删文件可能要进命令行。

**Comment by Liu-JiaCheng** [comment]
多谢帮助，但我重新下了个9751960字节的simhei.ttf重新安装了一下，用XeLaTeX编译后原来的汉字还是方框。

具体来说标题中的Ascii字符似乎并不受影响，比如我把ustcthesis.cls的第1134行改为如下：
……
% 定义一些常量。
\ifustc@degree@doctor
  \newcommand\ustc@thesis@name{博士学位论文YE！!！}
  \newcommand\ustc@thesis@name@en{A dissertation for doctor's degree}
……
其他地方不变，那么编译后的结果如图所示：
![2020-11-01_163336](https://user-images.githubusercontent.com/46340154/97798328-1afa9500-1c60-11eb-95f6-a43a4ca10054.png)
不知道是不是标题的那个字体本身不支持汉字。

**Comment by zepinglee** [comment]
https://github.com/CTeX-org/forum/issues/94 有个相关的讨论，但是也没有结论。

你的 WIndows 7 是不是日语版的？

**Comment by zepinglee** [comment]
另外我注意到 fc-list.txt 里字体名为 simhei 的有三个：
```
C:/Windows/fonts/font_1.ttf: SimHei,素晴字体,SubahibiFont:style=Regular,Normal,obyčejné,Standard,Κανονικά,Normaali,Normál,Normale,Standaard,Normalny,Обычный,Normálne,Navadno,Arrunta
C:/Windows/fonts/���׺���.ttf: SimHei,黑体:style=Regular
C:/Windows/fonts/simhei.ttf: SimHei,黑体:style=Regular,Normal,obyčejné,Standard,Κανονικά,Normaali,Normál,Normale,Standaard,Normalny,Обычный,Normálne,Navadno,Arrunta
```
然而这个「素晴字体 Subahibi Font」的来历我也没查到，感觉应该是流氓软件的。

**Comment by stone-zeng** [comment]
看一下 <https://tieba.baidu.com/p/6207595649?cid=&pid=126789277413&red_tag=2377175068>？

**Comment by zepinglee** [comment]
看起来跟 Galgame 有关，但是 Galgame 也没必要覆盖系统的 SimHei 呀……

**Comment by Liu-JiaCheng** [comment]
多谢各位大佬！把素晴字体删了后就正常了！妈妈我再也不敢乱安装Galgame的字体了！
