### ISSUE TITLE
如何去掉表格汇总索引和图片汇总索引

### ISSUE THREAD

**Issue by srdczk** [ustctug/ustcthesis#279]
论文规范要求这个吗，感觉大部分都有但是模板里没有。

**Comment by stone-zeng** [comment]
取消注释后两行：

https://github.com/ustctug/ustcthesis/blob/fc0577ef00a6c43f2925ab37937b8835ffed9922/main.tex#L33-L35

**Comment by srdczk** [comment]
感谢

**Comment by zepinglee** [comment]
这个标题歧视女性。
