### ISSUE TITLE
给我们的repo改个名怎么样？

### ISSUE THREAD

**Issue by zepinglee** [ustctug/ustcthesis#28]
现在的名字有点丑啊，按照 github 的习惯，一般不会搞这么多大写字母啊。
另外“组织”称为 USTCThesis 有点奇怪，改成 USTCTUG怎么样？
所以我建议改成 github.com/ustctug/ustcthesis

**Comment by seisman** [comment]
可以改名，毕竟未来这个org的repo除了thesis之外，还可以包含很多跟LaTeX相关的内容，比如之前的repo中已经实现的beamer、letter等等。

我当初想的是要不要改成ustclatex

**Comment by zepinglee** [comment]
我觉得 ustctug 更霸气一些啊，我们已经有了 ustclug

**Comment by zepinglee** [comment]
我想趁大家还没开学，先发布一个 v2.0-beta1 让大家测试一下，LUG 那边应该有些大牛的

**Comment by seisman** [comment]
关于版本号，要从2.0开始吗？之前的模板其实一直是beta，没有正式的版本号，所以某种程度上连1.0都算不上。

**Comment by zepinglee** [comment]
之前的版本已经比较有知名度了，我们的叫2.0可以很好区分开来

**Comment by seisman** [comment]
OK.

**Comment by zepinglee** [comment]
那我先改名字了，可能需要重新git clone 一下

**Comment by seisman** [comment]
org的名字可以改，repo的名字暂时不要改吧？

**Comment by seisman** [comment]
之前的提交历史是都要保留吗？

**Comment by zepinglee** [comment]
已经改好了，服务器上的都保留，只是本地需要更改一下 origin 的 url

**Comment by seisman** [comment]
我当初以为这个repo只是用作临时开发，等到第一个版本发布的时候新建一个repo，然后这个repo就被放弃，之后的更改都在新的repo里。

**Comment by zepinglee** [comment]
没必要吧……
我再修改一下就给ustclug那边发个通知

**Comment by seisman** [comment]
之前的提交历史稍稍有些乱，可以考虑rebase一下。等到有人fork之后rebase就变得麻烦了

**Comment by zepinglee** [comment]
那好吧
其实我还不太懂怎么样去维护一个repo……需要经常rebase吗？

**Comment by seisman** [comment]
不会需要经常rebase。

常见的开发流程一般就是先开一个分支，如果开发周期比较长，可能就会经常提交一下，在要merge之前一般都会把提交历史合并一下，以使得提交不至于太乱，rebase就是用来修改提交历史的。

一旦有人fork之后，如果再rebase master分支，就会导致对方fork的repo和官方的repo不一致，就会造成一些麻烦。所以一般都会在push到服务器或者merge之前rebase一下。当然，如果提交历史比较干净的话不rebase也没问题。
