### ISSUE TITLE
sum求和符号的字体好粗

### ISSUE THREAD

**Issue by iamRyanChia** [ustctug/ustcthesis#280]
<img width="352" alt="截屏2020-12-16 下午10 17 10" src="https://user-images.githubusercontent.com/41557860/102360161-a2238280-3fec-11eb-8b18-6e0a277c19e5.png">

请问求和符号这么粗是正常的么？感觉不太对。

在macos11.0.1和win10下编译都是这个效果，使用的是texlive2020，编辑器为vscode+latex workshop。

**Comment by zepinglee** [comment]
目前的数学字体使用的是 `unicode-math` 和 XITS，其中的 `\sum` 符号的字形就是这个样子的。当时这样设置是出于两方面的考虑：
1. 遵循 GB/T 3102.11—1993 的符号（也包括了字形）；
2. 跟正文的西文字体 Times New Roman 保持兼容。

其他兼容 Times 的 `unicode-math` 数学字体或多或少有些字形的问题，比如 SITX2Math, TeX Gyre Termes Math。另外，使用传统的 Type 1 数学字体（比如 `newtxmath`）也有问题，比如跟 `siunitx` 的冲突。

**Comment by iamRyanChia** [comment]
请问可以怎么修改一下呢？现在看起来不是很协调

**Comment by zepinglee** [comment]
你来找个合适的字体？

**Comment by iamRyanChia** [comment]
我对字体不是很熟悉，如果这么做是符合标准的话，那么不改也无妨

**Comment by zepinglee** [comment]
这里是一份比较完整的 opentype math 字体：https://tex.stackexchange.com/a/425099/82731 

在模板中，你可以 `\ustcsetup{math-font=xits}` 切换数学字体，可选：`xits`, `stix`, `libertinus`, `lm`。

**Comment by iamRyanChia** [comment]
好的，非常感谢你的帮助👍

**Comment by zepinglee** [comment]
另外请教下 @stone-zeng ，混搭不同数学的字体会不会有 kerning 的问题，比如：
```latex
\setmathfont{XITSMath-Regular.otf}
\setmathfont{STIX2Math.otf}[range=\sum]
```

**Comment by stone-zeng** [comment]
至少 `\sum` 和 `\prod` 看上去问题不大，而且 XITS 和 STIX 本身就基本是度量兼容的吧：

![image](https://user-images.githubusercontent.com/18233088/102443037-c1f48e00-4060-11eb-83c4-0d26a123ee56.png)

**Comment by zepinglee** [comment]
> 至少 `\sum` 和 `\prod` 看上去问题不大，而且 XITS 和 STIX 本身就基本是度量兼容的吧：
> 
> ![image](https://user-images.githubusercontent.com/18233088/102443037-c1f48e00-4060-11eb-83c4-0d26a123ee56.png)

感谢！
