### ISSUE TITLE
编译出现字符无法显示

### ISSUE THREAD

**Issue by yangfyustc** [ustctug/ustcthesis#281]
- 编译器：VS Code - LaTex Workshop 8.15.0 / Tex Works
- 编译的系统：Windows 10 
- TeX 发行版：TeX Live 2020 

描述问题
如图，chapter以及section全部未显示，同时封面也均未显示。

截图：
![捕获](https://user-images.githubusercontent.com/76695648/103223650-a5890900-491e-11eb-9cd7-a51a7d2c64c2.JPG)

复现上述问题的代码：
releaseV3.2.1源代码直接编译，未做改动

**Comment by zepinglee** [comment]
是不是安装了 GALA game？

**Comment by yangfyustc** [comment]
确实同样是素晴日的汉化字体出的问题，fc-list以及main.log里面是同样的问题。
但是win10直接打开fonts文件夹删除了素晴字体，fc-list中也还能找到，重启了电脑也没用
我再去百度一下命令行
