### ISSUE TITLE
author-year 中文未按拼音排序

### ISSUE THREAD

**Issue by zepinglee** [ustctug/ustcthesis#282]
你好。我用的author-year格式，发现英文是严格按照作者姓名排序的。但中文既未按拼音排序，也未按文中顺序排。是怎么回事呢？谢谢您。
![Snipaste_2021-01-12_16-34-46](https://user-images.githubusercontent.com/32346042/104289456-1ff78280-54f4-11eb-8817-778ba166368a.png)

_Originally posted by @cugliming in https://github.com/ustctug/ustcthesis/issues/231#issuecomment-758497234_

**Comment by zepinglee** [comment]
由于 BibTeX 功能所限，无法自动获取著者姓名的拼音或笔画笔顺，所以也不能正确排序（实际的排序是按照 UTF-8 编码顺序排序的）。一种解决方案是在 bib 数据库中的 `key` 域录入著者姓名的拼音。
```
@book{capital,
  author = {马克思 and 恩格斯},
  key    = {ma3 ke4 si1 en1 ge2 si1}, ...
}
```

另外一种方式是使用 `biblatex-gb7714`。但目前模板跟 `natbib` 耦合，不能使用 `biblatex`。我稍后打算修改一下，允许用户选择 BibTeX 或者 biblatex。@cugliming 如果不急的话可以等更新。

**Comment by cugliming** [comment]
> 由于 BibTeX 功能所限，无法自动获取著者姓名的拼音或笔画笔顺，所以也不能正确排序（实际的排序是按照 UTF-8 编码顺序排序的）。一种解决方案是在 bib 数据库中的 `key` 域录入著者姓名的拼音。
> 
> ```
> @book{capital,
>   author = {马克思 and 恩格斯},
>   key    = {ma3 ke4 si1 en1 ge2 si1}, ...
> }
> ```
> 
> 另外一种方式是使用 `biblatex-gb7714`。但目前模板跟 `natbib` 耦合，不能使用 `biblatex`。我稍后打算修改一下，允许用户选择 BibTeX 或者 biblatex。@cugliming 如果不急的话可以等更新。

嗯，我查阅了一些资料。感觉中文环境下biblatex-gb7714-2015要强大的多额，尤其是作者按拼音排序这个功能解决了一大痛点。

**Comment by zepinglee** [comment]
d7f6574 添加了 biblatex 的支持，可以测试一下看看有没有别的问题。
