### ISSUE TITLE
编译后得到的页眉样式与原始模板不同

### ISSUE THREAD

**Issue by pikachuuu108** [ustctug/ustcthesis#283]
## 检查
- [✔] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [✔ ] 已经将模板升级到了最新版
- [✔] 已经阅读使用说明文档 `ustcthesis.pdf`
- [✔ ] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 10
- TeX 发行版：TeX Live 2020
- 模板类型：master

## 描述问题
在下载最新的模板 v3.2.1，未对文件作任何更改，并直接使用 latexmk 编译后，页眉样式与原始 main.pdf 不同。

原始 main.pdf 中摘要、目录、致谢及参考文献等非正文部分页眉不显示序号，且正文部分的页眉显示为中文“第 X 章  xxxx”；

而我得到编译后的 main.pdf 文件中非正文部分仍然显示页眉的编号，例如摘要部分的页眉样式为“Chapter 0. 摘要”，正文部分的页眉显示为“Chapter 1. 简介”，正文之后的部分页眉显示“附录. 致谢”

截图：
![image](https://user-images.githubusercontent.com/26197197/106542975-ceb14080-653f-11eb-9d71-6849cd8a28ac.png)

![image](https://user-images.githubusercontent.com/26197197/106543795-64999b00-6541-11eb-86f3-7360e27fe945.png)

![image](https://user-images.githubusercontent.com/26197197/106543818-6cf1d600-6541-11eb-8baa-025b3421d4cc.png)

复现上述问题的代码：
```TeX
% !TeX encoding = UTF-8
% !TeX program = xelatex
% !TeX spellcheck = en_US

\documentclass[degree=master]{ustcthesis}
% degree    = doctor|master|bachelor
% language  = chinese|english

% 加载宏包、全部的配置
\input{ustcsetup.tex}


\begin{document}

% 研究生论文:
%   封面，原创性声明和授权使用声明
%   frontmatter: 摘要，目录，[图、表清单]，[符号说明]
%   mainmatter: 正文章节，参考文献
%   appendix: 附录
%   backmatter: 致谢，已发表论文列表
%
% 本科生论文:
%   封面
%   frontmatter: 致谢，目录，摘要
%   mainmatter: 正文章节，参考文献
%   appendix: 附录

\maketitle
\copyrightpage

\frontmatter
\input{chapters/abstract.tex}
\tableofcontents
%\listoffigures
%\listoftables
\input{chapters/notation.tex}

\mainmatter
\input{chapters/intro.tex}
\input{chapters/floats.tex}
\input{chapters/math.tex}
\input{chapters/citations.tex}

\backmatter
\bibliographystyle{ustcthesis-numerical}  % 顺序编码制
% \bibliographystyle{ustcthesis-authoryear} % 著者出版年制
% \bibliographystyle{ustcthesis-bachelor}   % 本科生参考文献的格式
\bibliography{bib/ustc}

\appendix
\input{chapters/complementary.tex}

\input{chapters/acknowledgements.tex}
\input{chapters/publications.tex}

\end{document}

```

**Comment by zepinglee** [comment]
这是 `fancyhdr` 更新到 4.0 后导致 `ctex` 的 patch 失效，见 <https://github.com/CTeX-org/ctex-kit/issues/554>。我在 `ustcthesis` 的 3254a5f 已经修复，你可以使用 master 分支的最新版本，发布版可能要稍等一些时间。

**Comment by pikachuuu108** [comment]
下载master分支重新编译后成功解决了这个问题，感谢解答！😀
