### ISSUE TITLE
定积分公式上下限的符号位置

### ISSUE THREAD

**Issue by KaijinWu** [ustctug/ustcthesis#285]
老师，您好。模板编译的定积分公式上下限的位置是
![image](https://user-images.githubusercontent.com/24600548/110440984-3a18a000-80f4-11eb-9408-17e593cdcba0.png)
而实际应该是
![image](https://user-images.githubusercontent.com/24600548/110441087-56b4d800-80f4-11eb-9fb0-a630d0ee4282.png)
请问老师应该怎样修改，辛苦了。

**Comment by KaijinWu** [comment]
好的老师，谢谢。

**Comment by zepinglee** [comment]
v3.3.0 已经支持
```latex
\ustcsetup{
  math-style = TeX,
}
```

也可以单独设置
```latex
\ustcsetup{
  integral        = slanted,
  integral-limits = false,
}
```
