### ISSUE TITLE
图片上下放置时下面的图片颜色变浅

### ISSUE THREAD

**Issue by Jiang-Xian** [ustctug/ustcthesis#289]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 10 
- TeX 发行版：TeX Live 2020
- 模板类型：master

## 描述问题
图片上下放置时，如果有图题，则下面的图的黑色会变浅。如果没有图题，则没有这种问题。

截图：
有图题：
![condition_1](https://user-images.githubusercontent.com/40911220/113554513-04e86a80-962c-11eb-83c3-f0cc24018087.png)

无图题：
![condition_2](https://user-images.githubusercontent.com/40911220/113554520-07e35b00-962c-11eb-91d6-ace4eb11ef78.png)

复现上述问题的代码：
```TeX
\documentclass[degree=master]{ustcthesis}
\begin{document}
\begin{figure}[htb]
	\centering
	\includegraphics[width=0.8\textwidth]{fig1.pdf}
        \caption{样本一增长值}
        \label{sample1}
\end{figure}

\begin{figure}[htb]
	\centering
	\includegraphics[width=0.8\textwidth]{fig2.pdf}
	\caption{样本二增长值}
        \label{sample2}
\end{figure}
\end{document}
```

**Comment by zepinglee** [comment]
感觉也是 xdvipdfmx 处理伪粗的 bug，类似 #192 。

**Comment by Jiang-Xian** [comment]
> 感觉也是 xdvipdfmx 处理伪粗的 bug，类似 #192 。

有用，谢谢大佬。在\includegraphics{xxx}上面加入{\color{white}.}，颜色就正常了。
