### ISSUE TITLE
无法使用\include插入章节

### ISSUE THREAD

**Issue by vonfzm** [ustctug/ustcthesis#290]
## 检查
- [ ] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14
- TeX 发行版：TeX Live 2021
- 模板类型：master 

## 描述问题
把main.tex中的
\input{chapters/intro.tex}
\input{chapters/floats.tex}
\input{chapters/math.tex}
\input{chapters/citations.tex}
中\input改成\include后对应章节就没了。直接把模板的改了一下也是这样。

**Comment by zepinglee** [comment]
8f7ab71 修复了同时使用 `natbib` 和 `chapterbib` 宏包的问题，正确使用方法如下：
1. `natbib` 与 `chapterbib` 的加载顺序不重要。
2. `sectionbib` 参数需要传给 `natbib` 而不是 `chapterbib`（见 `natbib` 文档 2.15 节）。
3. 每章内容需要写到单独的 `.tex` 文件，在主文档中使用 `\include` 调用（不能用 `\input`），不带 `.tex` 后缀。
4. 每章都要使用 `\bibliographystyle` 和 `\bibliography`。
5. 编译时需要用 BibTeX 对每章的 `.aux` 文件进行编译，可以使用 `latexmk` 自动进行全部的编译过程。
