### ISSUE TITLE
新版《撰写手册》（2016 年 12 月版，2019 年 第 3 次印刷）更新

### ISSUE THREAD

**Issue by zepinglee** [ustctug/ustcthesis#291]
研究生院官网最近更新了《撰写手册》，改动的地方记录在这里。

**Comment by vonfzm** [comment]
来了来了！
1. 非涉密但要控制阅读的论文可在封面标注“控阅”。
2. 英文题目一般不应超过150个字母。
3. 摘要字数变多，博士论文中文摘要一般 800～1500个汉字，硕士论文中文摘要一般500～1000个汉字。
4. 摘要部分内容应以偶数页结束，内容不足则加一空白页。
5. 工程博士论文使用“结论与展望”作为结论部分内容的标题。
6. 附 录 格 式 与 正 文 相 同 ，并 依 顺 序 用 大 写 字 母 A，B，C 编 序 号 ，如 附录A，附录B，附录C。只有一个附录时不必编序号，即附录。附录中的图、表、数学表达式、参考文献等另行编序号，与正文分开，一律用阿拉伯数字编码，如图A.1，表B.2，式（C.3）等。
7. “致谢”、“在读期间发表的学术论文”与“取得的其他研究成果”均另面起。如还有其他内容，如个人简历等，可以放在“附录”之后“致谢”之前。
8. 参考文献示例中多了八条英文的（p58，59）。多了论文集和会议录（p60）。多了文献类型和电子文献载体标志代码（p61）
9. 格式示例中的封面校徽终于从丑版的换成了白底蓝花了（但本模版早就是了）

**Comment by zepinglee** [comment]
> 1. 非涉密但要控制阅读的论文可在封面标注“控阅”。
> 2. 英文题目一般不应超过150个字母。
> 3. 摘要字数变多，博士论文中文摘要一般 800～1500个汉字，硕士论文中文摘要一般500～1000个汉字。
> 4. 摘要部分内容应以偶数页结束，内容不足则加一空白页。
> 5. 工程博士论文使用“结论与展望”作为结论部分内容的标题。
> 6. 附 录 格 式 与 正 文 相 同 ，并 依 顺 序 用 大 写 字 母 A，B，C 编 序 号 ，如 附录A，附录B，附录C。只有一个附录时不必编序号，即附录。附录中的图、表、数学表达式、参考文献等另行编序号，与正文分开，一律用阿拉伯数字编码，如图A.1，表B.2，式（C.3）等。
> 7. “致谢”、“在读期间发表的学术论文”与“取得的其他研究成果”均另面起。如还有其他内容，如个人简历等，可以放在“附录”之后“致谢”之前。
> 8. 参考文献示例中多了八条英文的（p58，59）。多了论文集和会议录（p60）。多了文献类型和电子文献载体标志代码（p61）
> 9. 格式示例中的封面校徽终于从丑版的换成了白底蓝花了（但本模版早就是了）

我检查了一下其实不需要修改模板内容。3 和 8 的示例已经更新。9 是 2011 年之前的旧版校徽，然而 Word 模板并没有改。
