### ISSUE TITLE
附录格式问题

### ISSUE THREAD

**Issue by wyixiang** [ustctug/ustcthesis#292]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 10
- TeX 发行版：TeX Live 2020
- 模板类型：master

## 描述问题
1.《研究生学位论文撰写手册》第9页要求
![image](https://user-images.githubusercontent.com/21034627/114704759-8e4d1a80-9d59-11eb-91dc-674f46e97b2c.png)
而模板编译的结果是
![image](https://user-images.githubusercontent.com/21034627/114705798-b7ba7600-9d5a-11eb-942e-8cb0234899a9.png)
仅有一个附录也会编号

2. 《研究生学位论文撰写手册》第94页的附录样例是
![image](https://user-images.githubusercontent.com/21034627/114705136-fbf94680-9d59-11eb-8695-56a5a1a5cc25.png)
而模板编译的结果是
![image](https://user-images.githubusercontent.com/21034627/114705160-03b8eb00-9d5a-11eb-903a-56b1f7e8aa02.png)

模板的页眉也是带有编号的附录标题，但根据《研究生学位论文撰写手册》第90页的目录样例中的“附录”字样和第94页页眉的“附录”字样，推测附录的章名（一级标题）应是不带编号和题目的“附录”。目前我在编译时想要让附录部分的页眉与目录中的附录章节应维持“附录”字样，不添加编号和题名

**Comment by zepinglee** [comment]
> 只有一个附录时不必编号，即附录。

这个其实很不合理。比如标题是“附录”，那么图表编号“A.1”的“A”是怎么来的？而且 `\chapter` 命令必须有个题名参数。所以我不打算在 `\appendix \chapter{Foo}` 实现这个。如果实在有需要可以写
```latex
\appendix
\backmatter
\chapter{附录}
```
这样附录就作为 back matter 的一章。
