### ISSUE TITLE
resizebox 导致表格后的字体变粗

### ISSUE THREAD

**Issue by humaolin** [ustctug/ustcthesis#294]
## 检查
- [ ] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)
resizebox 导致表格后的字体变粗
![image](https://user-images.githubusercontent.com/10299866/115377588-597e0f00-a202-11eb-8813-3dbcd2d53059.png)
![image](https://user-images.githubusercontent.com/10299866/115377754-7fa3af00-a202-11eb-9eb5-7aacfe1f7f5d.png)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2020
- 模板类型：doctor / master / bachelor

## 描述问题
《研究生学位论文撰写手册》第 xx 页要求……而模板编译的结果是……

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{ustcthesis}
\begin{document}
\begin{table*}[htbp]
	\caption{消融实验数据}
	\resizebox{\textwidth}{!}{
		\begin{tabular}{lcccccccccccccc}
			\toprule
			类别与模型     & 飞机 &  凳子 &	\\ 	\bottomrule
			%		\hline
		\end{tabular}
	}
	\label{tab:ablation}
\end{table*}

本模板 \pkg{ustcthesis} 是中国科学技术大学本科生和研究生学位论文的 \LaTeX{}
模板， 按照《\href{http://gradschool.ustc.edu.cn/static/oldsite/ylb/material/xw/wdxz/32.pdf}
{中国科学技术大学研究生学位论文撰写手册}》（以下简称《撰写手册》）和
《\href{https://www.teach.ustc.edu.cn/notice/notice-teaching/11530.html}
\end{document}
```

**Comment by zepinglee** [comment]
见 #251 和 #192 。
