### ISSUE TITLE
I can't remove English title page and English abstract

### ISSUE THREAD

**Issue by Luke9086** [ustctug/ustcthesis#298]
I wanna remove them because it's superfluous.

**Comment by zepinglee** [comment]
1. Remove `\ustc@makeentitle` in `\maketitle`.
https://github.com/ustctug/ustcthesis/blob/b772e306cb644e87187e24c4ed8378ee6b9b3827/ustcthesis.cls#L1846

2. Remove the whole `abstract*` environment.

**Comment by Luke9086** [comment]
It has been solved!
Thanks for your help!
