### ISSUE TITLE
根据学校的要求，可以在封面加入学号字项

### ISSUE THREAD

**Issue by Chernyang** [ustctug/ustcthesis#301]

**Comment by zepinglee** [comment]
有没有官方文件的链接？

**Comment by Chernyang** [comment]
学院教秘发过来的封面要求：
链接：https://rec.ustc.edu.cn/share/413d6f60-ac81-11eb-80a1-df0b680f7df5

**Comment by zepinglee** [comment]
有没有联系方式？需要讨论：

1. 这是你们系的特殊要求还是全校本科生的要求？
2. 学校的视觉形象识别系统对校名的字体有规定，不是这份 Word 文档中的华文行楷。

**Comment by Chernyang** [comment]
教秘说这是去年的格式，可能只是个参考，这是我的QQ: 502551399

**Comment by zepinglee** [comment]
教秘的联系方式

**Comment by Chernyang** [comment]
薛佳老师，计算机学院教秘。
jiaxue@ustc.edu.cn

**Comment by yusanshi** [comment]
@Chernyang 我也是计算机学院，教秘是薛佳老师，但是还没有收到这个封面要求。请问你是在哪里收到的啊，能截图看一下吗？:)

**Comment by Chernyang** [comment]
教秘之前发的邮件，邮件内容如下：
<img width="313" alt="屏幕截图 2021-05-11 145540" src="https://user-images.githubusercontent.com/43635836/117771771-06c7ce00-b269-11eb-9ac5-bbc032529c7d.png">

**Comment by zepinglee** [comment]
我去确认过了，本科生用这个很多横线的封面。我会尝试用 LaTeX 制作这个，但是这个横线的处理很麻烦，如果未完成的话就只能用 Word 封面了。

**Comment by Chernyang** [comment]
老哥，我今天去打印论文，发现那个封面其实是学校默认给定的外皮封面，所以就不需要制作这个了

**Comment by Chernyang** [comment]
我今天去打印论文，发现那个封面其实是学校默认给定的外皮封面，所以就不需要制作这个了

**Comment by zepinglee** [comment]
总算搞定了。

跟 Word 文档对比的效果：
<img width="678" alt="Screen Shot 2021-06-03 at 23 06 21" src="https://user-images.githubusercontent.com/12290822/120667698-52fcdb80-c4c0-11eb-98b0-747b469b353e.png">

**Comment by zepinglee** [comment]
> 我今天去打印论文，发现那个封面其实是学校默认给定的外皮封面，所以就不需要制作这个了

能不能传一份制本厂制作封皮的那个 Word 文档？我再跟你们学院教秘发的文档比对一下

**Comment by Chernyang** [comment]
这个我没有啊，学校直接打印制作的

**Comment by HankerWu** [comment]
overleaf 模板中的 figures 里没有 `ustc-title-page-heading.pdf` 这个文件
