### ISSUE TITLE
v3.3.0版本目前表格使用longtable包，表格上方段落的行间距和表格行间距会消失

### ISSUE THREAD

**Issue by ColdPepsi** [ustctug/ustcthesis#302]
## 检查!
- [x] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 11.3
- TeX 发行版： MacTeX 2021
- 模板类型：master
- 用win10编译情况一样

## 描述问题
表格使用longtable包，表格上方段落的行间距和表格行间距会消失

截图：
![image](https://user-images.githubusercontent.com/43885572/116942569-6855ce80-aca4-11eb-8433-1c18c98f92f7.png)

复现上述问题的代码：
```TeX
\section{三线表}
三线表是《撰写手册》推荐使用的格式，如表~\ref{tab:exampletable}。编制表格应简单明了，表达一致，明晰易懂，表文呼应、内容一致。
排版时表格字号略小，或变换字体，尽量不分页，尽量不跨节。
表格太大需要转页时，需要在续表上方注明“续表”，表头页应重复排出。
{
\small
\begin{longtable}{ccccc}
	\caption{示例表}
	\label{tab:exampletable}\\
	\toprule
	字段名 & 中文含义 & 数据类型 & 是否为空 & 备注 \\
	\midrule
	\endfirsthead %此命令之前为表格首页表头
	\multicolumn{5}{r}{续表}\\
	\toprule
	字段名 & 中文含义 & 数据类型 & 是否为空 & 备注 \\
	\midrule
	\endhead % 以上命令之间表示其他页表头
	\bottomrule
	\multicolumn{5}{c}{（接下页）}\\
	\endfoot % 以上表示除表格最后一页其他页的表尾
	\bottomrule
	\endlastfoot %最后一页的表尾
	示例字段 & 示例字段 & 示例字段 & 否 &示例字段\\
	示例字段 & 示例字段 & 示例字段 & 否 &示例字段\\
\end{longtable}
}


```

**Comment by zepinglee** [comment]
1. 第一段内容需要跟 `{ \small` 之间空一行分段。因为 `\small` 会设置 1.2 倍字号的行距，而行距是段落的属性，所以会破坏第一段原来 20 bp 的 行距。
2. 表格与上方文字的间距也不是完全消失，二是不知为啥比预期要小一些。我测试了一下这个距离跟 `longtable` 默认的字号命令 `\small` 的行距有关，也跟 `\arraystretch` 有关。

标准的 `table` 环境不会有这个问题，感觉跟 `longtable` 的实现有关。

**Comment by ColdPepsi** [comment]
你好，还有一个问题就是表格内的每行行间距会变小

**Comment by coolxxy** [comment]
1. 表格外段落行距过小：并没有手动 `\small` 的必要性，模板中已经处理了表格内字体小于正文的需求，去掉你的代码中的 `\small` 命令，表格外内容会恢复正常。
2. 表格内文字行距过小，似乎是模板的问题，我提了一个不成熟的 PR，期待作者修复。

**Comment by zepinglee** [comment]
研究生《手册》要求正文 12 bp，行距 20 bp，是字号的 5/3 倍。这个行距比较适合中文，但是对于西文来说就偏大了。对于表格的情况，《手册》中没有规定字号和行距，只在 52 页提到字号略小。但考虑到大部分表格是列出数据，默认按照西文的情况处理更合适。所以我在重定义 `\normalsize` 为 `\@setfontsize\normalsize{12bp}{20bp}`时并没有处理 `\small`、`\large` 等命令，保留原来 1.2 倍字号的行距。这样在浮动体和 `longtable` 中默认会使用 `\small`，显得行距相对于字号的比例小于正文。

对于用户来说，如果感觉 table 中 1.2 倍字号的行距不合适，可以在 `table` 内用 `\linespread` 或者 `\arraystretch` 进行调整，也可以用 `\fontsize{}{}\selectfont` 直接指定字号和行距。`longtable` 的情况比较特殊，如果要整体修改字号必须用外部使用命令，比如 `{\footnotesize\beign{longtable}...\end{longtable}}`，但这样会被模板中 `\AtBeginEnvironment{longtable` 的 patch 所覆盖。我打算改成
```latex
\ifdim\f@size pt > 12pt\relax
  \small
\fi
```
这样如果用户已经调整过字号就不会再修改了。

**Comment by coolxxy** [comment]
> 研究生《手册》要求正文 12 bp，行距 20 bp，是字号的 5/3 倍。这个行距比较适合中文，但是对于西文来说就偏大了。对于表格的情况，《手册》中没有规定字号和行距，只在 52 页提到字号略小。但考虑到大部分表格是列出数据，默认按照西文的情况处理更合适。所以我在重定义 `\normalsize` 为 `\@setfontsize\normalsize{12bp}{20bp}`时并没有处理 `\small`、`\large` 等命令，保留原来 1.2 倍字号的行距。这样在浮动体和 `longtable` 中默认会使用 `\small`，显得行距相对于字号的比例小于正文。
> 
> 对于用户来说，如果感觉 table 中 1.2 倍字号的行距不合适，可以在 `table` 内用 `\linespread` 或者 `\arraystretch` 进行调整，也可以用 `\fontsize{}{}\selectfont` 直接指定字号和行距。`longtable` 的情况比较特殊，如果要整体修改字号必须用外部使用命令，比如 `{\footnotesize\beign{longtable}...\end{longtable}}`，但这样会被模板中 `\AtBeginEnvironment{longtable` 的 patch 所覆盖。我打算改成
> 
> ```
> \ifdim\f@size pt > 12pt\relax
>   \small
> \fi
> ```
> 
> 这样如果用户已经调整过字号就不会再修改了。

中文内容的表格，1.2 倍行距确实显得很拥挤，我尝试了下把模板中的修改表格字体的 `\small` 替换成 `\fontsize{10.5bp}{17.5bp}\selectfont` 看起来效果还行。

**Comment by coolxxy** [comment]
这样说来还是你的方式更合理，可以在 `ustcsetup.tex` 提供选项或者提供自定义命令。
我那个 PR 考虑不够成熟，麻烦大佬关闭下，我把代码贴到这里，给用户应急参考下即可：
![image](https://user-images.githubusercontent.com/11879017/117608329-76b65580-b190-11eb-9348-b99100888eb9.png)
