### ISSUE TITLE
在使用`Tikz`宏包时会产生`Incompatible color definition.`警告

### ISSUE THREAD

**Issue by yuxguo** [ustctug/ustcthesis#303]
## 检查
- [✅ ] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [✅ ] 已经将模板升级到了最新版
- [✅ ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [✅ ] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 11.3.1
- TeX 发行版：MacTeX 2019
- 模板类型：bachelor

## 描述问题
在`ustcsetup.tex`中引入画图宏包`Tikz`时会与`\copyrightpage`命令产生`Incompatible color definition.`警告。

## 解决办法
修改`ustcthesis.cls`第411行`\RequirePackage{color}`改为`\RequirePackage{xcolor}`可以消除警告。

**Comment by zepinglee** [comment]
我无法复现你的问题。是 v3.3.0 版本吗？

**Comment by zepinglee** [comment]
刚刚看错。

`xcolor` 的文档解释了原因：
<img width="510" alt="Screen Shot 2021-05-08 at 15 18 55" src="https://user-images.githubusercontent.com/12290822/117530627-bd7d4180-b010-11eb-8c94-e6dd20ef80d5.png">

模板中尽可能减少所依赖的宏包，所以不打算换成 `xcolor`。解决方案是把 `\definecolor` 放到 `\AtBeginDocument` 中，这样推迟会调用 `xcolor` 的 `\definecolor`。
