### ISSUE TITLE
中英文摘要之间怎么添加空白页

### ISSUE THREAD

**Issue by miraclewk** [ustctug/ustcthesis#305]
请问一下中英文摘要之间怎么手动添加空白页

**Comment by zepinglee** [comment]
哪里要求的？

**Comment by miraclewk** [comment]
> 哪里要求的？
中国科学技术大学研究生学位论文撰写手册第16页1.10的第二条

**Comment by zepinglee** [comment]
<img width="702" alt="Screen Shot 2021-05-10 at 20 13 48" src="https://user-images.githubusercontent.com/12290822/117657552-442a4e00-b1cc-11eb-88d2-d5278055c877.png">

“各部分间不必留空白页”

**Comment by miraclewk** [comment]
> <img alt="Screen Shot 2021-05-10 at 20 13 48" width="702" src="https://user-images.githubusercontent.com/12290822/117657552-442a4e00-b1cc-11eb-88d2-d5278055c877.png">
> 
> “各部分间不必留空白页”

各部分不必留空白页应该说的是正文每一章吧。然后第二行括号（英文摘要和目录均另面起）这里的另面我以为是要另页，但如果我想另页起，应该怎么操作

**Comment by zepinglee** [comment]
这里规定了“英文摘要”和“目录”均另面起，所以模板不会作修改。

如果你自己需要另页起，可以用 `\cleardoublepage`。

**Comment by miraclewk** [comment]
> 这里规定了“英文摘要”和“目录”均另面起，所以模板不会作修改。
> 
> 如果你自己需要另页起，可以用 `\cleardoublepage`。

谢谢了，我后续看印刷要求再来看，如果没问题我就按模板的弄
