### ISSUE TITLE
本科毕业论文英文文献期刊名需要斜体

### ISSUE THREAD

**Issue by zheyuanhu01** [ustctug/ustcthesis#306]
## 检查
- [√] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [ √] 已经将模板升级到了最新版
- [√ ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [√ ] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Overleaf
- TeX 发行版：TeX Live 2019
- 模板类型：bachelor

## 描述问题
《关于本科毕业论文（设计）格式和统一封面的通知》最后一页最后一行要求外文期刊名用白斜体，而模板编译的结果是Times New Roman

截图：
![image](https://user-images.githubusercontent.com/51265771/118157718-7eeee900-b44d-11eb-8f08-71f9c9885a9a.png)

复现上述问题的代码：
@article{kukar2003transductive,
  title={Transductive reliability estimation for medical diagnosis},
  author={Kukar, Matja{\v{z}}},
  journal={Artificial Intelligence in Medicine},
  volume={29},
  number={1-2},
  pages={81--106},
  year={2003},
  publisher={Elsevier}
}

感谢学长的辛勤付出，你们辛苦了！

**Comment by zepinglee** [comment]
自己改下 `\bibliographystyle`

**Comment by high-velocity-rotating-pigeon** [comment]
\bibliographystyle 命令似乎不起作用

**Comment by zepinglee** [comment]
`\bibliographystyle{ustcthesis-bachelor}`

**Comment by high-velocity-rotating-pigeon** [comment]
> `\bibliographystyle{ustcthesis-bachelor}`

我使用 TeXstudio  3.0.4, 输入这个命令以后编译,  反馈
This is BibTeX, Version 0.99d (MiKTeX 21.1)
The top-level auxiliary file: main.aux
The style file: ustcthesis-numerical.bst
Illegal, another \bibstyle command---line 169 of file main.aux
 : \bibstyle
 :          {ustcthesis-bachelor}
I'm skipping whatever remains of this command
Database file #1: bib/ustc.bib
(There was 1 error message)
出现错误

并且结果没有变化, 请问问题出在哪里?

**Comment by taoky** [comment]
> > `\bibliographystyle{ustcthesis-bachelor}`
> 
> 我使用 TeXstudio 3.0.4, 输入这个命令以后编译, 反馈
> This is BibTeX, Version 0.99d (MiKTeX 21.1)
> The top-level auxiliary file: main.aux
> The style file: ustcthesis-numerical.bst
> Illegal, another \bibstyle command---line 169 of file main.aux
> : \bibstyle
> : {ustcthesis-bachelor}
> I'm skipping whatever remains of this command
> Database file #1: bib/ustc.bib
> (There was 1 error message)
> 出现错误
> 
> 并且结果没有变化, 请问问题出在哪里?

https://github.com/ustctug/ustcthesis/blob/master/ustcsetup.tex#L57

**Comment by zepinglee** [comment]
标准情况下一份文档只能用一个 `\bibliographystyle`，你把 https://github.com/ustctug/ustcthesis/blob/ae77e5e4cf1d48a5319eb0f825a4c6387c83e118/ustcsetup.tex#L47-L49 注释掉，再反注释 https://github.com/ustctug/ustcthesis/blob/ae77e5e4cf1d48a5319eb0f825a4c6387c83e118/ustcsetup.tex#L55-L57 
然后删掉 `.aux` 文件重新编译。

**Comment by high-velocity-rotating-pigeon** [comment]
我找到问题了, 已解决非常感谢!
