### ISSUE TITLE
当二级节标题上面有图片，图片上面有列表的时候，二级节标题的段前间距过小

### ISSUE THREAD

**Issue by ColdPepsi** [ustctug/ustcthesis#307]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.15
- TeX 发行版：MacTeX 2021
- 模板类型：master

## 描述问题
当二级节标题上面有图片，图片上面有列表的时候，二级节标题的段间距过小

截图：

![image](https://user-images.githubusercontent.com/43885572/119068970-c8c06c00-ba17-11eb-8ba6-fea0c1bd52d7.png)

复现上述问题的代码：
```TeX
\section{插图}

有的同学可能听说“\LaTeX{} 只能使用 eps 格式的图片”，甚至把 jpg 格式转为 eps。
事实上，这种做法已经过时。
而且每次编译时都要要调用外部工具解析 eps，导致降低编译速度。
所以我们推荐矢量图直接使用 pdf 格式，位图使用 jpeg 或 png 格式。

\begin{itemize}
	\item 示例
	\item 示例
\end{itemize}

\begin{figure}[h]
  \centering
  \includegraphics[width=0.3\textwidth]{ustc-badge.pdf}
  \caption{图号、图题置于图的下方}
  \label{fig:badge}
\end{figure}

\subsection{示例标题}
关于图片的并排，推荐使用较新的 \pkg{subcaption} 宏包，
不建议使用 \pkg{subfigure} 或 \pkg{subfig} 等宏包。
```

**Comment by zepinglee** [comment]
图题段后要求 12 bp，二级节标题要求段前 6 bp，LaTeX 的算法是取最大的值，所以这里应该没有问题。

**Comment by ColdPepsi** [comment]
> 图题段后要求 12 bp，二级节标题要求段前 6 bp，LaTeX 的算法是取最大的值，所以这里应该没有问题。

![image](https://user-images.githubusercontent.com/43885572/119128892-d0f4c780-ba68-11eb-8e33-733a3c2b96eb.png)
如果插入图的前面没加空行，段间距就会变大

**Comment by zepinglee** [comment]
> 如果插入图的前面没加空行，段间距就会变大

这我就搞不懂了，一般都是要加空行的。

**Comment by ColdPepsi** [comment]
> > 如果插入图的前面没加空行，段间距就会变大
> 
> 这我就搞不懂了，一般都是要加空行的。
麻烦您再看一下这个问题，表格后的2.2节标题段前间距和2.3相比是不是有点小？

**Comment by ColdPepsi** [comment]
> > 如果插入图的前面没加空行，段间距就会变大
> 
> 这我就搞不懂了，一般都是要加空行的。

麻烦您再看一下这个问题，表格后的2.2标题段前间距是不是比2.3的稍微小点？谢谢
![image](https://user-images.githubusercontent.com/43885572/119212894-f5df4e00-baed-11eb-85c0-d27400e65925.png)

**Comment by qiaowzh** [comment]
这个12如何改呢？下面的代码中只有6啊。
\setlength{\floatsep}{6\bp@}
\setlength{\textfloatsep}{6\bp@}
\setlength{\intextsep}{6\bp@}
\DeclareCaptionLabelSeparator{zhspace}{\hspace{\ccwd}}
\captionsetup{
  format         = hang,
  font           = small,
  labelsep       = zhspace,
  skip           = 6\bp@,
  figureposition = bottom,
  tableposition  = top,
}

**Comment by zepinglee** [comment]
这个图题和 section 标题的距离太复杂，我实在搞不定。

**Comment by zepinglee** [comment]
> 这个12如何改呢？下面的代码中只有6啊。

@qiaowzh 

> 图号、图题置于图的下方，段前 6 磅，段后 12 磅，
表号、表题置于表的上方，段前 6 磅，段后 6 磅，

LaTeX2e kernel 中没法将图、表分开设置，所以只能取 6bp，再设置
https://github.com/ustctug/ustcthesis/blob/35439599a6a46e816d9cbedfc05c0a74cca89941/ustcthesis.cls#L2545-L2547

b772e30 中将这一距离改错了，现已修复。
