### ISSUE TITLE
只有一个附录时不必编号，即附录

### ISSUE THREAD

**Issue by ColdPepsi** [ustctug/ustcthesis#312]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.15
- TeX 发行版：MacTeX 2021
- 模板类型：master

## 描述问题
《研究生学位论文撰写手册》第 8 页要求只有一个附录是不必编号，即附录。而模板编译的结果是附录A
![image](https://user-images.githubusercontent.com/43885572/119365798-e4ab6280-bce2-11eb-9c45-d8eab80f4f24.png)

截图：

![image](https://user-images.githubusercontent.com/43885572/119365847-f12fbb00-bce2-11eb-9265-bf49e1e985b5.png)

**Comment by zepinglee** [comment]
如果附录不编号，那么其中的小节、图、表等都无法编号，所以这个规定其实很蠢。

如果实在需要，可以
```latex
\backmatter
\chapter{附录}
```
