### ISSUE TITLE
问题：有什么比较优雅的办法把摘要、目录、参考文献等放进目录么？

### ISSUE THREAD

**Issue by zhiyuanzhai** [ustctug/ustcthesis#313]
一个纯粹的技术问题。
目前我试过`\addcontentsline`，但是这个命令会自动附加一个bookmark，会和模板本身的bookmark重复。

**Comment by sikouhjw** [comment]
不考虑模板实现的情况下，用 `\ctexset{chapter/numbering=false}` 抑制编号即可。

**Comment by zepinglee** [comment]
参考文献本身是在目录里的，摘要和目录需要分别将其定义中的 `\ustc@chapter` 改为 `\chapter`

**Comment by zhiyuanzhai** [comment]
> 参考文献本身是在目录里的，摘要和目录需要分别将其定义中的 `\ustc@chapter` 改为 `\chapter`。

感谢🙏
另外一点就是，当使用`biblatex`时，需要在`printbibliography`后加参数`heading=bibintoc`才能在目录中加入参考文献一项。这是今天发现的一个可能需要提醒的地方（或者doc里有而我没注意到？）

**Comment by zepinglee** [comment]
> 另外一点就是，当使用`biblatex`时，需要在`printbibliography`后加参数`heading=bibintoc`才能在目录中加入参考文献一项。这是今天发现的一个可能需要提醒的地方（或者doc里有而我没注意到？）

这个问题在 7289bf9 中顺带解决了。
