### ISSUE TITLE
2021-05-08最新硕士论文word模板不一致地方

### ISSUE THREAD

**Issue by FantDing** [ustctug/ustcthesis#314]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 10
- TeX 发行版：TeX Live 2020
- 模板类型：master

## 描述问题
[2021-05-08最新硕士论文word模板](https://gradschool.ustc.edu.cn/column/65)中有几处和仓库代码不一样：
- 最新的word中是“控阅”，不是“保密”
![image](https://user-images.githubusercontent.com/21337200/119448022-5a571300-bd63-11eb-849c-ac8054b74dc8.png)

- word中仍是蓝底的标，本仓库代码是白底的标
![image](https://user-images.githubusercontent.com/21337200/119448073-69d65c00-bd63-11eb-9ebe-e6e3531af103.png)

**Comment by zepinglee** [comment]
1. 没错，我稍后修改下。

2. 白底的是 http://vi.ustc.edu.cn/ 规定的，而蓝底的是旧版的校徽。我之前反馈过这个问题，但 Word 模板还没有更正过来。

**Comment by FantDing** [comment]
> 1. 没错，我稍后修改下。
> 2. 白底的是 http://vi.ustc.edu.cn/ 规定的，而蓝底的是旧版的校徽。我之前反馈过这个问题，但 Word 模板还没有更正过来。

蓝底能搞个选项吗？还是想和word保持一致，大部分人还是用word写的

**Comment by zepinglee** [comment]
> 蓝底能搞个选项吗？还是想和word保持一致，大部分人还是用word写的

不打算。实在需要的话自己找素材然后改 `.cls` 的代码。

**Comment by zepinglee** [comment]
另外 Word 模板封面校名的字体也不同，详见 #174。如果要跟 word 严格一致最好用 word 转成 pdf 再用 `pdfpages` 添加进来。
