### ISSUE TITLE
请教：如何将附录编号改为阿拉伯数字？

### ISSUE THREAD

**Issue by zhiyuanzhai** [ustctug/ustcthesis#317]
虽然这个需求可能有点奇怪，但是敝校模板有此要求，所以来这里问一下。

首先想到的办法是直接修改`\thechapter`命令，也就是在appendix后面直接加一行
```latex
\renewcommand\thechapter{\arabic{chapter}}
```
但是这样只修改了节标题的序号（即从A.1, A.2变成了1.1, 1.2），但是章标题仍旧显示为“附录A”。

然后就想可不可以重新定`appendix`. 按照`classes`文档
```latex
\renewcommand\appendix{\par
  \setcounter{chapter}{0}%
  \setcounter{section}{0}%
  \gdef\@chapapp{\appendixname}%
  \gdef\thechapter{\@arabic\c@chapter}%
}
```
然后直接放在`LoadClass{ctexbook}`之后。但这样的话附录章标题就变成“第1章”这样了。

刚刚入门LaTeX模板的开发，多有不懂的地方，望见教。

**Comment by zepinglee** [comment]
建议用 `ctex` 设置 `appendix/number`，设置这个主要是为了不影响 `\thechapter` 的编号。

`ctex` 重定义了 `\appendix`，所以不建议在 `\LoadClass{ctexbook}` 后再 `\renewcommand\appendix`。

**Comment by zhiyuanzhai** [comment]
感谢解答（抱歉，差点忘了这边还开了个issue）
