### ISSUE TITLE
如何更改论文参考文献的间距，编译出来是1.5倍行距，如何改为单倍行距？

### ISSUE THREAD

**Issue by qiaowzh** [ustctug/ustcthesis#320]
## 检查
- [ ] 已经阅读《研究生学位论文撰写手册》或《关于本科毕业论文（设计）格式和统一封面的通知》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型：doctor / master / bachelor

## 描述问题
《研究生学位论文撰写手册》第 xx 页要求……而模板编译的结果是……

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{ustcthesis}
\begin{document}
abc
\end{document}
```

**Comment by qiaowzh** [comment]
> 哪里的要求？

就是和WORD版相比，参考文献页数有些多，想更改下行距。

**Comment by zepinglee** [comment]
<img width="749" alt="Screen Shot 2021-10-17 at 10 01 21" src="https://user-images.githubusercontent.com/12290822/137607468-a5b9fccd-fd92-4421-9522-0dd84e4e0b8b.png">

研究生院《撰写手册》规定了具体的字号和行距，那应该是 Word 版没按要求执行。

**Comment by qiaowzh** [comment]
好的。谢谢。
