### ISSUE TITLE
顺序编码制-文内标注-英文作者名后的”et al“改为“等”

### ISSUE THREAD

**Issue by Lewis-Liu** [ustctug/ustcthesis#321]
根据学位论文撰写手册P57中的顺序编码制的说明（见图片），需要生成如下形式：
”张教授等[4] “ （[4]为上标）

![顺序编码](https://user-images.githubusercontent.com/5558564/145140785-4be5869b-637b-4980-be99-40bbf7e1ff65.jpg)

目前通过命令 \citet{} 生成的是 et al.， 如何把et al 修改成 撰写手册给出的形式。

另外，在学位论文撰写手册关于顺序编码制的介绍中，只给出了中文文献例子，英文文献的文内引用格式没有给出，所以准备统一使用“等”。

**Comment by zepinglee** [comment]
第 61 页进行了规定。

<img width="726" alt="Screen Shot 2021-12-08 at 11 18 47" src="https://user-images.githubusercontent.com/12290822/145142394-1cbee990-0a55-4f76-adac-91e1d523d4c0.png">

**Comment by Lewis-Liu** [comment]
> 第 61 页进行了规定。
> 
> <img alt="Screen Shot 2021-12-08 at 11 18 47" width="726" src="https://user-images.githubusercontent.com/12290822/145142394-1cbee990-0a55-4f76-adac-91e1d523d4c0.png">

 这是 著作-出版年制 两个文内标注的方法。我目前就是按照2.14.2的方法来标注的。

就是不知道 顺序编码制 能不能混用 著作-出版年制 文内标注的方法。

**Comment by zepinglee** [comment]
> 这是 著作-出版年制 两个文内标注的方法。我目前就是按照2.14.2的方法来标注的。
> 
> 就是不知道 顺序编码制 能不能混用 著作-出版年制 文内标注的方法。

对，我搞混了。

目前模板“顺序编码制”的 `\citet` 效果应该是中文姓名加“ 等”（如“张教授 等”），西文姓名加“et al.”（如“Mittelbach et al.”）。《撰写手册》中没有针对西文姓名给出示例，但我认为加“et al.”也是合理的。一是从上下文方面“et al.”能说得通，其本身就是拉丁语中“and others”的意思，其次可以类比“著者-出版年制”的 `\citet`，姓名也是作为句子的主要成分。当然“Mittelbach 等”在中文的上下文语境也可以，但时我不打算在模板中进行修改。因为有同学使用英文写作在这种情况下会有问题。

如果你需要将西文姓名也改成加“等”，可以自行修改 `ustcthesis-numerical.bst`，需要将
https://github.com/ustctug/ustcthesis/blob/d2cddee6169296b309b0da4f8abf7e65b0422777/ustcthesis-numerical.bst#L158-L163
改为
```bst
FUNCTION {bbl.space}
{ entry.lang lang.zh =
    { "" }
    { " " }
  if$
}
```
这样可以去掉“张教授”与“等”字之间的空格。

然后将
https://github.com/ustctug/ustcthesis/blob/d2cddee6169296b309b0da4f8abf7e65b0422777/ustcthesis-numerical.bst#L190-L195
改为
```bst
FUNCTION {citation.et.al}
{ "等"}
```

**Comment by Lewis-Liu** [comment]
@zepinglee  非常感谢。

**Comment by Lewis-Liu** [comment]
@zepinglee  
我已经将ustcthesis-numerical.bst文件中的两处修改完毕，但是依旧是 et al，没有变成 “等”。 

是否还有其他地方需要修改。

**Comment by sikouhjw** [comment]
> @zepinglee 我已经将ustcthesis-numerical.bst文件中的两处修改完毕，但是依旧是 et al，没有变成 “等”。 使用的是\citet{}命令。
> 
> 是否还有其他地方需要修改。

删除全部辅助文件再编译？

**Comment by Lewis-Liu** [comment]
> > @zepinglee 我已经将ustcthesis-numerical.bst文件中的两处修改完毕，但是依旧是 et al，没有变成 “等”。 使用的是\citet{}命令。
> > 是否还有其他地方需要修改。
> 
> 删除全部辅助文件再编译？

已经删除所有辅助文件。

**Comment by sikouhjw** [comment]
1. 下载最新版
2. 修改 bst
3. `latexmk`

我的编译结果正确，建议你提供 MWE。
![图片](https://user-images.githubusercontent.com/49770925/145159766-3d7187f6-97f5-42bb-bc9a-48d9c651298c.png)

**Comment by Lewis-Liu** [comment]
> 1. 下载最新版
> 2. 修改 bst
> 3. `latexmk`
> 
> 我的编译结果正确，建议你提供 MWE。 ![图片](https://user-images.githubusercontent.com/49770925/145159766-3d7187f6-97f5-42bb-bc9a-48d9c651298c.png)

OK。我再试一试最新版。

还有一点需要说明的是，我使用的是BibLaTeX 宏包，不是 BibTeX + natbib 宏包
% 参考文献使用 BibLaTeX 宏包
\usepackage[style=ustcthesis-numeric]{biblatex}

另外，你给出的截图是编者出版年选项。麻烦再测试下修改顺序编码制的选项，多谢。

**Comment by sikouhjw** [comment]
> 还有一点需要说明的是，我使用的是BibLaTeX 宏包，不是 BibTeX + natbib 宏包
> 
> ```
> % 参考文献使用 BibLaTeX 宏包
> \usepackage[style=ustcthesis-numeric]{biblatex}
> ```

你为什么不早说？

**Comment by zepinglee** [comment]
> 还有一点需要说明的是，我使用的是BibLaTeX 宏包，不是 BibTeX + natbib 宏包
> 
> ```
> % 参考文献使用 BibLaTeX 宏包
> \usepackage[style=ustcthesis-numeric]{biblatex}
> ```

不早说……

自行阅读 `biblatex-gb7714-2015` 的文档。

**Comment by sikouhjw** [comment]
真的是浪费时间啊~不按 ISSUE_TEMPLATE 来的应该无视……

**Comment by Lewis-Liu** [comment]
不好意思，因为没有按模板写问题，耽误大家时间了。
