### ISSUE TITLE
公式字体如何还原成原始的latex默认字体

### ISSUE THREAD

**Issue by ProfKong** [ustctug/ustcthesis#324]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新3.3.1版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型：doctor

## 描述问题
《研究生学位论文撰写手册》第 xx 页要求……而模板编译的结果是……

我在使用你们维护的3.3.1版本的毕业论文模版，发现里面的字体使用了多种选项都没办法还原成latex默认的字体（和花体），好像是因为使用了unicode-math这个包的原因。我想把这段公式

\begin{align}
 &\ddot{\delta\chi}_k + 3H\dot{\delta\chi}_k + \frac{k^2}{a^2} \delta \chi _ k = \frac{\sqrt{2\epsilon_{\chi}}}{M_{\rm Pl}} \big[ \ddot{\phi}\delta\phi_k + \mathcal{S}_k \big],
\label{EoMQchi}\\
 &\ddot{\delta\phi}_k + 3H\dot{\delta\phi}_k + \left( \frac{k^2}{a^2} - \mathcal{M}_{\rm eff}^2 \right) \delta\phi_k = 0 ~,
\label{EoMQphi}
\end{align}

实现成如截图的字体效果，

请问应该如何修改模版？

截图：
![粘贴的图形-1](https://user-images.githubusercontent.com/26546259/148966648-23581c87-8fb4-44ae-b421-5d503f400084.png)

**Comment by ProfKong** [comment]
你好，谢谢解答。我尝试使用原来 Type 1 cm 字体，`\ustcsetup{math-font = cm}`，但是显示无效值，请问该如何解决？

<img width="1440" alt="iShot2022-01-12 00 31 38" src="https://user-images.githubusercontent.com/26546259/148982848-3a8ef7bc-4847-4760-be88-32f88325b4a8.png">

另外这样修改能恢复原来的积分号和偏微分号成为默认的斜体吗？

**Comment by zepinglee** [comment]
> 你好，谢谢解答。我尝试使用原来 Type 1 cm 字体，`\ustcsetup{math-font = cm}`，但是显示无效值，请问该如何解决？

我写错了，应该是 `\ustcsetup{math-font = none}`，感觉这里改成 `cm` 更好一些。

> 另外这样修改能恢复原来的积分号和偏微分号成为默认的斜体吗？

对，cm 只有斜体。其他 opentype math 字体可以设置 `math-style = TeX`。

**Comment by ProfKong** [comment]
你好，我改成了`\ustcsetup{math-font = none}`后有其他的报错，如截图所示
<img width="1440" alt="iShot2022-01-12 01 10 36" src="https://user-images.githubusercontent.com/26546259/148989415-106ed2e4-2bd9-4f43-b811-2f1152f57ed9.png">

**Comment by zepinglee** [comment]
这是因为 `math-font = none` 的原意是在数学字体方面不作任何配置，但是示例中使用了 `unicode-math` 的一些命令，所以会产生报错。

如果要让示例文档运行起来，需要额外进行以下配置：
```latex
\usepackage{amssymb}
\usepackage{bm}
\let\increment\Delta
\let\uppi\pi
\let\symup\mathrm
\let\symbf\bm
\let\symbfsf\mathsf
```

我稍后修改一下模板，新增选项 `math-font = cm`，会包含以上配置。

**Comment by ProfKong** [comment]
非常感谢！幸苦了。其实我觉得《手册》里面要求的西文字体是 Times New Roman 应该只对正文适用，公式使用 Computer Morden应该没有问题，因为如果要求公式的西文部分也是 Times New Roman 配置的话，也只是大致接近，并不是完全符合

**Comment by zepinglee** [comment]
> 非常感谢！幸苦了。其实我觉得《手册》里面要求的西文字体是 Times New Roman 应该只对正文适用，公式使用 Computer Morden应该没有问题，因为如果要求公式的西文部分也是 Times New Roman 配置的话，也只是大致接近，并不是完全符合

严格来说是的。但是但是 cm math 主要问题主要在于它的字形比 Times 细很多。可能在以中文为主要语言的论文中不是很明显（因为正文的中文字体通常比 Times 要细一些），但是在英文论文中，或者公示跟文字混合的情况下，就会显得不搭配。比如上面提到的例子。
<img alt="Screen Shot 2022-01-11 at 23 36 27" width="437" src="https://user-images.githubusercontent.com/12290822/148973105-4eb8723f-13f9-430b-a11d-9fe73975811c.png">
一眼看过去 “iff.” 和 "and" 仿佛加粗了一样。

**Comment by ProfKong** [comment]
请问
`\usepackage{amssymb}
\usepackage{bm}
\let\increment\Delta
\let\uppi\pi
\let\symup\mathrm
\let\symbf\bm
\let\symbfsf\mathsf`
这一段是要加在哪个文件的

**Comment by zepinglee** [comment]
8748832 直接设置
```latex
  math-style         = TeX,
  math-font          = cm,
```

**Comment by ProfKong** [comment]
> [8748832](https://github.com/ustctug/ustcthesis/commit/874883287e5bce8777ca749e095b3d6deaac1310) 只需要设置
> 
> ```
>   math-style         = TeX,
>   math-font          = cm,
> ```
> 
> 就可以了。

你好，我用原模版这么设置之后还是报错，

![iShot2022-01-12 21 18 49](https://user-images.githubusercontent.com/26546259/149148121-cfc476c6-ce12-474b-a1f5-7d00a31668b3.png)

请问可以上传一下你说的这个修改后可以编译 `math-font = cm` 这个选项的模版吗

> 这是因为 `math-font = none` 的原意是在数学字体方面不作任何配置，但是示例中使用了 `unicode-math` 的一些命令，所以会产生报错。
> 
> 如果要让示例文档运行起来，需要额外进行以下配置：
> 
> ```
> \usepackage{amssymb}
> \usepackage{bm}
> \let\increment\Delta
> \let\uppi\pi
> \let\symup\mathrm
> \let\symbf\bm
> \let\symbfsf\mathsf
> ```
> 
> 我稍后修改一下模板，新增选项 `math-font = cm`，会包含以上配置。

**Comment by sikouhjw** [comment]
> > [8748832](https://github.com/ustctug/ustcthesis/commit/874883287e5bce8777ca749e095b3d6deaac1310) 只需要设置
> > ```
> >   math-style         = TeX,
> >   math-font          = cm,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 就可以了。
> 
> 你好，我用原模版这么设置之后还是报错，
> 
> ![iShot2022-01-12 21 18 49](https://user-images.githubusercontent.com/26546259/149148121-cfc476c6-ce12-474b-a1f5-7d00a31668b3.png)
> 
> 请问可以上传一下你说的这个修改后可以编译 `math-font = cm` 这个选项的模版吗
> 
> > 这是因为 `math-font = none` 的原意是在数学字体方面不作任何配置，但是示例中使用了 `unicode-math` 的一些命令，所以会产生报错。
> > 如果要让示例文档运行起来，需要额外进行以下配置：
> > ```
> > \usepackage{amssymb}
> > \usepackage{bm}
> > \let\increment\Delta
> > \let\uppi\pi
> > \let\symup\mathrm
> > \let\symbf\bm
> > \let\symbfsf\mathsf
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 我稍后修改一下模板，新增选项 `math-font = cm`，会包含以上配置。

你没用过 github 吗？https://github.com/ustctug/ustcthesis/commit/874883287e5bce8777ca749e095b3d6deaac1310 已经是修改后的 cls，下载不就好了？

**Comment by ProfKong** [comment]
> 

对不起，我不太会用，给你们添麻烦，打扰了。我下完那个文件之后已经编译成功，但好像对 `\mathscr` 这样的符号还没兼容。

**Comment by sikouhjw** [comment]
> > 
> 
> 对不起，我不太会用，给你们添麻烦，打扰了。我下完那个文件之后已经编译成功，但好像对 `\mathscr` 这样的符号还没兼容。

1. 『对数学字体不作任何配置』本身就没有做任何事
2. 你用 `article` 写 `\mathscr` 也需要加载 `mathrsfs` 宏包
3. 所以 `unicode-math` 为什么好用呢，因为不用操心符号问题
