### ISSUE TITLE
【建议】将ustcthesis开头的style文件移到某一文件内

### ISSUE THREAD

**Issue by ymmshi** [ustctug/ustcthesis#326]
然后在latexmkrc文件中指定 style 路径即可，这样看上去更清晰

$ENV{'TEXINPUTS'}='./ustcthesis//:' . $ENV{'TEXINPUTS'}; 
$ENV{'BSTINPUTS'}='./ustcthesis//:' . $ENV{'BSTINPUTS'};

**Comment by zepinglee** [comment]
这样的话其他编辑器/IDE 需要额外配置才能编译。目前项目使用扁平式的结构主要是为了保证用户能够直接编译出示例。

**Comment by ymmshi** [comment]
了解，这个 issue 就留给大家做个参考吧
