### ISSUE TITLE
文内引用文献样式问题

### ISSUE THREAD

**Issue by ProfKong** [ustctug/ustcthesis#327]
## 检查
- [是] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [是] 已经将模板升级到了最新版
- [是] 已经阅读使用说明文档 `ustcthesis.pdf`
- [是] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 12.2.1
- TeX 发行版：Texpad
- 模板类型：doctor

## 描述问题
我根据《ustcthesisdoc》的提示，在ustcsetup里面添加了 cite-style = inline，想实现文内引用文献形式为“文献[1]”这样的与正文平排格式，但是出来的效果还是上标样式，请问是怎么回事？另外的问题是 cite-style = inline 是控制我选用的 ustcthesis-numerical.bst 的哪个函数？

截图：

<img width="1956" alt="image" src="https://user-images.githubusercontent.com/26546259/156779357-c73d88a9-6680-4fa9-bc84-5656b8a40d9d.png">

复现上述问题的代码：
```TeX
\ustcsetup{ cite-style = inline, }

\usepackage[sort]{natbib}
\bibliographystyle{ustcthesis-numerical}

```

**Comment by zepinglee** [comment]
我能复现这个问题。似乎是在 `\begin{document}` 前设置 `cite-style = inline` 无效，在之后设置才有效果。

**Comment by zepinglee** [comment]
这个问题是因为设置 `cite-style` 时还未载入 `natbib` 宏包，所以没有进行正确的配置。试一下 [`cite-style`](https://github.com/ustctug/ustcthesis/tree/cite-style) 分支的 9c467a8 有没有解决问题。

> 另外的问题是 cite-style = inline 是控制我选用的 ustcthesis-numerical.bst 的哪个函数？

`cite-style` 是调用 LaTeX 宏进行配置，并没有控制 `.bst` 的函数。具体地说，载入 `natbib` 后，`\ustcsetup{cite-style = inline}` 会调用 `\citestyle{inline}`，而 `\citestyle` 会调用模板中定义的 `\bibstyle@inline`，其内容为 `\bibpunct{[}{]}{,}{n}{,}{,}`。这是 `natbib` 控制引用样式的方法。

**Comment by ProfKong** [comment]
问题完美解决了，非常感谢！
