### ISSUE TITLE
宏包版本检测

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#33]
目前的模板实际上对某些宏包的版本是有要求的，最重要的一个要求就是ctex版本大于2.0。模板中是否需要写一段代码检测ctex的版本号，以保证这一条件被满足？

主要是考虑到一些Windows用户会使用[CTeX套装](http://www.ctex.org/CTeXDownload)（最新版是2012），而且有些人不懂得更新且不看说明文档。。。

参考：http://tex.stackexchange.com/a/13309

**Comment by zepinglee** [comment]
这些都会写在使用说明里，另外这句
```
\LoadClass[a4paper, UTF8, zihao=-4]{ctexbook}[2015/06/19]
```
已经可以保证满足 ctex 2.0+了，你的意思是输出额外的报错信息？

**Comment by seisman** [comment]
你可以做个测试，比如把`[2015/06/19]`改成`[2015/08/20]`，给出的警告如下，而这个警告会淹没在LaTeX的一大堆输出中，基本不可能看到：
~~~
LaTeX Warning: You have requested, on input line 56, version                     
               `2015/08/20' of document class ctexbook,                          
               but only version                                                  
               `2015/07/01 v2.2 Chinese adapter for class book (CTEX)'           
               is available.
~~~

**Comment by zepinglee** [comment]
原来输出的是warning不是error啊……那我改成强行中断报error

**Comment by seisman** [comment]
main.pdf中的第一章是不是得写一写如何在Windows、Linux和Mac下构建一个LaTeX环境。

**Comment by zepinglee** [comment]
我觉得应该写进 ustcthesis.pdf 的附录里，做为新手指南
