### ISSUE TITLE
正文中的四级标题编号

### ISSUE THREAD

**Issue by Lewis-Liu** [ustctug/ustcthesis#330]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统： Windows 10 
- TeX 发行版：TeX Live 2020
- 模板类型：doctor

## 描述问题
在正文中使用\subsubsection{四级标题}生成四级标题时，生成的编号是 **1. **  的形式，而非 **1.1.1.1** 的形式。

如何在正文中生成形如**1.1.1.1** 的四级标题编号？

截图：
![Snipaste_2022-03-19_17-38-35](https://user-images.githubusercontent.com/5558564/159115963-9f73dc3b-c03a-45a2-a75e-3dd05596d0e1.jpg)

**Comment by zepinglee** [comment]
《手册》中没有规定四级标题的格式，模板中的默认设置主要是参考了 Word 模板：
<img width="647" alt="Screen Shot 2022-03-19 at 18 00 15" src="https://user-images.githubusercontent.com/12290822/159116618-6cc56fb8-4533-47c4-922d-d0766d412378.png">

如果你需要修改，可以使用 `\ctexset` 设置 `paragraph/number`，参考 `ctex` 的文档。

**Comment by Lewis-Liu** [comment]
好的，多谢。
