### ISSUE TITLE
2021 年 11 月新版本科毕业论文格式问题

### ISSUE THREAD

**Issue by Adven00** [ustctug/ustcthesis#332]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 10
- TeX 发行版：TeX Live 2021
- 模板类型：bachelor

## 描述问题
按 [中国科学技术大学本科毕业论文（设计）格式](https://www.teach.ustc.edu.cn/?attachment_id=13867) 中附带的模板，英文摘要的标题为大写的ABSTRACT（小二Times New Roman），和本模板的格式不一致。

## 截图
![QQ截图20220322230010](https://user-images.githubusercontent.com/55445154/159512320-2e2f757e-bbab-4597-8222-3424b6461c3a.png)

**Comment by zepinglee** [comment]
确实，这个是 2021 年 11 月新版的改动。

不过由于 GitHub 的 Internal Server Error，我暂时无法 push 上去。

**Comment by Adven00** [comment]
非常感谢学长这么晚还在处理issue。我又对照了一下新版格式，和当前模板还有几处不同

1. 中英文摘要的关键词都用顿号隔开。
2. 英文参考文献的期刊名用白斜体。
3. 致谢的最后附有日期。

**Comment by zepinglee** [comment]
> 1. 中英文摘要的关键词都用顿号隔开。

这个不符合英文的用法，英文中没有顿号。不妨给教务处反馈一下？

> 2. 英文参考文献的期刊名用白斜体。

需要手动将这里切换为本科生的 bibstyle，然后编译出来就是白斜体了。
https://github.com/ustctug/ustcthesis/blob/6e7abb15cd183f4097fee9732f871af358423406/ustcsetup.tex#L48-L59
<img width="681" alt="Screen Shot 2022-03-23 at 17 43 18" src="https://user-images.githubusercontent.com/12290822/159670261-46eb873d-3834-424c-a3d5-95a69fe52d14.png">

> 3. 致谢的最后附有日期。

这个可以加。

**Comment by Adven00** [comment]
我已经向教务处反馈，再次感谢您的工作。

**Comment by zepinglee** [comment]
刚刚顺便发现了另外几个问题，希望也一同反馈给教务处。可以 cc 给我一份邮件 <zepinglee@gmail.com>。

1. 关键词的正确用法是"Keywords"不是“Key Words”。
<img width="685" alt="Screen Shot 2022-03-23 at 19 49 18" src="https://user-images.githubusercontent.com/12290822/159692752-1f8d7388-3eb0-49ec-8d60-d457c3003a59.png">
 
2. 参考文献的英文应使用 Times New Roman 而不是中易宋体。
<img width="686" alt="Screen Shot 2022-03-23 at 19 51 03" src="https://user-images.githubusercontent.com/12290822/159693056-ad3a53f1-a94a-4bea-82b7-db4ddc3c3080.png">

3. 第 3 条参考文献的出版地“Washington”不是书名的组成部分，不应用斜体。
4. 第 4 条参考文献的姓名“Hutson JM”后应使用句点，跟上文保持一致。
5. 第 4 条文献跟第 1 条都是期刊论文，建议统一显示或隐藏标题。
6. 第 4 条参考文献的页码“4237”前应使用冒号，跟第 1 条期刊文章保持一致。

**Comment by zepinglee** [comment]
可能教务处需要一些时间，我先 merge 到 master 并 release 一个版本吧。

**Comment by Adven00** [comment]
教务处已经回复了。关于
> 关键词的正确用法是"Keywords"不是“Key Words”。

这一条，他们认为两种用法都不算错，为了和研究生院保持一致就不做改动了。其余改动应该会尽快同步到教务处网站上。
