### ISSUE TITLE
已解决

### ISSUE THREAD

**Issue by MeLee95** [ustctug/ustcthesis#333]

**Comment by zepinglee** [comment]
前段时间略忙没空打理这边的 issue。

我无法复现你的问题。

```
\documentclass[degree=doctor]{ustcthesis}
% degree      = doctor | master | bachelor
% degree-type = academic | professional
% language    = chinese | english
% fontset     = windows | mac | ubuntu | fandol

% 加载宏包、全部的配置
\input{ustcsetup.tex}


\begin{document}

\chapter{简介 123 和 abc}
\section{简介 123 和 abc}
\subsection{简介 123 和 abc}
\subsubsection{简介 123 和 abc}

\end{document}
```
<img width="727" alt="Screen Shot 2022-04-03 at 19 53 55" src="https://user-images.githubusercontent.com/12290822/161426706-8fec8e9d-cc90-4653-81ea-e6027520e001.png">

**Comment by zepinglee** [comment]
另外建议不要删掉原来 issue 的内容，并且在关掉前给出问题的解决方案。这样可以为后人留存知识，类似的 bug 不会再上演。

**Comment by sikouhjw** [comment]
> 另外大佬打扰您了，不好意思，不过正好还有个小问题问您

不相关的问题尽量单独提问。

> 就是我用的是overleaf的模板来写的，我想知道怎么设置能够取消参考文献中url和doi的输出，毕竟一条条删太麻烦了。

参考《参考文献的如何去掉editor、DOI和url》[^1]。

如果你一定要修改，用 `bibtex` 时，参考 `texdoc gbt7714`，修改你使用的 bst 文件，将其中的 `show.url` 和 `show.doi` 改为 `#0`。

用 `biblatex` 时，参考 `texdoc biblatex-gb7714-2015`，在导言区加载 `biblatex` 宏包时添加 `url=false, doi=false` 选项。

[^1]: https://github.com/ustctug/ustcthesis/issues/262
