### ISSUE TITLE
如何在“中国科学技术大学学位论文授权使用声明”页面添加文字

### ISSUE THREAD

**Issue by LinG955** [ustctug/ustcthesis#334]
## 检查
- [X] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [X] 已经将模板升级到了最新版
- [X] 已经阅读使用说明文档 `ustcthesis.pdf`
- [X] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 10
- TeX 发行版：TeX Live 2019
- 模板类型：master

## 描述问题
怎么在“中国科学技术大学学位论文授权使用声明”页面添加文字？只找到生成该页面的命令行“\copyrightpage”，没找到可编辑的源文件

截图：
![image-20220407161112407](https://user-images.githubusercontent.com/36889092/162152396-d6988b12-04a8-40cc-9366-4e0cfbf2ced2.png)

**Comment by sikouhjw** [comment]
https://github.com/ustctug/ustcthesis/blob/e498ea8e1ac8834d4da2290bb07c53b59bcdf33f/ustcthesis.cls#L2054-L2086

这段代码加到导言区，最后的间距自己调

```tex
\makeatletter
 \renewcommand\copyrightpage{% 
   \begin{titlepage}% 
     \ustc@pdfbookmark{原创性和授权使用声明}% 
     \null 
     \vskip 0.3cm% 
     {\centering\sffamily\fontsize{16bp}{32bp}\selectfont 
       中国科学技术大学学位论文原创性声明\par}% 
     \vskip 0.7cm% 
     \ustc@originality\par 
     \vskip 1.3cm% 
     作者签名：\ustc@underline{}\hspace{2.7cm}% 
     签字日期：\ustc@underline{}\par 
     \vskip 1.9cm% 
     {\centering\sffamily\fontsize{16bp}{32bp}\selectfont 
       中国科学技术大学学位论文授权使用声明\par}% 
     \vskip 0.7cm% 
     \ustc@authorization\par 
     \vskip 0.6cm% 
     \ifx\ustc@secret@level\@empty 
       \ustc@checkbox{} 公开\quad 
       $\square$ 控阅（\ustc@underline[0.85cm]{}年）\par 
     \else 
       $\square$ 公开\quad 
       \ustc@checkbox{} 控阅（\ustc@underline[0.8cm]{\ustc@secret@year}年）\par 
     \fi 
     \vskip 0.5cm% 
     作者签名：\ustc@underline{}\hspace{2.7cm}% 
     导师签名：\ustc@underline{}\par 
     \vskip 0.5cm% 
     签字日期：\ustc@underline{}\hspace{2.7cm}% 
     签字日期：\ustc@underline{}\par 
     \vskip 0.5cm% 
     评审专家签名：\ustc@underline{}\hspace{2.7cm}% 
     评审专家签名：\ustc@underline{}\par 
   \end{titlepage}% 
 } 
\makeatother
```

**Comment by LinG955** [comment]
> https://github.com/ustctug/ustcthesis/blob/e498ea8e1ac8834d4da2290bb07c53b59bcdf33f/ustcthesis.cls#L2054-L2086
> 
> 这段代码加到导言区，最后的间距自己调
> 
> ```
> \makeatletter
>  \renewcommand\copyrightpage{% 
>    \begin{titlepage}% 
>      \ustc@pdfbookmark{原创性和授权使用声明}% 
>      \null 
>      \vskip 0.3cm% 
>      {\centering\sffamily\fontsize{16bp}{32bp}\selectfont 
>        中国科学技术大学学位论文原创性声明\par}% 
>      \vskip 0.7cm% 
>      \ustc@originality\par 
>      \vskip 1.3cm% 
>      作者签名：\ustc@underline{}\hspace{2.7cm}% 
>      签字日期：\ustc@underline{}\par 
>      \vskip 1.9cm% 
>      {\centering\sffamily\fontsize{16bp}{32bp}\selectfont 
>        中国科学技术大学学位论文授权使用声明\par}% 
>      \vskip 0.7cm% 
>      \ustc@authorization\par 
>      \vskip 0.6cm% 
>      \ifx\ustc@secret@level\@empty 
>        \ustc@checkbox{} 公开\quad 
>        $\square$ 控阅（\ustc@underline[0.85cm]{}年）\par 
>      \else 
>        $\square$ 公开\quad 
>        \ustc@checkbox{} 控阅（\ustc@underline[0.8cm]{\ustc@secret@year}年）\par 
>      \fi 
>      \vskip 0.5cm% 
>      作者签名：\ustc@underline{}\hspace{2.7cm}% 
>      导师签名：\ustc@underline{}\par 
>      \vskip 0.5cm% 
>      签字日期：\ustc@underline{}\hspace{2.7cm}% 
>      签字日期：\ustc@underline{}\par 
>      \vskip 0.5cm% 
>      评审专家签名：\ustc@underline{}\hspace{2.7cm}% 
>      评审专家签名：\ustc@underline{}\par 
>    \end{titlepage}% 
>  } 
> \makeatother
> ```

非常感谢！

**Comment by sikouhjw** [comment]
从你提供的截图看，这里更使用用表格去实现。

**Comment by zepinglee** [comment]
@LinG955 这是哪个学院？我可以在模板中针对学院设置。

另外能不能传一份右边的文档？我测量一下具体位置。

**Comment by LinG955** [comment]
> @LinG955 这是哪个学院？我可以在模板中针对学院设置。
> 
> 另外能不能传一份右边的文档？我测量一下具体位置。

@zepinglee 国家同步辐射实验室。文档中新增的文字，感觉位置比较随意，没有对齐。你们可以适当调整，影响不大
[中国科学技术大学学位论文原创性声明.docx](https://github.com/ustctug/ustcthesis/files/8448099/default.docx)

**Comment by zepinglee** [comment]
> 国家同步辐射实验室。

@LinG955 似乎只能用封面填写的「学科专业」用于判断。国家同步辐射实验室相关的学科专业都有哪些？

**Comment by LinG955** [comment]
硕士：核科学与技术，以及物理学、光学工程、化学、材料科学与工程、能源动力（专硕）。
博士：核科学与技术，以及能源动力（工程博士）。


核科学与技术的人数相对比较多



---原始邮件---
发件人: "Zeping ***@***.***&gt;
发送时间: 2022年4月8日(周五) 中午11:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ustctug/ustcthesis] 如何在“中国科学技术大学学位论文授权使用声明”页面添加文字 (Issue #334)




  
国家同步辐射实验室。
  
@LinG955 似乎只能用封面填写的「学科专业」用于判断。国家同步辐射实验室相关的学科专业都有哪些？

**Comment by zepinglee** [comment]
> 硕士：核科学与技术，以及物理学、光学工程、化学、材料科学与工程、能源动力（专硕）。 博士：核科学与技术，以及能源动力（工程博士）。 核科学与技术的人数相对比较多

感觉还是不太方便判断是否用同步辐射实验室的格式。

我提议加个选项 `reviewer = true/false`，默认为 `false`，如果设为 `true` 则显示「评审专家签名」。

**Comment by LinG955** [comment]
我觉得这个提议可以，「评审专家签名」可能其他学院也会用到。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zeping ***@***.***&gt;; 
发送时间: 2022年4月8日(星期五) 中午12:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ustctug/ustcthesis] 如何在“中国科学技术大学学位论文授权使用声明”页面添加文字 (Issue #334)





  
硕士：核科学与技术，以及物理学、光学工程、化学、材料科学与工程、能源动力（专硕）。 博士：核科学与技术，以及能源动力（工程博士）。 核科学与技术的人数相对比较多
  
感觉还是不太方便判断是否用同步辐射实验室的格式。
 
我提议加个选项 reviewer = true/false，默认为 false，如果设为 true 则显示「评审专家签名」。

**Comment by LinG955** [comment]
没问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zeping ***@***.***&gt;; 
发送时间: 2022年4月8日(星期五) 晚上8:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ustctug/ustcthesis] 如何在“中国科学技术大学学位论文授权使用声明”页面添加文字 (Issue #334)





 
@LinG955 试一下 issue#334 有没有问题。

**Comment by zepinglee** [comment]
OK，我 merge 进 master 了。

**Comment by LinG955** [comment]
感谢！辛苦了！



---原始邮件---
发件人: "Zeping ***@***.***&gt;
发送时间: 2022年4月8日(周五) 晚上9:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ustctug/ustcthesis] 如何在“中国科学技术大学学位论文授权使用声明”页面添加文字 (Issue #334)




 
OK，我 merge 进 master 了。
