### ISSUE TITLE
好奇为什么ctan里面没有ustcthesis

### ISSUE THREAD

**Issue by Wongboo** [ustctug/ustcthesis#336]
非bug，使用
```
tlmgr list | grep University  | grep thesis 
```
可以看到
```
i pkuthss: LaTeX template for dissertations in Peking University
i thuthesis: Thesis template for Tsinghua University
i njustthesis: Thesis template for the Nanjing University of Science and Technology
i bjfuthesis: A thesis class for Beijing Forestry University
i buctthesis: Beijing University of Chemical Technology Thesis Template
i cquthesis: LaTeX Thesis Template for Chongqing University
i fduthesis: LaTeX thesis template for Fudan University
i hustthesis: Unofficial thesis template for Huazhong University
i sduthesis: Thesis Template of Shandong University
i shtthesis: An unofficial LaTeX thesis template for ShanghaiTech University
```
无ustcthesis

**Comment by Wongboo** [comment]
如果加入了，应该也可以方便区分自己写的部分和模版部分（就我本人而言，这些都在同一个文件夹下，模版更新时还有所不便）

**Comment by sikouhjw** [comment]
因为『学位论文没必要传到 ctan 上』[^1]，而且传到 ctan 里，版本管理相对比较麻烦，比如提问的时候不容易说清是哪个版本。

[^1]: https://github.com/whutug/whu-thesis/issues/29#issuecomment-807941722

> 如果加入了，应该也可以方便区分自己写的部分和模版部分（就我本人而言，这些都在同一个文件夹下，模版更新时还有所不便）

你可以建一个文件夹放你自己的写的部分，再 `\input` 进去。

**Comment by Wongboo** [comment]
> 因为『学位论文没必要传到 ctan 上』[1](#user-content-fn-1-96483035343d5803847488d694ce5f25)，而且传到 ctan 里，版本管理相对比较麻烦，比如提问的时候不容易说清是哪个版本。
> 
> > 如果加入了，应该也可以方便区分自己写的部分和模版部分（就我本人而言，这些都在同一个文件夹下，模版更新时还有所不便）
> 
> 你可以建一个文件夹放你自己的写的部分，再 `\input` 进去。
> 
> ## Footnotes
> 1. [docstrip 化与 LaTeX3 化 whutug/whu-thesis#29 (comment)](https://github.com/whutug/whu-thesis/issues/29#issuecomment-807941722) [↩](#user-content-fnref-1-96483035343d5803847488d694ce5f25)

版本问题，可以在issue template中让提出者运行
```
tlmgr info njuthesis
```
暂时还没看懂他写的原因

**Comment by sikouhjw** [comment]
你对使用者的要求太高了，用 latex 的一半以上不懂命令行。

**Comment by zepinglee** [comment]
1. tlmgr 更新很不方便。比如 TeX Live 2022 发布后，安装在本地的 TeX Live 2021 就无法更新宏包了。这意味着 TeX Live 发行版中的模板大概率是过时的。thuthesis 的 issue 中有很多 bug 是用户在编译时调用了发行版中的旧版模板导致的。
2. 严格地讲，校徽的版权属于学校，不能上传到 CTAN 上。
