### ISSUE TITLE
ubuntu编译时设置fontset=windows时的报错

### ISSUE THREAD

**Issue by sheng208** [ustctug/ustcthesis#337]
![tex](https://user-images.githubusercontent.com/101086344/162941743-2706f1ce-66b1-4c5b-af61-94c5bac73d46.png)

**Comment by sikouhjw** [comment]
ubuntu 没有这个字体，请使用模板配置好的、适合 ubuntu 的字体选项，比如 `font=xits`。

**Comment by sheng208** [comment]
阅读ustcthesis-doc字体设置一节时，里面说windows字体可能更符合《撰写守则》，所以尝试fontset=windows；默认是auto自动配置，font=xits是如何设置呢？

**Comment by sheng208** [comment]
有没有可能把相应winfonts字体移到ubuntu而使tex支持该字体

**Comment by sheng208** [comment]
我试着将windows下的三种字体Times New Roman, Courier, Arial移动到ubuntu的~/.fonts目录下；然后在fontset=windows情况下可以成功make；这种情况是否可行？和真正在windows系统下的字体支持是否一致？

**Comment by zepinglee** [comment]
> 我试着将windows下的三种字体Times New Roman, Courier, Arial移动到ubuntu的~/.fonts目录下；然后在fontset=windows情况下可以成功make；这种情况是否可行？和真正在windows系统下的字体支持是否一致？

是的。
