### ISSUE TITLE
Overleaf 本科毕设模板 缺失 figure/ustc-title-page-heading.pdf 

### ISSUE THREAD

**Issue by jzyustc** [ustctug/ustcthesis#340]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Overleaf
- TeX 发行版：TeX Live 2020
- 模板类型： bachelor

## 描述问题

学士学位论文模板封面编译需要 figure/ustc-title-page-heading.pdf  文件，但当前 overleaf 模板中缺失该文件。

截图：
![image](https://user-images.githubusercontent.com/66950072/163913504-4d6d42b3-4e52-404e-b124-defb00a1d80a.png)

复现上述问题的代码：
```TeX
\documentclass[degree=bachelor]{ustcthesis}
\begin{document}
abc
\end{document}
```

**Comment by zepinglee** [comment]
我在下个版本上传 overleaf 时补上这个吧。
