### ISSUE TITLE
argmax问题

### ISSUE THREAD

**Issue by Wongboo** [ustctug/ustcthesis#341]
非模版问题，类似讨论可见https://tex.stackexchange.com/questions/5223/command-for-argmin-or-argmax
可能的打法如下：
- \arg\max: ![formula](https://render.githubusercontent.com/render/math?math=\arg\max)
- \arg\\!\max: ![formula](https://render.githubusercontent.com/render/math?math=\arg%5C!\max)
二者有细微差异，前者会多一个微小的空格（markdown中貌似显示更小），但我暂未查阅到GB/T 3102.11—1993《物理科学和技术中使用的数学符号》对argmax书写方式的规定，不知应该采用哪一种。
当然，还是希望模版也可以多此符号的支持

**Comment by zepinglee** [comment]
模板只处理《撰写手册》中规定的符号。这是因为数学符号太多，模板中不能完全覆盖。而且有的符号在不同学科中使用习惯不同，所以最好给用户更多的灵活性，不宜在模板中统一定义。

至于 argmax，我个人的经验是高票答案中的 `arg\,max` 更常见一些。

**Comment by Wongboo** [comment]
也就是说撰写手册里没有规定`argmax`写法是吧

**Comment by zepinglee** [comment]
> 也就是说撰写手册里没有规定`argmax`写法是吧

没有相关规定。
