### ISSUE TITLE
kpathsea:make_tex: Invalid filename `FandolKai-Regular/OT:script=hani;language=dflt;', contains ':'

### ISSUE THREAD

**Issue by Maktiny** [ustctug/ustcthesis#342]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统： Ubuntu 20.04 
- TeX 发行版：TeX Live 2019
- 模板类型：master

## 描述问题
latexmk -xelatex main.tex
Latexmk: This is Latexmk, John Collins, 26 Dec. 2019, version: 4.67.
Latexmk: applying rule 'xelatex'...
Rule 'xelatex': The following rules & subrules became out-of-date:
      'xelatex'
------------
Run number 1 of rule 'xelatex'
------------
------------
Running 'xelatex -file-line-error -halt-on-error -interaction=nonstopmode -no-pdf -synctex=1 -no-pdf -recorder  "main.tex"'
------------
This is XeTeX, Version 3.14159265-2.6-0.999991 (TeX Live 2019/Debian) (preloaded format=xelatex)
 restricted \write18 enabled.
entering extended mode
(./main.tex
LaTeX2e <2020-02-02> patch level 2
L3 programming layer <2020-02-14> (./ustcthesis.cls
Document Class: ustcthesis 2022/03/25 {v3.3.2} USTC thesis template
(/usr/share/texlive/texmf-dist/tex/generic/iftex/iftex.sty)
(/usr/share/texlive/texmf-dist/tex/generic/kvdefinekeys/kvdefinekeys.sty)
(/usr/share/texlive/texmf-dist/tex/generic/kvsetkeys/kvsetkeys.sty)
(/usr/share/texlive/texmf-dist/tex/latex/kvoptions/kvoptions.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/keyval.sty)
(/usr/share/texlive/texmf-dist/tex/generic/ltxcmds/ltxcmds.sty))
(/usr/share/texlive/texmf-dist/tex/latex/ctex/ctexbook.cls
(/usr/share/texlive/texmf-dist/tex/latex/l3kernel/expl3.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3backend/l3backend-xdvipdfmx.def))
Document Class: ctexbook 2019/05/29 v2.4.16 Chinese adapter for class book (CTE
X)
(/usr/share/texlive/texmf-dist/tex/latex/l3packages/xparse/xparse.sty)
(/usr/share/texlive/texmf-dist/tex/latex/l3packages/l3keys2e/l3keys2e.sty)
(/usr/share/texlive/texmf-dist/tex/latex/ctex/ctexhook.sty)
(/usr/share/texlive/texmf-dist/tex/latex/ctex/ctexpatch.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/fix-cm.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/ts1enc.def))
(/usr/share/texlive/texmf-dist/tex/latex/ms/everysel.sty)
(/usr/share/texlive/texmf-dist/tex/latex/ctex/config/ctexopts.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/base/book.cls
Document Class: book 2019/12/20 v1.4l Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/bk12.clo))
(/usr/share/texlive/texmf-dist/tex/latex/ctex/engine/ctex-engine-xetex.def
(/usr/share/texlive/texmf-dist/tex/xelatex/xecjk/xeCJK.sty
(/usr/share/texlive/texmf-dist/tex/latex/l3packages/xtemplate/xtemplate.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.sty
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec-xetex.sty
(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty)
(/usr/share/texlive/texmf-dist/tex/latex/fontspec/fontspec.cfg)))
(/usr/share/texlive/texmf-dist/tex/xelatex/xecjk/xeCJK.cfg))
(/usr/share/texlive/texmf-dist/tex/xelatex/xecjk/xeCJKfntef.sty
(/usr/share/texlive/texmf-dist/tex/generic/ulem/ulem.sty)))
(/usr/share/texlive/texmf-dist/tex/latex/zhnumber/zhnumber.sty
(/usr/share/texlive/texmf-dist/tex/latex/zhnumber/zhnumber-utf8.cfg))
(/usr/share/texlive/texmf-dist/tex/latex/ctex/scheme/ctex-scheme-plain-book.def
) (/usr/share/texlive/texmf-dist/tex/latex/ctex/ctex-cs4size.clo))
(/usr/share/texlive/texmf-dist/tex/latex/ctex/config/ctex.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/etoolbox/etoolbox.sty)
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsmath.sty
For additional information on amsmath, use the `?' option.
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amstext.sty
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsgen.sty))
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsbsy.sty)
(/usr/share/texlive/texmf-dist/tex/latex/amsmath/amsopn.sty))
(/usr/share/texlive/texmf-dist/tex/latex/geometry/geometry.sty
(/usr/share/texlive/texmf-dist/tex/generic/iftex/ifvtex.sty))
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphicx.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/graphics.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics/trig.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/graphics.cfg)
(/usr/share/texlive/texmf-dist/tex/latex/graphics-def/xetex.def)))
(/usr/share/texlive/texmf-dist/tex/latex/fancyhdr/fancyhdr.sty)
(/usr/share/texlive/texmf-dist/tex/latex/graphics/color.sty
(/usr/share/texlive/texmf-dist/tex/latex/graphics-cfg/color.cfg))
(/usr/share/texlive/texmf-dist/tex/latex/titlesec/titletoc.sty)
(/usr/share/texlive/texmf-dist/tex/latex/caption/caption.sty
(/usr/share/texlive/texmf-dist/tex/latex/caption/caption3.sty))
(/usr/share/texlive/texmf-dist/tex/latex/footmisc/footmisc.sty)
(/usr/share/texlive/texmf-dist/tex/latex/url/url.sty)
(/usr/share/texlive/texmf-dist/tex/latex/notoccite/notoccite.sty)
(/usr/share/texlive/texmf-dist/tex/latex/multirow/multirow.sty)
(/usr/share/texlive/texmf-dist/tex/latex/filehook/filehook.sty)kpathsea:make_tex: Invalid filename `FandolKai-Regular/OT:script=hani;language=dflt;', contains ':'
kpathsea:make_tex: Invalid filename `FandolKai-Regular/B/OT:script=hani;language=dflt;', contains ':'
)
(./ustcsetup.tex
(/usr/share/texlive/texmf-dist/tex/latex/unicode-math/unicode-math.sty
(/usr/share/texlive/texmf-dist/tex/latex/unicode-math/unicode-math-xetex.sty
(/usr/share/texlive/texmf-dist/tex/latex/unicode-math/unicode-math-table.tex)))
kpathsea:make_tex: Invalid filename `[XITSMath-Regular', contains '['
kpathsea:make_tex: Invalid filename `[xits-math.otf]/OT', contains '['

./ustcsetup.tex:26: Package fontspec Error: The font "xits-math" cannot be foun
d.

For immediate help type H <return>.
 ...                                              
                                                  
l.26 }
      
No pages of output.
Transcript written on main.log.
=== TeX engine is 'XeTeX'
Latexmk: Log file says no output from latex
Latexmk: For rule 'xelatex', no output was made
Latexmk: Errors, so I did not complete making targets
Collected error summary (may duplicate other messages):
  xelatex: Command for 'xelatex' gave return code 1
      Refer to 'main.log' for details
Latexmk: Use the -f option to force complete processing,
 unless error was exceeding maximum runs, or warnings treated as errors.
make: *** [Makefile:23：main.pdf] 错误 12

复现上述问题的代码：
直接make就报错

**Comment by zepinglee** [comment]
似乎是没装 fandol 和 xits 字体？通常可以 `tlmgr install fandol xits`，不过 Debian 打包的 texlive 可能不太一样。

**Comment by Maktiny** [comment]
> 似乎是没装 fandol 和 xits 字体？通常可以 `tlmgr install fandol xits`，不过 Debian 打包的 texlive 可能不太一样。
非常感谢，已解决

**Comment by Maktiny** [comment]
> 似乎是没装 fandol 和 xits 字体？通常可以 `tlmgr install fandol xits`，不过 Debian 打包的 texlive 可能不太一样。
非常感谢，已解决
