### ISSUE TITLE
Overleaf cannot compile v3.3.1 and v3.3.2 bachelor template properly

### ISSUE THREAD

**Issue by thisiszy** [ustctug/ustcthesis#344]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Overleaf
- TeX 发行版：TeX Live 2021
- 模板类型：bachelor

## 描述问题
1. 无法正确在overleaf上编译bachelor模版，master和doctor正常。具体情况表现为字体和格式错误，缺少学校校徽。见下图。
2. 问题仅仅出现在最新的两个版本中（v3.3.1, v3.3.2），v3.3.0正常

![image](https://user-images.githubusercontent.com/43633145/164888935-16c96c2c-c9c8-4822-8466-a3d9feaeba5c.png)

**Comment by zepinglee** [comment]
1. 目前的 overleaf 版缺少校名 [`figures/ustc-title-page-heading.pdf`](https://github.com/ustctug/ustcthesis/blob/master/figures/ustc-title-page-heading.pdf) 导致编译不通过，见 #340。将会在下个版本上传 overleaf 时修复。暂时先自行上传 GitHub 上对应的 pdf 文件吧。

2. 本科生的封面是制本厂提供的，没有校徽，见 #301。
