### ISSUE TITLE
degree=bachelor 时，出现多个 Overfull \vbox 和 Overfull \hbox 警告

### ISSUE THREAD

**Issue by ipython3** [ustctug/ustcthesis#345]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Overleaf / macOS 12.3.1
- TeX 发行版：MacTeX 2022
- 模板类型：bachelor

## 描述问题

将 degree=doctor 修改为 degree=bachelor后，在 Overleaf 上，通过手动上传 ustc-title-page-heading.pdf，解决了找不到此文件的问题。但是在 \copyrightpage 处出现多个 Overfull \vbox 和 Overfull \hbox 警告。

截图：
<img width="609" alt="截屏2022-05-01 14 56 49" src="https://user-images.githubusercontent.com/31297905/166135885-0c5b0e1c-ccd2-4506-9dba-6540934422d2.png">

我尝试在本地做（macOS 12.3.1，MacTeX 2022），依然有同样的问题。

我看到说明文档中提到，\copyrightpage 命令的作用是生成声明页面，其中的内容根据 secret-level 和 secretyear 的内容自动填写。考虑到要写的文章完全不涉及到保密，我直接去除了这条 \copyrightpage 命令。但是 Overfull 警告依然存在，报错的位置也下移到了另一条指令：

<img width="508" alt="截屏2022-05-01 14 58 47" src="https://user-images.githubusercontent.com/31297905/166136074-f27d35b2-d04d-4a50-96a4-a59ce66d8925.png">

那么问题应该并不在 \copyrightpage 和声明页面上。我搜索了一下关于这个 Overfull 警告的资料，查到的基本都是和表格相关的讨论。例如：
[Removing an "Overfull \vbox" message caused by a nested table](https://tex.stackexchange.com/questions/99679/removing-an-overfull-vbox-message-caused-by-a-nested-table)

然而在源代码中，我并没有在 \copyrightpage 附近看到和表格有关的代码。由于对 Latex 了解有限，走到这步也就不知道该怎么解决这个问题了。

我肉眼没有观察到最终生成的 pdf 文件中有什么错误，但是 Overfull 总令人感觉好像有东西被“挤”出来了😂。不知道这个问题有没有可能被定位和解决呢？

复现上述问题的代码：将 degree=doctor 修改为 degree=bachelor。

**Comment by zepinglee** [comment]
这个是封面的警告，由于 LaTeX 机制问题警告在下一行。

开启 draft 选项后可以看到，overfull box 都是封面的这个表格导致的。

<img width="621" alt="Screen Shot 2022-05-01 at 19 37 03" src="https://user-images.githubusercontent.com/12290822/166144159-e746baba-d0bb-403d-8fed-5bbee5f248cf.png">

本科生的封面在 #301 中改成了现在的样式，基于 `tabular` 实现的，而且为了标题能自动换行还使用了很多 dirty tricks，所以改起来比较麻烦。建议如果在视觉上没有问题的话就忽略警告吧。

https://github.com/ustctug/ustcthesis/blob/df62a2627f42556ab421700577e3b90af3947189/ustcthesis.cls#L1976-L2013

**Comment by ipython3** [comment]
理解了，那我先忽略这几个警告😂。
很感谢您的耐心回复！

**Comment by zepinglee** [comment]
当然，如果你愿意修这几个警告的话也欢迎 PR。

**Comment by zepinglee** [comment]
2bd5e6b 中使用了 `\multicolumn` 的方法消除了封面的警告。@ipython3 试一下你的论文封面还会不会有警告？

**Comment by ipython3** [comment]
我在本地试了一下，没有警告了，很爽😂。
非常感谢您的维护！
