### ISSUE TITLE
参考文献中，article类型的参考文献题目无法显示

### ISSUE THREAD

**Issue by zqc-cs** [ustctug/ustcthesis#346]
## 检查
- 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- 已经将模板升级到了最新版
- 已经阅读使用说明文档 `ustcthesis.pdf`
- 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14
- TeX 发行版：TeX Live 2021
- 模板类型：bachelor

## 描述问题
  如题，使用xelatex编译.doc文件，发现参考文献类型为article时题目无法显示

截图：
<img width="376" alt="截屏2022-05-03 上午4 26 27" src="https://user-images.githubusercontent.com/56622096/166321441-75727682-7b02-4e8a-ae64-7516ce82c23d.png">
<img width="442" alt="截屏2022-05-03 上午4 26 37" src="https://user-images.githubusercontent.com/56622096/166321537-a3dd74f9-f9d1-46c7-bab0-0c2ad66cf9cb.png">

复现上述问题的代码：
```TeX
@article{knuth84,
  author     = {Donald E. Knuth},
  title      = {Literate Programming},
  journal    = {The Computer Journal},
  year       = {1984},
  number     = {2},
  volume     = {27},
  pages      = {97--111},
}
```

**Comment by zqc-cs** [comment]
*编译模板main.tex时

**Comment by zepinglee** [comment]
2021 年 11 月及更早版本的《[中国科学技术大学本科毕业论文（设计）格式](https://www.teach.ustc.edu.cn/?attachment_id=13867)》的参考文献示例就是不显示期刊文章标题的，而且这种格式也存在于像 Physics Review Letters 这样的期刊，并非 bug。
<img width="673" alt="Screen Shot 2022-05-03 at 10 12 22" src="https://user-images.githubusercontent.com/12290822/166395353-31b1e6df-7a1b-4efd-bd40-dd41a43a615c.png">

不过本科生教务处在 2022 年 3 月进行了更新（<https://www.teach.ustc.edu.cn/?attachment_id=13867>），我最近再修改一下吧。

<img width="625" alt="Screen Shot 2022-05-03 at 10 16 44" src="https://user-images.githubusercontent.com/12290822/166395589-28d4f155-9634-4506-ba8b-b8340fba36b6.png">

**Comment by zepinglee** [comment]
这个新版的参考文献格式还是很混乱，感觉是从一个样式中找了两篇中文文献，又从另一个样式找了英文文献，其实格式完全不统一。

1. 外文期刊名没有按照前文的要求使用斜体。
2. 两篇英文文献标题后的“[J]”并非标题的组成部分，而是参考文献国标 GB/T 7714—2015 特有的文献类型标识，而两篇中文文献却没有相应的标识，
3. 中文文献的出版年在期刊名或者出版者后，而英文文献的出版年紧跟着作者姓名。

@Adven00 上次跟教务处沟通时是哪个老师回复你的？我再去沟通一下。

**Comment by Adven00** [comment]
@zepinglee 教务处的沐林老师mll@ustc.edu.cn

**Comment by zepinglee** [comment]
回复说“具体请请教导师”。感觉就是教务处不管这个，具体的格式要求也并不严格。

我打算加上英文期刊的标题，就不再修改其他格式了。

**Comment by zepinglee** [comment]
@zqc-cs 试一下 81fdf45 的效果怎样？

**Comment by zqc-cs** [comment]
@zepinglee 不好意思，这段时间没上Github。新的修改效果不错，但是对于某些arXiv参考文献，论文题目虽然能显示，但显示为白斜体。

代码如下：
@article{Shortcuts,
  author = {{Eddie Schoute} and {Laura Mancinska} and {Tanvirul Islam} and {Iordanis Kerenidis} and {Stephanie Wehner}},
  title = {Shortcuts to quantum network routing},
  year = {2016},
  eprint = {arXiv:1610.05238}
}

文献显示如下：
<img width="521" alt="截屏2022-05-12 上午4 48 36" src="https://user-images.githubusercontent.com/56622096/167945213-f6af69aa-87ed-4f18-ad8a-19ddc6f46986.png">

**Comment by zepinglee** [comment]
见 <https://github.com/ustctug/ustcthesis/issues/353#issuecomment-1123354980>。我稍后合并进 master。

另外姓名不要使用大括号。教务处给的示例就是缩写的形式。
<img width="636" alt="Screen Shot 2022-05-12 at 13 08 20" src="https://user-images.githubusercontent.com/12290822/167996280-2780c3f7-ad54-4fc0-b54e-f5356f12ca88.png">
