### ISSUE TITLE
关于论文类型改为本科生论文后校徽无法显示的问题

### ISSUE THREAD

**Issue by zqc-cs** [ustctug/ustcthesis#347]
## 检查
- 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- 已经将模板升级到了最新版
- 已经阅读使用说明文档 `ustcthesis.pdf`
- 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14
- TeX 发行版：TeX Live 2021
- 模板类型：bachelor

## 描述问题
在模板的main.tex文件中修改论文类型为本科生论文：
<img width="431" alt="截屏2022-05-03 下午2 18 10" src="https://user-images.githubusercontent.com/56622096/166411642-87b7b328-27f1-424c-adc5-6ea35b2e4596.png">
编译后封面显示如下：
<img width="557" alt="截屏2022-05-03 下午2 19 04" src="https://user-images.githubusercontent.com/56622096/166411708-8973c4e2-7ce7-49d1-870f-17140a41a90b.png">
校徽图片等不能正常显示。

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=bachelor]{ustcthesis}
```

**Comment by zepinglee** [comment]
#301

**Comment by Wongboo** [comment]
> #340

这似乎是两个问题，校徽对应的是`figures/ustc-badge.pdf`而非`figures/ustc-title-page-heading.pdf`。我的文档中二者皆存在，但校徽仍不显示

**Comment by zepinglee** [comment]
> > #340
> 
> 这似乎是两个问题，校徽对应的是`figures/ustc-badge.pdf`而非`figures/ustc-title-page-heading.pdf`。我的文档中二者皆存在，但校徽仍不显示

写错了，应该是 #301。本科生的封面本来就没有校徽。
