### ISSUE TITLE
关于数学公式引用格式的规范

### ISSUE THREAD

**Issue by AllanZyne** [ustctug/ustcthesis#348]
《撰写手册》好像没有写明数学公式的引用格式，比如是“式1.1”，还是“式(1.1)”，还是“式（1.1）”。加半角括号似乎是通常的写法，并且 LaTeX 的 `amsmath` 包有专门的数学公式引用命令 `\eqref` 可以在公式的编号两边加上括号。

这点可以在说明文档里补充一个示例吗？

**Comment by zepinglee** [comment]
我觉得在市里文档中添加 `\eqref` 的用法即可，说明文档中页需要吗？

**Comment by AllanZyne** [comment]
哦，是的，在示例文档里加最好了。

顺便很想建议在“量和单位“里补充几个简单而常用的例子，比如像 1s、1.66×10^-27 kg、0.333 μm 这种可以立即模仿使用的情况。

**Comment by zepinglee** [comment]
你可以添加示例发个 PR 吗？

**Comment by AllanZyne** [comment]
好的
