### ISSUE TITLE
使用本科生参考文献格式，如果是期刊，就不显示文章题目

### ISSUE THREAD

**Issue by ddkkpp** [ustctug/ustcthesis#350]
## 检查
- [ ] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Overleaf
- TeX 发行版：TeX Live 2021
- 模板类型： bachelor

## 描述问题
《研究生学位论文撰写手册》第 xx 页要求……而模板编译的结果是……

截图：

复现上述问题的代码：
\usepackage[sort]{natbib}
\bibliographystyle{ustcthesis-bachelor}

![image](https://user-images.githubusercontent.com/57699856/167277987-1c4df90f-16bc-4b00-af73-493d5f0ea6a1.png)

**Comment by zepinglee** [comment]
同 #346。

你试一下 [issues#346](https://github.com/ustctug/ustcthesis/tree/issue%23346) 分支的 6b0d40b 可以吗？

**Comment by zepinglee** [comment]
> [issues#346](https://github.com/ustctug/ustcthesis/tree/issue%23346) 分支的 [6b0d40b](https://github.com/ustctug/ustcthesis/commit/6b0d40bd5be902695fa7958fe1c554923f350ecf) 可以解决，但是会议名前面的“in：”可以去掉吗，修改哪里可以呢

本科生其实没有规定具体的格式，问教务处回复“咨询导师”（<https://github.com/ustctug/ustcthesis/issues/346#issuecomment-1118425260>）。

那我改得再朴素一些去掉“In:”吧。

**Comment by zepinglee** [comment]
@ddkkpp 试一下 e1a2700 的效果可以吗？

**Comment by ddkkpp** [comment]
> @ddkkpp 试一下 [ea3ea7b](https://github.com/ustctug/ustcthesis/commit/ea3ea7b7142b1c9922b7e0a9af6a953e58cf9a69) 的效果可以吗？

解决了，感谢，辛苦了。
