### ISSUE TITLE
本科生毕业论文关键词分隔符可能存在问题

### ISSUE THREAD

**Issue by RubyOcelot** [ustctug/ustcthesis#354]
根据最新 《[中国科学技术大学本科毕业论文（设计）格式](https://www.teach.ustc.edu.cn/?attachment_id=13867)》 的要求和示例，中文关键词应为顿号分隔，英文关键词应为逗号分隔。而 overleaf 模板当前最新版里中英文关键词都是分号分隔。

**Comment by zepinglee** [comment]
确实，这是 2021 年 11 月版新增的格式要求，需要修改一下。
