### ISSUE TITLE
本科生参考文献排版缺失文章名

### ISSUE THREAD

**Issue by sheng208** [ustctug/ustcthesis#355]
![citation](https://user-images.githubusercontent.com/101086344/168575519-2b818ada-567e-4d9e-a4d4-b45e39d80d08.png)

**Comment by sheng208** [comment]
按ustc.bib关于本科生论文参考文献格式写bib，但编译后无法正常显示英文文章名

**Comment by zepinglee** [comment]
试一下 master 分支的最新版？

**Comment by sheng208** [comment]
我是用的release v3.3.2；这版不是最新的吗？

**Comment by zepinglee** [comment]
> 我是用的release v3.3.2；这版不是最新的吗？

参考文献格式是最近修改的（见 #346），尚未发布。

**Comment by sheng208** [comment]
ok，这个问题解决了，非常感谢！
