### ISSUE TITLE
Docker 镜像疑似有问题，Github Actions 检查失败

### ISSUE THREAD

**Issue by richardlee159** [ustctug/ustcthesis#357]
[模版未经任何修改](https://github.com/richardlee159/test)，Github Actions 检查失败，但是本地 make test 成功，疑似是镜像 tunathu/thuthesis-test-env 更新导致。

**Comment by zepinglee** [comment]
```
Running l3build with target "check" with configuration test/config-biblatex
Running checks on
  biblatex-authoryear (1/4)
  biblatex-bachelor (2/4)
          --> failed

  biblatex-inline (3/4)
          --> failed

  biblatex-numeric (4/4)
          --> failed


  Check failed with difference files
  - ./build/test-test/config-biblatex/biblatex-bachelor.xetex.diff
  - ./build/test-test/config-biblatex/biblatex-inline.xetex.diff
  - ./build/test-test/config-biblatex/biblatex-numeric.xetex.diff
```

这个应该是上游 `biblatex-gb7714-2015` 的更新导致的。

**Comment by Kasper4649** [comment]
<img width="884" alt="2023-08-05 17 03 48@2x" src="https://github.com/ustctug/ustcthesis/assets/30112685/3e864953-4118-4e46-a53b-e4fa04593c2e">
看起来好像又挂掉了🤔️

**Comment by zepinglee** [comment]
@Kasper4649 这个应该是上游 `caption` 宏包的变动导致的。

不过 `caption` 最近变动较多，可以先不急着更新 regression test 的 log 文件。
