### ISSUE TITLE
模版在MacOS编译PDF一、二级标题问题

### ISSUE THREAD

**Issue by m13673737851** [ustctug/ustcthesis#358]
经测试，在MacOS编译生成的PDF文件中文章一二级标题内容无法正常复制（复制到记事本中显仅能显示编号 无标题内容）

导致在查重过程中算法无法捕捉标题内容，继而不能识别章节（会将参考文献等本不应该计入查重的内容算入）

**Comment by zepinglee** [comment]
同 <https://github.com/tuna/thuthesis/issues/787>，应该是 `xdvipdfmx` 的 bug。

可以尝试使用 TeX Live 2021 或者 Windows 的字体。

**Comment by m13673737851** [comment]
进一步请教，手动添加Windows字体的方法是？

**Comment by zepinglee** [comment]
> 进一步请教，手动添加Windows字体的方法是？

一种方法是将 Windows 的几个中文字体 SimSun, Simhei, Fangsong, Kaiti 拷贝、安装到 mac 系统，然后在模板中设置 `fontset = windows`。另一方法是如果安装了 mac 版 microsoft word 的话，按照下面的方法调用 word 的字体。

https://github.com/tuna/thuthesis/blob/6f59c86178e08cbc95146a3e5d987552fddfda9b/thuthesis.dtx#L2579-L2598

**Comment by m13673737851** [comment]
已经根据后者方法在cls中补充，编译后问题仍然存在；
修改\documentclass[degree=bachelor,fontset=mac-word]{hfutthesis}后报错为：
` Class hfutthesis Error: Invalid value "fontset = mac-word".`

**Comment by m13673737851** [comment]
根据第一个方法，已解决问题，感谢帮助。

**Comment by zepinglee** [comment]
完整的修改见 <https://github.com/tuna/thuthesis/commit/dd4ae257c46720e7a772f6571889a979cd8cedae>。THU 进行修改主要是因为学校对中易宋体要求得比较严格，ustcthesis 也需要修改吗？

**Comment by m13673737851** [comment]
好的，我尝试再做反馈。
