### ISSUE TITLE
中文问号编译显示不是宋体

### ISSUE THREAD

**Issue by ProfKong** [ustctug/ustcthesis#359]
## 检查
- [ - ] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [ - ] 已经将模板升级到了最新版
- [ - ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [ - ] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 12.4
- TeX 发行版：Texpad 1.9.9
- 模板类型：doctor

## 描述问题

编译中文问号显示的不是宋体

截图：
![iShot_2022-05-26_12 51 56](https://user-images.githubusercontent.com/26546259/170419386-cb0a0d1f-82c6-4686-a449-637b6708bf10.jpg)

**Comment by zepinglee** [comment]
复现上述问题的代码？

**Comment by tanukihee** [comment]
是宋体，但不是中易宋体

**Comment by ProfKong** [comment]
> 

代码就是正文环境的“平坦？”

**Comment by taoky** [comment]
因为 宋体-简 的问号就长这样：

<img width="875" alt="image" src="https://user-images.githubusercontent.com/2109893/170808501-4f48f2b2-cede-4826-8b1a-b847c78aac38.png">

如果要和 Windows 的字体效果一致的话，需要修改 fontset（<https://github.com/ustctug/ustcthesis/blob/master/main.tex#L9>），并且把 Windows 中的相关字体复制过来，或者干脆直接在 Windows 下编译最终提交的版本。
