### ISSUE TITLE
建议增加单页打印选项

### ISSUE THREAD

**Issue by Adven00** [ustctug/ustcthesis#360]
## 检查
- [-] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [-] 已经将模板升级到了最新版
- [-] 已经阅读使用说明文档 `ustcthesis.pdf`
- [-] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

最近去打印论文，发现制本厂默认本科生论文是单面打印的。而模板的 print 选项是双面打印，会出现带页码的空白页；electronic 选项虽然是单面但超链接带有颜色。目前我是设置成 electronic 再修改 ustcthesis.cls 的设置。

https://github.com/ustctug/ustcthesis/blob/052eeee6b4bcfe5f76c681fb060f757f5e3268b7/ustcthesis.cls#L3123-L3131

希望能增加一个单面打印的选项。

**Comment by zepinglee** [comment]
刚刚在 [052eeee](https://github.com/ustctug/ustcthesis/commit/052eeee6b4bcfe5f76c681fb060f757f5e3268b7) 中去掉了空白页的页码，并且去掉了 `\mainmatter` 的 `\cleardoublepage`，应该符合要求。

不建议使用单面打印的 `onepage` 选项，这可能导致第 1 页的目录在左侧，所以保留了 `\tableofcontents` 的 `\cleardoublepage`。
https://github.com/ustctug/ustcthesis/blob/052eeee6b4bcfe5f76c681fb060f757f5e3268b7/ustcthesis.cls#L2395-L2399

**Comment by Adven00** [comment]
问题解决了，非常感谢
