### ISSUE TITLE
为什么使用algorithm2e宏包时，位置选择H时没有间距？只有选择htb时有间距。

### ISSUE THREAD

**Issue by woshigerunze** [ustctug/ustcthesis#361]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14
- TeX 发行版：MacTeX 2019
- 模板类型：master

## 描述问题
《研究生学位论文撰写手册》第 xx 页要求……而模板编译的结果是……

截图：
<img width="824" alt="image" src="https://user-images.githubusercontent.com/34369385/177960602-9da37098-59dc-4960-b75d-161f9ffe779a.png">
![Uploading image.png…]()

复现上述问题的代码：
```
\begin{algorithm}[H]
  \small
  \SetAlgoLined
  \KwData{订阅者网络信息SubscriberNetInfo，发布者自身网络信息PublisherNetInfo}
  \KwResult{自适应通信连接地址，connectURL}

  \caption{创建算法}
  \label{create}
\end{algorithm}
```

**Comment by zepinglee** [comment]
浮动体与正文的间距非常复杂，而 `[H]` 又是另外一套机制。我建议不要使用 `[H]`。
