### ISSUE TITLE
\centernot 斜线位置问题

### ISSUE THREAD

**Issue by SirNing** [ustctug/ustcthesis#362]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 11
- TeX 发行版：TeXLive 2021
- 模板类型：doctor

## 描述问题
\centernot 的斜线出现在被否定符号的前面，而不是被否定符号上

截图：
![image](https://user-images.githubusercontent.com/13313201/179334294-9cd2bb9b-73c8-4271-93ea-2863f9cbb74e.png)

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{ustcthesis}
\begin{document}
$0.5 \centernot \in \mathbb{Z}$ \\
$\mathbb{Q} \centernot \subset \mathbb{Z}$ \\
$1 \centernot = 0.5$ \\
$1 \neq 0.5$
\end{document}
```

**Comment by xkwxdyy** [comment]
```latex
\documentclass[degree=doctor]{ustcthesis}
\begin{document}
$0.5 \notin \mathbb{Z}$

$\mathbb{Q} \nsubset \mathbb{Z}$

$1 \neq 0.5$
\end{document}
```
<img width="263" alt="image" src="https://user-images.githubusercontent.com/87134063/179337727-a19b4323-7be7-43d0-9627-e059fd48b031.png">

**Comment by zepinglee** [comment]
模板中使用了 `unicode-math` 宏包，直接使用 `\not \in`，没必要使用 `centernot`。
