### ISSUE TITLE
word版本校名 ustc_text_logo更新了

### ISSUE THREAD

**Issue by Wangwhr** [ustctug/ustcthesis#367]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 描述问题
2022年5月22日的模板https://gradschool.ustc.edu.cn/column/65 的logo是
![image](https://user-images.githubusercontent.com/32191719/223724775-1b605689-c3cd-46d3-8f2e-221786df5263.png)

而latex模板里的是
![image](https://user-images.githubusercontent.com/32191719/223724947-93c0c9dd-1e84-48b5-9986-94dcee8f8d05.png)

**Comment by zepinglee** [comment]
跟研究生院的老师讨论过，latex 模板用第二个 logo。
