### ISSUE TITLE
请问一下为什么切换到本科毕业论文的时候，没有科大的校徽图标，而博士和硕士毕业论文均有？

### ISSUE THREAD

**Issue by sun0405** [ustctug/ustcthesis#368]
## 检查
- [ ] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型：doctor / master / bachelor

## 描述问题
《研究生学位论文撰写手册》第 xx 页要求……而模板编译的结果是……

截图：
![图片](https://user-images.githubusercontent.com/85325368/224642760-a1fac88d-19c6-4717-a7d1-5f9f95a964c9.png)

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{ustcthesis}
\begin{document}
abc
\end{document}
```

**Comment by sikouhjw** [comment]
既不阅读《中国科学技术大学本科毕业论文（设计）格式》也不翻阅 issue，甚至连 issue 模板里的内容都不看一眼。

https://github.com/ustctug/ustcthesis/issues/347#issuecomment-1123123124

**Comment by zepinglee** [comment]
#301

**Comment by sun0405** [comment]
非常抱歉，我再仔细看看，打扰你们了，谢谢你们的回答
