### ISSUE TITLE
会议论文BiBTeX参考文献的格式问题

### ISSUE THREAD

**Issue by zhangchaoheng** [ustctug/ustcthesis#369]
开发团队您好，我是在windows10上使用的Overleaf版本的模板，检查是最新版本，ISSUE上的问题我也看过，与我的并不相同，这是一个可能比较个人的问题。

问题如下：

导师指出我的会议论文格式不对，他认为

![image](https://user-images.githubusercontent.com/77487669/227433032-0cd5c408-a645-407a-a55a-5e6b2d1fd7a5.png)

应当将会议论文集的文献格式改为 

作者.文献题名[A].会议论文集名[C].出版地:出版社,出版年:起止页码

我阅读了研究生论文手册，与他所要求的格式并不完全一致，但是导师坚持他的要求，我为了通过他的审核，不得不修改Overleaf上的会议参考文献格式，但不知如何下手。

我找到OverLeaf上的会议论文参考文献inproceedings格式，应是在 ustcthesis-numerical.bst 文件中，其函数如下：

FUNCTION {inproceedings}
{ 
  "C" set.entry.mark
  incollection
}

FUNCTION {conference} { inproceedings }

还请开发团队指点一下如何修改成  “作者.文献题名[A].会议论文集名[C].出版地:出版社,出版年:起止页码”这种格式，关键在于对ustc.bib中booktitle的识别修改。

麻烦你们十分抱歉，如能赐教，感激不尽！

**Comment by note286** [comment]
你可以定稿前，把`.bbl`中的粘出来，手动修改一下就好了，想改成啥改成啥。相当于用`BibTeX`帮助你写`bibitem`。

**Comment by zhangchaoheng** [comment]
首先，非常感谢您回答我的问题！

我现在是在OverLeaf上下载了. bbl 的文件，并在其中修改了

将原先的

`\bibitem[Hoang et~al.(2010)Hoang and Low]{2010Multi}
HOANG T~D, LOW K~L.
\newblock Multi-resolution screen-space ambient
  occlusion\allowbreak[C]//\allowbreak
Acm Symposium on Virtual Reality Software & Technology.
\newblock 2010: 101-102.`

修改为

`\bibitem[Hoang et~al.(2010)Hoang and Low]{2010Multi}
HOANG T~D, LOW K~L.
\newblock Multi-resolution screen-space ambient occlusion\allowbreak[A].
\newblock Acm Symposium on Virtual Reality Software & Technology[C].
\newblock 2010: 101-102.`

然后我将.bbl文件重新上传到overleaf上，改名后取代了之前的ustc.bib文件

![image](https://user-images.githubusercontent.com/77487669/227444894-ae7b0273-25f9-414a-b4ad-ad42ca881a28.png)

但文献格式并未发生改变，和原来的还是一样。

**Comment by zhangchaoheng** [comment]
请问bbl文件后续这样的操作正确吗？如果不正确，那应该如何做呢？还请赐教，非常感激！

**Comment by zhangchaoheng** [comment]
我编译过几次，查看文献格式是没有改变的，请问bbl文件后续这样的操作正确吗？

如果不正确，那应该如何做呢？还请赐教，非常感激！

**Comment by note286** [comment]
当然，修改`.bst`是最好的解决办法，但是由于能力问题，可能不现实，因此我建议可以直接使用`thebibliography`环境。

先解释一下为什么修改`.bbl`之后不生效，是因为Overleaf每次都会重新生成`.bbl`，被覆盖了。所以，我才说我们的思路是利用BibTeX帮助我们生成`\bibitem`。

下面给出一个示例，提供思路，具体情况你具体分析。

```latex
\documentclass{article}
\begin{document}
\cite{angenendt}\cite{augustine}
\bibliographystyle{plain}
\bibliography{biblatex-examples}
\end{document}
```

```shell
pdflatex -synctex=-1 main
bibtex main
pdflatex -synctex=-1 main
pdflatex -synctex=-1 main
```

编译之后我们可以得到`.bbl`文件：

```latex
\begin{thebibliography}{1}

\bibitem{angenendt}
Arnold Angenendt.
\newblock In honore salvatoris~-- vom sinn und unsinn der patrozinienkunde.
\newblock 97:431--456, 791--823.

\bibitem{augustine}
Robert~L. Augustine.
\newblock {\em Heterogeneous catalysis for the synthetic chemist}.
\newblock Marcel Dekker.

\end{thebibliography}
```

这时候我们不再使用BibTeX，而是直接修改我们的`.tex`文件：

```latex
\documentclass{article}
\begin{document}
\cite{angenendt}\cite{augustine}
\begin{thebibliography}{1}
\bibitem{angenendt}
Arnold Angenendt.
\newblock In honore salvatoris~-- vom sinn und unsinn der patrozinienkunde.
\newblock 97:431--456, 791--823.
\bibitem{augustine}
Robert~L. Augustine.
\newblock {\em Heterogeneous catalysis for the synthetic chemist}.
\newblock Marcel Dekker.
\end{thebibliography}
\end{document}
```

```shell
pdflatex -synctex=-1 main
```

建议你阅读一下lshort中6.1节关于参考文献和BibTeX工具的介绍。

手写`thebibliography`会导致你失去BibTeX自动排序等功能，因此建议你定稿之后再修改。

**Comment by zepinglee** [comment]
吐槽一下，学校有明确规定还有什么格式不对的，非要搞特殊。

https://github.com/ustctug/ustcthesis/blob/ccf3b0661aaaf6b377ff54e93fe2989cce1172e7/ustcthesis-numerical.bst#L2035-L2038

这里改成 `"A"`。

https://github.com/ustctug/ustcthesis/blob/ccf3b0661aaaf6b377ff54e93fe2989cce1172e7/ustcthesis-numerical.bst#L969-L980

这个函数末尾加上
```
  type$ "inproceedings" = type$ "conference" = or
    { "[C]" * }
    'skip$
  if$
```

**Comment by zhangchaoheng** [comment]
首先，非常感谢俩位老师非常详细和辛苦地帮助我解决问题，谢谢！

 @zepinglee 我采用了zepinglee 老师的方法，基本解决了问题，tql!

唯一还存在的问题是
![image](https://user-images.githubusercontent.com/77487669/227678224-8cc2abd8-5f47-42e0-b9a4-70cc413ff2de.png)

这里 //不知道怎么去掉，换成 . 这种格式？

![image](https://user-images.githubusercontent.com/77487669/227678360-7f154c57-fa10-4c11-ba72-2eb8f062f826.png)

**Comment by zepinglee** [comment]
https://github.com/ustctug/ustcthesis/blob/ccf3b0661aaaf6b377ff54e93fe2989cce1172e7/ustcthesis-numerical.bst#L78

这里改成 `none`。

**Comment by zhangchaoheng** [comment]
非常感谢 @zepinglee 和 @note286 两位老师的指导，我的问题解决了！
