### ISSUE TITLE
数学环境需要汉化（比如“定理”“推论”）

### ISSUE THREAD

**Issue by zepinglee** [ustctug/ustcthesis#37]
刚刚看了老的模板，发现还需要做很多关于数学环境的定义

**Comment by seisman** [comment]
看了一下科大的微积分教材，有几点与模板不同的地方：

1. `定理 10.5.1`而不是`定理 10.5.1.`
2. `定理`之前缩进两个空格
3. `定理 10.5.1`后有一个空格

**Comment by zepinglee** [comment]
ok，我去做这个

**Comment by seisman** [comment]
这个估计没有统一的标准，可以暂且按照科大微积分书上来，再等专业人士提具体需求。

**Comment by zepinglee** [comment]
现在应该好些了，但是“证明”我还不太清楚搞成什么样

**Comment by seisman** [comment]
看了一下严镇军的复变函数，证明是粗体，前空两个字符，后空一个字符。其他没问题。

**Comment by zepinglee** [comment]
d0751e6 修改了proof 环境，但是缩进距离还不太对
