### ISSUE TITLE
怎么解决论文索引上标和正常标混用的情况？

### ISSUE THREAD

**Issue by HaitaoXu06** [ustctug/ustcthesis#371]
怎么解决论文索引上标和正常标混用的情况？

**Comment by sikouhjw** [comment]
https://github.com/ustctug/ustcthesis/blob/ccf3b0661aaaf6b377ff54e93fe2989cce1172e7/ustcthesis.cls#L2776-L2778

**Comment by zepinglee** [comment]
<img width="561" alt="Screenshot 2023-03-29 at 17 50 35" src="https://user-images.githubusercontent.com/12290822/228496716-dd7d3c51-cf4a-430d-a193-37cdfdc12bc0.png">

麻烦读一下文档，不必在 issue、discussion、电子邮件都发一遍。
