### ISSUE TITLE
按照最新的《中国科学技术大学本科毕业论文（设计）格式》，是否需要更新扉页设计？

### ISSUE THREAD

**Issue by chrysoljq** [ustctug/ustcthesis#374]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 11
- TeX 发行版：TeX Live 2019
- 模板类型： bachelor

## 描述问题
按照最新的格式，论文封面格式应为如下图所示
![image](https://user-images.githubusercontent.com/58966022/236665647-b9a71cea-5549-4315-8310-927a65332579.png)

**Comment by zepinglee** [comment]
有没有官方文件的链接？

**Comment by YueWu2002** [comment]
> 有没有官方文件的链接？

https://www.teach.ustc.edu.cn/notice/notice-teaching/15097.html/attachment/%e4%b8%ad%e5%9b%bd%e7%a7%91%e5%ad%a6%e6%8a%80%e6%9c%af%e5%a4%a7%e5%ad%a6%e6%9c%ac%e7%a7%91%e6%af%95%e4%b8%9a%e8%ae%ba%e6%96%87%ef%bc%88%e8%ae%be%e8%ae%a1%ef%bc%89%e6%a0%bc%e5%bc%8f

**Comment by zepinglee** [comment]
已在 674d95c 中更新。
