### ISSUE TITLE
修改#1 'uppercase.name := 为 #0后，参考文献列表作者名仍全大写

### ISSUE THREAD

**Issue by zzhli** [ustctug/ustcthesis#377]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 11
- TeX 发行版：TeX Live 2023
- 模板类型：doctor

## 描述问题
已经参考常见问题在ustcthesis-authoryear.bst文件中将 load.config 函数中的 #1 'uppercase.name := 改为 #0，参考文献列表中作者名仍全部大写。

截图：
![image](https://github.com/ustctug/ustcthesis/assets/60774771/20e37f0c-71b2-4182-b0ee-3fb3360340a5)
![image](https://github.com/ustctug/ustcthesis/assets/60774771/88e469ae-1fd6-44c4-ae50-4704c76d302f)

**Comment by zepinglee** [comment]
给出浮现问题的 `.bib` 代码。

**Comment by zzhli** [comment]
> 清除所有辅助文件（`.aux`, `.log`, `.bbl` 等）后，再重新编译，是否还是全大写？

是的，清除所有辅助文件重新编译后问题仍在。

**Comment by zzhli** [comment]
> 给出浮现问题的 `.bib` 代码。

[thesis0809_minimal.zip](https://github.com/ustctug/ustcthesis/files/12309123/thesis0809_minimal.zip)
这里给出了在我的配置下能复现此问题的最小环境。
系统：Windows 11
编辑器：VS Code v1.81.0 + Latex Workshop v9.13.4
TeX环境：Tex Live 2023
排版引擎：XeLatex和luaLatex下都能复现此问题

**Comment by zzhli** [comment]
> 给出浮现问题的 `.bib` 代码。

[thesis0809_minimal.zip](https://github.com/ustctug/ustcthesis/files/12309198/thesis0809_minimal.zip)

这里给出了在我的配置下能复现此问题的最小环境。
系统：Windows 11
编辑器：VS Code v1.81.0 + Latex Workshop v9.13.4
TeX环境：Tex Live 2023
排版引擎：XeLatex和luaLatex下都能复现此问题

**Comment by zepinglee** [comment]
> > 这个代码用的是 `biblatex`……
> > 把 `ustcsetup.tex` 里面
> > ```
> > \usepackage[style=ustcthesis-authoryear,eprint=false,doi=false]{biblatex}
> > \addbibresource{bib/ustc.bib}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 注释掉，再把
> > ```
> > % \usepackage[sort]{natbib}
> > % \bibliographystyle{ustcthesis-numerical}
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 取消注释。`main.tex` 里面 `\printbibliography` 也要换成 `\bibliography{bib/ustc}`。
> 
> 是的，但我的目的就是使用`biblatex`，有没有使用`biblatex`的同时调整作者名不要全部大写的方法呢？ 要补充一条信息：使用`biblatex`但将引用格式设置为bachelor时，引用列表中作者名只会首字母大写。是不是`ustcthesis-bachelor.bst`中的
> 
> ```
> #0 'uppercase.name :=
> ```
> 
> 生效了？但我在`ustcthesis-authoryear.bst`和`ustcthesis-numerical.bst`中做出这样的修改时则不起作用。

biblatex 的用法参考 `texdoc biblatex-gb7714-2015`。

`.bst` 文件是 BibTeX 的，跟 biblatex 无关。

**Comment by zzhli** [comment]
> > > 这个代码用的是 `biblatex`……
> > > 把 `ustcsetup.tex` 里面
> > > ```
> > > \usepackage[style=ustcthesis-authoryear,eprint=false,doi=false]{biblatex}
> > > \addbibresource{bib/ustc.bib}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 注释掉，再把
> > > ```
> > > % \usepackage[sort]{natbib}
> > > % \bibliographystyle{ustcthesis-numerical}
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 取消注释。`main.tex` 里面 `\printbibliography` 也要换成 `\bibliography{bib/ustc}`。
> > 
> > 
> > 是的，但我的目的就是使用`biblatex`，有没有使用`biblatex`的同时调整作者名不要全部大写的方法呢？ 要补充一条信息：使用`biblatex`但将引用格式设置为bachelor时，引用列表中作者名只会首字母大写。是不是`ustcthesis-bachelor.bst`中的
> > ```
> > #0 'uppercase.name :=
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 生效了？但我在`ustcthesis-authoryear.bst`和`ustcthesis-numerical.bst`中做出这样的修改时则不起作用。
> 
> biblatex 的用法参考 `texdoc biblatex-gb7714-2015`。
> 
> `.bst` 文件是 BibTeX 的，跟 biblatex 无关。

了解，多谢解答！

**Comment by zzhli** [comment]
👍

**Comment by sunlover1995** [comment]
如果使用的是biblatex，可修改ustcthesis-authoryear.bbx
\ProvidesFile{ustcthesis-authoryear.bbx}[2021/01/19 v1.0 USTCThesis biblatex
  bibliography style]

\RequireBibliographyStyle{gb7714-2015ay}

\ExecuteBibliographyOptions{
  gbnamefmt = lowercase,
  gbpub = false}
