### ISSUE TITLE
开始 : "C:/texlive/2023/bin/windows/bibtex.exe" "main"  I couldn't open file name `main.aux'  出现错误

### ISSUE THREAD

**Issue by syp986063115** [ustctug/ustcthesis#378]
## 检查
- [ ] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型：doctor / master / bachelor

## 描述问题
《研究生学位论文撰写手册》第 xx 页要求……而模板编译的结果是……

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{ustcthesis}
\begin{document}
abc
\end{document}
```

**Comment by note286** [comment]
```
xelatex main
bibtex main
xelatex main
xelatex main
```

TeX Live 2023，Windows 10 无法复现你的问题。

**Comment by syp986063115** [comment]
什么意思啊，没看懂

在2023-11-15 ***@***.***写道：

xelatex main
bibtex main
xelatex main
xelatex main


TeX Live 2023，Windows 10 无法复现你的问题。

**Comment by note286** [comment]
就是字面意思啊，直接克隆仓库，执行上述命令，可以编译，没法复现你的问题。

**Comment by syp986063115** [comment]
那我这个问题如何解决啊，我想用这个写毕业论文，但不是计算机相关专业的，看不懂这个啊

在2023-11-15 ***@***.***写道：

就是字面意思啊，直接克隆仓库，执行上述命令，可以编译，没法复现你的问题。

**Comment by note286** [comment]
根据你目前所有的描述，没人能够帮助你。

我现在能说的就是，直接下载仓库，直接编译，没有问题，可能是你的环境问题，可能是你操作的问题，这些我都不知道，也没法猜测。

**Comment by sikouhjw** [comment]
直接上 Overleaf 吧，他这个应该是环境变量的问题，加上 texstudio 内的路径是手动写的，才会出这个问题

**Comment by syp986063115** [comment]
直接下载仓库是什么意思啊


在2023-11-15 ***@***.***写道：

根据你目前所有的描述，没人能够帮助你。

我现在能说的就是，直接下载仓库，直接编译，没有问题，可能是你的环境问题，可能是你操作的问题，这些我都不知道，也没法猜测。

**Comment by note286** [comment]
```
git clone https://github.com/ustctug/ustcthesis.git
```

或者

![image](https://github.com/ustctug/ustcthesis/assets/16207292/384337df-5fe9-45bc-8099-15cab269ef9d)

**Comment by zepinglee** [comment]
@syp986063115 这个问题主要在于你本地的配置，跟本模板无关。

如果你是初次接触 LaTeX，建议找有经验的同学线下指导，这样应该更容易解决。
