### ISSUE TITLE
模板无法实现小型大写字体\textsc命令

### ISSUE THREAD

**Issue by wyf18** [ustctug/ustcthesis#379]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 13.5.1 
- TeX 发行版：TeX Live 2023
- 模板类型：master

## 描述问题
本人论文中需要小型大写字体，而模板编译的结果是原样输出

应为截图：
<img width="266" alt="截屏2023-12-18 20 38 50" src="https://github.com/ustctug/ustcthesis/assets/44402561/4256c82d-d254-4ef1-a41d-a29dcd86f758">

实际输出截图：
![截屏2023-12-18 20 39 53](https://github.com/ustctug/ustcthesis/assets/44402561/1c145ab0-5474-4aef-ad29-f43023a21750)

复现上述问题的代码：
```TeX
\documentclass[degree=master]{ustcthesis}
\begin{document}
\textsc{Small Caps Text}
\end{document}
```
已在本机新建文档试过，是可以正常输出的，只有用了这个模板不行

**Comment by note286** [comment]
如果是Times New Roman，那么安装高版本的Times New Roman即可，你可以从Windows拷贝一份出来安装到macOS上。

**Comment by note286** [comment]
你可以试试

```latex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{Times New Roman}
\begin{document}
\textsc{Small Caps Text}
\end{document}
```

我印象中Times New Roman在macOS的版本有点低。

**Comment by wyf18** [comment]
> 你可以试试
> 
> ```
> \documentclass{article}
> \usepackage{fontspec}
> \setmainfont{Times New Roman}
> \begin{document}
> \textsc{Small Caps Text}
> \end{document}
> ```
> 
> 我印象中Times New Roman在macOS的版本有点低。

试过了还是不行，重装了一遍字体也不行

**Comment by sikouhjw** [comment]
用 XITS 呗
```tex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{XITS}
\begin{document}
\textsc{Small Caps Text}
\end{document}
```

**Comment by wyf18** [comment]
成功了。之前是从网上下载的字体，这次请同学复制了一个windows的Times New Roman字体，需要先卸载，再安装。

至于楼上说的XITS，我电脑上似乎并没有这个字体，添加了这行代码之后报错很多。

感谢各位的帮助！
