### ISSUE TITLE
compile error 

### ISSUE THREAD

**Issue by run** [ustctug/ustcthesis#38]
LaTeX Error: File `ustcthesis.cls' not found. 

Can I compile it in Windows + Texlive2015 ?

**Comment by seisman** [comment]
Not tested in Windows yet. But you need to run `xetex ustcthesis.dtx` to generate `.cls` from `.dtx` before compiling your thesis.

**Comment by run** [comment]
那你们开发用的是什么平台呢？ Linux 还是 Mac ？

**Comment by seisman** [comment]
我用的Linux，@zepinglee 用的应该是Mac。理论上模板不需要修改就可以在windows下编译，不过还没有做具体的测试。

**Comment by zepinglee** [comment]
用gnu make 比较方便，手工编译时参考 Makefile 里面的内容。

以后会写个 .bat 批处理文件用于windows
