### ISSUE TITLE
使用overleaf模板编译得到的pdf文件的中文字体不是撰写手册要求的中易宋体(SimSun)

### ISSUE THREAD

**Issue by enfancewlm** [ustctug/ustcthesis#380]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统： Overleaf
- TeX 发行版：TeX Live 2023
- 模板类型： master 
- 使用选项：fontset=windows

## 描述问题
想在overleaf中编译出和windows本地编译一样的pdf,  所以使用了[fontset=windows]选项， 但报错显示overleaf找不到SimSun字体，也就是说，overleaf本身没有安装这个字体，模板里也没有相应的字体文件。这份overleaf模板似乎需要调整和补充才能显示合适的字体。
截图：
这是直接编译得到的pdf中的字体，即没有使用[fontset=windows]选项，直接编译得到的pdf
![image](https://github.com/ustctug/ustcthesis/assets/81507627/86457076-44cb-43ff-a87a-1f617b492095)
不是SimSun，正确的字体应该是下面这样
![屏幕截图 2023-12-26 125652](https://github.com/ustctug/ustcthesis/assets/81507627/fd68bed8-74cd-46bc-8d42-daad36b3166e)

强烈希望加上一个[fontset=overleaf]选项！感觉会方便很多

**Comment by taoky** [comment]
中易宋体是有版权的，因此 overleaf 模板里面肯定不可能带一份。

**Comment by zepinglee** [comment]
主要是版权原因。另外可以考虑用 <https://www.texpage.com/>。
