### ISSUE TITLE
使用chapterbib分章节输出参考文献表出现问题

### ISSUE THREAD

**Issue by yangfyustc** [ustctug/ustcthesis#381]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 10，使用VSCode version 1.85的LaTeX Workshop v9.16.1扩展进行编译。
- TeX 发行版：TeX Live 2021
- 模板类型：master

## 描述问题

参考issue #242 #290 修改了main.tex，以及在每个独立的chapter的tex文件末尾加上了bibliographystyle和bibliography命令，使用latexmk -xelatex进行编译，报错且没有pdf文件输出。

请问应该如何去调整？

使用ustcthesis-bachelor格式，以及需要分章节输出参考文献表是因为往年课题组毕业论文格式均为该格式，但都使用word进行撰写都没用过latex。

以下为文件关键信息和报错信息。

> main.tex
\documentclass[degree=master]{ustcthesis}
\input{ustcsetup.tex}
\usepackage{chapterbib}
\begin{document}
\include{chapters/intro}
\include{chapters/chapter2}

> intro.tex
\chapter{123}
123\cite{1}
\bibliographystyle{ustcthesis-bachelor}
\bibliography{bib/ustc}

> chapter.tex
\chapter{2}
222\cite{2}
\bibliographystyle{ustcthesis-bachelor}
\bibliography{bib/ustc}

输出报错Error：
Illegal, another \bibstyle command 
Illegal, another \bibdata command

**Comment by yangfyustc** [comment]
我自己的问题，我没把ustcsetup里面的\bibliographystyle还有main里面的\bibliography{bib/ustc}给注释掉，注释掉之后每个章节后面正常出现了对应的参考文献表。

但是还是有问题，我们化学系参考文献往年都是另起一页，同时“参考文献”四个字居中置顶，字体、字号和chapter标题相同；同时参考文献以section标题的形式在目录中对应的chapter末尾出现，并注明页码号。

注释ustcsetup和main之后，输出的参考文献表在目录中正常显示，但正文中同样也是以section的形式出现，没有换页并居中。

请问应该如何调整以使得使用chapterbib分章节输出参考文献表，参考文献表以章(chapter)标题的形式另起一页输出，同时在目录中以节(section)的形式出现呢？

**Comment by sikouhjw** [comment]
> 但是还是有问题，我们化学系参考文献往年都是另起一页，同时“参考文献”四个字居中置顶，字体、字号和chapter标题相同；同时参考文献以section标题的形式在目录中对应的chapter末尾出现，并注明页码号。

> 请问应该如何调整以使得使用chapterbib分章节输出参考文献表，参考文献表以章(chapter)标题的形式另起一页输出，同时在目录中以节(section)的形式出现呢？

我总觉得是你的需求有问题，既要 chapter 又要 section。“往年”不代表是符合规范的，不代表是正确的。

**Comment by yangfyustc** [comment]
>> 我总觉得是你的需求有问题，既要 chapter 又要 section。“往年”不代表是符合规范的，不代表是正确的。

我的表述有问题还看错字号了，参考文献在教务处word模板里字体是 三号 16磅，我和章标题 小二 18磅 搞混了。

### 我的需求是（文章结构里 章 对应 chapter，节 对应 section）：

（文章结构里 章 对应 chapter，节 对应 section）

使得每一章后能输出该章对应的参考文献表，参考文献表输出格式与ustcthesis模板输出格式相同，同时每个章的参考文献表以节的形式出现在目录中。

### 目前我做的尝试是：

添加chapterbib宏包，成功输出了分章的参考文献表，目录的形式也正确。

### 目前我遇到的问题是：

参考文献表的格式在添加chapterbib宏包后与原输出格式不同，左对齐，并且字号、加粗与节标题相同，如图所示：
![捕获](https://github.com/ustctug/ustcthesis/assets/76695648/46ef5699-346a-4285-8875-d3620ff20f90)

>> “往年”不代表是符合规范的，不代表是正确的。

我也知道，但是交上去得给导师看，得给校内评审看，他们不会在意撰写指南是什么样，只关心和其他人写的有没有区别。

化学系几乎全都是word加endnote插入文献的形式，都是研究生教务处的word模板，参考文献表复制一下对应页然后插个分节符就能正常用endnote输出分章的参考文献表。

而且每一章的参考文献表量都很大，综述部分一般都是引100篇左右的文章，每一章课题相关的也都基本要引60篇相关的文章，并且不一定会重复，分章的参考文献表对于给评审阅读的纸质版来说更友好。

实在是非常抱歉！我latex具体格式设置几乎完全不通，只会做一些简单的调整，基本都是直接用的模板默认格式。

**Comment by sikouhjw** [comment]
我还是没太懂你的需求，不过我猜测你的意思是：
1. 目录中的行为保持与 section 一致
2. 正文中的行为需要“居中置顶”和“三号 16磅”

也就是说，你需要「临时切换 section 在正文中的行为」。这在 latex 中需要修改
https://github.com/ustctug/ustcthesis/blob/3900c0d711c01972ccf57fedb14911d1d7dc711b/ustcthesis.cls#L2244-L2250
也就是说，你需要在每章的
```
\bibliographystyle{ustcthesis-numerical}
\bibliography{bib/ustc}
```
之前修改 section 的行为，同时也需要在其之后修改回去：
```
% 修改 section 行为为你的需求
\bibliographystyle{ustcthesis-numerical}
\bibliography{bib/ustc}
% 修改回去
```

综上，你可以考虑使用这份代码：
```
\ctexset{
  section= {
    format      = \centering\sffamily\bfseries\fontsize{16bp}{26.67bp}\selectfont,
  },
}

\bibliographystyle{ustcthesis-numerical}
\bibliography{bib/ustc}

\ctexset{
  section= {
    format      = \sffamily\fontsize{14bp}{23.33bp}\selectfont,
  },
}
```
如果输出与你的预期不符，可尝试调整 format 部分的代码。

**Comment by yangfyustc** [comment]
https://github.com/ustctug/ustcthesis/issues/381#issuecomment-1884954518

非常感谢！完全满足了我的需求。我实在是不知道从何处对 ustcthesis.cls 下手。

在您的提醒下，我仔细浏览了 ustcthesis.cls 文件，发现加载了 chapterbib 宏包后确实是以调用 section 命令的形式输出 引用文献表 的标题，而未加载时则调用的是 chapter 命令。

插入 clearpage 手动换行后，修改 section 的行为为 ustcthesis.cls 文件里的 chapter 的行为，并在添加引用文献表后将 section 的行为修改回原行为，即可。

**Comment by yangfyustc** [comment]
段前间距未能显示，不过问题不大，效果如图所示：
![捕获](https://github.com/ustctug/ustcthesis/assets/76695648/bfeb3c74-87db-4782-b090-cbc583f87c93)

需额外修改 ustcthesis.cls 。
https://github.com/ustctug/ustcthesis/blob/3900c0d711c01972ccf57fedb14911d1d7dc711b/ustcthesis.cls#L3429C1-L3444C2

添加字距命令，改为：
`% \subsubsection{\pkg{chapterbib} 宏包}

\AtEndOfPackageFile*{chapterbib}{
  \@ifpackageloaded{natbib}{%
    \@ifpackagewith{chapterbib}{sectionbib}{%
      \ustc@error{The "sectionbib" option cannot be used with chaperbib if natbib loaded}%
    }{}%
    \renewcommand\bibsection{%
      \begingroup
        \ctexset{section/numbering=false}%
        \ziju{0.5}%手动添加0.5字距 @yangfyustc
        \section{\bibname}%
        \ziju{0}%改回去 @yangfyustc
      \endgroup
    }
  }{}
}
`

每章的tex文件末尾添加：
`\clearpage

\ctexset{
  section= {
    format      = \centering\sffamily\bfseries\fontsize{16bp}{26.67bp}\selectfont,
    afterskip   = 18bp,
    fixskip     = true,
  },
}

\bibliographystyle{ustcthesis-numerical} %所使用的引文编码制
\bibliography{bib/ustc}

\ctexset{
  section= {
    format      = \sffamily\fontsize{14bp}{23.33bp}\selectfont,
    afterskip   = 6bp,
    fixskip     = false,
  },
}
`
