### ISSUE TITLE
提供专业硕士模板，封面设计，和本人学院的版本不一致，请求修改一个版本

### ISSUE THREAD

**Issue by hongrenbeibei** [ustctug/ustcthesis#382]
## 检查
- [ ] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型：doctor / master / bachelor

## 描述问题
提供专业硕士模板，封面设计，和本人学院的版本不一致，请求修改一个版本

截图：本学院专硕的论文封面页是
![image](https://github.com/ustctug/ustcthesis/assets/89065816/8916f6f2-f47e-4b99-b39c-9009d90f1479)
，与提供的封面不一致。本人联系邮箱983494070@qq.com，可以提供本学院的WORD论文模板

**Comment by hongrenbeibei** [comment]
不一致地方，主要是增加了专业类别，专业领域，实践导师等信息。本人所属先进技术研究院，本人联系邮箱983494070@qq.com

**Comment by sikouhjw** [comment]
为什么还需要联系你的邮箱呢，开源项目的需求应当公开处理，才能方便后续有需求者。
更何况学院给的模板也不应该是需要保密的东西。

**Comment by hongrenbeibei** [comment]
[中国科学技术大学专业学位硕士论文模板_IAT_2202209.pdf](https://github.com/ustctug/ustcthesis/files/13914585/_IAT_2202209.pdf)
好的，我把本学院论文模板PDF上传了，封面页设计与提供不一致，可以修改吗？或者给些指导建议

**Comment by zepinglee** [comment]
相关的代码在

<https://github.com/ustctug/ustcthesis/blob/3900c0d711c01972ccf57fedb14911d1d7dc711b/ustcthesis.cls#L1901-L1906>

原来的“企业导师”、“Advisor”改成了“实践导师”和“Instructor”？

**Comment by hongrenbeibei** [comment]
好的，我试试

**Comment by zepinglee** [comment]
> [中国科学技术大学专业学位硕士论文模板_IAT_2202209.pdf](https://github.com/ustctug/ustcthesis/files/13914585/_IAT_2202209.pdf) 好的，我把本学院论文模板PDF上传了，封面页设计与提供不一致，可以修改吗？或者给些指导建议

@hongrenbeibei 这是软件工程专硕的模板吗？

**Comment by ShangGL123** [comment]
> > [中国科学技术大学专业学位硕士论文模板_IAT_2202209.pdf](https://github.com/ustctug/ustcthesis/files/13914585/_IAT_2202209.pdf)好的，我把本学院论文模板PDF上传了，封面页设计与提供不一致，可以修改吗？或者给些指导建议
> 
> @hongrenbeibei 这是软件工程专硕的模板吗？

这是先研院的模板，除了上述变动还增加了【专业类别】这一项，想请教下这两处在现有模板上如何进行修改

**Comment by sikouhjw** [comment]
改这里
https://github.com/ustctug/ustcthesis/blob/3900c0d711c01972ccf57fedb14911d1d7dc711b/ustcthesis.cls#L1898-L1908
加一行
```tex
\textsf{专业类别：} & xxx \\
```
的事

**Comment by ShangGL123** [comment]
> 改这里
> 
> https://github.com/ustctug/ustcthesis/blob/3900c0d711c01972ccf57fedb14911d1d7dc711b/ustcthesis.cls#L1898-L1908
> 
> 
> 加一行
> ```
> \textsf{专业类别：} & xxx \\
> ```
> 
> 的事

![image](https://github.com/ustctug/ustcthesis/assets/50814697/d4d25cb8-3dc7-4588-bd97-995b50014a74)
我尝试在英文封面对应部分也将major插入下述代码，但是遇到了自动分页的问题
![image](https://github.com/ustctug/ustcthesis/assets/50814697/73c7a50e-bae1-46cf-a5cf-d5d21a1688cd)

**Comment by sikouhjw** [comment]
> ![image](https://private-user-images.githubusercontent.com/50814697/309698000-d4d25cb8-3dc7-4588-bd97-995b50014a74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDU1NDMsIm5iZiI6MTcwOTU0NTI0MywicGF0aCI6Ii81MDgxNDY5Ny8zMDk2OTgwMDAtZDRkMjVjYjgtM2RjNy00NTg4LWJkOTctOTk1YjUwMDE0YTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA5NDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhN2NiYzhmMzczNGM4Yjg3YzNiZmJjMDI4NmFkMDJmN2Q5YzVlYWVkOTFkZDc1MGUwYjUzYWYzZmNjZDk0ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JL0fwxQr5zygrBoeV4Nra9ou_aZuPWfH2PCRd8wSgr8) 我尝试在英文封面对应部分也将major插入下述代码，但是遇到了自动分页的问题 ![image](https://private-user-images.githubusercontent.com/50814697/309698599-73c7a50e-bae1-46cf-a5cf-d5d21a1688cd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1NDU1NDMsIm5iZiI6MTcwOTU0NTI0MywicGF0aCI6Ii81MDgxNDY5Ny8zMDk2OTg1OTktNzNjN2E1MGUtYmFlMS00NmNmLWE1Y2YtZDVkMjFhMTY4OGNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA5NDA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwNGMxZWM4ZjhkYmIxYTg5YTA5OTU3NzY2YjBjMjYxOGI2YjU5M2M3MzdiNmNhODJmZTFhYzA5NTUwMDRkOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HunMjPgt3RMuZKvAOqk81xUmBmrcj7zHTgUA5PtCRjs)

调整 `\vskip` 后的数值，使得其不分页。
https://github.com/ustctug/ustcthesis/blob/3900c0d711c01972ccf57fedb14911d1d7dc711b/ustcthesis.cls#L1938-L1962

**Comment by ShangGL123** [comment]
非常感谢！回复太及时了
