### ISSUE TITLE
 LaTeX 默认风格的数学符号如何修改

### ISSUE THREAD

**Issue by phygavin** [ustctug/ustcthesis#383]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型： master 

## 描述问题  
-就是第一个问题，  数学公式的字体为何不是 LaTeX 默认的 Computer Modern？
 实在需要 LaTeX 默认风格的数学符号，可以设置 math-font = newcm 选择 [New Computer Modern](https://www.ctan.org/pkg/newcomputermodern)。

请问如何操作，添加这一个包。

如下是用模板得到的，积分号和字体均不够一般的数学形式。
![image](https://github.com/ustctug/ustcthesis/assets/102457230/b2d6d4c8-f4cf-4f90-be51-18f630f423e2)

**Comment by sikouhjw** [comment]
https://github.com/ustctug/ustcthesis/blob/3900c0d711c01972ccf57fedb14911d1d7dc711b/ustcsetup.tex#L25
属于是喂到嘴边都不看。

**Comment by phygavin** [comment]
十分感谢您的及时回复，  虽然我还没有解决所有的问题。  我换了三个选项 stix, xits, libertinus，还没有达到理想的效果，我再尝试。   
选 math-font = newcm 选择 [New Computer Modern] ， 不知将这个文件添加到系统的哪个位置 ?

**Comment by zepinglee** [comment]
另外最新版 `math-style = GB` 的上下限是在右侧的。建议检查是不是最新的模板。

<img width="250" alt="Screenshot 2024-02-29 at 18 06 01" src="https://github.com/ustctug/ustcthesis/assets/12290822/a64d6408-a4de-48d4-a2db-cb45739abd8f">

**Comment by phygavin** [comment]
十分感谢，您说的对，我现在解决了公式的格式问题 。

还有个问题是章编号改为汉字，包括章开头和页眉， “第1章”改为"第一章", arabic -> chinese,
也是通过cls 文件改成功， 请问该如何修改这段？
https://github.com/ustctug/ustcthesis/blob/3900c0d711c01972ccf57fedb14911d1d7dc711b/ustcthesis.cls#L2229C1-L2238C24

**Comment by zepinglee** [comment]
> 还有个问题是章编号改为汉字，包括章开头和页眉， “第1章”改为"第一章", arabic -> chinese, 也是通过cls 文件改成功， 请问该如何修改这段？ 

学校要求是“第 1 章”。

<img width="872" alt="Screenshot 2024-03-01 at 14 48 19" src="https://github.com/ustctug/ustcthesis/assets/12290822/3e2be4b4-995f-4a36-8e8f-d8dbabcfac0b">

**Comment by phygavin** [comment]
多谢您， 我通过number = \chinese{chapter}, 成功了，感谢贵校的模板，我是别的学校借用的 。

**Comment by zepinglee** [comment]
> 多谢您， 我通过number = \chinese{chapter}, 成功了

嗯，是这么设置的。
