### ISSUE TITLE
关于文献引用中双作者的问题

### ISSUE THREAD

**Issue by YimengSun21** [ustctug/ustcthesis#384]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 10
- TeX 发行版：TeX Live 2019
- 模板类型：master

## 描述问题
您好，看到要求说当引用文献的作者在两人及以上时，只需显示第一位即可，但导师个人偏好，比较倾向于将双作者的名字全部展示出来，我在ustcthesis-authoryear.bst中对参数citation.et.al.min做了修改，可以做到上述功能，但是现在展示的结果是A, B，而不是A & B，想问下这个有办法通过修改来更正吗？知道这并非模版要求，想请教一下，如有打扰，抱歉。

截图：

![截图1](https://github.com/ustctug/ustcthesis/assets/96295142/90cdc806-537e-47ee-8150-c79401d51ef7)

**Comment by zepinglee** [comment]
嗯这个需求有道理。但是目前基于 BibTeX 的方案无法自动对中文文献进行排序。所以建议看看使用 biblatex-gb7714-2015 能不能实现。

另外中文和英文都是使用“&”符号吗（即张三 & 李四；Doe & Roe）？

**Comment by YimengSun21** [comment]
感谢回复，确实没想到中文引用的问题，因为个人的文章里英文文献占多数。
目前探索了一个方法，不过略显得暴力，还是分享一下。
首先在ustcthesis-authoryear.bst中找到函数：
FUNCTION {citation.and}
{ terms.in.macro
    { "{\biband}" }
    'bbl.and
  if$
}
发现这里的terms.in.macro默认是0（可以在FUNCTION {load.config}里看到），所以应该直接用bbl.and的内容，找到bbl.and：
FUNCTION {bbl.and}
{ "" }
然后将这里的函数改成了：
FUNCTION {bbl.and}
{ " \& " }
这样确实使得连接变成了&符号，但是因为这个函数在最后的参考文献中也有运用，所以参考文献里的并列也变成了&连接，故这种方法不合适。
采用更直接的方式，直接将FUNCTION {citation.and}改为如下：
FUNCTION {citation.and}
{ " \& " }
因为默认terms.in.macro为0，所以也没什么影响（仅对我个人），最后保存.bst文件再重新编译tex，发现可以展示成A&B的形式：
![截图1](https://github.com/ustctug/ustcthesis/assets/96295142/48ba3a55-8f26-4cc2-8169-1c9b6da261d2)
不过这里的前提是对FUNCTION {load.config}中的citation.et.al.min进行更改，以使得展示结果符合预期。这里的话主要看个人偏好，可以自行调整。
以上方法仅供参考，希望后续可以进一步丰富引用的选择，感恩。

**Comment by zepinglee** [comment]
> 采用更直接的方式，直接将 `FUNCTION {citation.and}` 改为如下： `FUNCTION {citation.and} { " \& " }`

完全正确！看来你读懂了我的代码。
