### ISSUE TITLE
《研究生学位论文撰写手册》的链接挂了

### ISSUE THREAD

**Issue by ImVictorCheng** [ustctug/ustcthesis#385]
如题，链接挂了，是不是学校存到别处了？请问模板能否更新链接，或者直接将手册pdf附到模板文件夹内？

## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型：doctor / master / bachelor

## 描述问题
《研究生学位论文撰写手册》第 xx 页要求……而模板编译的结果是……

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{ustcthesis}
\begin{document}
abc
\end{document}
```

**Comment by zepinglee** [comment]
见 <https://github.com/ustctug/ustcthesis/issues/390#issue-2285755454>。我已经在文档中更新了描述。
