### ISSUE TITLE
预评审要求表注的\note{}和表格左对齐，而不是居中或者与正文左对齐。

### ISSUE THREAD

**Issue by zjh3608** [ustctug/ustcthesis#386]
预评审盲审老师要求：表注的\note{}和表格左对齐，而不是居中或者与正文左对齐。

**Comment by zjh3608** [comment]
目前的解决方案如下，不知道有没有更好的办法。
\documentclass{article}
\usepackage[flushleft]{threeparttable} % 
\usepackage{booktabs} % 
 
\begin{document}
 
\begin{table}[h]
  \centering  
  \caption{示例表格}
  \label{tab:exampletable}
  \begin{threeparttable} 
    \begin{tabular}{lcc} 
      \toprule 
      & 列1 & 列2  \\
      \midrule 
      行1 & A & B \\
      行2 & C & D \\
      \bottomrule 
    \end{tabular}
    \begin{tablenotes} 
      \item[1] 注释内容。 
    \end{tablenotes}
  \end{threeparttable}
\end{table}

**Comment by zepinglee** [comment]
学校的《撰写手册》并没有规定表注的格式。据我了解只能使用 `threeparttable` 了。

**Comment by zepinglee** [comment]
那我顺便把 `chapters/floats.tex` 的示例也改一下吧。https://github.com/ustctug/ustcthesis/blob/3900c0d711c01972ccf57fedb14911d1d7dc711b/chapters/floats.tex#L7-L24

**Comment by zjh3608** [comment]
> 那我顺便把 `chapters/floats.tex` 的示例也改一下吧。
> 
> https://github.com/ustctug/ustcthesis/blob/3900c0d711c01972ccf57fedb14911d1d7dc711b/chapters/floats.tex#L7-L24

我对照了一下，没有看出来哪里做了修改

**Comment by zepinglee** [comment]
上次忘记推送了，现在已经修改。

https://github.com/ustctug/ustcthesis/blob/9a274dbb4c10ab513b990054b4f5f152f99c9a94/chapters/floats.tex#L26-L46
