### ISSUE TITLE
三级标题似乎应该顶格？

### ISSUE THREAD

**Issue by xaswq** [ustctug/ustcthesis#387]
## 检查
- [√] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [√] 已经将模板升级到了最新版
- [ √] 已经阅读使用说明文档 `ustcthesis.pdf`
- [ √] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统： Overleaf
 
 

## 描述问题

https://gradschool.ustc.edu.cn/column/65

下载的撰写模板截图如下，三级标题是顶格的，模板编译出来是空了2个格子，似乎是缩进了2个字。

截图：

<img width="753" alt="image" src="https://github.com/ustctug/ustcthesis/assets/85377380/639c9a33-c1c9-487f-8cc1-889f89000897">

<img width="702" alt="image" src="https://github.com/ustctug/ustcthesis/assets/85377380/cf0e4f03-a251-4c60-9802-b96af83c2270">

**Comment by zepinglee** [comment]
嗯？又改了？

2021 年版的《撰写手册》是这么规定的。现在不知为何研究生院的网站上找不到这个文件了。

<img width="783" alt="Screenshot 2024-05-01 at 19 53 45" src="https://github.com/ustctug/ustcthesis/assets/12290822/441765d0-8dff-4a71-9baa-35b46a762e2e">

2021 年版的“博士学位论文撰写模板.doc”是这样。

<img width="734" alt="Screenshot 2024-05-01 at 19 55 03" src="https://github.com/ustctug/ustcthesis/assets/12290822/b8cc6a00-f038-45ed-b4f8-84b6404a574f">

能不能联系一下研究生院的老师确认修改？

**Comment by xaswq** [comment]
感谢前辈，已发邮件，等待回复ing

**Comment by zepinglee** [comment]
已在 master 分支修改。研究生院确认后我再发布一个新版本。

**Comment by zepinglee** [comment]
研究生院回复：

> 学位论文撰写模版最近仍在修订中，LaTeX模板还没有进行修订，等到学位论文撰写模板定稿后可以麻烦你帮我们改一版，谢谢。

> 另外研究生学位论文撰写手册为早些年出版社出版的，相对复杂，不方便操作，近期没有再进行维护，因而撤下来了。

那我发布一个 v4.0.0-beta1？
