### ISSUE TITLE
LiShu font is required on input line 1820 

### ISSUE THREAD

**Issue by xaswq** [ustctug/ustcthesis#395]
## 编译环境
- 编译的系统： Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型：doctor 

## 描述问题

编译的时候会出现告警，专业博士和专业硕士这块的报错。

请问是否有优雅点的在学校latex平台上的解决方案，感谢！

截图：
<img width="687" alt="image" src="https://github.com/ustctug/ustcthesis/assets/85377380/85746682-dc9d-430b-be05-0f365fcdd2f9">
<img width="625" alt="image" src="https://github.com/ustctug/ustcthesis/assets/85377380/e1df9ccb-4d79-4854-83e5-22c7ddb558ca">

**Comment by zepinglee** [comment]
这个没什么办法，专业学位的封面上需要隶书的“专业学位名称”。而 Overleaf 不提供该字体。

**Comment by xaswq** [comment]
感谢作者，不过好像最新版本的模板已经和学术博士一样统一为了黑体

https://gradschool.ustc.edu.cn/static/upload/article/file/1709607943793/501e0fec03da46f7b0c1b99d89f18d90.doc

https://gradschool.ustc.edu.cn/static/upload/article/file/1709607877110/3bdd26a82b2c45f2a9a4a73c4ba7c149.doc

**Comment by zepinglee** [comment]
这一部分目前还是隶书。可能是你的系统没有隶书字体，所以 fallback 到了黑体。

<img width="853" alt="Screenshot 2024-06-06 at 22 24 42" src="https://github.com/ustctug/ustcthesis/assets/12290822/f2934409-e002-4dc6-a009-765ab9c374eb">
