### ISSUE TITLE
大写字母间距较大问题

### ISSUE THREAD

**Issue by shawnl111** [ustctug/ustcthesis#396]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 14.3
- TeX 发行版： MacTeX 2019 / 
- 模板类型：master 

## 描述问题
大写字母间距很大，（1）使用mathit之后，字体变细。（2）使用\!减小字体间距不和谐。如何解决呢？

截图：
<img width="307" alt="image" src="https://github.com/ustctug/ustcthesis/assets/38712239/cdf64d53-c804-45da-93e2-df7ff6a0ae53">
<img width="298" alt="image" src="https://github.com/ustctug/ustcthesis/assets/38712239/eb2d4041-be28-4e43-b5be-e182aaa9b68c">

复现上述问题的代码：
```TeX
\begin{equation}
    \mathit{RMSE\%}RMSE=\sqrt{\frac{\sum_{i=1}^n[F(i)-\widehat{F}(i)]^2}{\sum_{i=1}^nF(i)^2}}\times100\%
    \label{eq:rmse}
\end{equation}  

\begin{equation}
\mathit{Intensity}I\!ntensityIntensity=\sum_{t=1}^{n} H(t)
  \label{eq:2.18}
\end{equation}
```

**Comment by zepinglee** [comment]
我印象中这种通常会用正体 `\text{RMSE} = ...`。

**Comment by sikouhjw** [comment]
我一般会
```tex
\newcommand{\MSE}{\text{MSE}}
```
