### ISSUE TITLE
图表章节引用编号与文字间的间距修改

### ISSUE THREAD

**Issue by zlzhang1124** [ustctug/ustcthesis#398]
## 检查
- [x] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [x] 已经将模板升级到了最新版
- [x] 已经阅读使用说明文档 `ustcthesis.pdf`
- [x] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：Windows 10
- TeX 发行版： MiKTeX 2.9.6753
- 模板类型：doctor

## 描述问题
我在正文中引用图片、表格或章节编号时，发现所有的编号和前面的文字（图/表/节）之间的间距和其他文本不一致，似乎多出了一个小空格间距，如下面图中的文字“用”和随后的章节编号“1.1”间的间距，以及文字“图”和随后的图片编号“1.1”间的间距，均比正常文本间的间距宽一些。请问这是啥情况呢？如何修改？

截图：
![1](https://github.com/user-attachments/assets/3be45782-2f8d-44f1-a264-f486159e3142)

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{ustcthesis}
\input{ustcsetup.tex}

\begin{document}

\chapter{测试章}
\label{c:1}

\section{测试节}
\label{s:1.1}

引用~\ref{s:1.1}节测试。
如下面所示图~\ref{fig:1.1}显示了测试图片。

\begin{figure}[h]
  \centering
  \includegraphics[width=0.3\textwidth]{ustc-badge.pdf}
  \caption{测试图片}
  \note{注：测试图注测试图注测试图注测试图注测试图注测试图注测试图注测试图注测试图注测试图注测试图注测试图注测试图注}
  \label{fig:1.1}
\end{figure}

\end{document}
```

**Comment by sikouhjw** [comment]
`图~\ref{test} 需要空格`

**Comment by zlzhang1124** [comment]
> `图~\ref{test} 需要空格`

如果每个引用后均加了一个空格，那这样均会比正常文字之间的间隔大了一个空格宽度，能否只是删除这里多出的“空格”宽度，而不是额外在编号后再加一个空格呢？

**Comment by tanukihee** [comment]
中西文之间**需要**添加空格

**Comment by zlzhang1124** [comment]
> 中西文之间**需要**添加空格

多谢，原来如此！另外建议可以直接重定义"\ref"命令，不需要用户额外再逐个添加空格：

\let\originalref\ref
\renewcommand\ref[1]{\originalref{#1} }

**Comment by SmartHypercube** [comment]
不行，加不加空格是需要人工判断的，例如：
本算法流程图见图 \ref{test}。
如果数字和句号之间有空格就不对了。

**Comment by zlzhang1124** [comment]
> 不行，加不加空格是需要人工判断的，例如： 本算法流程图见图 \ref{test}。 如果数字和句号之间有空格就不对了。
> 
> edit：好像我见过有宏包能按一些规则决定各种地方要不要加空格，可能可以自动化解决？

是这么回事，希望后面可以自动化

**Comment by zepinglee** [comment]
没有能覆盖全部情况的自动方法，所以还是建议手动处理空格。

**Comment by zlzhang1124** [comment]
简单加了自动处理，测试了下，完全可以满足我的需求，仅供参考：

% 引用编号后添加空格：中西文之间需要添加空格（一些标点符号除外）
\makeatletter
\let\originalref\ref
\renewcommand\ref[1]{%
  \originalref{#1}\@ifnextchar{、}{}{\@ifnextchar{。}{}{\@ifnextchar{，}{}{%
  \@ifnextchar{！}{}{\@ifnextchar{？}{}{\@ifnextchar{；}{}{%
  \@ifnextchar{：}{}{\@ifnextchar{（}{}{\@ifnextchar{）}{}{%
  \@ifnextchar{《}{}{\@ifnextchar{》}{}{\@ifnextchar{.}{}{%
  \@ifnextchar{,}{}{\@ifnextchar{;}{}{\@ifnextchar{:}{}{%
  \@ifnextchar{!}{}{\@ifnextchar{?}{}{\@ifnextchar{(}{}{%
  \@ifnextchar{)}{}{\@ifnextchar{<}{}{\@ifnextchar{>}{}{%
  \space}}}}}}}}}}}}}}}}}}}}}%
}
\makeatother

**Comment by sikouhjw** [comment]
你没用代码块，`@` 前面的 `\` 都被吞了。
