### ISSUE TITLE
是否考虑增加自定义字体的选项？

### ISSUE THREAD

**Issue by redsky0802** [ustctug/ustcthesis#40]
ctex自动处理字体的情况下，我的论文中“〇”字未能正确显示，而老版中没有这个问题（我在老版中一直用的是adobefonts选项），这应该是与字体选择有关。所以是否能考虑增加字体选择的配置选项？

**Comment by hosiet** [comment]
[OT]

能说明一下出问题时操作系统平台、CTeX 版本和 LaTeX 引擎的使用情况吗？

近期 CTeX 有过大更新，问题可能和版本有关。

Yuanchong Zhu <notifications@github.com> 於 2015年10月4日週日 21:56 寫道：

**Comment by redsky0802** [comment]
@hosiet Archlinux x86_64，texlive 具体版本如下：

local/texlive-bin 2015.37497-3
    TeX Live binaries
local/texlive-core 2015.37554-1 (texlive-most)
    TeX Live core distribution
local/texlive-fontsextra 2015.37556-1 (texlive-most)
    TeX Live - all sorts of extra fonts
local/texlive-langchinese 2015.37467-1 (texlive-lang)
    TeX Live - Fonts and macro packages to typeset Chinese texts
local/texlive-latexextra 2015.37553-1 (texlive-most)
    TeX Live - Large collection of add-on packages for LaTeX
local/texlive-science 2015.37382-1 (texlive-most)
    TeX Live - Typesetting for natural and computer sciences

**Comment by seisman** [comment]
在不显式指定字体时，Linux下默认使用Fandol字体，在`main.tex`中指定文档类时，可以使用ctex定义的相关选项，模板会自动把这些选项传递给ctex宏集。可以使用`fontset=adobe`指定adobe字体或使用`fontset=windows`指定windows字体。

我在CentOS7下，测试了Fandol、adobe、windows字体，大写的零都可以正常显示。

**Comment by hosiet** [comment]
@seisman 

如图所示，使用 Fandol 字体时中文大写的零看起来有点奇怪。这是 bug 吗？

![_036](https://cloud.githubusercontent.com/assets/8443926/10298756/d5aed62e-6c14-11e5-88bc-a9ee1f3f5aca.png)

**Comment by seisman** [comment]
这应该是字体本来就是这样设计的吧。分别用Fandol、adobe、windows，这个零的大小都不太一样。

**Comment by redsky0802** [comment]
@seisman 我这里实测：fontset=adobe可用，Fandol似乎没有安装，windows字体有缺失

**Comment by hosiet** [comment]
TeX Live 2014 之后都自带 Fandol 中文字体，在非 mac/windows 环境下，如果未指明字体，会被 CTeX
自动载入。当然前提是 TeX Live 安装要完整。

对于 XeTeX 来说，在 Linux 下其它字体都是调用 fontconfig 管理载入的，如果系统内装入了对应字体才能使用，Windows
的字体默认是不会存在的。

Yuanchong Zhu <notifications@github.com> 於 2015年10月7日週三 01:03 寫道：

**Comment by seisman** [comment]
准确地说，应该是从texlive 2014开始自带fandol字体。

对于texlive2014而言，ctex版本应该是1.3，不能自动调用fandol字体，需要将fandol字体放到系统字体路径里，然后在tex代码中显式指定fandol字体。

对于texlive2015而言，ctex版本为2.0，linux下默认使用fandol字体，不需要任何操作即可使用。

**Comment by redsky0802** [comment]
@seisman 又试了一下fontset=fandol，首字母改成小写之后似乎正常了，这下编译出来的东西跟默认情况一样，还是缺字……

**Comment by hosiet** [comment]
缺字有效果图可以看看吗？是大写的零缺字还是其它的地方有缺字呢？

Yuanchong Zhu <notifications@github.com> 於 2015年10月7日週三 02:34 寫道：

**Comment by redsky0802** [comment]
暂时只是大写零缺字
![2015-10-07-170047_591x43_scrot](https://cloud.githubusercontent.com/assets/1460673/10333261/4e66424a-6d15-11e5-99f8-41468610f3d2.png)

**Comment by seisman** [comment]
我这边三个字体都没有问题，会不会是你的fandol字体的版本比较老？

检查一下你的`${TEXHOME}/2015/texmf-dist/doc/fonts/fandol/README`里的fandol版本号。目前最新版本是v0.3。

**Comment by zepinglee** [comment]
老版本中可能有做过特殊处理，我还没完整review过老版本，估计要等到寒假了

**Comment by seisman** [comment]
@redsky0802  还是直接试试windows字体或者adobe字体的大写零是否有问题吧。

fandol字体不确定能否通过论文审查。

**Comment by redsky0802** [comment]
@seisman adobe字体的大写零没问题，前面已经说过了。本科论文用的就是adobe字体。

**Comment by zepinglee** [comment]
设置字体有以下几种方式，我会写进 manual 里
1. 设置文档类参数
```
\documentclass[doctor,fontset=adobe]{ustcthesis}
```
 这个参数会传递给 ctexbook；

2. 使用 ctex 的命令
```
\documentclass[fontset = none]{ustcthesis}
\ctexset{fontset = adobe}
```
具体见 ctex 宏包的说明；

3. 用 fontspec 宏包的接口自己设置，但可能会引起错误。
