### ISSUE TITLE
fine

### ISSUE THREAD

**Issue by SKY-66** [ustctug/ustcthesis#408]
## 检查
- [ ] 已经阅读《研究生学位论文撰写手册》或《中国科学技术大学本科毕业论文（设计）格式》
- [ ] 已经将模板升级到了最新版
- [ ] 已经阅读使用说明文档 `ustcthesis.pdf`
- [ ] 已经阅读 [常见问题](https://github.com/ustctug/ustcthesis/wiki/常见问题)

## 编译环境
- 编译的系统：macOS 10.14 / Windows 10 / Ubuntu 18.04 / Overleaf
- TeX 发行版：TeX Live 2019 / MacTeX 2019 / MiKTeX 2.9.6753
- 模板类型：doctor / master / bachelor

## 描述问题
《研究生学位论文撰写手册》第 xx 页要求……而模板编译的结果是……

截图：

复现上述问题的代码：
```TeX
\documentclass[degree=doctor]{ustcthesis}
\begin{document}
abc
\end{document}
```

**Comment by zepinglee** [comment]
你可以将这个文件改成任何名字。
