### ISSUE TITLE
汉字〇没显示出来

### ISSUE THREAD

**Issue by run** [ustctug/ustcthesis#41]
Hi，你好，

我在一台 ubuntu 14.04 + Texlive 2015 上编译了一下模板，发现第一页的日期本应该是 “二〇一五” ，“〇”显示为一个叉叉，不知道该如何解决这个问题？ 你们的机器上没有这个问题吗？

Thanks

**Comment by hosiet** [comment]
clerkma/fandol-fonts#2

**Comment by run** [comment]
@hosiet  那个问题我也搜到了，但是并没有给出解决方法啊？  ustcthesis 并没有用到FandolSong

**Comment by hosiet** [comment]
ustcthesis 用了是 ctex 宏集，ctex 在 Linux 平台默认用 Fandol Song。
所以尝试手动指定其它字体比较好。

**Comment by run** [comment]
请问该怎么手动设置呢？ 我在 mac osx 和 linux 上编译都显示不出

**Comment by hosiet** [comment]
请查看 ctex 文档（例，使用 texdoc ctex 命令）第4.3节。

**Comment by run** [comment]
好的，谢谢。 还有一个问题，新版用 ustcthesis.dtx 生成 .cls，这与以前的不同，请问有什么学习资料能帮助理解这个 dtx 文档吗？因为我要做一些改动

**Comment by hosiet** [comment]
http://www.tex.ac.uk/FAQ-dtx.html

**Comment by zepinglee** [comment]
@run 关于 dtx，参考 dtxtut、doc、docstrip。
