### ISSUE TITLE
页眉的线没有和正文字体对齐，如图

### ISSUE THREAD

**Issue by run** [ustctug/ustcthesis#42]
<img width="699" alt="screenshot 2015-12-24 17 05 30" src="https://cloud.githubusercontent.com/assets/647045/11998700/b83c85fc-aa60-11e5-9f2e-bd6e714d7d6b.png">

请问控制页眉线的代码是在哪呢？ 
我找了一下貌似没有直接指明线的起始位置和长度？

**Comment by run** [comment]
上图 “种类” 的种 字在线外，而右侧则感觉缩进去一个字的大小，这个在repo的模板里不是很明显，因为字少，但是真正有大段文字的时候，非常的明显

**Comment by seisman** [comment]
~~~latex
\newpagestyle{main}[\ustc@header@size]{
    \sethead{}{\ustc@main@header}{}
    \ifustc@page@pageright
        \setfoot[\thepage][][]{}{}{\thepage}
    \else
        \setfoot{}{\thepage}{}
    \fi
    \headrule
}
~~~
页眉的线是由`\headrule`控制的，至于为什么没有对齐，目前还不清楚原因。

**Comment by seisman** [comment]
把代码中的如下语句注释掉，则不会出现该bug。
~~~latex
\ifustc@opt@bachelor
    \renewcommand\normalsize{\setfontsize{12bp}[22bp]}
\else
    \renewcommand\normalsize{\setfontsize{12bp}[20bp]}
\fi
~~~
为何重定义`\normalsize`会引起此bug尚不知，具体如何修改尚不知。

**Comment by seisman** [comment]
如下宏定义中的空格与换行，导致该bug的产生。
~~~latex
\DeclareDocumentCommand \setfontsize { m o } {
    \IfValueTF {#2}
        { \fontsize{#1}{#2} }
        { \fontsize{#1}{1.2 \dimexpr#1} }
    \linespread{1}\selectfont\relax}
~~~
目前的解决办法是在一行内写完该宏定义。若有更好的解决办法，可以再PR。

**Comment by run** [comment]
非常感谢！！！！  
我自己昨天折腾了好久都不知道怎么修这个bug！

**Comment by jiaopjie** [comment]
按 seisman 说的, 这好像的确是重定义 `\normalsize` 引起的. 我试了一下, 重定义 `\normalsize` 的时候使用 `LaTeX` 原本的 `\fontsize` 不会有问题 (反正只有这一处没有用你们自定义的命令, 也无所谓吧). `\renewcommand\normalsize{\fontsize{12bp}{22bp}\selectfont}` 这里也需要一行写完, 中间不要有多余的空格.

要是实在是追求完美, 一定要用你们自定义的命令. 其实也不需要把那么长全写在一行上. 把多余的空格删掉, 在每一行末尾紧接着加百分号就行了.

另外, 不懂你们在设置字体命令里面加上 `\linespread{1}` 干什么... 如果是为了修正 `ctex` 修改默认的 `\baselinestretch` 值造成的行间距过大问题的话, 直接在使用 `ctexbook` 之后使用一次这条命令就行了. 不用每次设置字体都设置啊...

LaTeX 懂的不多, 所以也不知道 `\relax` 是干什么的...

```
\DeclareDocumentCommand\setfontsize{mo}{%
  \IfValueTF{#2}
    {\fontsize{#1}{#2}\selectfont}
    {\fontsize{#1}{2\dimexpr#1}\selectfont}%
}
```
我自己试的, 上面的修改似乎是可行的 (我习惯在 `\fontsize` 之后立马使用 `\selectfont`). 如果不考虑缩进的规律性的话, 可以把第一行最后一个左花括号放到第二行开始 `{\IfValueTF...`, 把最后一个右花括号提前到上一行的最后, 紧贴着上一个右花括号 `\selectfont}}`. 这样不需要用百分号.

```
\DeclareDocumentCommand\setfontsize{mo}
  {\IfValueTF{#2}
    {\fontsize{#1}{#2}\selectfont}
    {\fontsize{#1}{2\dimexpr#1}\selectfont}}
```

**Comment by zepinglee** [comment]
> 其实也不需要把那么长全写在一行上. 把多余的空格删掉, 在每一行末尾紧接着加百分号就行了.

这个我们原来就是那样写的，确实会产生问题；这个可能跟 xparse 的 `\IfValueTF` 有关，但具体没有细致研究。

> 在设置字体命令里面加上 \linespread{1}

这个确实没有必要，我们这样写就是把字号、行距相关的命令集中在一起，显得更清晰

> LaTeX 懂的不多, 所以也不知道 \relax 是干什么的...

`\relax` 就是一个空的操作，主要做语法分析的时候避免一些错误，感觉这里应该不需要 `\relax`

>  如果不考虑缩进的规律性的话, 可以把第一行最后一个左花括号放到第二行开始 {\IfValueTF..., 把最后一个右花括号提前到上一行的最后, 紧贴着上一个右花括号 \selectfont}}. 这样不需要用百分号.

这个是不同的 coding style，我参考的是大部分 LaTeX 宏包（比如 source2e ）的风格

**Comment by jiaopjie** [comment]
我觉得跟 `\IflueTF` 没有太大关系. 问题应该的确集中在重定义 `\normalsize` 上. 在重定义的时候即便使用原本的 `\fontize` 和 `\selectfont` 命令, 如果在命令中间有多余的空格的话, 也会产生类似的问题. 就是不知道这是 `LaTeX` 的问题还是使用的控制页眉的宏包的问题.

**Comment by jiaopjie** [comment]
你们原来的空格太多了, 并且有换行造成的空格. 在行尾加 `%` 虽然也比较丑, 但也比写在一行好看点 (我说的是在说明文档里. 源代码里面其实也无所谓) 话说你们重定义 `\normalsize` 是为了在文档开始的时候自动就是学校要求的字体大小和行间距对吧.
