### ISSUE TITLE
如何显示代码

### ISSUE THREAD

**Issue by run** [ustctug/ustcthesis#44]
Hello ~
请问如果要在论文里面贴一些代码片段（不需要高亮，也不需要行号）
类似下图这样，该怎么做呢？

----------

<img width="467" alt="screenshot 2015-12-28 00 42 35" src="https://cloud.githubusercontent.com/assets/647045/12016117/efca2748-acfb-11e5-9b5f-931dfd6993d2.png">

**Comment by hosiet** [comment]
Google: latex document insert code

**Comment by run** [comment]
非常感谢！   用 \begin{verbatim} 基本上可以达到我的要求

**Comment by zepinglee** [comment]
这种问题参考 lshort，不要在这里问了

如果有时间我会写进 manual，但是至少等到寒假了
