### ISSUE TITLE
图片与段落之间间距是否太大？

### ISSUE THREAD

**Issue by run** [ustctug/ustcthesis#45]
似乎图片与后段落文字之间的距离太大了？ 
而且一篇论文里面，不同的图片这个距离不完全一样，有细微的差别。
我查看了《规范》，的确是说图的后间距是12，但是感觉有点怪怪的。
我尝试修改了

\captionsetup[figure]{
position = bottom,
aboveskip = 6bp,
belowskip = 0bp,
}

看上去顺眼多了。。。 Orz

以下是截取的某一张不太顺眼的图。。。

<img width="537" alt="screenshot 2016-01-03 15 28 41" src="https://cloud.githubusercontent.com/assets/647045/12081481/2b66fb2c-b22f-11e5-88c2-27d166d7659b.png">

**Comment by run** [comment]
我尝试修改了 

\captionsetup[figure]{
    position = bottom,
    aboveskip = 6bp,
    belowskip = 0pt,
}

但是发现，这个belowskip 的值并不会影响到最后的文章排版，可能是 bug ?

**Comment by zepinglee** [comment]
我看起来感觉还好啊……
因为 figure 环境的 box 和后继段落文字的 box 之间，会加一个可伸缩距离，这样 TeX 引擎会自动找到合适的位置，所以不同的图片到后继文字的距离可能不一样。
我理解“图的后间距”是在 figure box 内部的额外固定 12bp。

**Comment by run** [comment]
对对，我也发现了是这样。那也就是说想要解决这个排版问题，只能靠自己人肉调整段落的字数来填充这个空白咯？

**Comment by zepinglee** [comment]
我觉得没有问题啊，这样就可以啊。
这个 12bp 本来就不是图到下面文字的绝对距离。
你在 MS Word 里面设置图片的 Distance From Text，top 和 bottom 都设置成 0，那也不是紧贴文字的，还有一个行距或者段距

**Comment by run** [comment]
哦哦，了解。
我说的是 figure 环境的 box 和后继段落的 box 的可伸缩距离只能靠人肉调整的好看点了

**Comment by zepinglee** [comment]
不用这样，人肉调整就违背了 TeX 的设计初衷，按照默认的就行。
TeX 调整位置时考虑的东西很多，比如不能在一页的最后新开启的一段不能只占一行，要么只占两行，要么都放到下一页。
具体见 Knuth 大神的 The TeXbook。

**Comment by zepinglee** [comment]
你要是非要控制这个距离，可以用 minipage 什么的

**Comment by run** [comment]
对对，我也发现了这个规律。。。Orz

**Comment by run** [comment]
这样说来，如果论文里面图片和之后的文字段落间距太大也不好调整咯？
要是答辩的时候格式不通过咋办。。。。
-----
不用这样，人肉调整就违背了 TeX 的设计初衷，按照默认的就行。
TeX 调整位置时考虑的东西很多，比如不能在一页的最后新开启的一段不能只占一行，要么只占两行，要么都放到下一页。
具体见 Knuth 大神的 The TeXbook。

**Comment by zepinglee** [comment]
我觉得不是很大啊，你把你的pdf发到我邮箱看看
标记一下距离太大的位置

**Comment by run** [comment]
我现在手头没有特别明显的例子，因为我已经学会了控制图片上面的段落和下面的段落的文字数量，来让排版好看一些的新姿势。。。Orz   

等我哪天又看到这样的例子之后再请教你哈，多谢了~~

**Comment by qiaowzh** [comment]
\captionsetup[figure]{
position = bottom,
aboveskip = 6bp,
belowskip = 0bp,
}
这个是修改bst文件吗？我修改了不起作用啊。
