### ISSUE TITLE
`\studentid` 似乎没有用到

### ISSUE THREAD

**Issue by zepinglee** [ustctug/ustcthesis#46]

**Comment by seisman** [comment]
http://www.teach.ustc.edu.cn/?attachment_id=1586 

本科毕业论文封面中需要学号信息

**Comment by seisman** [comment]
http://www.teach.ustc.edu.cn/?attachment_id=1656

封面是到学校制本厂统一打印的，所以在论文中实际上不需要封面，而本科论文对扉页没有特别要求，目前本科的扉页和研究生的扉页是一样的，所以其实也不需要学号信息。

**Comment by zepinglee** [comment]
那好我删了
