### ISSUE TITLE
文档中加入英文字体的说明

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#49]
~~~tex
\setmainfont{Times New Roman}                                            
\setsansfont{Arial}                                                      
\setmonofont{Courier New}   
~~~

**Comment by seisman** [comment]
关于英文字体，Linux下是需要从Windows复制字体的，不知道Mac如何？

**Comment by zepinglee** [comment]
Mac 下都自带了，Linux 一般自带哪些英文字体啊？
Times New Roman 和 Arial 是论文强制要求的；Courier New 在 Windows、Mac下都有，比 TeX 默认的Computer Modern Typewriter 好看一些。（其实我更喜欢Monaco，但是 Windows 没有）

**Comment by seisman** [comment]
Linux下倒是有一些替代字体，只是需要额外的安装，而且不同平台下安装包的名字也不一样，所以比较难统一，最简单的方式还是从Windows下复制字体。
