### ISSUE TITLE
中英文摘要页页眉线有差异

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#51]
细看的话，英文摘要页的页眉线比中文摘要页的页眉线要高一点。

**Comment by zepinglee** [comment]
这是正常的。
Word 里面的页眉定义为从纸张顶端到页眉文字上边缘的高度，由于中英文字体的高度不同（即使是同一字号），所以页眉线的高度也就跟着变了。

**Comment by zepinglee** [comment]
这不到1毫米的差异你都能看出来……😓

**Comment by seisman** [comment]
从头到尾翻一遍，一不小心就看出来了……
