### ISSUE TITLE
引用多个参考文献中间使用的是分号

### ISSUE THREAD

**Issue by liuhuimin** [ustctug/ustcthesis#54]
发现引用多个参考文献中间使用的是分号，是不是改成逗号比较好？

**Comment by seisman** [comment]
Fixed in 5654db3057a2086a25e3cdf4c7e95b81585621c2。请更新到最新版再试试看。

**Comment by liuhuimin** [comment]
恩恩，我试了，还是原来的效果，两个连续的引用中间是分号如[5;6]，我对latex不太熟，里面没有ustcextra.sty和ustcthesis.cls文件，我是从原来的拷贝过来的，是不是因为这个原因？这两个文件应该怎样生成？
另外还有个问题想请教一下，就是直接使用引用不想使用上标应该怎么办？比如我想写“文献[1]中提到”这类语句，使用上标不太好。
谢谢

**Comment by seisman** [comment]
ustcextra.sty和ustcthesis.cls都是从ustcthesis.dtx中自动生成的。

Linux直接make即可，Windows下不太清楚。

**Comment by liuhuimin** [comment]
谢谢，我用的windows，研究一下
