### ISSUE TITLE
图表标题在上方

### ISSUE THREAD

**Issue by liuhuimin** [ustctug/ustcthesis#55]
图表标题应该在下方的吧？还是我使用的版本老？

**Comment by seisman** [comment]
图标题在上方，表标题在下方。图和表的标注都在下方。
![selection_001](https://cloud.githubusercontent.com/assets/3974108/13457014/d70c94d8-e0a0-11e5-9b5b-31fea79f035b.png)
![selection_002](https://cloud.githubusercontent.com/assets/3974108/13457015/d7338dd6-e0a0-11e5-8270-768c4fef4ba8.png)

**Comment by gdshen95** [comment]
贴出来的图里，图标题在图的下方，表标题在表的上方。文字表述反了

**Comment by seisman** [comment]
恩，写错了，已更正。

**Comment by liuhuimin** [comment]
能不能将ustcextra.sty和ustcthesis.cls也放到工程里？谢谢

**Comment by liuhuimin** [comment]
我找到windows下的生成这两个文件的方法了，但试了最新版的，图的标题还是在上方，我现在知道问题在哪儿了：把\caption{图片标题}写在了\includegraphics{}之前图的标题就在图上方，写在之后就在图下方，\note{}同理，如果把\note{}放到\caption{}之前，图标题就在注释下方。
