### ISSUE TITLE
为Windows用户增加bat脚本

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#56]

**Comment by zepinglee** [comment]
呃我木有 Windows 环境，不太方便测试

**Comment by seisman** [comment]
我后来想了想，觉得其实没有必要为windows用户提供bat脚本。主要是因为bat脚本的功能太单一。编译论文需要一个脚本，清理临时文件也需要一个。

我在REAME里新增了一些说明，我感觉windows用户打开cmd直接敲几个latexmk的命令其实也挺方便的。

**Comment by zepinglee** [comment]
有道理，少一个文件更好。
我一看到目录里面一大堆东西就烦
