### ISSUE TITLE
增加算法和代码环境

### ISSUE THREAD

**Issue by liuhuimin** [ustctug/ustcthesis#57]
我看到旧版本有定义算法和代码环境，2.0版是否也有定义？直接用algorithm环境不行

**Comment by seisman** [comment]
暂无，未来会考虑添加。

**Comment by seisman** [comment]
Fixed in 89c54b43170e10a68bbd77a2f16e57c4c2f693ea f0b4aa6b91dcc8644c77a4a9c812762830802f48 。

直接下载最新版即可使用，但是因为算法环境和代码环境没有规范可以遵循，所以具体的样式可能需要用户自己调整。

**Comment by liuhuimin** [comment]
好的，谢谢

**Comment by zepinglee** [comment]
奇怪你们会把代码放进论文嘛？
代码直接用listings宏包，我觉得这个超出了模板的要求，不应放入模板中，最多写进demo里吧。
algorithm 宏包不能用嘛？不会吧？

**Comment by seisman** [comment]
目前代码和算法都放在了ustcextra里了。

算法宏包有很多，我是参考了之前的旧模板用了algorithm2e。算法相关宏包的讨论见： http://tex.stackexchange.com/questions/229355/

至于代码放论文里的问题，我是有见过本科论文在附录里贴了十几页的代码的。。。

**Comment by zepinglee** [comment]
我觉得数学定理那些似乎也应该放进ustcextra啊，毕竟不是规范要求的

**Comment by zepinglee** [comment]
让那种本科生见鬼去吧……

**Comment by liuhuimin** [comment]
我数学定理设置为楷体有问题，不清楚是和我使用windows系统有关。
另外希望把算法环境的冒号去掉，就是“算法2.1：算法”的冒号

**Comment by zepinglee** [comment]
楷体？不会啊，请确认你已经升级到最新

**Comment by seisman** [comment]
可以将数学定理之类的放进ustcextra里，毕竟这些东西基本只有数学系的人在用。cls文件应该做到符合学校的规范，除此之外不做其他多余的事情。

**Comment by zepinglee** [comment]
嗯好的
那把ustcextra从dtx里面剥离出来怎么样？
就把它视为demo的一部分，也方便用户自行修改
顺便建议换个不以u开头名字，好让我按tab能快速补齐

**Comment by seisman** [comment]
剥离出来是指将ustcextra放在单独的文件中？直接以sty文件的形式发布？

这样也可以，一旦稳定下来之后基本可以保证ustcthesis.cls文件完全符合学校的需求，而ustcextra.sty是可以用户自定义的。

至于换名字的事情，还是应该以ustc开头吧。。。

**Comment by liuhuimin** [comment]
我是用的最新版的，使用仿宋等其他字体（\fangsong）没问题，但使用楷体（\kaiti）提示没有定义

**Comment by seisman** [comment]
@liuhuimin 重新开Issue，贴出最小测试代码以及出错提示。
