### ISSUE TITLE
加入代码索引会导致PDF书签中目录重复出现

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#58]
若 `main.tex` 中使用 `\lstlistoflistings` 加入代码索引，会导致PDF的书签中目录重复出现，原因未知，目前的处理方式是不加入代码索引。

**Comment by zepinglee** [comment]
似乎得看底层代码了，我忙完考研复试再搞

**Comment by zepinglee** [comment]
谁会加入代码索引啊，我觉得把代码加到论文就够丢人了，还要加个索引也太丢人了吧
