### ISSUE TITLE
将ustcextra分离到单独的文件中

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#59]

**Comment by seisman** [comment]
ustcextra是要从ustcthesis.dtx里拿出来，直接放在ustcextra.sty里吗？

**Comment by zepinglee** [comment]
需要稍微修改下，我来搞吧

**Comment by zepinglee** [comment]
另外我建议把 cls 文件放进去repo里面吧，新手windows 用户实在搞不定这个

**Comment by seisman** [comment]
说明文档里已经写了 `xetex ustcthesis.dtx`，一句话就搞定了。。。

**Comment by seisman** [comment]
既然ustcextra.sty提取出来了，ustcthesis.cls也放一个进去吧，这样大多数人都可以直接使用，而不必去理会源码dtx文件

**Comment by zepinglee** [comment]
嗯，同意

**Comment by zepinglee** [comment]
fixed in 897c8da
