### ISSUE TITLE
在定理里使用楷体报错

### ISSUE THREAD

**Issue by liuhuimin** [ustctug/ustcthesis#60]
在定理中使用楷体报错，如图：
![](http://painterliu.com/public/img/error.JPG)
楷体命令所加位置在源文件math.tex ![](http://painterliu.com/public/img/kaiti.JPG)
另刚发现使用其他字体如\fangsong字体没有变化。
我使用的是windows7系统，latex是最新版
还有一个问题，编译ustcthesis.pdf报错，一直卡在这里
![](http://painterliu.com/public/img/error1.JPG)

**Comment by seisman** [comment]
字体命令是由ctex定义的，在ctex中只定义了songti, heiti, fangsong, kaishu

**Comment by liuhuimin** [comment]
哦哦，原来是kaisu，我ustcthesis.pdf编译不通过，在原来的里面显示的字体命令为kaiti

**Comment by zepinglee** [comment]
我写错了……

**Comment by liuhuimin** [comment]
恩恩，能不能对定理定义等环境设置个区别于正文的默认字体？这类内容和正文字体一样显现不出特殊性。

**Comment by seisman** [comment]
字体问题，文档中已经fix 3d8bdcc79cdc1be0c94f31e2d68d6335cfec6bf4

**Comment by zepinglee** [comment]
定理的样式是用 \newtheoremstyle 设置的。
我当时按照科大的数学分析教材的样式设计。
不过这部分代码会有所移动，建议你稍后再修改。

**Comment by liuhuimin** [comment]
哦哦，好的，谢谢

**Comment by seisman** [comment]
对于第二个问题，fangsong控制的是中文字体，而示例文档中的定理都是英文，所以fangsong对其无效，你可以自己写一条中文定理来做测试。

BTW：示例文档中的这部分内容还是需要汉化一下的。
