### ISSUE TITLE
ustcthesis.pdf在windows下无法编译通过

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#61]
报错如下：
![image](https://cloud.githubusercontent.com/assets/3974108/13657571/4beadef8-e6ab-11e5-8495-1e8a9da2d15d.png)

**Comment by seisman** [comment]
错误原因：在定义shellcmd时使用了中文下的 `|` 符号
Fixed in d04c9d3148410c97ce03d2f6701317f0b45624fd.

**Comment by zepinglee** [comment]
我擦咧……
