### ISSUE TITLE
模板维护应遵循的几个原则

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#62]
列出几个维护过程中应遵循的原则，待讨论 @zepinglee  @ywgATustcbbs：

1. 每一个正式发布版，都应该在多个平台下编译通过，平台包括（待定）：

    - TeXLive for Linux
    - TeXLive for Windows
    - TeXLive for Mac？
    - MiKTeX？
    - CTEX套装？（CTEX套装即将发布新版，看情况决定）

2. 兼容性问题。由于TeX宏包众多且更新频繁，不可能去兼容所有版本也不可能为某个版本的宏包的bug单独打补丁。建议的做法是，模板只需在两个快照下编译通过即可，即当年的TeXLive最原始版本（即TUG下载下来的TeXLive的DVD镜像），以及当日更新了所有宏包之后的版本。

3. 不兼容问题。比如2016年10月发布的模板，只要求兼容TeXLive 2016即可，能兼容TeXLive 2015最好，但是不强制要求。这样可以尽量避免冗余的代码。

**Comment by zepinglee** [comment]
MacTeX 事实上是 TeX Live + GhostScript + 一些 Mac 下的工具 Apps（TeXShop，BibDesk等等，我都不用的），所以可以忽略
MikTeX 据说某些软件的实现跟 TeX Live 不同，不过我目前还没遇到过；
另外 Windows 上也很少有人装 TeX Live，暂时忽略吧。

**Comment by seisman** [comment]
从核心功能上看，MacTeX等效于TeXLive？MiKTeX我没有查到它的发布规律，所以不清楚它是不是像TeXLive那样定期发布一个版本。

Windows下用TeXLive的还是很多的吧，主要是现在CTEX一直不更新，Windows下其实没什么好用的TeX发行版，很多人只能选择TeXLive，然后自己再装个好用的编辑器。

**Comment by zepinglee** [comment]
差不多等效吧，MacTeX 没年6月份发布一次。

Windows 方面无能为力……

**Comment by seisman** [comment]
那就确定下来：
- TeXLive for Linux
- TeXLive for Windows
- TeXLive for Mac
- 新版CTEX套装
至于CTEX套装，其实际上是基于MiKTeX，所以还得再看看它的更新策略。

**Comment by hosiet** [comment]
OT一下，CTeX套装可能不会太快发新版；开发人员给了一个愚人节的参考时间，但是表示如果跳票也是极其正常的。

另外，新版CTeX套装极可能是最后一版CTeX套装。

**Comment by seisman** [comment]
那CTEX套装就暂时不考虑了。只测试TeXLive在三个平台下的兼容性。

**Comment by hosiet** [comment]
CTeX 已确认跳票来着。

> 我荣幸地宣布
> 我们要跳！票！啦！

https://github.com/CTeX-DEV/CTeX/issues/11#issuecomment-203953554
