### ISSUE TITLE
生成的 PDF 学校查重系统是否能识别？

### ISSUE THREAD

**Issue by run** [ustctug/ustcthesis#63]
Hello，

我在 Mac 下用ustcthesis v2.0生成了 PDF 版的论文，但是当在 Windows 下用 Adobe 专业版导出为 word 时都是乱码。

不知道学校查重的时候直接提交 PDF 系统能识别吗？以前有同学这样通过了吗？

**Comment by zepinglee** [comment]
字符编码问题？

**Comment by run** [comment]
Hello, 

是这样的：我在 Mac 下生成的 PDF，在 Windows 下打开，然后选中拷贝，粘贴到文本编辑器里面，就会发现有些字是“？”，但也不是全部都这样，大概占十分之一吧。 然后试了下网上的论文查重系统，直接提交 PDF 结果和上面差不多，能识别文字但也有些“？”

你说的字符编码我该怎么调整呢？

**Comment by zepinglee** [comment]
论文查重系统的地址是？我去看看

**Comment by zepinglee** [comment]
据我了解，查重系统使用的是 OCR，所以不会有问题

**Comment by run** [comment]
Hello，不好意思最近比较忙没有及时回复~
我已经在学校的查重平台上测试通过了，只是上传论文之后 chrome 和 IE 无法查看论文，一查看就崩溃，只有firefox 可以正常查看， Firefox 中的英文字符显示不出来（这些有可能与我 Mac 环境配置也有关系）。

但总而言之，学校的查重系统是可以识别的！ 另外，我是研究生查重的平台，地址是 http://pyxt.ustc.edu.cn/stu_admin/

谢谢 @zepinglee 的回复~

**Comment by gdshen95** [comment]
本科生的论文，如果不是优秀论文的话，似乎不查重

**Comment by zepinglee** [comment]
@run 你试试在 \hypersetup 里面加上 unicode=true, 看看还会不会导致复制的乱码？
