### ISSUE TITLE
BBS上新模板替换旧模板

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#64]
BBS上似乎还是有很多人不知道新版本的存在，估计是直接看到BBS上的置顶贴就直接下了旧版本了。

现在TeX版没有版主，所有很多事情都会变得很麻烦。 @ywgATustcbbs 你有修改置顶帖的权限吗？

**Comment by zepinglee** [comment]
现在貌似没有版主

**Comment by zepinglee** [comment]
@seisman 现在没版主，貌似只要去board版申请就可以吧，你有没有兴趣做版主呢？我今年毕业就滚离科大了，就不太方便。

**Comment by seisman** [comment]
我也快毕业了。。。
