### ISSUE TITLE
参考文献作者名字全部大写

### ISSUE THREAD

**Issue by liuhuimin** [ustctug/ustcthesis#65]
刚发现参考文献中作者名字全部是大写的，学校的要求应该是作者名字首字母大写

**Comment by zepinglee** [comment]
嗯……现在是按照 GB/T 7714-2005 的范例写成全大写，我也觉得改成教务处推荐的首字母大写更好认些

**Comment by zepinglee** [comment]
c2252ee 改好了

**Comment by seisman** [comment]
Confirmed and closed.
