### ISSUE TITLE
MacTeX下目录和脚注始终为红色，即print选项无用

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#68]
详细讨论见：http://bbs.ustc.edu.cn/cgi/bbstcon?board=TeX&file=M.1458637212.A

@zepinglee 你在mac下测试一下？

**Comment by zepinglee** [comment]
应该是 hyperref 的 bug，类似 #21 ，新版已经修复

**Comment by seisman** [comment]
嗯，等那个用户升级之后再看看是否解决了问题。

**Comment by zepinglee** [comment]
你们怎么喜欢在上 bbs，我觉得那个页面的阅读性和很差啊

**Comment by seisman** [comment]
我也不喜欢BBS。问题是，虽然GitHub很火，但其实很小众啊。。。

**Comment by zepinglee** [comment]
已解决，这应该是 hyperref 的 bug，应该将 MacTeX 2015 升级到最新（里面的 packages 还是在不断更新的）：

1. 如果熟悉命令行工具，使用以下命令：

先设置 repository 为校园的镜像（这样比较快），再更新，需要输入密码

sudo tlmgr option repository http://mirrors.ustc.edu.cn/CTAN/systems/texlive/tlnet
sudo tlmgr update —-self --all

2. 如果对命令行工具不熟，可以使用 texlive utility.app （应该是叫这个）更新
