### ISSUE TITLE
无法处理英文专业名过长的情况

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#69]
如图所示：
![selection_001](https://cloud.githubusercontent.com/assets/3974108/14079219/ae93f3b8-f4c1-11e5-82f2-3b0e3546d0e1.png)

比较容易出现问题的主要就是英文专业名以及双导师的情况。强制断行后也会出现类似的问题。得想想看有没有更灵活的处理方式。

**Comment by zepinglee** [comment]
教务处规定了左右距离，又规定了字体字号，结果放不下了……（表情：怪我咯）
一个比较灵活的方式是，谁的空间不够了自己悄悄把字号改小点

**Comment by zepinglee** [comment]
@seisman 我用 tikz 重新设计了封面，你看看，在 https://github.com/ustctug/ustcthesis/tree/titlepage branch

**Comment by zepinglee** [comment]
现在可以放更长的文字了，如果实在太长的话就用 `\parbox`，比如：
```
\major{\parbox[t]{5cm}{一段很长很长很长很长很长很长的文字}}
```
上面 5cm 的距离自己去调

**Comment by seisman** [comment]
使用`\enmajor{\parbox[t]{5cm}{Information and Communication Engineering}}` 的结果如下：

![selection_001](https://cloud.githubusercontent.com/assets/3974108/14845947/ddf4a2de-0c26-11e6-8b5e-dd6c95ba8359.png)

看上去目前的做法是固定了表格的中心，当表格高度增加时，向上和向下占据额外的空间。

我觉得，更好的做法是，固定表格上边界与论文标题之间的距离，当表格高度增加时，向下占据额外的空间。

**Comment by seisman** [comment]
规范里严格规定了表格的下边界距离，所以我上一条评论的想法不对。

英文标题`距顶边16cm，可以根据字数适当上下调整文本框位置`，所以如果严格按照规范来的来，唯一可调的就是英文标题的位置了。

**Comment by zepinglee** [comment]
那个5cm 是让用户自己去调的，我调了一下：
```
\enmajor{\parbox[t]{8cm}{\centering{}Information and Communication Engineering}}
```
感觉这样行距不太对，不管了
