### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by LUXUV587** [ustctug/ustcthesis#70]
您们这个模板写得好漂亮，不过实现的细节还有很多地方可以改进。比如目录部分：

1. 章与章之间的目录需要空行。
2. 对图、表、算法目录间行距不一致。用\addtocontents{lot/lof/loa}{}稍微调一下。
3. 能不能把目录编号前后的字、间距、字体什么的属性都添加一下，因为有些需要加粗换字体。像图表目录一般都是“图 1.1 某某”
3. LaTeX默认生成的目录点太稀疏，不好看。word的要密不少。
4. 对于章标题，直接使用加粗会类似微软雅黑粗体会比word的simhei加粗要粗很多。这是因为一般中文字体只有一种regular的形式，xeCJK的包可能把字体加粗的平移量调得过大。win10中有一个新字体叫做“等线”有light、regular和bold，为了美观可以尝试一下。

如果你们把学位论文模板的90%以上的细节、样式都考虑到了，再再加以相应的注释，完全可以抽象成为一个中国大学的学位论文标准模板。因为这个也是有国标的【GB-T 7713.1-2006】学位论文编写规则，各个学校间差异并不大。以后其他学校的人想复用就不需要因为一些微小的样式修改而花大量的时间了，直接根据你们的注释就修改参数就行了。这样可以大大降低不同学校LaTeX模板的编写难度，不用重复造轮子，且可以保证模板质量。你们以后就负责除了封面以外部分的通用格式更改，其它学校的就把自己学校的封面什么比较个性化的东西自己定制就好了。一定程度降低LaTeX的使用难度，才会更好地推广它吧。

**Comment by zepinglee** [comment]
1. 本科生论文目录的空行已经实现，研究生好像不需要空行
2, 3. @seisman 
4. 我用titletoc按照学校的要求写的，可能是latex的行距跟word不太一样，我还需要研究下底层 TeX。
5. 字体的选择完全依赖 ctex 2.0，所以这种底层的我不太方便修改，最好向ctex-kit 提出建议吧，而且我也不用windows
不同学校的要求还是很不一样的，比如清华的。关于国标7713.1，我没有太大的兴趣，别的学校直接拿去修改就好了（授权是允许的）。而且，本模板也是参考了thuthesis 的很多写法。
非常感谢你的建议！

**Comment by seisman** [comment]
1. 研究生论文里没有明确要求章与章之间要空一行，但规范里给的示例里的确是有空行的，可以考虑加上。

**Comment by seisman** [comment]
我试着处理一下1, 2, 3.

**Comment by zepinglee** [comment]
1. 我觉得没必要吧，没有明确说明就没必要做

**Comment by zepinglee** [comment]
我还没懂 3 是什么意思

**Comment by seisman** [comment]
我也不理解3是什么意思。现在模板中表目录的格式是
~~~
1.1 标题 ......  5
~~~
他可能是觉得要变成
~~~
图1.1 标题 ...... 5
~~~
如果是这样的话，有待商榷。

**Comment by zepinglee** [comment]
他的意思是改成黑体字吧？我觉得加个“图”字还可以，但是改成黑体没有必要，跟前面的章节目录不太协调

**Comment by LUXUV587** [comment]
对于你们的格式要求来说，3并没有啥必要。主要是觉得你们如果在各个地方考虑得更多一些，以后其它学校的人在你们的基础上做小改进就是件比较容易的事情，要省很多事。毕竟为了改一个小地方的格式查文档甚至是源码是件挺耗时间的事情。不是所有的人的代码能力和查阅信息的能力都有那么强，比如我，很多人用LaTeX只是为了更漂亮的排版。模板完美还好说，有些小格式不一致简直要逼死普通用户。
