### ISSUE TITLE
算法宏包的选择与设置

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#72]
1. 算法宏包有很多，不同宏包的语法似乎不同，应该如何选择？
2. 算法目录应与图表目录的格式相同

**Comment by zepinglee** [comment]
那就去掉算法目录吧

**Comment by zepinglee** [comment]
刘海洋提到的用于排版算法的宏包有：
1. clrscode
2. algorithm2e
3. algorithmicx

**Comment by seisman** [comment]
先用algorithm2e吧，看上去自定义功能比较强大。我看看解决一下算法目录的问题。
