### ISSUE TITLE
目录中不同结构的页码字号不一致

### ISSUE THREAD

**Issue by wujfhero** [ustctug/ustcthesis#73]
不知道目录页码大小不一样是feature还是bug？
看到研究生院的word模板的目录页码大小是一样的

**Comment by zepinglee** [comment]
观察得好仔细！

**Comment by zepinglee** [comment]
chapter的四号太大，subsection的五号太小，我决定执两用中，设置页码为section的小四号

**Comment by zepinglee** [comment]
fixed in cafe6f99
