### ISSUE TITLE
硕士论文怎样把摘要目录的罗马页码居中？

### ISSUE THREAD

**Issue by liuhuimin** [ustctug/ustcthesis#74]
硕士论文怎样把摘要目录的罗马页码居中？发现现在摘要等正文前的页码是居于一侧的，往届都是居中

**Comment by liuhuimin** [comment]
而且罗马页码是小写的

**Comment by seisman** [comment]
罗马页码小写这个是bug，稍后会修复。

至于页码是居中还是居右这个事情，我印象中当初讨论过，论文规范中本身是矛盾的，所以统一使用了居于外侧的做法。

这个还需要再确认一下。

**Comment by liuhuimin** [comment]
我看往届的硕士论文前面摘要及目录部分页码居中

**Comment by liuhuimin** [comment]
谢谢回复

**Comment by seisman** [comment]
@zepinglee 罗马页码小写是 `\frontmatter` 的默认行为，感觉只能重定义 `\frontmatter` 了，不知你有更好的解法没？

**Comment by liuhuimin** [comment]
这个我不懂，建议你可以参考下老版模板的实现

**Comment by zepinglee** [comment]
ok 我可以修复小写bug，但是居中还是外侧，我觉得应该全局一致吧，分开会很难看

**Comment by liuhuimin** [comment]
因为目录字体前面是罗马数字，后面是阿拉伯数字，本身不一样，不会显得难看的，这个也无所谓，看个人喜好

**Comment by zepinglee** [comment]
@seisman 突然想到，《规范》写的是

> 页码从绪论开始按阿拉伯数字(1,2,3......)连续编排,此前的部分(中英 文摘要、目录等)用大写罗马数字(I,II,III...)单独编排,页码位置居于页脚居 中。封面、扉页、创新性声明等不编页码。

可以理解为，只要“此前的部分”页码居中，正文中依然放在外侧，这样就没有矛盾了

**Comment by seisman** [comment]
这样理解也可以。。。

所以要把frontmatter的页码强制居中么？ pagecenter和pageouter只用来控制正文的页码

**Comment by zepinglee** [comment]
嗯

**Comment by seisman** [comment]
OK

**Comment by zepinglee** [comment]
我明天改吧，现在困了

**Comment by zepinglee** [comment]
fixed in ae7c01d

**Comment by run** [comment]
@zepinglee  请问一下罗马数字大写应该修改哪个地方？ 在 fix ae7c01d 中没看出来

**Comment by zepinglee** [comment]
写错了，在 2f704c7

**Comment by liuhuimin** [comment]
现在试了下，找不到abstract的定义了

**Comment by zepinglee** [comment]
咦？什么意思？
我这里编译正常啊

**Comment by liuhuimin** [comment]
我这里提示“Undefined control sequence. \begin{abstract}”,我也不清楚什么情况，貌似是abstract没定义

**Comment by zepinglee** [comment]
@seisman 来看看，我又试了一下没有错误

**Comment by liuhuimin** [comment]
莫非是windows的问题？

**Comment by zepinglee** [comment]
你 merge 的时候有没有冲突？

**Comment by seisman** [comment]
~~~
! Undefined control sequence.
\caption@chapter@ORI ...\CTEX@chapter@afterindent
                                                  \@afterindenttrue \else \@...
l.1 \begin{abstract}
~~~

**Comment by seisman** [comment]
Linux下测试没有问题，Windows下有问题。

**Comment by seisman** [comment]
似乎我的宏包很久没更新了，待我更新完再测试一遍。不过其实我也没看懂你加的这几句的目的是什么。。。

**Comment by zepinglee** [comment]
是这样的，我们的abstract 和 toc 都是用 `\chapter*`来实现的，而 ctex 重定义了 `\chapter`, 里面有一句 `\thispagestyle{\CTEX@chapter@pagestyle}`，这样如果设置，目录的第一页的 footer 位置就不正确

**Comment by zepinglee** [comment]
你试下在windows 把 第832行 `\renewcommand\chapter{%` 前面加上 `\show\chapter` ，然后把报的错误信息返回给我

**Comment by seisman** [comment]
所有宏包升级到最新之后的报错信息：
~~~
> \chapter=\long macro:
->\if@openright \cleardoublepage \else \clearpage \fi \thispagestyle {\CTEX@cha
pter@pagestyle }\global \@topnum \z@ \ifodd \CTEX@chapter@afterindent \@afterin
denttrue \else \@afterindentfalse \fi \secdef \@chapter \@schapter .
l.178 \show\chapter
                   \renewcommand\chapter{%
?
~~~

**Comment by zepinglee** [comment]
这句 \show 就是会打断的……
我本来是想让你升级前show 一下 \chapter 展开成什么了
那算了，我再调整下，尽量做到兼容吧


李泽平

Sent from my iPhone.

中国科学技术大学 数学科学学院
School of Mathematical Sciences, University of Science and Technology of China
联系电话 Mobile: (+86)15556984192
电子邮件 E-mail: leezp@mail.ustc.edu.cn

**Comment by zepinglee** [comment]
@liuhuimin 你在测试下

**Comment by seisman** [comment]
测试通过

**Comment by liuhuimin** [comment]
抱歉，来晚了。现在测试能够运行，前面罗马字母也改好了，但发现有一个小问题：使用阿拉伯数字页码的第一页页码居中，后面的都是在两侧

**Comment by zepinglee** [comment]
你需要确认一下你用的是最新版，或者用 tlmgr 升级一下你的宏包

**Comment by liuhuimin** [comment]
确认了，现在就阿拉伯数字页码第一页居中有问题，其他页码都好

**Comment by zepinglee** [comment]
我怎么没问题……

**Comment by zepinglee** [comment]
你的是每一章的第1页页码有问题，还是只有第一章第1页有问题？

**Comment by liuhuimin** [comment]
刚注意到，每一章都是这种情况，另外我刚发现切换参考文献风格为numerical时，后面的参考文献列表没编号。

**Comment by liuhuimin** [comment]
我是用的Texstudio编辑器，有时会出现奇怪的问题

**Comment by zepinglee** [comment]
我生成的都很好啊，把你的代码让我看看

**Comment by liuhuimin** [comment]
哪个文件的代码？

**Comment by zepinglee** [comment]
全部

**Comment by liuhuimin** [comment]
我怎么发送？

**Comment by zepinglee** [comment]
你可以push 到github上来，或者打包发到我邮箱

**Comment by liuhuimin** [comment]
我直接从工程上下载最新的运行就是这个问题，上传打包感觉也一样

**Comment by zepinglee** [comment]
那就是你的TeX 的安装问题，升级宏包

**Comment by liuhuimin** [comment]
好吧，麻烦你了，谢谢，想问一下，切换为numerical风格参考文献时，参考文献列表有编号没？

**Comment by zepinglee** [comment]
你是怎么切换的？

**Comment by liuhuimin** [comment]
%\bibliographystyle{ustcauthoryear}
\bibliographystyle{ustcnumerical}

**Comment by zepinglee** [comment]
我这样声称的 bib 怎么有序号啊

**Comment by liuhuimin** [comment]
不太懂。。

**Comment by liuhuimin** [comment]
刚发现默认仓库设置成本地的了，我说前面更新没反应，以为不需要更新呢，抱歉

**Comment by zepinglee** [comment]
把你安装的 TeX 升级到最新应该就没问题的

**Comment by liuhuimin** [comment]
我更新好了再试试，非常抱歉，自己的问题麻烦你了

**Comment by liuhuimin** [comment]
现在页码没问题了，另外请教一下使用numerical风格的正确姿势

**Comment by zepinglee** [comment]
就是那样用的，你再试试

**Comment by liuhuimin** [comment]
好像好了，不清楚怎么回事，谢谢
