### ISSUE TITLE
吐槽、灌水专用 Issue

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#76]
release发布的太随意了。。。
在发布release之前，应该把整个文档过一遍，至少要把README以及文档中的版号号更新一下。否则用户下载的v2.1.1的包，但是文档显示的却是v2.1，很容易让人困惑。

**Comment by likaiguo** [comment]
都要把论文写完了,才发现这个版本的模板,真是蛋疼.

我现在是这么搞的:  markdown --> python 脚本 --> pandoc --> latex --> pdf

始终感觉,直接在latex里边搞, 写论文时候始终在调整格式.....真的很....

**Comment by zepinglee** [comment]
@likaiguo 好奇地问下为何需要python 脚本？

**Comment by run** [comment]
能介绍一下 markdown --> python 脚本 --> pandoc --> latex --> pdf  这个玩法是怎么搞的吗？
