### ISSUE TITLE
MacTex2015不能更新_MacTex目录颜色仍然红色

### ISSUE THREAD

**Issue by luluxing** [ustctug/ustcthesis#77]
请教大神，今天准备更新MacTex2015，但是提示“TeX Live 2015 is frozen forever and will no
longer be updated”，没能更新，所以目录颜色仍为红色，不知道有没有什么方法可以补救呢？多谢啦！

**Comment by zepinglee** [comment]
把全部的报错信息贴出来

**Comment by zepinglee** [comment]
估计是没用sudo 权限不够

**Comment by luluxing** [comment]
TeX Live 2015 is frozen forever and will no
longer be updated.  This happens in preparation for a new release.

If you're interested in helping to pretest the new release (when
pretests are available), please read http://tug.org/texlive/pretest.html.
Otherwise, just wait, and the new release will be ready in due time.
tlmgr: package repository http://mirrors.ustc.edu.cn/CTAN/systems/texlive/tlnet
dyld: lazy symbol binding failed: Symbol not found: ___strlcpy_chk
  Referenced from: /System/Library/Perl/5.12/darwin-thread-multi-2level/auto/Cwd/Cwd.bundle
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: ___strlcpy_chk
  Referenced from: /System/Library/Perl/5.12/darwin-thread-multi-2level/auto/Cwd/Cwd.bundle
  Expected in: /usr/lib/libSystem.B.dylib

**Comment by luluxing** [comment]
麻烦指教

**Comment by zepinglee** [comment]
提示 /usr/lib/ 里面少了东西，可能是你的系统文件被删了；
更可能是 TeX 安装版损坏了，重装一遍再更新

**Comment by luluxing** [comment]
但是重新安装了以后还是这个问题啊 怎么办呢

**Comment by zepinglee** [comment]
升级到最新
