### ISSUE TITLE
建议，目录中大的章节名数字换成中文，如第三章

### ISSUE THREAD

**Issue by liuhuimin** [ustctug/ustcthesis#78]
另外目录中没包含目录本身和图表索引的页码，不清楚是包含好还是不包含好

**Comment by zepinglee** [comment]
1. chapter 标题用中文数字，有道理，规范里写道

> 各章标题
第一章 ×××
黑体 16 磅加粗居中,单倍行距,段前 24 磅,段后 18 磅,章序号与章名间空一个汉字符

但是跟范例不一样，忘记什么时候改的了

2. 关于目录中包含“目录本身和图表索引”，这个有讨论过，最后决定不添加，你搜索一下issue

**Comment by seisman** [comment]
在规范的2.6.2.1中写到
~~~
论文标题分层设序。层次以少为宜，根据实际需要选择。各层次标题一律用阿拉伯数字连续编号；不同层次的数字之间用小圆点“．”相隔，末位数字后面不加点号，如“1”，“1.1”，“1.1.1”等
~~~
所以规范本身就是自相矛盾的

**Comment by liuhuimin** [comment]
恩，规范我看了示例，发现是阿拉伯数字，主要发现是发现往届师兄的都用的中文数字，所以提个建议。
另外规范也需要更新了，里面校徽都是用的老的

**Comment by zepinglee** [comment]
1. 《规范》中有很多自相矛盾的，甚至《规范》的示例都不符合规范
2. 旧模板有很多不合规范的 bug，不用去参考
3. 校徽是换了颜色吧？我记得ustc.edu.cn有个校徽，但是一时找不到

**Comment by gdshen95** [comment]
校徽在这有
http://vi.ustc.edu.cn/badge/201104/t20110428_103574.html

**Comment by zepinglee** [comment]
这个跟论文里用的是一样的啊

**Comment by liuhuimin** [comment]
我是说规范里的校徽不对，一直没更新

**Comment by zepinglee** [comment]
请致信研究生院，顺便提醒修改一下矛盾的地方，并且更新参考文献的规范；
反正我给他们发过邮件，他们是不鸟我的

**Comment by liuhuimin** [comment]
应该也不会鸟我。。。
