### ISSUE TITLE
博士论文页眉和页码问题

### ISSUE THREAD

**Issue by luluxing** [ustctug/ustcthesis#80]
刚刚发现用的最新的模板，每一章的第一页页码居中，而后的都居两侧。

还有一个问题就是每一章的第一页的页眉也消失了，包括附录的第一页。

还有就是，请教有没有别的办法让论文里的hyperref的颜色都变黑色呢，我的mac就是不能用tlmgr更新。

先谢过啦！

**Comment by seisman** [comment]
1. Linux下测试的结果是，每章的第一页页码是在两侧的，所以估计还是你的MacTeX的问题
2. 这个是bug，规范2.6.3节要求`各部分的首页也需有页眉` @zepinglee

**Comment by seisman** [comment]
确认了一下。。。每一章首页是有页眉的。没有bug。。。

**Comment by seisman** [comment]
如下面两张图所示，都显示正常。
![selection_001](https://cloud.githubusercontent.com/assets/3974108/14642485/38c93afc-0610-11e6-8578-873fa84a8828.png)
![selection_002](https://cloud.githubusercontent.com/assets/3974108/14642501/419576a0-0610-11e6-9ce9-e1f7acfc0e00.png)

你还是先解决你的MacTeX的更新问题吧 @luluxing

**Comment by zepinglee** [comment]
@luluxing 你先把宏包升级到最新

**Comment by zepinglee** [comment]
@seisman 这个应该是 ctex 调整了对 hook 的使用有关，我明天改用更兼容的方法再实现frontmatter 页码居中吧。
另外我还有个想法，就是不用 ctex 的接口，只用 ctex 提供的对中文的支持，其他全部用底层命令实现

**Comment by luluxing** [comment]
真是抱歉，我换了其他mac又试了一下，颜色和页眉的问题都不存在了，果然是自己电脑的问题，我的就是没法更新了，估计是10.8的系统太老了吧。。。。
总之，非常感谢两位大神的帮助～

**Comment by seisman** [comment]
1. 不建议重写frontmatter去兼容旧版本的ctex，主要原因是兼容旧版本会加入额外的代码，给后人的维护带来麻烦，而且如果要兼容旧版本的ctex那是不是还得顺便解决一下旧版本hyperref的bug，这样修复下去就没止境了。TeXLive 2016就要出来了，倒不如从TeXLive 2016再开始考虑兼容性问题。

2. 不建议不使用ctex的接口。因为目前使用ctex的接口并没有造成实质性的困难，而不使用ctex的接口，则需要自己写很多额外的代码。

**Comment by zepinglee** [comment]
1. 我觉得还是比较简单的，先给你看看再merge。
2. 有道理，我估计我要是写出来，全校就没几个人能再改了

**Comment by seisman** [comment]
1. 主要是兼容的意义不大。如果要考虑兼容性的话，就得兼容TeXLive 2015的最原始的版本，而这个版本已知ctex和hyperref都有bug，至少得把两个都兼容了，才有可能说模板兼容TeXLive 2015
