### ISSUE TITLE
参考文献中年份的位置

### ISSUE THREAD

**Issue by wujfhero** [ustctug/ustcthesis#81]
我用了最新的author，year形式的参考文献，但是发现文后参考文献中出版年份显示在期刊之后，看研究生院的标准，出版年份好像是在作者后面。是bug还是我设置问题？

另外如果引用文献是博士论文，怎么在条目上[D]之后显示[Ph.D.]以及显示毕业论文所在学校？

谢谢

**Comment by wujfhero** [comment]
另外参考文献的标题中有字母缩略字需要大写的，但是编译生成的默认都改成了小写该如何处理？

**Comment by zepinglee** [comment]
我完全按照GBT写的，这一部分是科大修改过的，我待会fix吧

**Comment by zepinglee** [comment]
@wujfhero 第2个问题你能不能贴个bib的例子

**Comment by seisman** [comment]
改之后在文档附录或者其他地方加个说明，解释一下科大的规范与GBT之间的差异，方便以后的维护。 @zepinglee

**Comment by zepinglee** [comment]
@seisman 那我把bst 整合到dtx 里面吧，可以加注释；另外两个风格的 bst 95% 以上的内容都一样，改起来也方便

**Comment by zepinglee** [comment]
发现教务处要求的 author-year 和 numerical 完全不一样，那算了就不整合了

**Comment by wujfhero** [comment]
@zepinglee 引用博士论文我的bib是从endnote里导入的，例子如下：
@PhdThesis{Kuester2007a,
  author =         {Kuester, Michele Ann},
  title =          {Analysis of convectively generated gravity waves within a tropical cyclone environment: Model simulation and satellite observation},
  school =         {UNIVERSITY OF COLORADO AT BOULDER},
  year =           {2007},
  address=         {Boulder, USA}
}


编译显示的结果是：
![qq 20160423133740](https://cloud.githubusercontent.com/assets/3103885/14759498/8399e39c-0958-11e6-8ab6-8f419ff3b2bf.png)

**Comment by wujfhero** [comment]
关于参考文献标题中个别需要大写的特定字母我用添加{}方式解决了，这个应该在bst中不好单独设置

**Comment by zepinglee** [comment]
你说的“字母缩略字需要大写”，在你的例子中是指哪个词啊？

原来默认 title 域会修改成首字母大写，其余小写；我可以把这句话删掉，保持原样

我尽量修改 bst 使得 endnote 导出就可以直接用吧

正在修改中……

**Comment by wujfhero** [comment]
@zepinglee 比如下面这个例子，我title开头的AIRS等这个是一个卫星的名字需要全部大写，目前是再加一个大括号来保证它显示出来是大写的。
@Article{Aumann2003,
  author =  {Aumann, H. H. and Chahine, M. T. and Gautier, C. and Goldberg, M. D. and Kalnay, E. and McMillin, L. M. and Revercomb, H. and Rosenkranz, P. W. and Smith, W. L. and Staelin, D. H. and Strow, L. L.et al.},
  title =   {{AIRS/AMSU/HSB} on the Aqua mission: design, science objectives, data products, and processing systems},
  journal = {Geoscience and Remote Sensing, IEEE Transactions on},
  year =    {2003},
  volume =  {41},
  number =  {2},
  pages =   {253-264},
  doi =     {10.1109/TGRS.2002.808356},
  issn =    {0196-2892}
}

**Comment by wujfhero** [comment]
@zepinglee 我理解有可能有些文献从网上或者endnote中导出成bib格式时默认会把所有标题字母都大写，这样的话你首字母大写方法就会很有帮助。所以这个功能估计是智者见智吧

**Comment by wujfhero** [comment]
另外参考文献中引用的文章只有两个作者比如A 和B，那么在引用时用（A and B, 2016）这样子会比（A et. al.）这样好看些？
这个是研究生院规范的表述，貌似没有指定样式“ 引用多位著者的文献时，对欧美著者只需标注第一个著者的姓，其后附“et al”,**仅两位作者的也可全部注出,中间用“and”；**”

比如我文献中有这么一条：Fritts D C, Alexander M J. Gravity wave dynamics and effects in the middle atmosphere[J]
目前在正文中是以 (Fritts, et al., 2003)出现的。

**Comment by zepinglee** [comment]
1. 大小写，用大括号是推荐的方法，我还是保持默认的首字母大写吧

2. citation 里面两个作者，这个比较麻烦，需要会时间

我先处理以下问题：

1. year 在 author 之后

2. 处理 school 域，这样就不用手动调整了

2. 文献类型标志后面的[Ph.D.]

3. 非 journal 的 pages 前面用逗号

**Comment by zepinglee** [comment]
fixed in 3149606

**Comment by wujfhero** [comment]
@zepinglee  谢谢你的辛苦工作，确实很赞，我刚写完论文初稿，大部分都很完美。看到可能有的小问题是在[M][C][R]就是在book，InProceedings和techreport里面如果缺少address域就会显示[S.l.]，应该是缺少publisher就会显示[s.n.]，感觉不是很好，比如我引用了基本上从谷歌学术中导出都没有address信息，所以都显示[s.l]。另外我的techreport项里面貌似不能识别author域。举例如下：
@InProceedings{Aumann2006,
  author =    {Aumann, Hartmut H and Gregorich, David and De Souza-Machado, Sergio M},
  title =     {{AIRS} observations of deep convective clouds},
  booktitle = {Optics \& Photonics},
  year =      {2006},
  pages =     {63010J-63010J-7},
  publisher = {International Society for Optics and Photonics}
}

@TechReport{Skamarock2008,
  author =         {Skamarock, W. C. and Klemp, J. B. and Dudhia, J. and Gill, D. O. and Barker, M. and Duda, K. G. and Huang, Y. and Wang, W. and Powers, J. G.},
  title =          {A description of the {Advanced Research WRF Version 3}},
  year =           {2008},
  doi =            {citeulike-article-id:8996748},
}
@Book{Andrews1987,
  title =     {Middle atmosphere dynamics},
  publisher = {Academic press},
  year =      {1987},
  author =    {Andrews, David G and Holton, James R and Leovy, Conway B},
  isbn =      {0120585766}
}
上面三条编译出的参考文献形式为
![inpr](https://cloud.githubusercontent.com/assets/3103885/14766459/884d99d4-0a3d-11e6-907a-be9dded32fab.png)
![r](https://cloud.githubusercontent.com/assets/3103885/14766460/8fbc0700-0a3d-11e6-84dd-466ae39c4771.png)
![book](https://cloud.githubusercontent.com/assets/3103885/14766461/92899038-0a3d-11e6-9fbb-b8021b5ecef8.png)


主要是techreport的author不能识别，有可能像book类的按规范要提供publisher和address以及起始页码等，但是导入的时候没有这些域，只能显示[s.l][s.n]也能理解。

另外昨天说的作者是两个人就显示（a and b, 2016）这种形式，刚好我们专业的期刊提供的bst是这个形式的，但是我看不懂，给您作参考
[agufull08.zip](https://github.com/ustctug/ustcthesis/files/233353/agufull08.zip)

**Comment by zepinglee** [comment]
1. 出版地的问题，这个是国标要求的（我也不觉得好看）GB/T 7714-2005 第8.4.1.3节：

> 无出版地的中文文献著录“出版地不详”，外文文献著录“S.l.”，并置于方括号内。如果通过计算机网络存取的联机电子文献无出版地，可以省略此项。

第8.4.2.3节：

> 无出版者的中文文献著录“出者地不详”，外文文献著录“s.n.”，并置于方括号内。如果通过计算机网络存取的联机电子文献无出版者，可以省略此项。

我不知道有 DOI 的算不算。

2. techreport 的 author 是个bug

3. 我参考下你们期刊的 bst

**Comment by zepinglee** [comment]
“仅两位作者的也可全部注出,中间用“and””，这个只是教务处规定的，不是 GBT 允许的，所以我不打算修改模板。你可以自行修改，把 `FUNCTION {format.lab.names}` 这个函数替换成：
```
FUNCTION {format.lab.names}
{ 's :=
  s #1 "{vv~}{ll}" format.name$
  s num.names$ duplicate$
  #2 >
    { pop$
      ", " * format.et.al *
    }
    { #2 <
        'skip$
        { s #2 "{ff }{vv }{ll}{ jj}" format.name$ "others" =
            { ", " * format.et.al * }
            { " and " *
              s #2 "{vv~}{ll}" format.name$ *
            }
          if$
        }
      if$
    }
  if$
}
```

**Comment by zepinglee** [comment]
110b65600d 修复了techreport 的 author 域
