### ISSUE TITLE
更新到最近的commit时编译出来的显示有些问题

### ISSUE THREAD

**Issue by wujfhero** [ustctug/ustcthesis#85]
当我用[31364e0](https://github.com/ustctug/ustcthesis/commit/31364e08bf32de174eec8ad5b7bab28afebe5336)这个版本时，某章第一页是如下格式：
![1](https://cloud.githubusercontent.com/assets/3103885/15064945/c50ca8f8-138c-11e6-8318-16969c2c6ab8.png)

但是更新到[4c45ce6](https://github.com/ustctug/ustcthesis/commit/4c45ce644cd845de1fe78357678d6f1e025ce5f3)版本时，内容没有任何变化，这页显示就变成了下面格式，
![2](https://cloud.githubusercontent.com/assets/3103885/15064968/f3c8bac4-138c-11e6-8a77-bd0b5237be7b.png)

这导致这章最后一页多出来一个表格，比较难看。请教下这是什么原因？

**Comment by zepinglee** [comment]
我看不到你的图

**Comment by wujfhero** [comment]
@zepinglee 第一张图http://222.195.83.245/~wujf/1.png
第二张图http://222.195.83.245/~wujf/2.png

**Comment by zepinglee** [comment]
你能不能将你的源码发给我一份？我需要再现一下这个bug

**Comment by wujfhero** [comment]
@zepinglee 你要什么源码？我论文吗，因为包括了图片文件比较大，那我压缩下，给你地址？

**Comment by zepinglee** [comment]
嗯

**Comment by wujfhero** [comment]
地址在http://222.195.83.245/~wujf/phd.rar 麻烦你了

**Comment by zepinglee** [comment]
\setfontsize 中行距的问题，我研究下

**Comment by zepinglee** [comment]
@seisman 怎么看？

**Comment by wujfhero** [comment]
我不知道是不是后来封面格式定义的某些内容影响到正文章节标题的间距了？

**Comment by zepinglee** [comment]
没错，主要是单倍行距是用 \setfontsize 统一设置的。原来封面下面要求的单倍行距没有被正确设置，后来更正后，不知为什么导致章节的高度增加了……

**Comment by zepinglee** [comment]
这是 latex 分页的问题，与模板无关。

因为这一页的末尾恰好是图片，又是下一 section 的开始，所以分出了奇怪的结果……

至于解决方案，貌似很多人吐槽过 TeX 的分页，我也不知道……

**Comment by zepinglee** [comment]
《规范》要求的标题为单倍行距，所以现在才是正确的

**Comment by zepinglee** [comment]
解决方法：你把第 1 节少写一行就好了

**Comment by wujfhero** [comment]
好的，谢谢你
