### ISSUE TITLE
每章第一页的页眉怎么没了？

### ISSUE THREAD

**Issue by zhyuxi** [ustctug/ustcthesis#86]
请问为什么我下载了最新的版本编译后每章第一页的页眉不显示（摘要，目录等的第一页页眉都不显示）。4月12号版本以后好像就不对了
![1](https://cloud.githubusercontent.com/assets/19220349/15066807/b487c654-139e-11e6-971c-a066d3bb4047.png)
![2](https://cloud.githubusercontent.com/assets/19220349/15066812/bbf2ea86-139e-11e6-8045-29f3219b2ea8.png)

**Comment by zepinglee** [comment]
更新 texlive

**Comment by zhyuxi** [comment]
更新后解决了，多谢！
