### ISSUE TITLE
维护letter、vi和beamer三个项目

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#88]
1. https://github.com/ywgATustcbbs/ustcthesis.letter
2. https://github.com/ywgATustcbbs/ustcthesis.vi
3. https://github.com/ywgATustcbbs/ustcthesis.beamer

这三个项目要不要也接管过来？简单试了一下，beamer可以正常编译和使用，其余两个似乎都有问题。

**Comment by zepinglee** [comment]
那个beamer 的好丑，我觉得 https://github.com/thomasWeise/latexSlides 更好看些

**Comment by seisman** [comment]
我的意思并不是要把这三个项目fork过来由ustctug维护，而是指是否要从头开始做科大的letter、vi和beamer这三个项目。

**Comment by seisman** [comment]
简单看了一下你提到的这个项目，的确是更好看。但是结构有点乱，而且是纯英文的，对中文的支持比较有限。

**Comment by zepinglee** [comment]
我对 beamer 不熟，目前没有精力再去开发了

**Comment by seisman** [comment]
可以先建几个空的repo，提上日程，谁有兴趣谁实现。

**Comment by zepinglee** [comment]
ywg 可以把他的 repo transfer 过来，不用新建

**Comment by seisman** [comment]
ywg下的这几个项目，除了beamer之外，都无法正常使用。transfer过来也没啥用

**Comment by ywgATustcbbs** [comment]
怎么transfer

**Comment by ywgATustcbbs** [comment]
vi其实是一套eps的合集，怎么会不能用了呢
letter也只使用了最基本的pgf tikz，应该是不会户问题的啊

**Comment by ywgATustcbbs** [comment]
我似乎知道了，那个vi得下载zip文件下来，打开是没有问题的，但是直接repo点进去下载单独的文件似乎是不能正常显示的。

**Comment by ywgATustcbbs** [comment]
vi里边pdf编译有点问题，导致pdf中间的颜色显示不出来，重新编译一下就对了，可以回头再提交一次pdf

**Comment by ywgATustcbbs** [comment]
beamer是很早之前的一个同学分享的，仅仅是建了一个repo，没有对代码进行梳理。更何况演示的东西不同人有不同的喜好，统一起来没什么必要，仅仅作为供大家学习研究的示例就好了

**Comment by ywgATustcbbs** [comment]
我重新检查了下vi和letter，两个都没有问题，只是pdf 文件损坏，需要重新生成……

**Comment by seisman** [comment]
letter我编译出来是这样的：
![selection_003](https://cloud.githubusercontent.com/assets/3974108/15177669/dc50a214-1736-11e6-8862-43b5940b56c8.png)
科大的信息都在纸张的右上角。科大的信纸是这样的吗？能找到更官方的版本吗？

下面是科大研究生院提供的在读证明模板（http://gradschool.ustc.edu.cn/articles/2008/12/6.html ）
![selection_004](https://cloud.githubusercontent.com/assets/3974108/15177771/7edfa14c-1737-11e6-8c1b-cce3a5492d39.png)
我印象中科大信纸是类似这样的。

另外，BBS的置顶帖里有另一个不同风格的信纸模板 http://staff.ustc.edu.cn/~yhshen/software/ustc-letter.zip

**Comment by seisman** [comment]
vi我是直接编译，然后报错
~~~tex
! LaTeX Error: File `xecjk.sty' not found.
~~~
把`xecjk`改成`xeCJK`就可以用了。

**Comment by ywgATustcbbs** [comment]
http://vi.ustc.edu.cn/visual/201104/t20110428_104212.html

**Comment by ywgATustcbbs** [comment]
我这边编译是没问题的，可能是windows不区分大小写？

**Comment by seisman** [comment]
看了一下，letter的确是符合官方要求的。

官方的要求在：http://vi.ustc.edu.cn/visual/201104/t20110428_104212.html
B01-03、B01-04和B01-05

**Comment by seisman** [comment]
应该是Windows不区分大小写的问题。

**Comment by seisman** [comment]
是否要将这三个项目重命名一下？改成ustclogo、ustcletter、ustcbeamer更合理一些，毕竟这几个项目与论文无关。
