### ISSUE TITLE
support travis CI

### ISSUE THREAD

**Issue by seisman** [ustctug/ustcthesis#96]
使用 travis 持续构建服务，每次有新的commit时，自动在 Linux, Mac 和 Windows 下使用最新版本的TeXLive做编译测试。

两个说明：

1. travis目前只支持Linux 和 OSX，不支持Windows，Linux为 Ubuntu 14.04。似乎有其他持续集成服务是支持Windows的，这个需要再调查一下
2. 持续构建只能测试最新的模板能否在TeXLive最新版本（所有宏包都更新到最新）下编译成功，并不能测试是否由于宏包的更新而导致某些地方显示有错误。但至少可以确保编译成功，聊胜于无

**Comment by zepinglee** [comment]
我不太了解这个诶，你可以自己去搞

**Comment by seisman** [comment]
恩，我有些经验，如果你觉得有需要，我可以找时间实现。

**Comment by seisman** [comment]
Support Linux and OSX in d55addbb72cfb66665d8786a80491969e7581ded. Windows is not supported.

**Comment by zepinglee** [comment]
不错不错

**Comment by zepinglee** [comment]
不错不错
